table DimTemps
	lineageTag: a0321ef1-7121-4b3a-a222-3cafafe477c1

	column Dates
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: d1ca6c55-6017-4a5a-ad97-107156daf0cd
		summarizeBy: none
		sourceColumn: Dates

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Clé
		dataType: int64
		isKey
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: e8b93e3f-0d00-48dc-aaf6-6de7a339af1b
		summarizeBy: none
		sourceColumn: Clé

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of year inv'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3f86e138-f8b7-486e-b154-62059576098a
		summarizeBy: none
		sourceColumn: Day of year inv

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of year inv calendar'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 13846e0c-c63e-46b1-acac-58279a749aed
		summarizeBy: none
		sourceColumn: Day of year inv calendar

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 01243412-907a-49f6-bd74-8037adc6040e
		summarizeBy: none
		sourceColumn: DayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: c033d72d-c77a-480b-b83b-949defbf9a46
		summarizeBy: none
		sourceColumn: DayOfMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 9f338f5f-36ac-43c2-b909-bc1d46ace2c7
		summarizeBy: none
		sourceColumn: DayOfWeek

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 4bb78cd4-667b-497a-98fb-86e94a22c01c
		summarizeBy: none
		sourceColumn: DayOfYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'DayOfYear Calendar'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2e21cf2e-9115-484f-8d58-52e7d23e12b1
		summarizeBy: none
		sourceColumn: DayOfYear Calendar

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DaySuffix
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: a569bb70-60aa-4eba-81d0-9f85731850cd
		summarizeBy: none
		sourceColumn: DaySuffix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstDayOfMonth
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: cb105205-6848-4e0e-8a7d-6ac4d1760768
		summarizeBy: none
		sourceColumn: FirstDayOfMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstFiscalMonth
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 80e66263-7ef2-409f-b6b4-b5e8aa913f51
		summarizeBy: none
		sourceColumn: FirstFiscalMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalFirstDayOfMonth
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: db0af3d3-3549-467e-9142-31c3acbc0519
		summarizeBy: none
		sourceColumn: FiscalFirstDayOfMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalLastDayOfMonth
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: d44f9494-81cf-4e0d-88eb-b168b4bbb3a8
		summarizeBy: none
		sourceColumn: FiscalLastDayOfMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalMonth
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: cc081916-2feb-4961-9f5e-f8a1d1a323eb
		summarizeBy: none
		sourceColumn: FiscalMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalMonthYear
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: ede5c35f-eb9f-4027-8d74-b95146cdf487
		summarizeBy: none
		sourceColumn: FiscalMonthYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalPeriodeID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 5ca11e82-f82e-4a64-ae60-66f19dfa879b
		summarizeBy: none
		sourceColumn: FiscalPeriodeID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: c4204830-3b15-49c2-8594-35d3008f3d74
		summarizeBy: none
		sourceColumn: FiscalQuarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 3ee236b3-7104-478f-b181-d1063f992b2a
		summarizeBy: none
		sourceColumn: FiscalQuarterName
		sortByColumn: FiscalQuarter

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a3d9b6ff-02f2-497e-903c-24df5358fc13
		summarizeBy: none
		sourceColumn: FiscalYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalYearName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 01ed732a-5580-443a-8244-5ec722764907
		summarizeBy: none
		sourceColumn: FiscalYearName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HolidayName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: c4689baa-ebd8-46ef-959a-f04ce7dcf01b
		summarizeBy: none
		sourceColumn: HolidayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsWeekday
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 79146f3e-f5f7-4fb5-8cfe-5cecdc9452d1
		summarizeBy: none
		sourceColumn: IsWeekday

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsWorkingDay
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: eaceb8e5-9d8c-4245-b94c-6c1199d1329e
		summarizeBy: none
		sourceColumn: IsWorkingDay

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e9da1362-e395-41dd-a765-f8022344a48a
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: ebaaeaf0-916b-405a-96a9-860690aa5302
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: FiscalMonth

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthOfQuarter
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3dafc999-e197-437d-9b0c-d32190d101a7
		summarizeBy: none
		sourceColumn: MonthOfQuarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthShortName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: a163cedd-4d53-4c8d-a743-3a1e0af1d460
		summarizeBy: none
		sourceColumn: MonthShortName
		sortByColumn: FiscalMonth

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthYear
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 5aa2e6af-9c09-4ab3-bb15-f7111c43c1f2
		summarizeBy: none
		sourceColumn: MonthYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PeriodeID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ac1eed50-903f-4076-bf3b-03c515d34c56
		summarizeBy: none
		sourceColumn: PeriodeID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 105d3797-cd80-4ef7-8862-fe5548c7cc8e
		summarizeBy: none
		sourceColumn: Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QuarterName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 764dbec4-507e-4a81-81d7-d0614001478c
		summarizeBy: none
		sourceColumn: QuarterName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 8aca9f08-83c5-40d4-9f5b-63f2abe15e5f
		summarizeBy: none
		sourceColumn: WeekOfMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekOfYear
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 4f91a080-520d-40da-a260-c5a7513d2b1c
		summarizeBy: none
		sourceColumn: WeekOfYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d488c759-6113-4095-8779-4eca8ca06aa3
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YearName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 777ac285-a1ad-4b54-99e4-a13fa0a037c4
		summarizeBy: none
		sourceColumn: YearName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimTemps-d0f547d1-4dae-454e-bb4f-1b0d2eda62b1 = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("datayoyo.fr:19128", "Cacbi", [HierarchicalNavigation=true]),
				    public = Source{[Schema="public"]}[Data],
				    DimTemps1 = public{[Name="DimTemps"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(DimTemps1, each [FirstFiscalMonth] = 1)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

