table Parametrage
	lineageTag: 9a37f6fe-c6bf-4726-a089-337c10ac25e9

	column CodeAnouveauN
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 350995ed-b077-4123-ba95-4ec23f6b4ecc
		summarizeBy: none
		sourceColumn: CodeAnouveauN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CodeAnouveauN_1
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: c043d724-abd0-4b22-ac08-3da64e351ea2
		summarizeBy: none
		sourceColumn: CodeAnouveauN_1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DateOuvertureN
		dataType: dateTime
		formatString: Long Date
		lineageTag: ecae794c-533d-4ca9-b57d-bcfded28845d
		summarizeBy: none
		sourceColumn: DateOuvertureN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateClotureN
		dataType: dateTime
		formatString: Long Date
		lineageTag: abc63a5e-6552-49ae-86ee-b0c1d7b4d962
		summarizeBy: none
		sourceColumn: DateClotureN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateOuvertureN_1
		dataType: dateTime
		formatString: Long Date
		lineageTag: f2800e56-1c1f-4115-9224-a72e6aa8915b
		summarizeBy: none
		sourceColumn: DateOuvertureN_1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateClotureN_1
		dataType: dateTime
		formatString: Long Date
		lineageTag: c6506485-49bb-4fab-9398-1d20f832ebc6
		summarizeBy: none
		sourceColumn: DateClotureN_1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Materialite
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 62c09182-5aff-448f-8e14-4d60b5908904
		summarizeBy: sum
		sourceColumn: Materialite

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PM
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: fbd251c8-3755-42d2-ad1e-f877a8eda23b
		summarizeBy: sum
		sourceColumn: PM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AMPT
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: cd32d9b8-30dc-4993-9fd4-f0ec0f9cae63
		summarizeBy: sum
		sourceColumn: AMPT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AccountNumber
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(max)
		lineageTag: 86664c2c-2574-41dd-aced-a02380e5e326
		summarizeBy: none
		sourceColumn: AccountNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserMail
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 84387f61-6bed-4532-b028-b93c1356ed74
		summarizeBy: none
		sourceColumn: UserMail

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PremierMoisExercice
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: ac86de29-3d39-4d1c-9fc3-0c509843e439
		summarizeBy: none
		sourceColumn: PremierMoisExercice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CreatedAt
		dataType: dateTime
		formatString: General Date
		lineageTag: 7a11f4ae-de29-4fe9-8043-b05ff294c441
		summarizeBy: none
		sourceColumn: CreatedAt

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: 8e4ecf75-04c4-405a-b7b1-dec3e2fbaaba
		summarizeBy: count
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	partition Parametrage-edd26312-49da-4fd0-80f8-5430e2608e04 = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("datayoyo.fr:19128", "Cacbi", [HierarchicalNavigation=true]),
				    public = Source{[Schema="public"]}[Data],
				    Parametrage1 = public{[Name="Parametrage"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Parametrage1,{{"DateOuvertureN", type date}, {"DateClotureN", type date}, {"DateOuvertureN_1", type date}, {"DateClotureN_1", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [ClientID] = ClientID)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

