table 'CAshCompte - CA'
	lineageTag: 88f6ee0c-e20b-4658-9fb4-4900b2b9d4e2

	column CAsh
		dataType: string
		lineageTag: bed2a309-3b76-4253-8660-37591c00130e
		summarizeBy: none
		sourceColumn: CAsh

		annotation SummarizationSetBy = Automatic

	column 'CAsh detailed 2'
		dataType: int64
		formatString: 0
		lineageTag: 7a86fe18-8855-483f-9eaa-932b9fcef219
		summarizeBy: none
		sourceColumn: CAsh detailed 2

		annotation SummarizationSetBy = Automatic

	column 'CAsh agreg'
		dataType: string
		lineageTag: dca59dfc-9b5a-4242-a350-eedc00771a33
		summarizeBy: none
		sourceColumn: CAsh agreg

		annotation SummarizationSetBy = Automatic

	column Icone
		dataType: string
		lineageTag: c3891f33-05d6-4a2d-83c7-8a8e6ce514bc
		summarizeBy: none
		sourceColumn: Icone

		annotation SummarizationSetBy = Automatic

	column 'Cash detailed'
		dataType: string
		lineageTag: 220cf97f-19a4-42a2-8ea8-286c954308b3
		summarizeBy: none
		sourceColumn: Cash detailed

		annotation SummarizationSetBy = Automatic

	column 'Icone - CAsh detailed'
		dataType: string
		lineageTag: e104cc86-891d-4b2d-af20-5e3f79a6f56b
		summarizeBy: none
		sourceColumn: Icone - CAsh detailed
		sortByColumn: 'CAsh detailed rank1'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'CAsh detailed rank1'
		dataType: int64
		formatString: 0
		lineageTag: 2ac0bad0-d4a5-4603-b4f3-6efd1bb36e48
		summarizeBy: sum
		sourceColumn: CAsh detailed rank1

		annotation SummarizationSetBy = Automatic

	partition 'CAshCompte - CA' = m
		mode: import
		queryGroup: CAsh
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("vVTdToMwFH6VhitNpgM2hF02hOmFWZb93cxdVCiuyQamlD2NybybJL7F3sQn8BFsgW4rbolK3E1p+c73ne9wTplONRdeJ3Otodk6X1zIl8/1OhP7OQlDikHwkOq6aaMwRITipAwAp2FDmzX2uu22ZfPHaCKkP95fDveg2JkKwcp9DO9koibgjzd+8iIfkSTBSxyxREWBggHMAFZe+PHyGUfJNhO8lurPyAsfeLDnesNCVmRz6TZDkY85eUHKjNxyM083QZQgRuIIBCLgSKhVSWKcI4l5jiQOX7vQ2+t3kc9S3nqwfQXbjKHHBaElCk5gNxXNjhCFh6JwFRNa0paYMYql5FHEVgUdMXJ9Oc1Cr0/jICX5KEQJQ4yPwm50V6JkKf+TQKdqX3QXTirfHa6KT8mnEYkBZPLyiBq+QeDCuORwp3p5nPL2gIF3O77fq4tXAQa8YU/pgjcxybsoE5xE+bSr3lvC6Xg0UJynbHfTN6A4SX8Vgzd2Pb5t1OSbNfk167dq+resmv5r8nW9Jv9v9SMZcVXlb36VH/b+6Zc3+wI=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CAsh = _t, #"CAsh detailed 2" = _t, #"CAsh agreg" = _t, Icone = _t, #"Cash detailed" = _t, #"Icone - CAsh detailed" = _t, #"CAsh detailed rank1" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"CAsh", type text}, {"CAsh detailed 2", Int64.Type}, {"CAsh agreg", type text}, {"Icone", type text}, {"Cash detailed", type text}, {"Icone - CAsh detailed", type text}, {"CAsh detailed rank1", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

