table Accounts
	lineageTag: f82725e8-8889-45e8-b87c-20233e2950f3

	measure '_Immo_ taux Amort P&L global' = ```
			
			    DIVIDE( 
			        CALCULATE (
			        [_Gene_Solde GL],
			        'PlanCompteAEF'[DetailNiv3] = "Dot. amort, dépréciations et prov" ,Compte[Racine4]<=6813
			    ),
			        CALCULATE (
			            [_Gene_Solde GL],
			                ('PlanCompteAEF'[DetailNiv3] = "Immobilisations incorporelles brutes"||
			                'PlanCompteAEF'[DetailNiv3]  = "Immobilisations corporelles brutes") && NOT (PlanCompteAEF[LiasseCode] in {"AN", "AV", "AJA", "AL", "AX", "AH"})
			            ),0
			    )
			```
		lineageTag: 6a2127cd-9700-40fe-a42f-eff1d8306e6b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Couleur_solde_GL = IF([_Gene_Solde GL] > 0, "#A4E38A", "#FEA19E")
		lineageTag: 71488da4-7ad1-40eb-81ae-abf0c7682a49

		changedProperty = IsHidden

	measure Immos_acquisitions = ```
			CALCULATE([_Gene_Mvt Debit N], 'KPI'[Transfert]<>2)
			- CALCULATE([_Gene_Mvt Credit N], 
			'KPI'[Transfert]<>2,
			not (CONTAINSSTRING('KPI'[SchemaEcriture] , "|28") || CONTAINSSTRING('KPI'[SchemaEcriture] , "|675|")))
			```
		formatString: #,0
		lineageTag: 99062d29-0114-40c9-b49d-c2216c93c2d4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Immos_cessions = ```
			CALCULATE([_Gene_Mvt Credit N], 
			'KPI'[Transfert]<>2,
			FILTER(('KPI'),  CONTAINSSTRING('KPI'[SchemaEcriture] , "|28") || CONTAINSSTRING('KPI'[SchemaEcriture] , "|675|")))
			```
		formatString: #,0
		lineageTag: cc682ae1-4d6c-4fbc-813f-73fb4d4e118e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_ taux Amort P&L global N' =
			
			CALCULATE([_Immo_ taux Amort P&L global] , 'KPI'[Exercice] = "N")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 9ba1d07b-207b-4805-8a4a-9218509ee391

		changedProperty = IsHidden

	measure '_Immo_ taux Amort P&L global N-1' =
			
			CALCULATE([_Immo_ taux Amort P&L global] , 'KPI'[Exercice] = "N-1")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 40afa2ee-a9c7-49c7-b6f5-b447c90f4432

		changedProperty = IsHidden

	measure '_Gene_Solde Cumulé FY' =
			IF(Isblank([_Gene_Solde GL]),BLANK(),
			CALCULATE (
			    [_Gene_Solde GL],
			    FILTER (
			        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[FiscalQuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear] ),
			        AND(DimTemps[Dates] <= MAX (DimTemps[Dates]) ,
			        DimTemps[FiscalYear] = MAX ( DimTemps[FiscalYear] ))
			        ))
			)
		formatString: #,0.00
		lineageTag: 26782300-3107-444f-8272-ecfb2a11ef65

		changedProperty = IsHidden

	measure 'SOLDE GL hors AN' = CALCULATE([_Gene_Solde GL],'KPI'[CodeJournal] <> MAX(Parametrage[CodeAnouveauN]) &&'KPI'[CodeJournal] <> MAX(Parametrage[CodeAnouveauN_1]))
		formatString: #,0
		lineageTag: 61e7bac6-48c1-4ef8-a1cb-5d35bebc0f17

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Couleur_solde_GL hors AN' = IF([SOLDE GL hors AN] > 0, "#A4E38A", "#FEA19E")
		lineageTag: 548d2b91-bc44-4cf9-91e6-62d8f7da6216

		changedProperty = IsHidden

	measure 'testt taux' =
			CALCULATE (
			        [_Gene_Solde GL],
			        'PlanCompteAEF'[DetailNiv3] = "Dot. amort, dépréciations et prov" ,Compte[Racine4]<=6813
			    )
		lineageTag: 333e0ec6-8d56-4374-bbc8-3cb3a13290fc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Solde N Sankey' = CALCULATE([_Gene_Solde N] , 'KPI'[AN] = 2)
		formatString: #,0
		lineageTag: 3b258397-4ce1-4bb2-830a-dd2ab21c9130

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Solde N carte CAsh' =
			
			if(OR(MAX('CAshCompte - CA'[CAsh detailed rank1]) = 5 , MAX('CAshCompte - Creances'[CAsh detailed rank1]) = 11) ,CALCULATE( [_Gene_Solde N]+0- [_Gene_Solde N-1], ALL(SE)) , CALCULATE( [_Gene_Solde N carte] ))
		formatString: #,0
		lineageTag: c1862336-cfb7-4236-8bd6-3c3b403c02dd

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CAsh_Alerte = IF(ROUND([_Gene_Solde N],0) <> 0 , "L'écart dans le cadrage s'explique par la présence d'écritures déséquilibrées", BLANK())
		lineageTag: 2e73c2f9-b593-4662-aa1e-19c51f074dda

	measure TFT_Alerte = IF(ROUND([Solde ecart TFT Vecrit.],0) <> 0 , "L'écart dans le cadrage s'explique par la présence d'écritures déséquilibrées", BLANK())
		lineageTag: 4b0f7d5d-1335-46b0-a0cf-f8bc8a8c612a

	column AccountLegalName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: d27d1e9d-86ac-44a2-8cf3-2010235c1cbb
		summarizeBy: none
		sourceColumn: AccountLegalName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AccountNumber
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(max)
		lineageTag: 4f4c819d-db7f-4c04-bec2-ed7265db6a20
		summarizeBy: none
		sourceColumn: AccountNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: 7ac1456c-3a43-4fa9-97df-e13d8b69d23b
		summarizeBy: none
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	partition Accounts-1fdcd369-1ec7-4aef-80ba-02ac887b064c = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("datayoyo.fr:19128", "Cacbi", [HierarchicalNavigation=true]),
				    public = Source{[Schema="public"]}[Data],
				    Accounts1 = public{[Name="Accounts"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(Accounts1, each [ClientID] = ClientID)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

