table KPI
	lineageTag: 5e862e1b-6c7b-4a03-9a9c-d932589a30e3

	measure '_Achats_%var sous jacent' = ```
			var a = CALCULATE([_Gene_VariationN/N-1%],removefilters('Compte'[Racine3Libelle],'Compte'[Racine2],'Compte'[Racine3]),removefilters('KPI'[CompteName]))
			return 
			if ( a=0,"Sélectionner un sous-jacent",a)
			```
		formatString: #,##0.00 %
		displayFolder: 10. Achats
		lineageTag: b2a8d23d-254d-4fab-9632-24ed08bf9f10

		changedProperty = IsHidden

	measure _Achats_Ecart = ```
			VAR a =
			CALCULATE([_Gene_Solde N],removefilters('PlanCompteAEF'[DetailNiv2],'PlanCompteAEF'[DetailNiv3]))
			-(CALCULATE([_Gene_VariationN/N-1%],removefilters('Compte'[Racine3Libelle],'Compte'[Racine2],'Compte'[Racine3]),removefilters('KPI'[CompteName]))+1)
			* CALCULATE([_Gene_Solde N-1],removefilters('PlanCompteAEF'[DetailNiv2],'PlanCompteAEF'[DetailNiv3]))
			
			return
			if ( a=0,"Sélectionner un agrégat d'AACE",a)
			
			```
		formatString: #,##0
		displayFolder: 10. Achats
		lineageTag: dca0bc20-3e61-48f3-9f27-03e325ba9a57

		changedProperty = IsHidden

	measure '_Achats_Solde N-1' =
			var a = CALCULATE([_Gene_Solde N-1],removefilters('PlanCompteAEF'[DetailNiv2],'PlanCompteAEF'[DetailNiv3]))
			return
			if ( a=0,"Sélectionner un agrégat d'AACE",a)
		displayFolder: 10. Achats
		lineageTag: 641823e2-e76e-483b-aaec-de062cf864a7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Achats_Solde projeté' =
			var a = (CALCULATE([_Gene_VariationN/N-1%],removefilters('Compte'[Racine3Libelle],'Compte'[Racine2],'Compte'[Racine3]),removefilters('KPI'[CompteName]))+1)
			* CALCULATE([_Gene_Solde N-1],removefilters('PlanCompteAEF'[DetailNiv2],'PlanCompteAEF'[DetailNiv3]))
			
			return
			if ( a=0,"Sélectionner un agrégat d'AACE",a)
		formatString: #,##0
		displayFolder: 10. Achats
		lineageTag: ebc1d18a-1ce6-4ba4-9f75-d4c0150ad40c

		changedProperty = IsHidden

	measure '_Cadrage Mvts N' =
			VAR mvtcred = CALCULATE (SUM ( 'KPI'[MTCredit] ),'KPI'[Exercice] = "N")
			VAR mvtdev = CALCULATE (SUM ( 'KPI'[MTDebit] ),'KPI'[Exercice] = "N")
			
			RETURN
			
			if( isblank(mvtcred) || mvtcred = 0, -mvtcred, mvtdev)
		formatString: #,##0
		displayFolder: 08. Cadrage
		lineageTag: 2ca077db-996e-4ba9-b354-e6aa53d18f26

		changedProperty = IsHidden

	measure '_Cadrage Mvts N-1' =
			//if( isblank([_Gene_Mvt Debit N-1]) || [_Gene_Mvt Debit N-1] = 0,-[_Gene_Mvt Credit N-1],[_Gene_Mvt Debit N-1])
			
			VAR mvtcred = CALCULATE (SUM ( 'KPI'[MTCredit] ),'KPI'[Exercice] = "N-1")
			VAR mvtdev = CALCULATE (SUM ( 'KPI'[MTDebit] ),'KPI'[Exercice] = "N-1")
			
			RETURN
			
			if( isblank(mvtcred) || mvtcred = 0, -mvtcred, mvtdev)
		formatString: #,##0
		displayFolder: 08. Cadrage
		lineageTag: 266cc1ad-d6a0-4fce-9da2-ea561fe40ddd

		changedProperty = IsHidden

	measure _Cadrage_DateClotureCheck =
			
			IF(
			    OR (
			        [_Cadrage_DateClotureGL] = MAX ( 'Parametrage'[DateClotureN] ),
			        [_Cadrage_DateClotureGL] = MAX (Parametrage[DateClotureN_1] )
			    ),
			    1,
			    2
			)
		displayFolder: 08. Cadrage
		lineageTag: 5b9fc91c-3156-495c-8c13-a9c5474a704e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Cadrage_DateClotureGL = EOMONTH ( LASTDATE ( 'KPI'[DateComptable] ), 0 )
		formatString: dd/mm/yyyy
		displayFolder: 08. Cadrage
		lineageTag: c86acaa1-fba7-4cd7-b872-a29f8ad741b2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure _Cadrage_DateOuvertureCheck = ```
			
			IF(
			
			        [_Cadrage_DateOuvertureGL]
			            = MAX (Parametrage[DateOuvertureN] 
			    ),
			    1,
			    2
			)
			```
		displayFolder: 08. Cadrage
		lineageTag: ef4265c1-e3f4-471f-bcf6-0b35c033cc96

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Cadrage_DateOuvertureCheck 1' = ```
			
			IF(
			
			        [_Cadrage_DateOuvertureGL]
			            = MAX (Parametrage[DateOuvertureN_1] 
			    ),
			    1,
			    2
			)
			```
		displayFolder: 08. Cadrage
		lineageTag: 60cb636f-468f-4650-bc07-bf4813c26569

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Cadrage_DateOuvertureGL = STARTOFMONTH ( FIRSTDATE ( 'KPI'[DateComptable] ) )
		formatString: dd/mm/yyyy
		displayFolder: 08. Cadrage
		lineageTag: deadb0e5-918e-4dbf-aefb-48e3b2750e56

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure _Cadrage_EcartGL-BG = //[_Cadrage_Solde BG]-[_Gene_Solde GL]
		formatString: #,##0.00
		displayFolder: 08. Cadrage
		lineageTag: 6a9333a1-55a2-48fd-abc6-ea30c739c759

		changedProperty = IsHidden

	measure _Cadrage_EcartGL-BGABS = //ABS([_Cadrage_EcartGL-BG])
		displayFolder: 08. Cadrage
		lineageTag: 2c336a28-c02e-4cc6-9712-02981a634bbf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Cadrage_Solde BG' = //CALCULATE([Solde],FILTER('KPI','KPI'[BaseType]="BG"))
		formatString: #,##0
		displayFolder: 08. Cadrage
		lineageTag: bacb98d2-db26-4cd2-bd39-28a14c31e0b5

		changedProperty = IsHidden

	measure _Cadrage_Titre1 = //"Comptes présents en " & MAX('KPI'[BaseType]) & " uniquement: (" & DISTINCTCOUNT('KPI'[Compte]) & ")"
		displayFolder: 08. Cadrage
		lineageTag: 17517d68-4a82-4cc9-978c-4072539605ca

		changedProperty = IsHidden

	measure _Cadrage_TitreeA = //"Comptes présents en " & MAX('KPI'[BaseType]) & " uniquement: (" & DISTINCTCOUNT('KPI'[CompteSignificatifs]) & ")"
		displayFolder: 08. Cadrage
		lineageTag: ee1d98f9-980f-4707-b920-6c310ef4d533

		changedProperty = IsHidden

	measure _Gene_Cloture_Date = "Clôture du " & FORMAT(MAX(Parametrage[DateClotureN]),"dd/mm/yyyy")
		displayFolder: 08. Cadrage
		lineageTag: 79b934bc-0ba5-44ff-947a-f8e19723dfcf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Gene_Cloture_Date 2' = FORMAT(MAX(Parametrage[DateClotureN]),"dd/mm/yyyy")
		displayFolder: 08. Cadrage
		lineageTag: e49a2c88-a0ec-4d0a-a564-715be5f8b469

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _CP_CapSoc =
			IF(SELECTEDVALUE('Formes juridiques'[Formes juridiques]) <> {"Autre"},
			CALCULATE (
			    -[_Gene_Solde N],
			    PlanCompteAEF[LiasseCode]= "DA"),"Non applicable")
		formatString: #,##0
		displayFolder: 05. Capitaux propres
		lineageTag: a3b005e9-38a5-462d-99a5-5d1dc616b442

		changedProperty = IsHidden

	measure _CP_Controle1 = IF ( [_CP_SituationNette] > [_CP_MoitieCS], "OK", "Attention" )
		displayFolder: 05. Capitaux propres
		lineageTag: 0e0fcd8d-b93f-41b5-b004-67563c502a51

		changedProperty = IsHidden

	measure _CP_Controle1_num = IF([_CP_Controle1]="OK",1,0)
		displayFolder: 05. Capitaux propres
		lineageTag: f223bc73-a87e-4ca9-bc24-81a92b0acf6c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _CP_Controle2 =
			IF (SELECTEDVALUE('Formes juridiques'[Formes juridiques]) = "Autre","Non applicable",
			IF(DIVIDE([_CP_ReserveLegale],[_CP_CapSoc],0) >= 0.1,
			"OK : " & ROUND(DIVIDE([_CP_ReserveLegale],[_CP_CapSoc],0),4) * 100 & "%",
			"Attention : " & ROUND(DIVIDE([_CP_ReserveLegale],[_CP_CapSoc],0),4) * 100 & "%"))
		displayFolder: 05. Capitaux propres
		lineageTag: ea54a170-c3ea-415a-a67c-5977ef9d2e8f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _CP_Controle2_num = IF( [_CP_Controle2]="Non applicable",2, IF(DIVIDE([_CP_ReserveLegale] , [_CP_CapSoc],0)>=0.1,1,0))
		displayFolder: 05. Capitaux propres
		lineageTag: 8d397afa-c9eb-4215-b132-a435784598f2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _CP_HorsResultat =
			CALCULATE (
			    -[_Gene_Solde N],
			    'PlanCompteAEF'[DetailNiv1] = "Capitaux propres (hors résultat)"
			) + 1 * 0
		formatString: ### ### ###
		displayFolder: 05. Capitaux propres
		lineageTag: 050c42b0-d68f-4068-a22e-23ccd7b3d7cf

		changedProperty = IsHidden

	measure _CP_MoitieCS =
			CALCULATE (
			    -[_Gene_Solde N],
			    'PlanCompteAEF'[LiasseLibelle] = "DA - Capital social ou individuel"
			) / 2
		formatString: ### ### ###
		displayFolder: 05. Capitaux propres
		lineageTag: 5e7e8d12-e1b7-42bc-af6e-8398679f39e9

		changedProperty = IsHidden

	measure _CP_ReserveLegale =
			IF(SELECTEDVALUE('Formes juridiques'[Formes juridiques]) <> "Autre",
			CALCULATE (
			    -[_Gene_Solde N],
			    PlanCompteAEF[LiasseCode] = "DD"
			),"Non applicable")
		formatString: #,##0
		displayFolder: 05. Capitaux propres
		lineageTag: f7b2fb68-9a15-462f-ad64-7a6c038a6490

		changedProperty = IsHidden

	measure _CP_ResultatNet = CALCULATE ( -[_Gene_Solde N], 'PlanCompteAEF'[BilanNiv2] = "Résultat net" ,ALL(PlanCompteAEF[DetailNiv3]), ALL('KPI'[CompteSignificatifs]),ALL(Compte[Racine3]),ALL('KPI'[CompteName]),ALL(PlanCompteAEF[LiasseLibelle])) + 1 * 0
		formatString: ### ### ###
		displayFolder: 05. Capitaux propres
		lineageTag: 7e3d798d-4228-458e-b95a-1829eb5262de

		changedProperty = IsHidden

	measure '_CP_ResultatNet N-1' = CALCULATE ( [_Gene_Solde N-1], 'PlanCompteAEF'[BilanNiv2] = "Résultat net" ,ALL(PlanCompteAEF[DetailNiv3]), ALL('KPI'[CompteSignificatifs]),ALL(Compte[Racine3]),ALL('KPI'[CompteName]),ALL(PlanCompteAEF[LiasseLibelle])) + 1 * 0
		formatString: #,##0
		displayFolder: 05. Capitaux propres
		lineageTag: 35530023-637a-44fd-a4ba-9bde746979a5

		changedProperty = IsHidden

	measure _CP_SituationNette = [_CP_HorsResultat]+[_CP_ResultatNet]
		formatString: ### ### ###
		displayFolder: 05. Capitaux propres
		lineageTag: 051f35e6-fc78-4374-94ca-24d6fb3c0c09

		changedProperty = IsHidden

	measure '_Client_Tx prov' = -DIVIDE([_Clients_491],[_ClientsDouteuxHT],0)
		formatString: #,##0 %
		displayFolder: 03. Clients\Clients_global
		lineageTag: 08f5bf36-2241-45cc-b788-31cf22020912

		changedProperty = IsHidden

	measure '_Clients 416' =
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine3] = 416)+1*0
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: a9120762-66af-4b02-a948-6f603a854172

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _Clients_491 =
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine3] = 491)+1*0
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: d281d46d-dce2-4894-be4b-13b5baa2389d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Clients_681N = ```
			
			CALCULATE(
			    [_Gene_Solde GL],
			    Compte[Racine5] = 68174 || Compte[Racine4] = 6714,
			    'KPI'[Exercice] = "N"
			) + 0
			
			
			```
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: 97afabcd-3dfd-48f7-92aa-c2dbd4307221

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _Clients_781N =
			CALCULATE (
			CALCULATE(
			    [_Gene_Solde GL],
			    Compte[Racine5] = 78174 || Compte[Racine4] = 7714,
			    'KPI'[Exercice] = "N"
			) + 0
			)
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: daf712e3-b57a-47cc-b7e1-678ce4a23d42

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _Clients_Bouclage_Ecart = [_Clients_Var491Dépré] + [Clients_681N] + [_Clients_781N] + 1 * 0
		formatString: #,##0
		displayFolder: 03. Clients\Clients_global
		lineageTag: 09339a2f-a488-46e2-8b2a-f60056266650

		changedProperty = IsHidden

	measure _Clients_Bouclage_Ecart_num =
			IF (
			    AND ( [_Clients_Bouclage_Ecart] > -0.1, [_Clients_Bouclage_Ecart] < 0.1 ),
			    1,
			    0
			)
		displayFolder: 03. Clients\Clients_global
		lineageTag: e544cfcd-570a-43ff-a458-d4300cd2aab6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Clients_DRMCltsN =
			DIVIDE (
			    CALCULATE ( [_Gene_Solde GL], 'PlanCompteAEF'[LiasseCode] in {"BX","BY"} ),
			    CALCULATE ( [_Gene_Solde GL], 'PlanCompteAEF'[CategorieREX] = "Chiffre d'affaires" ),
			    0
			)
			    * DATEDIFF (
			        MAX ( Parametrage[DateClotureN] ),
			        MAX ( Parametrage[DateOuvertureN] ),
			        DAY
			    ) / ( 1 + [_mesValeurTVAN] / 100 )
		displayFolder: 03. Clients\Clients_global
		lineageTag: 6b31e763-faaa-453f-8020-a653a7ee817f

		changedProperty = IsHidden

	measure _Clients_DRMCltsN-1 =
			DIVIDE (
			    CALCULATE ( [_Gene_Solde GL], 'PlanCompteAEF'[LiasseCode] in {"BX","BY"}),
			    CALCULATE ( [_Gene_Solde GL], 'PlanCompteAEF'[CategorieREX] = "Chiffre d'affaires" ),
			    0
			)
			    * DATEDIFF (
			        MAX ( Parametrage[DateClotureN_1] ),
			        MAX ( Parametrage[DateOuvertureN_1] ),
			        DAY
			    ) / ( 1 + [_mesValeurTVAN-1] / 100 )
		displayFolder: 03. Clients\Clients_global
		lineageTag: 2b36fa00-2c1b-4121-a603-71be8122b2f0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Clients_TauxDepreClient =
			- DIVIDE (
			    CALCULATE ( [_Gene_Solde carte], 'PlanCompteAEF'[LiasseCode] = "BY" ),
			    CALCULATE ( [_Gene_Solde GL], PlanCompteAEF[LiasseCode] = "BX" )
			    ,
			    0
			)
		formatString: #,##0.0 %
		displayFolder: 03. Clients\Clients_global
		lineageTag: a0ef83dd-3174-47d0-9350-1d588c308cfc

		changedProperty = IsHidden

	measure _Clients_Var491Dépré =
			
			[_Clients_Var491Dépré pour table] +0
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: 8b148fcf-b3e9-4fed-b191-e903dced28cc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _ClientsDouteuxHT =
			
			DIVIDE(
			    [_Clients 416],
			    1+(if ( max('KPI'[Exercice]) = "N",[Selected value T1]/100,[Selected value T2]/100)),
			    0
			)+1*0
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: ea219697-9a2f-4cef-83e4-7c41962e2686

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Mvt Credit N' = ```
			
			
			CALCULATE(CALCULATE (SUM ( 'KPI'[MTCredit] ),'KPI'[Exercice] = "N", ParamAN[AN - O/N] = "Non"))
			
			```
		formatString: #,##0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 1c3d48da-2092-4f87-9f76-c2085632a11b

		changedProperty = IsHidden

	measure '_Gene_Mvt Credit N pour carte' = ```
			[_Gene_Mvt Credit N]+0
			
			```
		formatString: #,##0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 495cdc67-4de3-4090-a50e-90773e16544e

		changedProperty = IsHidden

	measure '_Gene_Mvt Credit N-1' =
			
			CALCULATE (
			    SUM ( 'KPI'[MTCredit] ),
			    'KPI'[Exercice] = "N-1",
			    ParamAN[AN - O/N] = "Non"
			)
		formatString: #,##0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: fe4aa448-df0c-4fe5-b4a5-a1cef9dc81fc

		changedProperty = IsHidden

	measure '_Gene_Mvt Credit N-1 pour carte' = ```
			[_Gene_Mvt Credit N-1]+0
			
			
			```
		formatString: #,##0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: a3947e2b-96ca-420a-93f1-e1e0c841f25f

		changedProperty = IsHidden

	measure '_Gene_Mvt Debit N' =
			
			
			CALCULATE (CALCULATE (
			    SUM ( 'KPI'[MTDebit] ),
			    'KPI'[Exercice] = "N",
			    ParamAN[AN - O/N] = "Non"
			))
		formatString: #,##0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: d13326a6-8934-4cf6-a458-bb73712f6615

		changedProperty = IsHidden

	measure '_Gene_Mvt Debit N inv' = -[_Gene_Mvt Debit N]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 312f08eb-564b-438a-b540-f9ff9a997a3e

		changedProperty = IsHidden

	measure '_Gene_Mvt Debit N pour carte' = ```
			[_Gene_Mvt Debit N]+0
			
			```
		formatString: #,##0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 8e91e9a2-67d9-447f-84fc-3570f015a62a

		changedProperty = IsHidden

	measure '_Gene_Mvt Debit N-1' =
			
			CALCULATE (
			    SUM ( 'KPI'[MTDebit] ),
			    'KPI'[Exercice] = "N-1",
			    ParamAN[AN - O/N] = "Non"
			)
		formatString: #,##0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 7b29d2cf-8cee-4418-962c-7412ff1273fa

		changedProperty = IsHidden

	measure '_Gene_Mvt Debit N-1 pour carte' = [_Gene_Mvt Debit N-1]+0
		formatString: #,##0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: c17ce10d-0b6c-43ef-9e25-2678fda9a117

		changedProperty = IsHidden

	measure '_Immo_Amort Bilan HorsAN' =
			
			CALCULATE(
			        [_Immo_Dot Amort N],
			        'PlanCompteAEF'[DetailNiv3] = "Dép. / amort. immobilisations incorporelles"
			            ||'PlanCompteAEF'[DetailNiv3] = "Dép. / amort. immobilisations corporelles"
			            ||'PlanCompteAEF'[DetailNiv3] = "Dép. immobilisations financières",
			        ParamAN[A/N - Bridge]=""
			)+ 1 * 0
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: b75658a4-a0a5-48c7-a536-2169e159001a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_Amort Bouclage Ecart' = [_Immo_Amort Bilan HorsAN]-[_Immo_Amort P&L]
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 0a8c79e6-a04f-4300-931d-fe4b4c9e9fb1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_Amort P&L' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    'PlanCompteAEF'[DetailNiv3] = "Dot. amort, dépréciations et prov",'KPI'[Exercice]="N" ,Compte[Racine4]<=6813
			)+0
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 8ca41d1a-bef4-4b2f-92b1-c0fa282599e6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_Dot Amort N' =
			
			CALCULATE(
			    SUM ( 'KPI'[MTCredit] ),
			    'KPI'[Exercice] = "N",
			    Compte[Racine2]<>29,
			    ParamAN[AN - O/N] = "Non"
			)
		formatString: ### ### ###
		displayFolder: 02. Immobilisations
		lineageTag: c842077f-ea56-4591-9a68-a54e25330f77

		changedProperty = IsHidden

	measure '_Immo_Dot Depre N' =
			
			CALCULATE(
			    SUM ( 'KPI'[MTCredit] ),
			    'KPI'[Exercice] = "N",
			    Compte[Racine2]=29,
			    ParamAN[AN - O/N] = "Non"
			)
		formatString: ### ### ###
		displayFolder: 02. Immobilisations
		lineageTag: f1c044c1-f895-4b14-823c-b4258abc2339

		changedProperty = IsHidden

	measure '_Immo_P CEAC' = [_Immo_P CEAC pour table]+0
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: d2d2cce3-e4f1-4a11-a43f-7a33f19927d1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_PV Cession' = -[_Immo_VNC P&L]+[_Immo_P CEAC] +0
		formatString: #,##0
		displayFolder: 02. Immobilisations
		lineageTag: 71d032a4-0a03-4cf1-b5cf-09d202257679

		changedProperty = IsHidden

	measure '_Immo_Rep Amort N' =
			
			CALCULATE(
			    SUM ( 'KPI'[MTDebit] ),
			    'KPI'[Exercice] = "N",
			    Compte[Racine2]<>29,
			    ParamAN[AN - O/N] = "Non"
			)
		formatString: ### ### ###
		displayFolder: 02. Immobilisations
		lineageTag: 4f2b092c-04b5-482a-a269-268af48f97cb

		changedProperty = IsHidden

	measure '_Immo_Rep Depre N' =
			
			CALCULATE(
			    SUM ( 'KPI'[MTDebit] ),
			    'KPI'[Exercice] = "N",
			    Compte[Racine2]=29,
			    ParamAN[AN - O/N] = "Non"
			)
		formatString: ### ### ###
		displayFolder: 02. Immobilisations
		lineageTag: 0315d68f-afb4-4633-99e1-fa19f0d706b1

		changedProperty = IsHidden

	measure '_Immo_Taux Depre' =
			
			DIVIDE (
			    CALCULATE (
			       [_Gene_Solde GL],
			       Compte[Racine5]=68662
			        ),
			    CALCULATE (
			        [_Gene_Solde GL],
			            'PlanCompteAEF'[DetailNiv3] = "Immobilisations incorporelles brutes"||
			            'PlanCompteAEF'[DetailNiv3]  = "Immobilisations corporelles brutes"||
			            'PlanCompteAEF'[DetailNiv3]  = "Immobilisations financières brutes"
			        )
			    )
			+ 1 * 0
		formatString: #,##0.0 %
		displayFolder: 02. Immobilisations
		lineageTag: eb4effe3-3925-4f07-9427-2ac511235a0a

		changedProperty = IsHidden

	measure '_Immo_Taux Dot' =
			
			DIVIDE (
			    [_Immo_Amort P&L],
			    CALCULATE (
			        [_Gene_Solde GL],
			            'PlanCompteAEF'[DetailNiv3] = "Immobilisations incorporelles brutes"||
			            'PlanCompteAEF'[DetailNiv3]  = "Immobilisations corporelles brutes"
			        ),0
			)
			+ 1 * 0
		formatString: #,##0.0 %
		displayFolder: 02. Immobilisations
		lineageTag: 55374491-b2b3-4ea0-82b0-cdd4821317c0

		changedProperty = IsHidden

	measure '_Immo_VNC Bilan' =
			
			[_Immo_VNC Bilan pour table]+ 1 * 0
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 691d7843-c4f4-43f9-8e36-335976ea0118

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_VNC Ecart' = [_Immo_VNC Bilan]- [_Immo_VNC P&L]
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: d3b0898d-84eb-42f4-9221-f1f3a716bd57

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Nbr de jours N' =
			FORMAT (
			    MAX ( 'Parametrage'[DateClotureN] )
			        - MAX ( 'Parametrage'[DateOuvertureN] ) + 1,
			    "General Number"
			)
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: f1493922-75d4-4a64-b476-6ea0772ab4ed

		changedProperty = IsHidden

	measure 'Nbr de jours N-1' =
			FORMAT (
			    MAX ( 'Parametrage'[DateClotureN_1] )
			        - MAX ( 'Parametrage'[DateOuvertureN_1] ) + 1,
			    "General Number"
			)
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: 5c63ee0a-ae55-4a6d-a1a3-ef2642472aae

		changedProperty = IsHidden

	measure 'Nbr jour max full year N' =
			
			VAR AccountNumber0 = SELECTEDVALUE ( Parametrage[AccountNumber] )
			VAR Annee0 = CALCULATE ( MAX ( 'DimTemps'[FiscalYear] ), FILTER('KPI',AND('KPI'[AccountNumber]=AccountNumber0,'KPI'[Exercice]="N")))
			RETURN
			    IF ( MOD ( Annee0, 4 ) = 0, 366, 365 )
		formatString: 0
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: 14a8353b-878a-4b5f-8165-e06a4adce348

		changedProperty = IsHidden

	measure 'Nbr jour max full year N-1' =
			
			VAR AccountNumber0 = SELECTEDVALUE ( Parametrage[AccountNumber] )
			VAR Annee0 = CALCULATE ( MAX ( 'DimTemps'[FiscalYear] ), FILTER('KPI',AND('KPI'[AccountNumber]=AccountNumber0,'KPI'[Exercice]="N-1")))
			RETURN
			    IF ( MOD ( Annee0, 4 ) = 0, 366, 365 )
		formatString: 0
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: 3bd95ad9-c7ba-439a-962a-777fed241782

		changedProperty = IsHidden

	measure 'Nbr jour max N' =
			
			VAR AccountNumber0 = SELECTEDVALUE ( Parametrage[AccountNumber] )
			
			Return
			CALCULATE(MAX(DimTemps[DayOfYear]), FILTER('KPI',AND('KPI'[AccountNumber]=AccountNumber0,'KPI'[Exercice]="N")))
		formatString: #,##0
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: 11b5b093-34b0-4aeb-b0b7-e1c5c28c72c9

		changedProperty = IsHidden

	measure 'Nbr jour max N-1' =
			//calculate (Max('DimTemps'[DayofYear]),'DimTemps'[Dates]=Max('Parametrage'[DateClotureN_1]))
			VAR AccountNumber0 = SELECTEDVALUE ( Parametrage[AccountNumber] )
			
			Return
			CALCULATE(MAX(DimTemps[DayOfYear]), FILTER('KPI',AND('KPI'[AccountNumber]=AccountNumber0,'KPI'[Exercice]="N-1")))
		formatString: #,##0
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: b9b1b0bc-194d-4889-aa87-33272995b326

		changedProperty = IsHidden

	measure 'Nbr jour min equiv N' = [Selected value T9] + [Nbr jour min N] -1
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: 8739ab79-2488-4e33-89d3-58c99625da53

		changedProperty = IsHidden

	measure 'Nbr jour min equiv N-1' = [Selected value T8] + [Nbr jour min N-1] -1
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: 26fdd200-c6ba-4b63-b8d3-07cb6ae07ea0

		changedProperty = IsHidden

	measure 'Nbr jour min N' = ```
			[Nbr jour max N]-[Nbr de jours N]+1
			
			```
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: a2e08e51-b54a-4515-af1b-a01dcf66c812

		changedProperty = IsHidden

	measure 'Nbr jour min N-1' = ```
			[Nbr jour max N-1]-[Nbr de jours N-1]+1
			
			```
		displayFolder: 01. Mesures globales\Nombre de jours (A revoir)
		lineageTag: a0944dca-0daa-4928-b34f-d751096e1df6

		changedProperty = IsHidden

	measure '_615_Population restante' = [_615_Population totale]-[_615_Population testée]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: c92515a2-7ed1-4893-a7f2-d01b8c62bb3f

		changedProperty = IsHidden

	measure '_615_Population testée' = ```
			
			    calculate(
			        [_Gene_Solde N],
			        TOPN([Selected value T3],
			        values('KPI'[EcritureNumero]),[_Gene_Solde N],
			        desc)
			    )
			```
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: bdeb227a-7791-4962-a9cd-28b8bcadcb49

		changedProperty = IsHidden

	measure '_615_Population totale' = CALCULATE([_Gene_Solde N],ALL('KPI'[EcritureNumero]))
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: 837572eb-8e8e-41f9-85a1-746e38b61549

		changedProperty = IsHidden

	measure '_SAP Pop globale' = CALCULATE([_Gene_Solde N],ALL(Compte[Racine3]),ALL('KPI'[CompteName]))
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: 2bd64167-a649-4f02-bc1d-6577cc6a730f

		changedProperty = IsHidden

	measure '_SAP Pop globale 1' = CALCULATE(0,ALL('KPI'[CompteName]))
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: 9db029ba-802b-4cfe-80a6-2b6c34427d2f

		changedProperty = IsHidden

	measure '_SAP Pop globale bilan' = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="Bilan",ALL(Compte[Racine3]),ALL('KPI'[CompteName]))
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: ce2e6444-28ea-4725-93ed-44f4cd28b35b

		changedProperty = IsHidden

	measure '_SAP Pop globale P&L' = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L",ALL(Compte[Racine3]),ALL('KPI'[CompteName]))
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: 28a97c90-1f21-48f6-a7fb-9dd367cd7ef7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_SAP Pop non testée' = [_SAP Pop globale]-[_SAP Pop testée]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: db2ac946-596f-4427-ad35-5b20a8d02650

		changedProperty = IsHidden

	measure '_SAP Pop non testée bilan' = [_SAP Pop globale bilan]-[_SAP Pop testée bilan]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: b90d0c81-c00c-41a5-91bc-319dcfb70d86

		changedProperty = IsHidden

	measure '_SAP Pop non testée P&L' = [_SAP Pop globale P&L]-[_SAP Pop testée P&L]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: c32f422d-2f8c-4325-afcd-572463d3766f

		changedProperty = IsHidden

	measure '_SAP Pop testée' = [_Gene_Solde N]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: 121d193a-254d-4734-afa7-9c6ec890801d

		changedProperty = IsHidden

	measure '_SAP Pop testée bilan' = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="Bilan")
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: c5bcafb7-bc6c-4bbf-9261-aefa130e2aa1

		changedProperty = IsHidden

	measure '_SAP Pop testée P&L' = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L")
		formatString: #,##0
		displayFolder: 01. Mesures globales\Population résiduelle
		lineageTag: 9407ca1b-9d2d-435a-b3ff-9c681f54482d

		changedProperty = IsHidden

	measure _615_Rankx =
			
			if([_615_RankX EcritureN]<=[Selected value T3],"Yes","No")
		displayFolder: 01. Mesures globales\Rank
		lineageTag: 2834a778-1377-4d05-8e3e-86c6d96c9a8c

		changedProperty = IsHidden

	measure '_615_RankX EcritureN' =
			rankx(
			        all('KPI'[EcritureNumero]),
			        calculate([_Gene_Solde N]),
			        ,
			        DESC,
			        Dense)
		displayFolder: 01. Mesures globales\Rank
		lineageTag: 40ce39a7-4414-4be4-911e-82da8348e740

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _CA_Rankx =
			
			if([_CA_RankX EcritureN]<=[Selected value T3],"Yes","No")
		displayFolder: 01. Mesures globales\Rank
		lineageTag: 4e515632-865e-4978-a892-c3922c8968ed

		changedProperty = IsHidden

	measure '_CA_RankX EcritureN' =
			rankx(
			        all('KPI'[EcritureNumero]),
			        -calculate([_Gene_Solde N]),
			        ,
			        DESC,
			        Dense)
		displayFolder: 01. Mesures globales\Rank
		lineageTag: 5e776ae8-1b27-448b-b0e8-79b6d09e234c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_CA_Top Ventes' = ```
			
			    calculate(
			        [_Gene_Solde inv],
			        TOPN([Selected value T3],
			        values('KPI'[EcritureNumero]),[_Gene_Solde inv],
			        desc)
			    )
			```
		displayFolder: 01. Mesures globales\Rank
		lineageTag: 8a244b05-a73a-4b0c-8a6f-5997dbe9a1ed

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_CA_Top Ventes N' = ```
			
			    calculate(
			        [_Gene_Solde N inv],
			        TOPN([Selected value T3],
			        values('KPI'[EcritureNumero]),[_Gene_Solde N inv],
			        desc)
			    )
			```
		displayFolder: 01. Mesures globales\Rank
		lineageTag: 64170879-f696-4dd3-b7b7-bb6a7ea3e1d2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_CA_Top Ventes N-1' = ```
			
			    calculate(
			        [_Gene_Solde N-1 inv],
			        TOPN([Selected value T3],
			        values('KPI'[EcritureNumero]),[_Gene_Solde N-1 inv],
			        desc)
			    )
			```
		displayFolder: 01. Mesures globales\Rank
		lineageTag: 74e34531-703c-4b6b-8355-bbce4ebd8468

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Gene_Solde carte' = [_Gene_Solde GL]+0
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 10f200b0-3660-45a7-9074-c2bcc6726556

		changedProperty = IsHidden

	measure '_Gene_Solde Cumulé' =
			
			IF(Isblank([_Gene_Solde GL]),BLANK(),
			CALCULATE (
			    [_Gene_Solde GL],
			    FILTER (
			        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[FiscalQuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear], DimTemps[FiscalQuarter] ),
			        DimTemps[Dates] <= MAX (DimTemps[Dates]) && DimTemps[FiscalMonth] <= MAX(DimTemps[FiscalMonth]) && DimTemps[FiscalQuarter] <= MAX(DimTemps[FiscalQuarter]) && DimTemps[DayOfYear] <= MAX(DimTemps[DayOfYear])
			       &&MAX('KPI'[Exercice])= "N")
			        ))
			+ IF(Isblank([_Gene_Solde GL]),BLANK(),
			CALCULATE (
			    [_Gene_Solde GL],
			    FILTER (
			        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[FiscalQuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear],DimTemps[FiscalQuarter] ),
			        DimTemps[Dates] <= MAX (DimTemps[Dates]) && DimTemps[FiscalMonth] <= MAX(DimTemps[FiscalMonth])&& DimTemps[FiscalQuarter] <= MAX(DimTemps[FiscalQuarter])&& DimTemps[DayOfYear] <= MAX(DimTemps[DayOfYear])
			       &&MAX('KPI'[Exercice])= "N-1")
			        ))
			
			//IF(Isblank([_Gene_Solde GL]),BLANK(),
			//CALCULATE (
			//    [_Gene_Solde GL],
			//    FILTER (
			//        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[FiscalQuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear] ),
			//        AND(DimTemps[Dates] <= MAX (DimTemps[Dates]) ,
			//        DimTemps[FiscalYear] = MAX ( DimTemps[FiscalYear] ))
			//        ))
			//)
		formatString: #,##0.00
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 53161d29-a840-4128-95cf-e75c50491291

		changedProperty = IsHidden

	measure '_Gene_Solde Cumulé inv' = -[_Gene_Solde Cumulé]
		formatString: #,##0.00
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: aaf90566-4d86-4a22-9f6d-e7f94d82c959

		changedProperty = IsHidden

	measure '_Gene_Solde GL' = CALCULATE([Solde])
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 874f4ab0-cae3-4666-8daf-6f8ca1fe16fa

		changedProperty = IsHidden

	measure '_Gene_Solde GL pour tod' = ```
			VAR filtre1 = Treatas(values ('KPI'[EcritureLibelle]), 'KPI'[EcritureLibelle])
			VAR filtre2 = Treatas(values ('KPI'[DateComptable]), 'KPI'[DateComptable])
			
			return
			
			CALCULATE([_Gene_Solde GL],'KPI'[EcritureLibelle] in filtre1 || 'KPI'[DateComptable] in filtre2 ) 
			```
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 63caa64b-d498-4f7b-a8a1-e27e8f551227

		changedProperty = IsHidden

	measure '_Gene_Solde inv' = -[_Gene_Solde GL]
		formatString: #,##0.00
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: a97cb03b-79e2-4247-a838-a7c8fcf4b43e

		changedProperty = IsHidden

	measure '_Gene_Solde inv debit' = calculate (-[_Gene_Solde GL],'KPI'[MTDebit]<>0)
		formatString: #,##0.00
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 23a56995-b6d4-47c8-b6f7-0e1fd8c5ef5b

		changedProperty = IsHidden

	measure '_Gene_Solde Inversé carte' = [_Gene_Solde inv]+0
		formatString: #,0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: dcae221b-33a5-4c7c-9074-9ce910a794a4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Solde Moyen' = ```
			
			
			    CALCULATE (
			        DIVIDE(
			            [_Gene_Solde GL],
			            [_Gene_Nb Lignes],
			            0))
			```
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 1f933c2c-ecec-42b4-9055-4bdb5c55c13d

		changedProperty = IsHidden

	measure '_Gene_Solde Moyen basic' = ```
			
			        DIVIDE(
			            [_Gene_Solde GL],
			            [_Gene_Nb Lignes],
			            0)
			    
			```
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: e1f28f83-eb7c-49b9-bde2-6371cd2e0823

		changedProperty = IsHidden

	measure '_Gene_Solde Moyen inv' = ```
			
			        DIVIDE(
			            [_Gene_Solde inv],
			            [_Gene_Nb Lignes],
			            0)
			```
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 22b4627b-c948-4dff-97f8-3e5a987c9a87

		changedProperty = IsHidden

	measure '_Gene_Solde Moyen N' =
			
			ABS(
			    CALCULATE(
			        DIVIDE(
			            [_Gene_Solde GL],
			            [_Gene_Nb Lignes],
			            0),
			        'KPI'[Exercice]="N"
			    )
			)
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 4e773e91-2adc-4c42-b63a-f6afbe5d60c4

		changedProperty = IsHidden

	measure '_Gene_Solde Moyen N-1' =
			
			ABS(
			    CALCULATE(
			        DIVIDE(
			            [_Gene_Solde GL],
			            [_Gene_Nb Lignes],
			            0),
			        'KPI'[Exercice]="N-1"
			    )
			)
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 26b68aa1-2907-430a-9ce4-2172ba7df53f

		changedProperty = IsHidden

	measure '_Gene_Solde N' = ROUND( CALCULATE([_Gene_Solde GL],FILTER('KPI','KPI'[Exercice]="N")),2)
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 4f11fb4e-728c-4d4a-891d-2c1a0c0cc3f1

		changedProperty = IsHidden

	measure '_Gene_Solde N AN' = ROUND(CALCULATE([_Gene_Solde N],ParamAN[AN - O/N] = "Oui"),2)
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: c2948fcf-ef7b-44f5-af10-bb19c4a1ab37

		changedProperty = IsHidden

	measure '_Gene_Solde N calculé' = [_Gene_Solde N-1]+[_Gene_Mvt Debit N]-[_Gene_Mvt Credit N]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 42110419-78d8-49d3-af48-808f10e655f0

		changedProperty = IsHidden

	measure '_Gene_Solde N calculé vs réel' = [_Gene_Solde N calculé]- [_Gene_Solde N]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 9685850a-5fc1-4c53-9a99-e2995b0e9178

		changedProperty = IsHidden

	measure '_Gene_Solde N inv' = - [_Gene_Solde N]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: c7f0f698-9ef1-4b9b-ad9b-24498c190d59

		changedProperty = IsHidden

	measure '_Gene_Solde N-1' = CALCULATE([_Gene_Solde GL],filter('KPI','KPI'[Exercice]="N-1"))
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 3187a39e-5af4-4d34-a0f7-96bc1b907633

		changedProperty = IsHidden

	measure '_Gene_Solde N-1 inv' = - [_Gene_Solde N-1]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 9142e411-048e-4894-981d-830faf140383

		changedProperty = IsHidden

	measure '_Gene_Solde pour excl nb jours N 1' = calculate ([_Gene_Solde N-1],AllEXCEPT('KPI','KPI'[Exercice]),All('Compte'))
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 7caaae56-4cb4-4454-8efe-98d7476c4148

		changedProperty = IsHidden

	measure '_Gene_Titre CA' = ```
			" Analyse "
			    & if(MAX('FieldParam_measures'[Code])=2,"des ","du ")
			    & MAX ( 'FieldParam_measures'[Value] ) & 
			    " par code journal"
			```
		formatString: #,##0.00
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 726b76af-2b94-4e0b-9149-42b831a5968a

		changedProperty = IsHidden

	measure '_Gene_Variation N/N-1' = [_Gene_Solde N]-[_Gene_Solde N-1]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 2e4c559a-c69b-484b-bcb8-0e01bc97094f

		changedProperty = IsHidden

	measure '_Gene_Variation N/N-1 abs' = abs([_Gene_Variation N/N-1])
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 00d8ddae-7742-49a6-8e75-b10a9b25a7e0

		changedProperty = IsHidden

	measure '_Gene_Variation N/N-1_inv' = -[_Gene_Variation N/N-1]
		formatString: #,##0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 2b1ae6e1-4b5d-498c-b801-1f4fd790fe60

		changedProperty = IsHidden

	measure _Gene_VariationN/N-1% = DIVIDE([_Gene_Variation N/N-1],[_Gene_Solde N-1],0)
		formatString: #,##0 %
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 2f57963d-a7ef-4ab6-b160-d872d1e67d26

		changedProperty = IsHidden

	measure _Gene_VariationN/N-1%_inv = -[_Gene_VariationN/N-1%]
		formatString: #,##0 %
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 8e442049-4063-4373-9327-855afd68bc6c

		changedProperty = IsHidden

	measure Solde =
			
			ROUND([Debit] - [Credit],2)
		formatString: #,0.00
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 2ae9a227-a54c-4825-a750-4aa02c9194c2

		changedProperty = IsHidden

	measure _Stocks_BouclageBrut = [_Stocks_VarBrutBilan] + [_Stocks_VarBrutP&L]
		formatString: #,##0
		displayFolder: 04. Stocks
		lineageTag: d096ef60-a3a1-446c-a895-b3d59b30e33f

		changedProperty = IsHidden

	measure _Stocks_BouclageBrut_num = IF(ABS([_Stocks_BouclageBrut])<0.1,0,1)
		displayFolder: 04. Stocks
		lineageTag: 8c3f50e5-93f7-4bf6-a4c8-fded870ae81a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Stocks_BouclageDépré = [_Stocks_VarDépréBilan] + [_Stocks_DotDépréP&L] + [_Stocks_RepDépréP&L] + 1*0
		formatString: #,##0
		displayFolder: 04. Stocks
		lineageTag: 79035615-80e6-4a98-8cf9-89e75649be87

		changedProperty = IsHidden

	measure _Stocks_BouclageDépré_num = IF( ABS([_Stocks_BouclageDépré])<0.1,0,1)
		displayFolder: 04. Stocks
		lineageTag: 5b408bc1-026a-47a0-a114-e4bd0c32fe0f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Stocks_DépréciationTaux =
			ROUND(DIVIDE (
			    ROUND(CALCULATE (
			        - [_Gene_Solde GL],
			        FILTER ( 'PlanCompteAEF', 'PlanCompteAEF'[MarquageStocks] = "Dépré Stocks" )
			    ),0),
			    ROUND(CALCULATE (
			        [_Gene_Solde GL],
			        FILTER ( 'PlanCompteAEF', 'PlanCompteAEF'[MarquageStocks] = "Stocks bruts" )
			    ),0),
			    0
			) ,3)
		formatString: #,##0.0 %
		displayFolder: 04. Stocks
		lineageTag: f4a485a3-14b6-4b35-b24c-eb4ace933c68

		changedProperty = IsHidden

	measure _Stocks_DotDépréP&L = CALCULATE ( [_Gene_Solde N], FILTER ( Compte, Compte[Racine5] = 68173 ) ) + 1 * 0
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: 0c32eabb-dfae-40aa-a5d5-f0683e87c117

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _Stocks_Ecoulement_MP = ```
			
			- divide(CALCULATE (
			    [_Gene_Solde GL],
			    FILTER (
			        'PlanCompteAEF',
			        'PlanCompteAEF'[LiasseCode] IN { "BT", "BL"}
			    )
			)
			    , CALCULATE (
			        [_Gene_Solde GL],
			        'PlanCompteAEF'[LiasseCode] in { "FS","FU","FV","FT"}
			    ),0)
			    * IF (
			        MAX ( 'KPI'[Exercice] ) = "N",
			        DATEDIFF (
			            MAX ( Parametrage[DateClotureN] ),
			            MAX ( Parametrage[DateOuvertureN] ),
			            DAY
			        ) + 1,
			        DATEDIFF (
			            MAX ( Parametrage[DateClotureN_1] ),
			            MAX ( Parametrage[DateOuvertureN_1] ),
			            DAY
			        ) + 1
			    ) 
			```
		displayFolder: 04. Stocks
		lineageTag: b2a3100e-5334-4fc1-b26f-08f80fe7e089

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Stocks_Ecoulement_PF = ```
			
			DIVIDE(CALCULATE (
			    [_Gene_Solde GL],
			    FILTER (
			        'PlanCompteAEF',
			        'PlanCompteAEF'[LiasseCode] in {"BR","BP","BN"}
			    )
			)
			    , CALCULATE (
			        [_Gene_Solde GL],
			        'PlanCompteAEF'[LiasseCode] in{ "FC","FF","FI"}
			    ),0)
			    * IF (
			        MAX ( 'KPI'[Exercice] ) = "N",
			        DATEDIFF (
			            MAX ( Parametrage[DateClotureN] ),
			            MAX ( Parametrage[DateOuvertureN] ),
			            DAY
			        ) + 1,
			        DATEDIFF (
			            MAX ( Parametrage[DateClotureN_1] ),
			            MAX ( Parametrage[DateOuvertureN_1] ),
			            DAY
			        ) + 1
			    ) 
			```
		displayFolder: 04. Stocks
		lineageTag: 6f47648a-0964-4d06-8d9b-12519646f149

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Stocks_RepDépréP&L = CALCULATE ( [_Gene_Solde N], FILTER ( Compte, Compte[Racine5] = 78173 ) ) + 1 * 0
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: c9264a93-fe24-489f-b56f-c4c4307807ed

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _Stocks_VarBrutBilan =
			(
			    CALCULATE ( [_Gene_Solde N], 'PlanCompteAEF'[MarquageStocks] = "Stocks bruts" )
			        - CALCULATE ( [_Gene_Solde N-1], 'PlanCompteAEF'[MarquageStocks] = "Stocks bruts" )
			) + 1 * 0
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: e457a372-9c7e-4f82-8f1f-4f5cfaa8b462

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _Stocks_VarBrutP&L =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[MarquageStocks]="Var stocks brut" || PlanCompteAEF[LiasseCode]= "FM",
			    'KPI'[Exercice]="N"
			)+0
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: 88154f48-f7c9-4e3b-b489-8998a8a6791a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _Stocks_VarDépréBilan =
			CALCULATE ( [_Gene_Solde GL], Compte[Racine2] = 39, 'KPI'[Exercice] = "N" )
			    - CALCULATE ( [_Gene_Solde GL], Compte[Racine2] = 39, 'KPI'[Exercice] = "N-1" ) + 1 * 0
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: 126954e0-6e72-4c04-bcc5-ebaafb8bdf51

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Nb Lignes' = ```
			
			CALCULATE(
			    COUNT('KPI'[Compte])
			   
			)
			```
		formatString: #,##0
		displayFolder: 12. JE
		lineageTag: 57ebc3c3-1e86-4e69-b6a6-fec4f5a6283d

		changedProperty = IsHidden

	measure '_Immo_VNC P&L' = [_Immo_VNC P&L pour table] +0
		formatString: #,##0
		displayFolder: 02. Immobilisations
		lineageTag: f74ee121-fa91-411d-8c23-5c21772dca3b

		changedProperty = IsHidden

	measure '_JE_Nb Ecritures N' =
			CALCULATE(
			    DISTINCTCOUNT('KPI'[EcritureNumero]),
			    'KPI'[Exercice]="N")
		formatString: #,0
		displayFolder: 12. JE
		lineageTag: 7fa13119-c164-4a8f-a474-4f6cb1ad0a96

		changedProperty = IsHidden

	measure '_JE_Nb EcrituresN-1' =
			CALCULATE(
			    DISTINCTCOUNT('KPI'[EcritureNumero]),
			    'KPI'[Exercice]="N-1")
		formatString: #,0
		displayFolder: 12. JE
		lineageTag: 8107cb1e-8fae-4c26-8617-fcc690db0725

		changedProperty = IsHidden

	measure '_JE_Nb Lignes' = COUNTROWS('KPI')
		displayFolder: 12. JE
		lineageTag: df267b5b-46ec-4f71-b39e-9aa38724d481

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_KPI_Tx Marge Brute' =
			
			DIVIDE (
			    CALCULATE([_Gene_Solde GL],'PlanCompteAEF'[MarquageMarge] = "Marge brute" ),
			    CALCULATE([_Gene_Solde GL],PlanCompteAEF[CategorieREX]="Chiffre d'affaires"),
			    0
			)
		formatString: #,##0.0 %
		displayFolder: 09. CA
		lineageTag: 6a4e85a4-968a-47ef-afd7-c071a85a7028

		changedProperty = IsHidden

	measure '_KPI_Tx REX/CA' =
			DIVIDE(
			    CALCULATE([_Gene_Solde Inversé carte],'PlanCompteAEF'[MarquageREX] = "REX"),
			    CALCULATE(
			        [_Gene_Solde inv],
			        'PlanCompteAEF'[CategorieREX] = "Chiffre d'affaires"
			    ),
			    0
			)
		formatString: #,##0.0 %
		displayFolder: 09. CA
		lineageTag: 8527e03f-6430-4cf2-95f1-d7033063516a

		changedProperty = IsHidden

	measure _Let_Ecart = [_Gene_Solde GL]-[_Let_Solde GL non let.]
		formatString: #,##0
		displayFolder: 08. Cadrage
		lineageTag: 2c1a3a21-4856-463f-865c-e256d3d87bdb

		changedProperty = IsHidden

	measure '_Let_Ecart abs' = abs([_Let_Ecart])
		formatString: #,##0
		displayFolder: 08. Cadrage
		lineageTag: 49239600-a8c7-4f2c-8e9f-d6e45bd5b16b

		changedProperty = IsHidden

	measure '_Let_Solde GL non let.' = CALCULATE([_Gene_Solde GL],isblank('KPI'[EcritureLet]))
		formatString: #,##0
		displayFolder: 08. Cadrage
		lineageTag: 804f1476-b84c-4265-a527-eeb5eb8d7d45

		changedProperty = IsHidden

	measure _mesValeurTVAN = MIN(SliderT1[Code])
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: 1f0d60ed-31bf-459f-886b-3d37725c7203

		changedProperty = IsHidden

	measure _mesValeurTVAN-1 = MIN(SliderT2[Code])
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: d60f1bfb-f818-4a9f-8297-14b55c1129a5

		changedProperty = IsHidden

	measure '_Personnel_Salaire Moyen N' = ```
			
			    DIVIDE(
			        CALCULATE(
			            [_Gene_Solde N],
			            PlanCompteAEF[LiasseCode]="FY"),
			            [Selected value T3])+0
			```
		displayFolder: 11. Personnel\Personnel_global
		lineageTag: ac74369d-89c1-497d-badf-52402e5a30c3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Personnel_Salaire Moyen N-1' = ```
			
			    DIVIDE(
			        CALCULATE(
			            [_Gene_Solde N-1],
			            PlanCompteAEF[LiasseCode]="FY"),
			            [Selected value T4])+0
			```
		displayFolder: 11. Personnel\Personnel_global
		lineageTag: 2dbef343-aaf0-4c52-acc7-5281296e7f5e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_SAP Stocks VB_ Ecart' = [_SAP Stocks VB_ Solde Bilan]-[_SAP Stocks VB_ Solde P&L]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 7b875283-049b-4318-a445-f17ae1fe1017

		changedProperty = IsHidden

	measure '_SAP Stocks VB_ Solde Bilan' = CALCULATE([_Gene_Variation N/N-1],PlanCompteAEF[BilanNiv1]="Bilan")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 803999b7-e17c-46dd-9407-e2aa120fcaaf

		changedProperty = IsHidden

	measure '_SAP Stocks VB_ Solde P&L' = -CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 8d950a92-4bd4-4d22-a39b-f05de45c6dcf

		changedProperty = IsHidden

	measure 'Calcul échéance +180 jours' =
			
			VAR a =
			    SUMMARIZE ('KPI',
			                'KPI'[CompAuxLib],
			                'KPI'[DateComptable],
			                "b", [_Gene_Cloture_Date 2],
			                "c", datediff(max(DimTemps[Dates]),[_Gene_Cloture_Date 2],DAY))
			
			VAR d = Calculate (IF(MAX(Compte[Racine2]) = 41 , [_Gene_Solde N] , [_Gene_Solde N inv]),filter (a,[c]>=180))
			Return
			d
		formatString: #,##0
		displayFolder: 03. Clients\Clients_WP
		lineageTag: 67f52b84-b2ee-4e1a-9abf-235aae68d040

		changedProperty = IsHidden

	measure 'Calcul échéance 180 jours' =
			VAR a =
			    SUMMARIZE ('KPI',
			                'KPI'[CompAuxLib],
			                'KPI'[DateComptable],
			                "b", [_Gene_Cloture_Date 2],
			                "c", datediff(max(DimTemps[Dates]),[_Gene_Cloture_Date 2],DAY))
			VAR d = Calculate (IF(MAX(Compte[Racine2]) = 41 , [_Gene_Solde N] , [_Gene_Solde N inv]),filter (a,and([c]<180,[c]>=90)))
			Return
			d
		formatString: #,##0
		displayFolder: 03. Clients\Clients_WP
		lineageTag: 2d407852-1096-4492-b81d-1b9336873ff9

		changedProperty = IsHidden

	measure 'Calcul échéance 30 jours' =
			VAR a =
			    SUMMARIZE ('KPI',
			                'KPI'[CompAuxLib],
			                'KPI'[DateComptable],
			                "b", [_Gene_Cloture_Date 2],
			                "c", datediff(max(DimTemps[Dates]),[_Gene_Cloture_Date 2],DAY))
			
			VAR d = Calculate (IF(MAX(Compte[Racine2]) = 41 , [_Gene_Solde N] , [_Gene_Solde N inv]),filter (a,[c]<30))
			Return
			d
		formatString: #,##0
		displayFolder: 03. Clients\Clients_WP
		lineageTag: 278b20ef-fc9a-4b6f-b337-e967e437f205

		changedProperty = IsHidden

	measure 'Calcul échéance 60 jours' =
			VAR a =
			    SUMMARIZE ('KPI',
			                'KPI'[CompAuxLib],
			                'KPI'[DateComptable],
			                "b", [_Gene_Cloture_Date 2],
			                "c", datediff(max(DimTemps[Dates]),[_Gene_Cloture_Date 2],DAY))
			
			VAR d = Calculate (IF(MAX(Compte[Racine2]) = 41 , [_Gene_Solde N] , [_Gene_Solde N inv]),filter (a,and([c]<60,[c]>=30)))
			Return
			d
		formatString: #,##0
		displayFolder: 03. Clients\Clients_WP
		lineageTag: 0769f98a-4e7a-4325-a9bd-fabce310ec65

		changedProperty = IsHidden

	measure 'Calcul échéance 90 jours' =
			VAR a =
			    SUMMARIZE ('KPI',
			                'KPI'[CompAuxLib],
			                'KPI'[DateComptable],
			                "b", [_Gene_Cloture_Date 2],
			                "c", datediff(max(DimTemps[Dates]),[_Gene_Cloture_Date 2],DAY))
			
			VAR d = Calculate (IF(MAX(Compte[Racine2]) = 41 , [_Gene_Solde N] , [_Gene_Solde N inv]),filter (a,and([c]<90,[c]>=60)))
			Return
			d
		formatString: #,##0
		displayFolder: 03. Clients\Clients_WP
		lineageTag: aa2b7252-48b6-41ae-95b2-f406b258c928

		changedProperty = IsHidden

	measure 'Comptes auxiliaires mouv' =
			VAR a =
			    SUMMARIZE ('KPI',
			                'KPI'[CompAuxLib],
			                "c", abs(sum('KPI'[MTCredit]))+abs(sum('KPI'[MTDebit])))
			
			VAR d = Calculate (distinctcount('KPI'[CompAuxLib]),filter (a,[c]<>0))
			Return
			d
		formatString: #,##0
		displayFolder: 03. Clients\Clients_WP
		lineageTag: 25416cd1-2738-4c6f-85f3-b7efd3349914

		changedProperty = IsHidden

	measure Credit =
			
			CALCULATE ( SUM ( 'KPI'[MTCredit] ) )
		displayFolder: 0. Mesures à classer
		lineageTag: 26018837-4655-44af-9ebe-42eec9f44319

		changedProperty = IsHidden

	measure Debit =
			
			CALCULATE ( SUM ( 'KPI'[MTDebit] ) )
		displayFolder: 0. Mesures à classer
		lineageTag: 00de7042-b352-47cc-9349-7df89f48a355

		changedProperty = IsHidden

	measure Debit_N =
			
			IF ( ISBLANK ( [Debit] ), BLANK (), CALCULATE ( SUMX ( 'DimTemps', [Debit] ) ) )
		formatString: #,0
		displayFolder: 0. Mesures à classer
		lineageTag: b7d0810d-afdb-45c1-84d1-a802c9911cbf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Debit_N_1 =
			
			VAR MinDates =
			    IF (
			        HASONEVALUE ( 'DimTemps'[Dates] ),
			        VALUES ( 'DimTemps'[Dates] ),
			        MIN ( 'DimTemps'[Dates] )
			    )
			VAR YYYY =
			    YEAR ( MinDates )
			VAR MaxDates =
			    IF (
			        HASONEVALUE ( 'DimTemps'[Dates] ),
			        VALUES ( 'DimTemps'[Dates] ),
			        CALCULATE (
			            MAX ( 'DimTemps'[Dates] ),
			            'DimTemps'[Dates] = YYYY,
			            'DimTemps'[FirstFiscalMonth] = 1
			        )
			    )
			RETURN
			    MaxDates
		displayFolder: 0. Mesures à classer
		lineageTag: 54087c38-b80c-4aff-b52d-1995dfc95988

		changedProperty = IsHidden

	measure 'Debit_N_1 R' =
			
			VAR _MinDate =
			    CALCULATE ( MIN ( 'DimTemps'[Dates] ), VALUES ( 'DimTemps'[Dates] ) )
			VAR _MaxDate =
			    CALCULATE ( MAX ( 'DimTemps'[Dates] ), VALUES ( 'DimTemps'[Dates] ) )
			VAR _FirstDateLastYear =
			    DATE ( YEAR ( _MinDate ) - 1, MONTH ( _MinDate ), DAY ( _MinDate ) )
			VAR _LastDateLastYear =
			    DATE ( YEAR ( _MaxDate ) - 1, MONTH ( _MaxDate ), DAY ( _MaxDate ) )
			RETURN
			    _MaxDate
			--CALCULATE([Debit], FILTER(DimTemps, Dimtemps[Dates] <= _LastDateLastYear && Dimtemps[Dates] >= _FirstDateLastYear ))
		displayFolder: 0. Mesures à classer
		lineageTag: 7a9a5140-1c0b-4985-93da-0cc5576828e6

		changedProperty = IsHidden

	measure Debit_Trash =
			
			VAR MinDates =
			    IF (
			        HASONEVALUE ( 'DimTemps'[Dates] ),
			        VALUES ( 'DimTemps'[Dates] ),
			        MIN ( 'DimTemps'[Dates] )
			    )
			VAR YYYY =
			    YEAR ( MinDates )
			VAR MM =
			    MONTH ( MinDates )
			VAR Q =
			    QUARTER ( MinDates )
			VAR CountS =
			    CALCULATE ( COUNTA ( 'DimTemps'[Dates] ) )
			VAR MaxDates =
			    IF (
			        HASONEVALUE ( 'DimTemps'[Dates] ),
			        VALUES ( 'DimTemps'[Dates] ),
			        CALCULATE (
			            MAX ( 'DimTemps'[Dates] ),
			            YEAR ( 'DimTemps'[Dates] ) = YYYY,
			            MONTH ( 'DimTemps'[Dates] ) = MM,
			            ALL ( 'DimTemps' )
			        )
			    )
			RETURN
			    CountS
		displayFolder: 0. Mesures à classer
		lineageTag: b2f9c7b5-8546-44f4-9c57-770aabdb6e22

		changedProperty = IsHidden

	measure 'Gene_ Couleur Transparent' = "#FFFFFF00"
		displayFolder: 0. Mesures à classer
		lineageTag: 4a075812-a530-4637-b371-45b667982140

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Lettrage = if (isblank(max('KPI'[EcritureLet])),"Non lettrées","Lettrées")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: cf14a385-b5af-4b57-a313-94525edeaee8

		changedProperty = IsHidden

	measure Measure = ```
			
			IF(OR(ISBLANK(MAX(PlanCompteAEF[LiasseCode])),ISBLANK(MAX(PlanCompteAEF[DetailNiv3]))),
			[_CP_ResultatNet],
			CALCULATE(CALCULATE (
			    SUM ( 'KPI'[MTCredit] ),
			    ParamAN[AN - O/N] = "Non"
			)))+0
			
			```
		displayFolder: 0. Mesures à classer
		lineageTag: e883abdd-fccc-4241-b361-baf76cabcab3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP_ Ecart acceptable % PM' = DIVIDE([Selected value T5] ,[SAP_PM],0)
		formatString: #,##0 %
		displayFolder: 0. Mesures à classer
		lineageTag: 4f320771-d151-4fda-bb7f-b5c618a6ab6d

		changedProperty = IsHidden

	measure 'SAP_Nbr de jours sélectionné N' =
			VAR AX =[Nbr de jours N] - [Selected value T9]+1
			RETURN
			IF( [Selected value T9]=1, "","des "
			& AX
			&" derniers jours")
			
			
			
			--If (MOD('DimTemps'[FiscalYear],4) = 0,366 ,365 )
		displayFolder: 0. Mesures à classer
		lineageTag: 0b67a8c8-df18-423a-a5a2-2ae781c663e4

		changedProperty = IsHidden

	measure 'SAP_Nbr de jours sélectionné N-1' =
			VAR AX =[Nbr de jours N-1] - [Selected value T8]+1
			RETURN
			IF( [Selected value T8]=1, "","des "
			& AX
			&" derniers jours")
			
			
			
			--If (MOD('DimTemps'[FiscalYear],4) = 0,366 ,365 )
		displayFolder: 0. Mesures à classer
		lineageTag: 29a423f1-9ec1-4ac8-ab55-4d0433cd5349

		changedProperty = IsHidden

	measure SAP_PM = MAX(Parametrage[PM])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: ba9f33d0-66d0-4236-be0a-ecd87053eee9

		changedProperty = IsHidden

	measure 'SAP_quick wins % Variation' = CALCULATE([_Gene_VariationN/N-1%],ALL('DimTemps'[DayOfYear]))
		formatString: #,##0 %
		displayFolder: 0. Mesures à classer
		lineageTag: e121857d-f628-48b3-87f7-ffdbbedb8ee5

		changedProperty = IsHidden

	measure 'SAP_quick wins solde N' = CALCULATE([_Gene_Solde N],ALL('DimTemps'[DayOfYear]))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: ecd9abe6-6f51-40c5-9a65-e16411fc81ce

		changedProperty = IsHidden

	measure 'SAP_quick wins solde N-1' = CALCULATE([_Gene_Solde N-1],ALL('DimTemps'[DayOfYear]))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 30acce04-fe4b-4872-92b5-84d2465a2c8f

		changedProperty = IsHidden

	measure 'SAP_quick wins Variation N/N-1' = CALCULATE([_Gene_Variation N/N-1],ALL('DimTemps'[DayOfYear]))
		formatString: ### ### ###
		displayFolder: 0. Mesures à classer
		lineageTag: 3fb11a1b-64e2-46d3-87e0-51cb5c0621ae

		changedProperty = IsHidden

	measure 'SAP_Solde N ignore filter' = CALCULATE([_Gene_Solde GL],'KPI'[Exercice]="N",ALL('DimTemps'[DayOfYear Calendar]))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: f4fa040e-24ab-4050-ab75-d52b5dd5c731

		changedProperty = IsHidden

	measure SAP_Vide = BLANK()
		displayFolder: 0. Mesures à classer
		lineageTag: 81c38da4-0355-49b3-a1ad-aebbda027201

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP_Vide 1' = "___________"
		displayFolder: 0. Mesures à classer
		lineageTag: 519ed16d-f893-4286-92fe-f842b8b73c51

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SAP_Zero = "."
		displayFolder: 0. Mesures à classer
		lineageTag: e60a77b6-b5f1-4b14-8db9-942bafd546a7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP1_Charges de personnel attendues' =
			if (ISBLANK([_Gene_Solde N-1]),BLANK() ,
			//Effectif moyen N
			    [Selected value T3]
			//Augmetation de salaire
			    *(1+[Selected value T1]/100
			//Nbr de jours concernés par l'augmentation
			    *[Selected value T2]/365)
			//Salaires N-1 hors éléments exceptionnels N-1
			    *Divide (([_Gene_Solde N-1]-[Selected value T6]),
			//Effectif moyen N-1
			    [Selected value T4],0)
			//Elements except. N
			    +[Selected value T7])
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: f619340d-73ce-4203-9627-81a67511dcfb

		changedProperty = IsHidden

	measure 'SAP1_Charges de personnel comptabilisées hors éléments except.' =
			if (ISBLANK([_Gene_Solde N-1]),BLANK() ,
			[_Gene_Solde N]-[Selected value T7])
		formatString: ### ### ###
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: 44502b2f-ff48-4ec1-a449-9ec9d0b25a63

		changedProperty = IsHidden

	measure 'SAP1_Charges de personnel N' = ```
			
			
			[_Gene_Solde N]+0
			
			```
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: 1fc135b5-dabf-4869-adc7-5b548ac2040c

		changedProperty = IsHidden

	measure 'SAP1_Charges de personnel N normalisé' = ```
			Divide ([_Gene_Solde N]-[Selected value T7],0)
			
			```
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: 629e35cb-3629-49d6-8a32-38f601bf4066

		changedProperty = IsHidden

	measure 'SAP1_Charges de personnel N-1' = ```
			
			
			[_Gene_Solde N-1]+0
			
			```
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: c928d7d2-add1-4e54-8a8f-47b0fa2e5cde

		changedProperty = IsHidden

	measure 'SAP1_Charges de personnel N-1 normalisé' = ```
			Divide ([_Gene_Solde N-1]-[Selected value T6],0)
			
			```
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: 26faf36e-7c19-49e5-9361-2f3647e0ae53

		changedProperty = IsHidden

	measure SAP1_Conclusion =
			IF (
			    ABS ( [SAP1_Ecart]) < [Selected value T5],
			    "Inférieur à l'écart acceptable",
			    "Supérieur à l'écart acceptable"
			)
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: d53adcd3-953e-4f6d-830a-3d15276f5d44

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SAP1_Ecart =
			if (ISBLANK([_Gene_Solde N-1]),BLANK() ,
			
			([_Gene_Solde N]-[SAP1_Charges de personnel attendues])+1*0)
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: 0a86bf96-0244-4905-aa1d-b9f5c3ccc909

		changedProperty = IsHidden

	measure 'SAP1_Ecart num' = IF([SAP1_Conclusion]="Inférieur à l'écart acceptable",1,0)
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: 039e6d14-73c4-44c8-aa9f-bcecb13491a8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP1_Salaire moyen attendu N' = ```
			DIVIDE([SAP1_Charges de personnel attendues]-[Selected value T7],[Selected value T3],0)+0.01
			
			```
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: d836aecc-5680-4941-82e7-39ca10cddc47

		changedProperty = IsHidden

	measure 'SAP1_Salaire moyen comptabilisé N' = DIVIDE([SAP1_Charges de personnel comptabilisées hors éléments except.],[Selected value T3],0)
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: 1c543d50-c04a-42b9-8ada-af74f147ea20

		changedProperty = IsHidden

	measure 'SAP1_Salaire moyen N-1' =
			if (ISBLANK([_Gene_Solde N-1]),BLANK() ,
			DIVIDE([_Gene_Solde N-1]-[Selected value T6],[Selected value T4],0))
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP1 Salaire moyen
		lineageTag: 774b691e-d312-4a96-bb0f-23c94ed93349

		changedProperty = IsHidden

	measure SAP10_Dividendes = [Selected value T4]*10^6+[Selected value T6]*10^3+[Selected value T7]+[Selected value T3]*10^(-2)
		displayFolder: 0. Mesures à classer
		lineageTag: 68bd9382-87ed-42b5-a1b2-6a9e7774d479

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP10_Solde BG N ouverture' = CALCULATE([_Cadrage_Solde BG],'KPI'[Exercice]="N-1")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3278d8a9-899f-4338-b8ec-b1ecfed5b210

		changedProperty = IsHidden

	measure 'SAP11_Charges comptabilisées' = CALCULATE([_Gene_Solde N], Compte[Racine1]="6")
		formatString: ### ### ###
		displayFolder: 0. Mesures à classer
		lineageTag: 24196b5b-bf3c-4460-8597-c005c2598e03

		changedProperty = IsHidden

	measure 'SAP11_Charges d''intérêts attendue' = [SAP11_Montant restant à l'ouverture]*[Selected value T1]*[Selected value T6]/365/100
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: f0c98775-4316-48de-946c-3e8df07fc33f

		changedProperty = IsHidden

	measure SAP11_Ecart = [SAP11_Charges comptabilisées]-[SAP11_Charges d'intérêts attendue]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 18d00d12-2cb1-4292-ac3f-24731c110463

		changedProperty = IsHidden

	measure 'SAP11_Montant restant à l''ouverture' = -CALCULATE([_Gene_Solde N-1], Compte[Racine2]="16")
		formatString: ### ### ###
		displayFolder: 0. Mesures à classer
		lineageTag: 617795db-49f0-4195-8d5b-889968b87790

		changedProperty = IsHidden

	measure 'SAP2_CS attendues' = [SAP2_Tx CS attendu]*[SAP2_Salaires N retraités]
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: c5930bf3-15f9-45bb-9cce-f0f9d172dfec

		changedProperty = IsHidden

	measure 'SAP2_CS N' = ```
			CALCULATE ([_Gene_Solde N],Compte[SapChargeSociales] in {"Charges sociales"}) 
			```
		formatString: ### ### ###
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: 7b366e73-a691-404e-929a-14f7d199e419

		changedProperty = IsHidden

	measure 'SAP2_CS N-1' = ```
			CALCULATE ([_Gene_Solde N-1],Compte[SapChargeSociales] in {"Charges sociales"}) 
			```
		formatString: ### ### ###
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: 7dc2b8bc-d97c-44db-ba22-06126b7ebb3c

		changedProperty = IsHidden

	measure 'SAP2_Description comptes agrégés' =
			"Pour la partie bilantielle, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes"
			& switch( true(),
			max('Choix du test_frs'[Code])=1, " #409 pour couvrir les avoirs à recevoir.",
			max('Choix du test_frs'[Code])=2, " #486 pour couvrir les charges constatées d'avance.",
			max('Choix du test_frs'[Code])=3, " #408 pour couvrir les factures non parvenues.",
			max('Choix du test_frs'[Code])=5, " #419 pour couvrir les avoirs à établir.",
			max('Choix du test_frs'[Code])=6, " #487 pour couvrir les produits constatés d'avance.",
			max('Choix du test_frs'[Code])=7, " #4181 pour couvrir les factures à établir.",
			
			 "")
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: fdc8ccc6-7cd1-42f1-99cb-c45901c0b459

		changedProperty = IsHidden

	measure 'SAP2_Description de la procédure' =
			switch( true(),
			max('Choix du test_frs'[Code])=1, "- Analyse prédictive des avoirs à recevoir sur la base du total des achats ;
			- Le niveau d'AAR attendu se fonde sur : le total des achats de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments exceptionnels saisis ;
			- La SAP est réalisée de manière agrégée.",
			max('Choix du test_frs'[Code])=2, "- Analyse prédictive des charges constatées d'avance sur la base du total des achats ;
			- Le niveau de CCA attendu se fonde sur : le total des achats de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments exceptionnels saisis ;
			- La SAP est réalisée de manière agrégée.",
			max('Choix du test_frs'[Code])=3, "- Analyse prédictive des factures non parvenues sur la base du total des achats ;
			- Le niveau de FNP attendu se fonde sur : le total des achats de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments exceptionnels saisis ;
			- La SAP est réalisée de manière agrégée.",
			max('Choix du test_frs'[Code])=5, "- Analyse prédictive des avoirs à établir sur la base du total des ventes ;
			- Le niveau d'AAE attendu se fonde sur : le total des ventes de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments non récurrents saisis ;
			- La SAP est réalisée de manière agrégée.",
			max('Choix du test_frs'[Code])=6, "- Analyse prédictive des produits constatés d'avance sur la base du total des ventes ;
			- Le niveau de PCA attendu se fonde sur : le total des ventes de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments non récurrents saisis ;
			- La SAP est réalisée de manière agrégée.",
			max('Choix du test_frs'[Code])=7, "- Analyse prédictive des factures à établir sur la base du total des ventes ;
			- Le niveau de FAE attendu se fonde sur : le total des achats de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments non récurrents saisis ;
			- La SAP est réalisée de manière agrégée.",
			 "")
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: c34b1888-9575-4a1a-a35b-65bc77b2c854

		changedProperty = IsHidden

	measure SAP2_Ecart = [SAP2_CS N]-[SAP2_CS attendues]
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: 66b21c8e-da36-48c1-8ba5-d2bb65455029

		changedProperty = IsHidden

	measure 'SAP2_Ecart num' = IF([SAP2_Résultat SAP]="Inférieur à l'écart acceptable",1,0)
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: b327827e-f630-465f-b3f6-219b51784aba

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP2_Résultat SAP' = IF(ABS([SAP2_Ecart])<=[Selected value T5],"Inférieur à l'écart acceptable","Supérieur à l'écart acceptable")
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: d03878be-e087-4184-972e-ac95d5974951

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP2_Salaires N' = CALCULATE([_Gene_Solde N],Compte[SapChargeSociales]="Salaires et traitements")
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: 878f42ab-2792-4b28-9669-40af40547408

		changedProperty = IsHidden

	measure 'SAP2_Salaires N retraités' = [SAP2_Salaires N]- [Selected value T7]
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: d5f30990-7499-4679-8014-2cd581e8ef01

		changedProperty = IsHidden

	measure 'SAP2_Salaires N-1' = CALCULATE([_Gene_Solde N-1],Compte[SapChargeSociales]="Salaires et traitements")
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: 98e7fae5-1bca-4262-89ad-34c94f3acba0

		changedProperty = IsHidden

	measure 'SAP2_Salaires N-1 retraités' = [SAP2_Salaires N-1]- [Selected value T6]
		formatString: ### ### ###
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: a44ba8e2-a461-4f0a-8f53-df3b55975d2c

		changedProperty = IsHidden

	measure 'SAP2_Tx charges N-1' = DIVIDE([SAP2_CS N-1],[SAP2_Salaires N-1 retraités],0)
		formatString: #,##0 %
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: 2a6c8e87-6959-4a11-a507-f848e787eb2e

		changedProperty = IsHidden

	measure 'SAP2_Tx CS attendu' = [SAP2_Tx charges N-1]+[Selected value T1 %]
		formatString: #,##0 %
		displayFolder: 11. Personnel\Personnel_SAP2 Charges sociales
		lineageTag: 387a70cb-5492-4677-b272-c06fd3fd8c29

		changedProperty = IsHidden

	measure 'SAP3_Charges à payer attendues' = [SAP3_Charges à payer N-1 retraitées]-[Selected value T7]
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP3 Charges à payer
		lineageTag: fbbe4ffc-4f68-4f4a-a7b1-4470f72dc7b7

		changedProperty = IsHidden

	measure 'SAP3_Charges à payer N-1 retraitées' = [_Gene_Solde N-1]+[Selected value T6]
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP3 Charges à payer
		lineageTag: 9e5e9f08-3b20-48fd-856a-d00159cc4780

		changedProperty = IsHidden

	measure SAP3_Ecart = [_Gene_Solde N]-[SAP3_Charges à payer attendues]
		formatString: #,##0
		displayFolder: 11. Personnel\Personnel_SAP3 Charges à payer
		lineageTag: de7b9630-a1f1-4140-ae11-6f5488d1abf5

		changedProperty = IsHidden

	measure 'SAP3_Ecart num' = IF([SAP3_Résultat SAP]="Inférieur à l'écart acceptable",1,0)
		formatString: 0
		displayFolder: 11. Personnel\Personnel_SAP3 Charges à payer
		lineageTag: 59a3c7e5-9e57-4800-a79e-ed35fc121c8b

		changedProperty = IsHidden

	measure 'SAP3_Résultat SAP' = IF(ABS([SAP3_Ecart])<=[Selected value T5],"Inférieur à l'écart acceptable","Supérieur à l'écart acceptable")
		displayFolder: 11. Personnel\Personnel_SAP3 Charges à payer
		lineageTag: a41c487c-e78a-468c-bf8e-b13e87f0d339

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_Bilan inv N' =
			
			-CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[BilanNiv1]="Bilan",
			    'KPI'[Exercice]="N")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 608e639f-294f-4253-8462-7efd71a31045

		changedProperty = IsHidden

	measure 'SAP4_Bilan inv N-1' =
			
			-CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[BilanNiv1]="Bilan",
			    'KPI'[Exercice]="N-1")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 749bf24d-65e7-46eb-8893-12b712b28bbc

		changedProperty = IsHidden

	measure 'SAP4_Bilan pour DRM inv N' =
			
			-CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[BilanNiv1]="Bilan",
			    'KPI'[Exercice]="N",
			    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))
			- [Selected value T7]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 8f5f5c6a-177c-4816-8e09-81c53e7120f1

		changedProperty = IsHidden

	measure 'SAP4_Bilan pour DRM inv N-1' =
			
			-CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[BilanNiv1]="Bilan",
			    'KPI'[Exercice]="N-1",
			    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))
			- [Selected value T6]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e8970c6e-457f-42f0-90aa-9d8d0851d7e8

		changedProperty = IsHidden

	measure 'SAP4_Bilan pour DRM N' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[BilanNiv1]="Bilan",
			    'KPI'[Exercice]="N",
			    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))
			- [Selected value T7]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 61b3973d-a69b-4d8c-8572-3eef4f457524

		changedProperty = IsHidden

	measure 'SAP4_Bilan pour DRM N-1' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[BilanNiv1]="Bilan",
			    'KPI'[Exercice]="N-1",
			    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))
			- [Selected value T6]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: a4301555-0990-4df1-a3d8-cd2b748eb4d9

		changedProperty = IsHidden

	measure 'SAP4_Chiffre d''affaires HT N-1' = (-CALCULATE([_Gene_Solde N-1], Compte[SapDrmClients]="Chiffre d'affaires"))
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: 7431c0b0-0dae-463d-88e6-4a1497950bf3

		changedProperty = IsHidden

	measure 'SAP4_Chiffre d''affaires TTC attendu N' = (-CALCULATE([_Gene_Solde N-1], Compte[SapDrmClients]="Chiffre d'affaires")-[Selected value T6])*([Selected value T2]/100+1)*([Selected value T3]/100+1)
		displayFolder: 0. Mesures à classer
		lineageTag: b067333f-aad0-4ccf-9c37-a6f0b89410a7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_Chiffre d''affaires TTC N' = (-CALCULATE([_Gene_Solde N], Compte[SapDrmClients]="Chiffre d'affaires")-[Selected value T7])*([Selected value T1]/100+1)
		displayFolder: 0. Mesures à classer
		lineageTag: 3ee6e361-c0cc-45d0-b864-92000629644c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_Chiffre d''affaires TTC N-1' = (-CALCULATE([_Gene_Solde N-1], Compte[SapDrmClients]="Chiffre d'affaires")-[Selected value T6])*([Selected value T1]/100+1)
		displayFolder: 0. Mesures à classer
		lineageTag: a65cb0c7-e56d-4bbd-b67d-f494c0e3f378

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_Créances N' = CALCULATE([_Gene_Solde N],Compte[SapDrmClients]="Créances clients")
		displayFolder: 0. Mesures à classer
		lineageTag: 4a164315-9f14-4689-8d76-dad4719ca917

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_Créances N-1' = CALCULATE([_Gene_Solde N-1],Compte[SapDrmClients]="Créances clients")
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: be047abe-834f-4094-b386-afd4e373a887

		changedProperty = IsHidden

	measure 'SAP4_DRM attendu N' = [SAP4_Créances N-1]/[SAP4_Chiffre d'affaires TTC attendu N]*[SAP4_Nb de jours N]+0
		displayFolder: 0. Mesures à classer
		lineageTag: ab4a8905-9e6f-476c-8af7-7e267aa8d28c

		changedProperty = IsHidden

	measure 'SAP4_DRM client N' = ```
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            [SAP4_P&L cumulé inv N] > [SAP4_Bilan pour DRM N]
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan = [SAP4_Bilan pour DRM N]
			VAR PL = calculate ( [_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L")
			
			
			RETURN
			
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 89ddfcc5-6d14-4a1b-b2d2-ff3899d16190

		changedProperty = IsHidden

	measure 'SAP4_DRM client N 1' = ```
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            [SAP4_P&L cumulé inv N] > [SAP4_Bilan pour DRM N]
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan = [SAP4_Bilan pour DRM N]
			VAR PL = calculate ( [_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L")
			
			
			RETURN
			
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 8c84a273-a49d-41f5-a6d5-e636a37e9c2f

		changedProperty = IsHidden

	measure 'SAP4_DRM client N-1' =
			VAR MAXI = [Nbr jour max N-1]
			VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1
			VAR MAXIFY = [Nbr jour max full year N-1]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            [SAP4_P&L cumulé inv N-1] > [SAP4_Bilan pour DRM N-1]
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan = [SAP4_Bilan pour DRM N-1]
			VAR PL = CALCULATE ( [_Gene_Solde N-1], PlanCompteAEF[BilanNiv1] = "P&L" )
			
			RETURN
			
			if ( bilan = 0 , 0,
			    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			    )+0
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3078e8eb-664a-4a04-9553-fb803ddbcd33

		changedProperty = IsHidden

	measure 'SAP4_DRM comptabilisé N' = DIVIDE([SAP4_Créances N],[SAP4_Chiffre d'affaires TTC N],0)*[SAP4_Nb de jours N-1]+0
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: cfdaf8f9-55eb-4534-97b7-dc52f02325e6

		changedProperty = IsHidden

	measure 'SAP4_DRM FRS N' =
			
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			var a = SUMMARIZE(Filter( all('DimTemps'[Day of year inv]),[SAP4_P&L cumulé N]>[SAP4_Bilan pour DRM inv N]),"minv",min('DimTemps'[Day of year inv]) ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan = [SAP4_Bilan pour DRM N]
			VAR PL = calculate ( [_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L")
			
			
			RETURN
			if ( bilan = 0 , 0,
			    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			    )+0
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 5458e36a-357c-4d1c-bf7a-702b210f104c

		changedProperty = IsHidden

	measure 'SAP4_DRM FRS N-1' = ```
			VAR MAXI = [Nbr jour max N-1]
			VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1
			VAR MAXIFY = [Nbr jour max full year N-1]
			
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            [SAP4_P&L cumulé N-1] > [SAP4_Bilan pour DRM inv N-1]
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    )
			VAR b =
			   MINX (
			        a,
			        [minv]
			    ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan = [SAP4_Bilan pour DRM N-1]
			VAR PL = CALCULATE ( [_Gene_Solde N-1], PlanCompteAEF[BilanNiv1] = "P&L" )
			
			RETURN
			
			if ( bilan = 0 , 0,
			    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			)+0
			
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e85c9df8-9b21-4ea9-8531-f0e7b0ddc6fd

		changedProperty = IsHidden

	measure 'SAP4_DRM N-1' =
			DIVIDE (
			    [SAP4_Créances N-1],
			    [SAP4_Chiffre d'affaires TTC N-1],
			    0
			) * [SAP4_Nb de jours N-1] + 0
		formatString: ### ### ###
		displayFolder: 0. Mesures à classer
		lineageTag: 6487cc1f-cee1-4004-8f3e-4bf2174663d5

		changedProperty = IsHidden

	measure 'SAP4_DRM Résultat SAP client' = IF(ABS([SAP4_écart DRM client])>=ABS([SAP4_Ecart accept. en jours]),"> à l'écart acceptable","< à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: a32b02cc-ebad-473e-a325-e6f0a3bde1d4

		changedProperty = IsHidden

	measure 'SAP4_DRM Résultat SAP frs' = IF(ABS([SAP4_écart DRM frs])>=ABS([SAP4_Ecart accept. en jours]),"> à l'écart acceptable","< à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: 095aa3b1-77b8-47e5-97e0-cc93df38fbc4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_DRM Résultat SAP MP' = IF(ABS([SAP4_écart DRS MP])>=ABS([SAP4_Ecart accept. en jours]),"> à l'écart acceptable","< à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: 1d68bacb-a663-4203-9a6e-9880b6dbcee2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_DRS MP N' =
			
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			var a = SUMMARIZE(Filter( all('DimTemps'[Day of year inv]),[SAP4_P&L cumulé N]>[SAP4_Bilan pour DRM N]),"minv",min('DimTemps'[Day of year inv]) ) /* , "inv",related(DimTemps[Day of year inv]))*/
			
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan = [SAP4_Bilan pour DRM N]
			VAR PL = calculate ( [_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L")
			
			RETURN
			
			if ( bilan = 0 , 0,
			    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			)+0
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 65dad49f-d703-4436-8245-e8deb2790b8d

		changedProperty = IsHidden

	measure 'SAP4_DRS MP N-1' =
			VAR MAXI = [Nbr jour max N-1]
			VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1
			VAR MAXIFY = [Nbr jour max full year N-1]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            [SAP4_P&L cumulé N-1] > [SAP4_Bilan pour DRM N-1]
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b = MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan = [SAP4_Bilan pour DRM N-1]
			VAR PL = CALCULATE ( [_Gene_Solde N-1], PlanCompteAEF[BilanNiv1] = "P&L" )
			
			RETURN
			if ( bilan = 0 , 0,
			    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			    )+0
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 4405e3e9-6111-4f50-b5f3-752cf81482ce

		changedProperty = IsHidden

	measure SAP4_Ecart = [SAP4_DRM comptabilisé N]-[SAP4_DRM attendu N]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3ef506e3-27e8-4d97-93b6-669b3be4dbf3

		changedProperty = IsHidden

	measure 'SAP4_Ecart accept. en jours' =
			ABS(divide([Selected value T5],
			    DIVIDE(CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L"),DATEDIFF(MAX(Parametrage[DateClotureN]),MAX(Parametrage[DateOuvertureN]),DAY)+1,0),0)
			    )
			    *(1+[Selected value T1]/100)+0
		formatString: #,##0.0
		displayFolder: 0. Mesures à classer
		lineageTag: d1387182-b324-4942-a98a-3a4d5b7cfc3a

		changedProperty = IsHidden

	measure 'SAP4_écart DRM client' = [SAP4_DRM client N]-[SAP4_DRM client N-1]+0
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 8572b5bd-0739-46b6-8ba4-e8f481051e46

		changedProperty = IsHidden

	measure 'SAP4_écart DRM frs' = [SAP4_DRM FRS N]-[SAP4_DRM FRS N-1]+0
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e9142e10-dd51-4cae-9b18-37a200eaffe2

		changedProperty = IsHidden

	measure 'SAP4_écart DRS MP' = [SAP4_DRS MP N]-[SAP4_DRS MP N-1]+0
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: a549f801-e3c6-46b7-a269-c7b3082e0450

		changedProperty = IsHidden

	measure 'SAP4_Ecart num client' = IF([SAP4_DRM Résultat SAP client]="< à l'écart acceptable",1,0)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e1c30f37-2d7f-4281-98f5-d8d514d0fe46

		changedProperty = IsHidden

	measure 'SAP4_Ecart num frs' = IF([SAP4_DRM Résultat SAP frs]="< à l'écart acceptable",1,0)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 0f8b2606-4737-411f-a2ea-fbbede332f33

		changedProperty = IsHidden

	measure 'SAP4_Ecart num MP' = IF([SAP4_DRM Résultat SAP MP]="< à l'écart acceptable",1,0)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3c01254a-7ee8-4fe4-9d52-42d8f5419c6e

		changedProperty = IsHidden

	measure 'SAP4_Nb de jours N' = -DATEDIFF(MAX(Parametrage[DateClotureN]),MAX(Parametrage[DateOuvertureN]),DAY)+1
		displayFolder: 0. Mesures à classer
		lineageTag: 3e841c87-4fe3-49f4-a724-820cc6ac07a7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_Nb de jours N-1' = -DATEDIFF(MAX(Parametrage[DateClotureN_1]),MAX(Parametrage[DateOuvertureN_1]),DAY)+1
		displayFolder: 0. Mesures à classer
		lineageTag: 4af262d1-1c51-4acf-a69f-0c92b1e8a9bd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_P&L cumulé inv N' = ```
			
			-IF(Isblank([_Gene_Solde GL] ),BLANK(),
			CALCULATE (
			    [_Gene_Solde GL],
			    'KPI'[Exercice]="N",
			    FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			)  
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 892199b5-e871-4e4d-960a-60876b1bf0fa

		changedProperty = IsHidden

	measure 'SAP4_P&L cumulé inv N-1' =
			
			-IF(Isblank([_Gene_Solde GL]),BLANK(),
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[BilanNiv1]="P&L",
			    'KPI'[Exercice]="N-1",
			    FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			)*(1+[Selected value T2]/100)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 9a97fb11-2914-4352-99a5-cf8e0bd714b3

		changedProperty = IsHidden

	measure 'SAP4_P&L cumulé N' =
			
			IF(Isblank([_Gene_Solde GL]),BLANK(),
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[BilanNiv1]="P&L",
			    'KPI'[Exercice]="N",
			    FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			)*(1+[Selected value T1]/100)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 6237e348-8895-4834-a504-8ea310c879e2

		changedProperty = IsHidden

	measure 'SAP4_P&L cumulé N-1' =
			
			IF(Isblank([_Gene_Solde GL]),BLANK(),
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[BilanNiv1]="P&L",
			    'KPI'[Exercice]="N-1",
			    FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			)*(1+[Selected value T2]/100)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3c71de59-426c-46e7-9320-10590e04a9c1

		changedProperty = IsHidden

	measure 'SAP4_Résultat SAP' = IF(ABS([SAP4_Ecart])<=[SAP4_Ecart accept. en jours],"Inférieur à l'écart acceptable","Supérieur à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: ada64b2e-1949-40e5-85d9-5663207a6587

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_Variation CA sur n derniers jrs' = -CALCULATE([_Gene_Solde N],Compte[SapDrmClients]="Chiffre d'affaires",'DimTemps'[DayOfYear Calendar]>334)
		formatString: ### ### ###
		displayFolder: 0. Mesures à classer
		lineageTag: 35394e1e-7662-4140-b669-619885d684b6

		changedProperty = IsHidden

	measure 'SAP5_AAE attendues N' = ([SAP5_Tx AAE / CA N-1]*[SAP5_CA N]+[Selected value T7])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 99b67801-cafe-47af-93db-28b32880b0d6

		changedProperty = IsHidden

	measure 'SAP5_AAE attendues N global' = ([SAP5_Tx AAE / CA N-1 global]*[SAP5_CA N global]+[Selected value T7])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e7d31eea-1fff-42bb-9910-b12c83b69dd2

		changedProperty = IsHidden

	measure 'SAP5_AAE attendues N inv' = ([SAP5_Tx AAE / CA N-1 inv]*[SAP5_CA N]+[Selected value T7])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 5f8fc633-4033-4786-a180-d5a519969175

		changedProperty = IsHidden

	measure 'SAP5_AAE avant retraitement N' = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))
		displayFolder: 0. Mesures à classer
		lineageTag: 22c0a9ee-2a43-448c-b73f-0dce5f28e61f

		changedProperty = IsHidden

	measure 'SAP5_AAE avant retraitement N inv' = ```
			-CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))
			
			```
		displayFolder: 0. Mesures à classer
		lineageTag: 884c54f2-8853-4a5e-a1f8-fce38b92eb40

		changedProperty = IsHidden

	measure 'SAP5_AAE avant retraitement N-1' = ```
			CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))
			
			```
		displayFolder: 0. Mesures à classer
		lineageTag: 34b20cd5-b4eb-4b56-939b-01f188d7dc99

		changedProperty = IsHidden

	measure 'SAP5_AAE avant retraitement N-1 global' =
			switch ( true(),
			max('Choix du test_frs'[Code]) in {1,2,7},[SAP5_AAE avant retraitement N-1],
			max('Choix du test_frs'[Code]) in {3,5,6},[SAP5_AAE avant retraitement N-1 inv],
			"")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 2b2400ac-4d26-44a9-a957-7982f50895a3

		changedProperty = IsHidden

	measure 'SAP5_AAE avant retraitement N-1 inv' = ```
			
			-CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))
			
			```
		displayFolder: 0. Mesures à classer
		lineageTag: 28f6ff9c-26c8-4d26-9e6e-2bfde798d88d

		changedProperty = IsHidden

	measure 'SAP5_AAE Comptabilisées N' =
			VAR a = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))+0
			return
			switch ( true(),
			max('Choix du test_frs'[Code]) in {1,2,7},a,
			max('Choix du test_frs'[Code]) in {3,5,6},-a,
			"")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: ddedc983-365d-4e49-8cc8-5971c6eac0a3

		changedProperty = IsHidden

	measure 'SAP5_AAE Comptabilisées N inv' = ```
			-CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))+0
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 7ba5c414-87c0-4b80-84d4-c0e67b714689

		changedProperty = IsHidden

	measure 'SAP5_AAE retraitées N' = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))-[Selected value T7]
		displayFolder: 0. Mesures à classer
		lineageTag: d46cdd16-b86f-4bd0-9fbb-a95a8d0b9534

		changedProperty = IsHidden

	measure 'SAP5_AAE retraitées N inv' = -CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))-[Selected value T7]
		displayFolder: 0. Mesures à classer
		lineageTag: 4ea789ad-5bc9-43dc-839d-6713518d485c

		changedProperty = IsHidden

	measure 'SAP5_AAE retraitées N-1' = CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))-[Selected value T6]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 41c35d65-e52d-403b-a842-9cae82f62b20

		changedProperty = IsHidden

	measure 'SAP5_AAE retraitées N-1 global' =
			switch ( true(),
			max('Choix du test_frs'[Code]) in {1,2,7},[SAP5_AAE retraitées N-1],
			max('Choix du test_frs'[Code]) in {3,5,6},[SAP5_AAE retraitées N-1 inv],
			"")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 579afc8f-5216-4ff6-b23c-29771edfd5fb

		changedProperty = IsHidden

	measure 'SAP5_AAE retraitées N-1 inv' = -CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]="Bilan",ALL('DimTemps'[DayOfYear]))-[Selected value T6]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: d5dbadef-a604-4da5-b6ef-33cb4c6c3bec

		changedProperty = IsHidden

	measure 'SAP5_CA N' = ```
			var MINI = [Nbr jour min N]
			VAR EquivJr= [Nbr jour min equiv N]
			RETURN 
			Calculate ([SAP5_CA N V2] , filter('DimTemps','DimTemps'[DayOfYear] >= EquivJr))
			
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: a2ec792d-2a4b-4824-87ae-b296e09a09e1

		changedProperty = IsHidden

	measure 'SAP5_CA N global' =
			switch ( true(),
			max('Choix du test_frs'[Code]) in {1,2,3},-[SAP5_CA N],
			max('Choix du test_frs'[Code]) in {7,5,6},[SAP5_CA N],
			"")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 9f9805d2-b297-415a-95a3-5eda6824f322

		changedProperty = IsHidden

	measure 'SAP5_CA N V2' = ```
			- CALCULATE (
			        [_Gene_Solde N],
			        PlanCompteAEF[BilanNiv1] = "P&L"
			    )
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: cdbdafd0-4a12-4201-ba1b-2d92e5387998

		changedProperty = IsHidden

	measure 'SAP5_CA N-1' = ```
			var MINI = [Nbr jour min N-1]
			VAR EquivJr=[Nbr jour min equiv N-1] 
			RETURN 
			Calculate ([SAP5_CA N-1 V2] , filter('DimTemps','DimTemps'[DayOfYear] >= EquivJr))
			
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 2eb50f75-7b49-432e-8000-1e3eb839d95e

		changedProperty = IsHidden

	measure 'SAP5_CA N-1 global' =
			switch ( true(),
			max('Choix du test_frs'[Code]) in {1,2,3},-[SAP5_CA N-1],
			max('Choix du test_frs'[Code]) in {7,5,6},[SAP5_CA N-1],
			"")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 0f1a6c4b-5ef8-4cba-b9d9-ce6db23df526

		changedProperty = IsHidden

	measure 'SAP5_CA N-1 V2' = -CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]="P&L")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: f7a828a7-9317-42bb-a03c-a83e95f945d0

		changedProperty = IsHidden

	measure SAP5_ecart = [SAP5_AAE Comptabilisées N]-[SAP5_AAE attendues N global]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 16f4873e-ddba-42ba-8d53-b6b8ce2f9581

		changedProperty = IsHidden

	measure 'SAP5_ecart inv' = [SAP5_AAE Comptabilisées N inv]-[SAP5_AAE attendues N inv]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 68feead1-2355-4db0-afa2-5f2cbf561cdb

		changedProperty = IsHidden

	measure 'SAP5_Ecart num' = IF([SAP5_Résultat SAP]="Inférieur à l'écart acceptable",1,0)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 6ad750f8-3d6b-4ae9-ad36-1e2688257bd2

		changedProperty = IsHidden

	measure 'SAP5_Nbr de jours sélectionné N en nombre' =
			VAR AX =[Nbr de jours N] - [Selected value T9]+1
			RETURN
			IF( [Selected value T9]=1, "",AX)
			
			
			--If (MOD('DimTemps'[FiscalYear],4) = 0,366 ,365 )
		displayFolder: 0. Mesures à classer
		lineageTag: aff6c99b-ac5d-48e5-83fe-305edef4d0db

		changedProperty = IsHidden

	measure 'SAP5_Nbr de jours sélectionné N-1 en nombre' =
			VAR AX =[Nbr de jours N-1] - [Selected value T8]+1
			RETURN
			IF( [Selected value T8]=1, "",AX)
			
			
			
			--If (MOD('DimTemps'[FiscalYear],4) = 0,366 ,365 )
		displayFolder: 0. Mesures à classer
		lineageTag: 70c11fef-5bfc-4301-bb08-853a928ae934

		changedProperty = IsHidden

	measure 'SAP5_Résultat SAP' = IF(ABS([SAP5_ecart])<=[Selected value T5],"Inférieur à l'écart acceptable","Supérieur à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: 9f5adaf2-a18a-4d6c-b558-703152bdcdba

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP5_Tx AAE / CA N-1' = DIVIDE([SAP5_AAE retraitées N-1],[SAP5_CA N-1],0)
		formatString: #,##0 %
		displayFolder: 0. Mesures à classer
		lineageTag: 7da6882b-a031-4ad9-8882-84f93a4ec6c8

		changedProperty = IsHidden

	measure 'SAP5_Tx AAE / CA N-1 global' = DIVIDE([SAP5_AAE retraitées N-1 global],[SAP5_CA N-1 global],0)
		formatString: #,##0.00 %
		displayFolder: 0. Mesures à classer
		lineageTag: 8c5e4582-60ba-4844-a9cd-4d2bbd6ac57e

		changedProperty = IsHidden

	measure 'SAP5_Tx AAE / CA N-1 inv' = DIVIDE([SAP5_AAE retraitées N-1 inv],[SAP5_CA N-1],0)
		formatString: #,##0 %
		displayFolder: 0. Mesures à classer
		lineageTag: 2bcb9fce-619c-4213-b196-bb0dde5bf7c0

		changedProperty = IsHidden

	measure SAP6_Apprentissage = [SAP6_Assiette taxe sur salaires]*SELECTEDVALUE(TaxeApprentissage[Value])
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: 3db510ea-45ac-4c51-b524-3f146ee2189a

		changedProperty = IsHidden

	measure 'SAP6_Assiette taxe sur salaires' = CALCULATE([_Gene_Solde N],Compte[Racine2]=64)
		formatString: #,0
		displayFolder: 0. Mesures à classer
		lineageTag: 1f44fd1b-9bd7-4072-97fb-872d3b613a99

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure SAP6_CSA = [SAP6_Assiette taxe sur salaires]*SELECTEDVALUE(TauxCSA[Value])
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: 4a46d049-43e4-43c8-846d-bbcf6718398a

		changedProperty = IsHidden

	measure SAP6_Ecart = [SAP6_Taxes sur salaires comptabilisées]-[SAP6_Taxes sur salaires calculées]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: ce60434f-d818-4a25-ad58-7f37de189226

		changedProperty = IsHidden

	measure SAP6_PEEC = [SAP6_Assiette taxe sur salaires]*SELECTEDVALUE(PEEC[Value])
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: bc27d36d-aaa1-4610-b1a1-8c40233f233b

		changedProperty = IsHidden

	measure 'SAP6_Résultat SAP' = IF(ABS([SAP6_Ecart])<=[Selected value T5],"Inférieur à l'écart acceptable","Supérieur à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: e87517aa-a314-4eea-aa80-f1a2d5a498d5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP6_Taxe transport' = [SAP6_Assiette taxe sur salaires]*[Selected value T1]
		displayFolder: 0. Mesures à classer
		lineageTag: 180b5d02-3c03-40b8-b8ad-4ef2e8167e7b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP6_Taxes sur salaires calculées' =
			
			[SAP6_Apprentissage]+
			[SAP6_Contribution formation]+
			[SAP6_CSA]+
			[SAP6_PEEC]+
			[SAP6_Taxe transport]
		displayFolder: 0. Mesures à classer
		lineageTag: c6b2fe9d-f46a-4706-af34-0dd983233dab

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP6_Taxes sur salaires comptabilisées' = CALCULATE([_Gene_Solde N],Compte[Racine2]="63")
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: c1f350b9-7ca9-4274-949b-824f43799707

		changedProperty = IsHidden

	measure SAP7_CA = CALCULATE([_Gene_Solde N inv],Compte[SapCVAE+]="1. Ventes")-[Selected value T7]
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: d506c696-759a-4b8d-8aa8-755569fb4d95

		changedProperty = IsHidden

	measure SAP7_Ecart = // [SAP7_Montant comptabilisé]-[SAP7_Montant attendu]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: b7426752-297a-48fd-b399-248c2bba405e

		changedProperty = IsHidden

	measure 'SAP7_Montant attendu' = // [SAP7_VA]*[SAP7_Tx applicable]
		displayFolder: 0. Mesures à classer
		lineageTag: 7a76a526-7f40-47b5-ab44-904a581be81c

		changedProperty = IsHidden

	measure 'SAP7_Montant comptabilisé' = // CALCULATE([_Gene_Solde N],Compte[Racine5]="63511")
		formatString: ### ### ###.##
		displayFolder: 0. Mesures à classer
		lineageTag: 2a823848-8cc5-4c50-a1a9-8eeee139b0cf

		changedProperty = IsHidden

	measure 'SAP7_Résultat SAP' = // IF(ABS([SAP7_Ecart])<=[Selected value T5],"Inférieur à l'écart acceptable","Supérieur à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: 3db55625-a10a-4f39-9219-bd31feaebf52

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP7_Tx applicable' = ```
			// SWITCH(TRUE(), 
			//     [SAP7_CA] < 500000, 0 ,
			//     [SAP7_CA] >= 500000 && [SAP7_CA] < 3000000, 0.005*([SAP7_CA]-500000)/2500000 , 
			//     [SAP7_CA] >= 3000000 && [SAP7_CA] < 10000000, 0.005+0.009*([SAP7_CA]-3000000)/7000000 , 
			//     [SAP7_CA] >= 10000000 && [SAP7_CA] < 50000000, 0.014+0.001*([SAP7_CA]-10000000)/40000000 , 
			//     [SAP7_CA] >= 5000000 , 0.0015)
			```
		displayFolder: 0. Mesures à classer
		lineageTag: cf0df35b-b3a4-4748-97b5-03f07e52560f

		changedProperty = IsHidden

	measure SAP7_VA = CALCULATE( [_Gene_Solde N inv], not ISBLANK(PlanCompteAEF[RankingVA]))
		formatString: #,0
		displayFolder: 0. Mesures à classer
		lineageTag: e3fee8b5-288f-4193-b3fd-3c782bc47f9d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure SAP7_VA/CA = // DIVIDE([SAP7_VA],CALCULATE([_Gene_Solde N inv],Compte[SapCVAE+]="1. Ventes"),0)
		displayFolder: 0. Mesures à classer
		lineageTag: da88dd29-489a-4ae6-bdbd-33518d698350

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SAP8_Bénéfice = CALCULATE([_Gene_Solde N inv],PlanCompteAEF[BilanNiv1]="P&L")
		formatString: ### ### ###
		displayFolder: 0. Mesures à classer
		lineageTag: 02de0c70-6a78-4f69-a7d5-e053db3b93af

		changedProperty = IsHidden

	measure 'SAP8_Calcul de la Réserve Spéciale de Participation' = IF( [SAP8_Bénéfice] <0 || ([SAP8_Bénéfice]-0.05*[SAP8_KP])<0 ,0,1/2*([SAP8_Bénéfice]-0.05*[SAP8_KP])*DIVIDE([SAP6_Assiette taxe sur salaires],[SAP7_VA],0))
		formatString: #,0
		displayFolder: 0. Mesures à classer
		lineageTag: 12bd388d-3457-483e-9afc-a3cdb05a9ea3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure SAP8_Ecart = [SAP8_Solde N comptabilisé]- [SAP8_Calcul de la Réserve Spéciale de Participation]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: a400351f-88e8-47fb-9321-e301f066dde6

		changedProperty = IsHidden

	measure 'SAP8_Forfait sociale' = // IF(SELECTEDVALUE(FiabilisationDonneesUtilisees[Value])="Oui",0.2,0)
		displayFolder: 0. Mesures à classer
		lineageTag: 00b0661b-4b1a-4cb2-b4b0-e13041d93c6d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SAP8_KP = CALCULATE([_Gene_Solde N inv],PlanCompteAEF[DetailNiv1]="Capitaux propres (hors résultat)")+ [SAP8_Bénéfice]
		formatString: ### ### ###
		displayFolder: 0. Mesures à classer
		lineageTag: 5b3f304e-f026-4267-8f5c-cda758bb9721

		changedProperty = IsHidden

	measure SAP8_Participation = // [SAP8_Calcul de la Réserve Spéciale de Participation]*(1+[SAP8_Forfait sociale])
		displayFolder: 0. Mesures à classer
		lineageTag: b3c98349-7c32-49dd-8cc3-dde4f8b1c82e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP8_Solde BG N' =
			IF(
			    OR(ISBLANK(MAX(PlanCompteAEF[LiasseCode])),ISBLANK(MAX(PlanCompteAEF[DetailNiv3]))),
			    [_CP_ResultatNet],
			    CALCULATE([_Cadrage_Solde BG],'KPI'[Exercice]="N"))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 20e56111-2907-4644-82ec-306b5783cad1

		changedProperty = IsHidden

	measure 'SAP8_Solde BG N-1' =
			IF(OR(ISBLANK(MAX(PlanCompteAEF[LiasseCode])),ISBLANK(MAX(PlanCompteAEF[DetailNiv3]))),
			[_CP_ResultatNet N-1],
			CALCULATE([_Cadrage_Solde BG],'KPI'[Exercice]="N-1"))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 76803bfc-1f81-4577-a12b-151b6186245a

		changedProperty = IsHidden

	measure 'SAP8_Solde N calculé' = [SAP8_Solde BG N-1]+[_Gene_Mvt Debit N]-[_Gene_Mvt Credit N]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: b7e08832-aa66-47ad-820b-220bb4c92351

		changedProperty = IsHidden

	measure 'Selected value Date' = MIN(DimTemps[Dates])
		displayFolder: 0. Mesures à classer
		lineageTag: 5f1cce2a-94ff-430f-97c2-ca5ebac72be2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected value T1' = MIN(SliderT1[Code])
		displayFolder: 0. Mesures à classer
		lineageTag: b1ab6883-e175-4357-90e9-c2011d3a3e8e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected value T1 %' = ```
			MIN(SliderT1[Code])/100
			
			```
		displayFolder: 0. Mesures à classer
		lineageTag: aca72b78-cab2-4691-a6a5-3276c1bfe76e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected value T2' = MIN(SliderT2[Code])
		displayFolder: 0. Mesures à classer
		lineageTag: af78ec97-dc0b-480b-a9f0-e37c6644a88d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected value T2 %' = [Selected value T2]/100
		formatString: #,##0.00 %
		displayFolder: 0. Mesures à classer
		lineageTag: a0e360af-5b56-4f99-b1df-85eef2c3b100

		changedProperty = IsHidden

	measure 'Selected value T3' = MIN(SliderT3[Code])
		displayFolder: 0. Mesures à classer
		lineageTag: 1fd84c71-45cf-4996-ac6c-12bb95fd7f09

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected value T3 %' = [Selected value T3]/100
		formatString: #,##0.00 %
		displayFolder: 0. Mesures à classer
		lineageTag: e1b4a3a4-1205-4b72-ad66-003b4e60b118

		changedProperty = IsHidden

	measure 'Selected value T4' = MIN(SliderT4[Code])
		displayFolder: 0. Mesures à classer
		lineageTag: cdbf4cf4-7fb9-4d1f-b44e-aeac24ecfb4f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected value T5' = MIN(SliderT5[Code])+0
		formatString: 0
		displayFolder: 0. Mesures à classer
		lineageTag: 6cabec17-053c-42a7-add5-f9d869ba3238

		changedProperty = IsHidden

	measure 'Selected value T6' = MIN(SliderT6[Code])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 422134ac-19eb-4ac4-bd7e-9c502f2c2ab7

		changedProperty = IsHidden

	measure 'Selected value T7' = MIN(SliderT7[Code])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 89b4760e-ddb9-49d4-b3af-4a7c6fb39b4f

		changedProperty = IsHidden

	measure 'Selected value T8' = MIN(SliderT8[Code])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 16503732-9318-412a-a3b9-64e3b1482f6d

		changedProperty = IsHidden

	measure 'Selected value T9' = MIN(SliderT9[Code])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: cfc9fa45-b9d7-4995-bb39-0ac48edc3612

		changedProperty = IsHidden

	measure SendComment = 1
		displayFolder: 0. Mesures à classer
		lineageTag: c3e8662d-4de7-4a94-88bd-fdb1439820c2

		changedProperty = IsHidden

	measure 'Solde pour bridge immo' =
			if (round(calculate ([_Gene_Solde N],filter('ParamAN','ParamAN'[A/N - Bridge]="A-nouveaux") , filter('ParamDC','ParamDC'[D/C TVI]="Cessions")
			
			    ),0)=0
			
			,blank(),[_Gene_Solde N])
		displayFolder: 0. Mesures à classer
		lineageTag: 0d0a49e0-efb0-4c39-87f3-99d4f8321db2

		changedProperty = IsHidden

	measure 'Titre KP onglets généraux' = if([_Gene_Solde Inversé carte]<0,"Pertes","Bénéfices")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: b57f574a-b18a-432d-a81b-963245fc3c67

		changedProperty = IsHidden

	measure 'TOD1_Acqui N' = ```
			var A = CALCULATE (
			    SUM ( 'KPI'[MTDebit] ),
			    'KPI'[Exercice] = "N",
			    ParamAN[AN - O/N] = "Non",
			    'PlanCompteAEF'[RankingNiv3] in {2,4,6})
			RETURN
			A
			//if ( max('PlanCompteAEF'[RankingNiv3]) in {2,4,6} , calculate ( [_Gene_Mvt Debit N]) , blank() )
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 47a29b69-fdab-44fa-b27b-cb09f9cd6b92

		changedProperty = IsHidden

	measure 'TOD1_Cession N' = ```
			var A = CALCULATE (
			    SUM ( 'KPI'[MTCredit] ),
			    'KPI'[Exercice] = "N",
			    ParamAN[AN - O/N] = "Non",
			    'PlanCompteAEF'[RankingNiv3] in {2,4,6})
			RETURN
			A
			
			
			//if ( max('PlanCompteAEF'[RankingNiv3]) in {2,4,6} , calculate ( [_Gene_Mvt Credit N]) , blank() )
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: b5acc387-f0c8-4244-8ea0-03622c77747d

		changedProperty = IsHidden

	measure 'TOD1_Desciption comptes agrégés' =
			
			switch( true(),
			max('Choix du test'[Code])in {1,2}, "Immobilisations incorporelles, immobilisations corporelles, immobilisations en cours.",
			max('Choix du test'[Code]) in {3,4}, "Services extérieurs."," ")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: ff141c4d-bccb-4102-bfc9-4dc76defb6b5

		changedProperty = IsHidden

	measure 'TOD1_Desciption comptes agrégés 2' =
			
			switch( true(),
			max('Choix du test'[Code])in {1,2}, "Il convient d'exclure les comptes d'amortissement (28) et les comptes de dépréciation (29).",
			max('Choix du test'[Code]) in {3,4}," "," ")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 30725172-d5cd-45e4-a6de-e8857c29f9e7

		changedProperty = IsHidden

	measure 'TOD1_Description de la procédure' =
			switch( true(),
			max('Choix du test'[Code])=2, "- À partir du tableau de variation des immobilisations, sélectionner les cessions à tester ;"&Unichar(10)&"- Pour chaque élément sélectionné, obtenir les justificatifs de cessions des immobilisations et corroborer la cession de l'actif avec la documentation pertinente afin d’effectuer les vérifications nécessaires.",
			max('Choix du test'[Code])=1, "- À partir du tableau de variation des immobilisations, sélectionner les acquisitions à tester ;"&Unichar(10)&"- Pour chaque élément sélectionné, obtenir les justificatifs d’achats des immobilisations et corroborer l’acquisition de l’immobilisation avec la documentation pertinente afin d’effectuer les vérifications nécessaires.",
			max('Choix du test'[Code]) in {3,4}, "- À partir du détail des charges d'entretien / petits matériel et outillages, sélectionner les dépenses à tester ;"&Unichar(10)&"- Pour chaque élément sélectionné, analyser le caractère immobilisable ou non des dépenses.", "")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 50cdcff5-7ae9-4523-a38d-a48acfda961e

		changedProperty = IsHidden

	measure 'TOD1_Dot Amort' = Calculate ( [_Immo_Dot Amort N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: ff492bc0-18d9-477e-b7ae-4a3bafb13af5

		changedProperty = IsHidden

	measure 'TOD1_Dot Depre' = Calculate ( [_Immo_Dot Depre N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 9e9f411f-08f3-4a1e-b4ac-27e347666ccd

		changedProperty = IsHidden

	measure 'TOD1_Rep Amort' = Calculate ( [_Immo_Rep Amort N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 7336d7b8-cfbc-4342-baf2-f4b597661de4

		changedProperty = IsHidden

	measure 'TOD1_Rep Depre' = Calculate ( [_Immo_Rep Depre N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 5fda3c2e-0f58-4e4e-b392-be9d84b00eae

		changedProperty = IsHidden

	measure 'TOD1_Solde N Amort / Depre' = Calculate ( [_Gene_Solde N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 763a22f6-ce74-4deb-9b9b-a1eb7808fb1d

		changedProperty = IsHidden

	measure 'TOD1_Solde N Amort / Depre AN' = Calculate ( [TOD1_Solde N Amort / Depre], ParamAN[AN - O/N] = "Oui")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 51dbccbc-6e71-4133-9d5c-8713b3e9b95c

		changedProperty = IsHidden

	measure 'TOD1_Solde N VB' = Calculate ( [_Gene_Solde N], 'PlanCompteAEF'[RankingNiv3] in {2,4,6})
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: df427117-2895-496f-a021-6212b9309834

		changedProperty = IsHidden

	measure 'TOD1_Solde N-1 Amort / Depre' = Calculate ( [_Gene_Solde N-1], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 67cfa320-fa47-4d14-bab0-07ab7808424a

		changedProperty = IsHidden

	measure 'TOD1_Solde N-1 VB' = Calculate ( [_Gene_Solde N-1], 'PlanCompteAEF'[RankingNiv3] in {2,4,6})
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: b33fe7f1-53f1-4e39-a13f-62229d955212

		changedProperty = IsHidden

	measure 'TOD1_Solde TOD acquisitions' = If ( max('Choix du test'[Code])=1, [_Gene_Mvt Credit N] , blank () )
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 19b41529-a7c1-4156-82cc-58119619e079

		changedProperty = IsHidden

	measure 'TOD1_Titre tableau de détail' =
			switch( true(),
			max('Choix du test'[Code])=1, "Détail des écritures débitrices (acquisitions) par n° d'écriture",
			max('Choix du test'[Code])=2, "Détail des écritures créditrices (cessions) par n° d'écriture",
			max('Choix du test'[Code])=3, "Détail des écritures de charges d'entretien", "Détail du grand-livre")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: f12ee3fb-2ff7-4241-876b-0d13ae8917d0

		changedProperty = IsHidden

	measure TOD1_VNC = [TOD1_Solde N VB]+[TOD1_Solde N Amort / Depre]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 4b91247f-25d2-4e82-987c-14472f0c99fd

		changedProperty = IsHidden

	measure 'TOD2 Charges attendues N' = ([TOD2 Solde bilan N-1]-[Selected value T6])*[Selected value T1 %]*[Selected value T3]/365
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 6aac9d85-dc22-4e6e-99e6-c52c62d8716c

		changedProperty = IsHidden

	measure 'TOD2 Compte 1' =
			IF (
			    CALCULATE (
			        [TOD2 Nombre de comptes sélectionnées],
			        REMOVEFILTERS ( 'KPI'[Compte] )
			    ) < 1,
			    0,
			CALCULATE (
			    MAXX (
			        TOPN (
			            1,
			            DISTINCT ( 'KPI'[Compte] ),
			            'KPI'[Compte], 1
			        ),
			        'KPI'[Compte]
			    ),
			    REMOVEFILTERS ( 'KPI'[Compte] )
			))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 445b42d9-f34c-41da-a941-25e3ddd7ca47

		changedProperty = IsHidden

	measure 'TOD2 Compte 2' =
			IF (
			    CALCULATE (
			        [TOD2 Nombre de comptes sélectionnées],
			        REMOVEFILTERS ( 'KPI'[Compte] )
			    ) < 2,
			    0,
			CALCULATE (
			    MAXX (
			        TOPN (
			            2,
			            DISTINCT ( 'KPI'[Compte] ),
			            'KPI'[Compte], 1
			        ),
			        'KPI'[Compte]
			    ),
			    REMOVEFILTERS ( 'KPI'[Compte] )
			))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 1aad3571-6ab7-4b9e-afbd-8b0302172b5d

		changedProperty = IsHidden

	measure 'TOD2 Compte 3' =
			IF (
			    CALCULATE (
			        [TOD2 Nombre de comptes sélectionnées],
			        REMOVEFILTERS ( 'KPI'[Compte] )
			    ) < 3,
			    0,
			CALCULATE (
			    MAXX (
			        TOPN (
			            3,
			            DISTINCT ( 'KPI'[Compte] ),
			            'KPI'[Compte], 1
			        ),
			        'KPI'[Compte]
			    ),
			    REMOVEFILTERS ( 'KPI'[Compte] )
			))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3e4ed04e-a00f-41dc-8067-2b255e62da03

		changedProperty = IsHidden

	measure 'TOD2 Compte 4' =
			IF (
			    CALCULATE (
			        [TOD2 Nombre de comptes sélectionnées],
			        REMOVEFILTERS ( 'KPI'[Compte] )
			    ) < 4,
			    0,
			CALCULATE (
			    MAXX (
			        TOPN (
			            4,
			            DISTINCT ( 'KPI'[Compte] ),
			            'KPI'[Compte], 1
			        ),
			        'KPI'[Compte]
			    ),
			    REMOVEFILTERS ( 'KPI'[Compte] )
			))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 626e47d9-3903-4d9a-921a-1d6f74b9c062

		changedProperty = IsHidden

	measure 'TOD2 Compte 5' =
			IF (
			    CALCULATE (
			        [TOD2 Nombre de comptes sélectionnées],
			        REMOVEFILTERS ( 'KPI'[Compte] )
			    ) < 5,
			    0,
			    CALCULATE (
			        MAXX (
			            TOPN (
			                5,
			                DISTINCT ( 'KPI'[Compte] ),
			                'KPI'[Compte], 1
			            ),
			            'KPI'[Compte]
			        ),
			        REMOVEFILTERS ( 'KPI'[Compte] )
			    )
			)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e159eadf-d8e1-47d5-815c-10db60e35d93

		changedProperty = IsHidden

	measure 'TOD2 Compte 6' =
			IF (
			    CALCULATE (
			        [TOD2 Nombre de comptes sélectionnées],
			        REMOVEFILTERS ( 'KPI'[Compte] )
			    ) < 6,
			    "-",
			CALCULATE (
			    MAXX (
			        TOPN (
			            6,
			            DISTINCT ( 'KPI'[Compte] ),
			            'KPI'[Compte], 1
			        ),
			        'KPI'[Compte]
			    ),
			    REMOVEFILTERS ( 'KPI'[Compte] )
			))
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 9e274238-bc99-4249-9b3b-066c2ca2ea66

		changedProperty = IsHidden

	measure 'TOD2 CompteName 1' =
			var A = [TOD2 Compte 1]
			return
			
			calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: f77509cf-a608-4a61-b0d2-bfbd969f38d4

		changedProperty = IsHidden

	measure 'TOD2 CompteName 2' =
			var A = [TOD2 Compte 2]
			return
			
			calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: abf6622a-87fc-4e43-973f-96bded90a2a4

		changedProperty = IsHidden

	measure 'TOD2 CompteName 3' =
			var A = [TOD2 Compte 3]
			return
			
			calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3651a03f-10e7-4ee6-826e-b440f7e2201d

		changedProperty = IsHidden

	measure 'TOD2 CompteName 4' =
			var A = [TOD2 Compte 4]
			return
			
			calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: f0d46495-4a6c-4742-9ba6-ad7de0e5a49d

		changedProperty = IsHidden

	measure 'TOD2 CompteName 5' =
			var A = [TOD2 Compte 5]
			return
			
			calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: b7147f0b-7da9-432e-863c-54ff7b8bf7e8

		changedProperty = IsHidden

	measure 'TOD2 CompteName 6' =
			var A = [TOD2 Compte 6]
			return
			
			calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: ace84e21-7f29-4b22-af12-6c98783a2bc8

		changedProperty = IsHidden

	measure 'TOD2 couleur bookmark1' = If( max('Choix du test'[Code])=1,"#FFFFFF00","#FFFFFF")
		displayFolder: 0. Mesures à classer
		lineageTag: e809d7ad-96ad-4206-af18-863b753fc4ad

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 couleur bookmark1 frs' = If( max('Choix du test_frs'[Code])=1,"#FFFFFF00","#FFFFFF")
		displayFolder: 0. Mesures à classer
		lineageTag: d0d465dc-6d36-4676-864a-3a4b85d9936e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 couleur bookmark2' = If( max('Choix du test'[Code])=2,"#FFFFFF00","#FFFFFF")
		displayFolder: 0. Mesures à classer
		lineageTag: 0fe6c13a-6330-4fd6-83d4-9a701392cb3d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 couleur bookmark2 frs' =
			If( max('Choix du test_frs'[Code])=2
			,"#FFFFFF00","#FFFFFF")
		displayFolder: 0. Mesures à classer
		lineageTag: 37dcd784-a352-42ab-9db1-1a0df01b0f2a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 couleur bookmark3' = If( mIN('Choix du test'[Code])=3,"#FFFFFF00","#FFFFFF")
		displayFolder: 0. Mesures à classer
		lineageTag: b20ce867-9fbf-4976-b317-fdd47cc84e2e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 couleur bookmark3 frs' = If( max('Choix du test_frs'[Code])=3,"#FFFFFF00","#FFFFFF")
		displayFolder: 0. Mesures à classer
		lineageTag: 66075ecd-5034-4f7f-bd27-2c70715992b7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 couleur bookmark5 frs' = If( max('Choix du test_frs'[Code])=5,"#FFFFFF00","#FFFFFF")
		displayFolder: 0. Mesures à classer
		lineageTag: 98da03b6-5b93-4d96-927f-46d11caa6bbf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 couleur bookmark6 frs' = If( max('Choix du test_frs'[Code])=6,"#FFFFFF00","#FFFFFF")
		displayFolder: 0. Mesures à classer
		lineageTag: f7827812-dbec-4e49-9fa2-4ca52795f61d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 couleur bookmark7 frs' = If( max('Choix du test_frs'[Code])=7,"#FFFFFF00","#FFFFFF")
		displayFolder: 0. Mesures à classer
		lineageTag: 44e7e448-1122-4799-b203-c4118360322b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 Ecart' = [TOD2 Solde P&L N]-[TOD2 Charges attendues N]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 839901f8-59a1-4959-a4ce-054564a4c7fd

		changedProperty = IsHidden

	measure 'TOD2 Nombre de comptes sélectionnées' = distinctCOUNT('KPI'[Compte])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: f8fc019a-3aeb-4b99-9670-d48c47d3346f

		changedProperty = IsHidden

	measure 'TOD2 SAP déagrégée - Ecart num' = // IF([TOD2 SAP déagrégée - Résultat]="Inférieur à l'écart acceptable",1,0)
		formatString: 0
		displayFolder: 0. Mesures à classer
		lineageTag: 7ec64091-0482-470e-ae06-8aa56be9f162

		changedProperty = IsHidden

	measure 'TOD2 SAP déagrégée - Elem impactant capital' = ```
			// var A = [TOD2 Compte 1]
			// var B = [TOD2 Compte 2]
			// var C = [TOD2 Compte 3]
			// var D = [TOD2 Compte 4]
			// var E = [TOD2 Compte 5]
			// var F = [TOD2 Compte 6]
			// return
			
			// switch ( true,
			// not (max('KPI'[Compte]) in {A,B,C,D,E,F}) , blank(),
			// max('KPI'[Compte]) = A , [Selected value T6.1],
			// max('KPI'[Compte]) = B , [Selected value T6.2],
			// max('KPI'[Compte]) = C , [Selected value T6.3],
			// max('KPI'[Compte]) = D , [Selected value T6.4],
			// max('KPI'[Compte]) = E , [Selected value T6.5],
			// max('KPI'[Compte]) = F , [Selected value T6.6],blank())
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e5d8b177-4a4a-4e04-8457-fafdf545e554

		changedProperty = IsHidden

	measure 'TOD2 SAP déagrégée - Période écoulée' = ```
			// var A = [TOD2 Compte 1]
			// var B = [TOD2 Compte 2]
			// var C = [TOD2 Compte 3]
			// var D = [TOD2 Compte 4]
			// var E = [TOD2 Compte 5]
			// var F = [TOD2 Compte 6]
			// return
			
			// switch ( true,
			// not (max('KPI'[Compte]) in {A,B,C,D,E,F}) , blank(),
			// max('KPI'[Compte]) = A , [Selected value T2.1],
			// max('KPI'[Compte]) = B , [Selected value T2.2],
			// max('KPI'[Compte]) = C , [Selected value T2.3],
			// max('KPI'[Compte]) = D , [Selected value T2.4],
			// max('KPI'[Compte]) = E , [Selected value T2.5],
			// max('KPI'[Compte]) = F , [Selected value T2.6],blank())
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 300607d6-024a-484f-b178-111589d379fe

		changedProperty = IsHidden

	measure 'TOD2 SAP déagrégée - Résultat' = // IF(ABS([TOD2 SAP déagrégée -Ecart])<=[Selected value T5],"Inférieur à l'écart acceptable","Supérieur à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: e69ddff1-fb49-4130-b6ca-6ca65cdfcfb7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD2 SAP déagrégée - Taux d''intérêt' = ```
			// var A = [TOD2 Compte 1]
			// var B = [TOD2 Compte 2]
			// var C = [TOD2 Compte 3]
			// var D = [TOD2 Compte 4]
			// var E = [TOD2 Compte 5]
			// var F = [TOD2 Compte 6]
			// return
			
			// switch ( true,
			// not (max('KPI'[Compte]) in {A,B,C,D,E,F}) , blank(),
			// max('KPI'[Compte]) = A , [Selected value T1.1]/100,
			// max('KPI'[Compte]) = B , [Selected value T1.2]/100,
			// max('KPI'[Compte]) = C , [Selected value T1.3]/100,
			// max('KPI'[Compte]) = D , [Selected value T1.4]/100,
			// max('KPI'[Compte]) = E , [Selected value T1.5]/100,
			// max('KPI'[Compte]) = F , [Selected value T1.6]/100,blank())
			
			```
		formatString: #,##0 %
		displayFolder: 0. Mesures à classer
		lineageTag: ae95b0d6-0360-4c0b-a185-58860f95fe89

		changedProperty = IsHidden

	measure 'TOD2 SAP déagrégée -Ecart' = // [TOD2 Solde P&L N]-[TOD2 SAP désagrégée - Charges attendues N 2]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 5fe5874a-ae45-45e4-906c-4875d1b1be6e

		changedProperty = IsHidden

	measure 'TOD2 SAP désagrégée - Charges attendues N' = // ([TOD2 SAP désagrégée - Solde bilan N-1 ]-[TOD2 SAP déagrégée - Elem impactant capital])*[TOD2 SAP déagrégée - Taux d'intérêt]*[TOD2 SAP déagrégée - Période écoulée]/365
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 0bee1b29-1516-42c9-ac61-81e412dc34c3

		changedProperty = IsHidden

	measure 'TOD2 SAP désagrégée - Charges attendues N 2' =
			// var A = [TOD2 Compte 1]
			// var B = [TOD2 Compte 2]
			// var C = [TOD2 Compte 3]
			// var D = [TOD2 Compte 4]
			// var E = [TOD2 Compte 5]
			// var F = [TOD2 Compte 6]
			
			// return
			
			// Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = A )
			// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = B )
			// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = C )
			// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = D )
			// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = E )
			// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = F )
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 05bb6358-9c1f-4fe1-afe3-ea4bafbca1a9

		changedProperty = IsHidden

	measure 'TOD2 SAP désagrégée - Solde bilan N-1 ' = ```
			var A = [TOD2 Compte 1]
			var B = [TOD2 Compte 2]
			var C = [TOD2 Compte 3]
			var D = [TOD2 Compte 4]
			var E = [TOD2 Compte 5]
			var F = [TOD2 Compte 6]
			
			return
			if( max ('KPI'[Compte]) in {A,B,C,D,E,F} , [TOD2 Solde bilan N-1] , blank() )
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 05bc0a35-36c0-4962-b3da-366c96136d55

		changedProperty = IsHidden

	measure 'TOD2 SAP désagrégée - Solde bilan N-1 hors except.' = // [TOD2 SAP désagrégée - Solde bilan N-1 ]-[TOD2 SAP déagrégée - Elem impactant capital]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e6745759-a495-442f-a2ae-b793c76da4cc

		changedProperty = IsHidden

	measure 'TOD2 Solde bilan N-1' =
			-
			CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]="Bilan")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e098e3f3-05fd-4e13-b757-e624c7a1cf2b

		changedProperty = IsHidden

	measure 'TOD2 Solde bilan N-1 hors except.' = ([TOD2 Solde bilan N-1]-[Selected value T6])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 5a27e8e9-39d2-4d35-ad9d-146dfbd5c0b9

		changedProperty = IsHidden

	measure 'TOD2 Solde P&L N' = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3b3f8eaf-64ad-4afd-ba69-41c47939c5c6

		changedProperty = IsHidden

	measure 'TOD2_Description abrev' = ```
			switch( true(),
			max('Choix du test_frs'[Code])=1, "AAR",
			max('Choix du test_frs'[Code])=3, "FNP",
			max('Choix du test_frs'[Code])=2, "CCA", 
			max('Choix du test_frs'[Code])=5, "AAE",
			max('Choix du test_frs'[Code])=6, "PCA",
			max('Choix du test_frs'[Code])=7, "FAE",
			"")
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 742d1110-170c-45b7-b4a7-470d8a6bbe31

		changedProperty = IsHidden

	measure 'TOD2_Description comptes agrégés' =
			switch( true(),
			max('Choix du test_frs'[Code])=1, "Pour couvrir les avoirs à recevoir, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #409.",
			max('Choix du test_frs'[Code])=3, "Pour couvrir les factures non parvenues, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #408.",
			max('Choix du test_frs'[Code])=2, "Pour couvrir les charges constatées d'avance, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #486.",
			max('Choix du test_frs'[Code])=5, "Pour couvrir les avoirs à établir, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #4198.",
			max('Choix du test_frs'[Code])=6, "Pour couvrir les produits constatés d'avance, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #487.",
			max('Choix du test_frs'[Code])=7, "Pour couvrir les factures à établir, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #4181."
			, "")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 764e96f4-a434-4dab-9c35-9e9cc9841445

		changedProperty = IsHidden

	measure 'TOD2_Description de la procédure' =
			switch( true(),
			max('Choix du test_frs'[Code])=1, "- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant du produit (tels que les avoirs reçus postérieurement, contrats ou autres justificatifs probants) ;"&Unichar(10)&"- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off achats et les circularisations fournisseurs.",
			max('Choix du test_frs'[Code])=2, "- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant de la charge (tels que les factures (reçues postérieurement), contrats ou autres justificatifs probants) ;"&Unichar(10)&"- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off achats et les circularisations fournisseurs.",
			max('Choix du test_frs'[Code])=3, "- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant de la charge (tels que les factures, contrats ou autres justificatifs probants) ;"&Unichar(10)&"- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off achats et les circularisations fournisseurs.",
			max('Choix du test_frs'[Code])=5, "- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant du produit (tels que les factures émises postérieurement, contrats ou autres justificatifs probants) ;
			- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off ventes et les circularisations clients.",
			max('Choix du test_frs'[Code])=6, "- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant du produit (tels que les factures, contrats ou autres justificatifs probants) ;
			- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off ventes et les circularisations clients.",
			max('Choix du test_frs'[Code])=7, "- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant du produit (tels que les factures émises postérieurement, contrats ou autres justificatifs probants) ;
			- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off ventes et les circularisations clients.",
			 "")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 9fc12b85-7428-427a-9550-a9daa13729d7

		changedProperty = IsHidden

	measure 'TOD2_Ecart num' = IF([TOD2_Résultat ]="Inférieur à l'écart acceptable",1,0)
		formatString: 0
		displayFolder: 0. Mesures à classer
		lineageTag: 2ce1c6a1-3eaf-4c4c-9cff-f67ea49a9e16

		changedProperty = IsHidden

	measure 'TOD2_Résultat ' = IF(ABS([TOD2 Ecart])<=[Selected value T5],"Inférieur à l'écart acceptable","Supérieur à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: e829cf45-8f8d-49c6-9bfc-ff0f661e826b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD3 Dotation aux amort. attendue' = [TOD3 Taux d'amort moyen normalisé N]*[TOD3 Solde bilan N hors except.]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: ddfd3287-40ac-45e2-a0aa-e24faedc1943

		changedProperty = IsHidden

	measure 'TOD3 Ecart' = [TOD3 Solde P&L N]-[TOD3 Dotation aux amort. attendue]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 249e9c53-09e1-4700-970f-5d3e4f7e73c9

		changedProperty = IsHidden

	measure 'TOD3 Solde Amort cumulé' = ```
			-CALCULATE (
			    [_Gene_Solde GL],
			    and ('Compte'[Racine2]>="28",'Compte'[Racine2]<"60"),
			//    'KPI'[Exercice]="N",
			    FILTER (
			        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[QuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear] ),
			        AND(DimTemps[Dates] <= MAX (DimTemps[Dates]) ,
			        DimTemps[FiscalYear] = MAX ( DimTemps[FiscalYear] ))
			        ))
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 750e4182-cd1f-4f87-8431-3981570351bf

		changedProperty = IsHidden

	measure 'TOD3 Solde bilan N' =
			
			CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="Bilan")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 5cca27b2-33b8-4618-97a7-34c1736e0da3

		changedProperty = IsHidden

	measure 'TOD3 Solde bilan N hors except.' = [TOD3 Solde bilan N]-[Selected value T7]
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 0f5641e7-6759-4911-9d35-7ce87d7d4ca7

		changedProperty = IsHidden

	measure 'TOD3 Solde bilan N-1' =
			
			CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]="Bilan")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e0fc2085-b6ee-4efe-be24-7b00a34774e5

		changedProperty = IsHidden

	measure 'TOD3 Solde bilan N-1 hors except.' = ([TOD3 Solde bilan N-1]-[Selected value T6])
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 179e1f41-5e3f-4ce3-9dc9-8042d09e1797

		changedProperty = IsHidden

	measure 'TOD3 Solde P&L' = CALCULATE([_Gene_Solde GL],PlanCompteAEF[BilanNiv1]="P&L")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: eb286066-bf79-4dc6-ab13-6a54a44c775e

		changedProperty = IsHidden

	measure 'TOD3 Solde P&L N' = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]="P&L")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3fb0eedb-fcd1-4b25-b09e-f820b9ca5d53

		changedProperty = IsHidden

	measure 'TOD3 Solde P&L N-1' = CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]="P&L")
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: e7ced162-b6e5-4757-9ed0-8386a58a823a

		changedProperty = IsHidden

	measure 'TOD3 Solde VB cumulé' = ```
			CALCULATE (
			    [_Gene_Solde GL],
			    'Compte'[Racine2]<"28",
			//    'KPI'[Exercice]="N",
			    FILTER (
			        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[QuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear] ),
			        AND(DimTemps[Dates] <= MAX (DimTemps[Dates]) ,
			        DimTemps[FiscalYear] = MAX ( DimTemps[FiscalYear] ))
			        ))
			
			```
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 3b1733bb-d00f-4dd4-8e55-f26228a89dc1

		changedProperty = IsHidden

	measure 'TOD3 Taux d''amort moyen N-1' = ROUND(Divide ([TOD3 Solde P&L N-1],[TOD3 Solde bilan N-1 hors except.],0),2)
		formatString: #,##0.00 %
		displayFolder: 0. Mesures à classer
		lineageTag: ce978073-b209-456f-90e4-5f5ac74205e4

		changedProperty = IsHidden

	measure 'TOD3 Taux d''amort moyen normalisé N' = [TOD3 Taux d'amort moyen N-1] + [Selected value T1]/100
		formatString: #,##0.00 %
		displayFolder: 0. Mesures à classer
		lineageTag: 66e8754b-dc88-4962-a138-fd00b3a77115

		changedProperty = IsHidden

	measure 'TOD3_Ecart num' = IF([TOD3_Résultat]="Inférieur à l'écart acceptable",1,0)
		formatString: 0
		displayFolder: 0. Mesures à classer
		lineageTag: 862ba387-25cc-48e0-9cf7-f956b18fca55

		changedProperty = IsHidden

	measure TOD3_Résultat = IF(ABS([TOD3 Ecart])<=[Selected value T5],"Inférieur à l'écart acceptable","Supérieur à l'écart acceptable")
		displayFolder: 0. Mesures à classer
		lineageTag: 1ef55a8d-554a-4dd0-99ec-d751282de7b7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD3_Solde Amort / Depre' = -Calculate ( [_Gene_Solde GL], 'PlanCompteAEF'[RankingNiv3] in {3,5,7},'KPI'[AN]=2)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 9fb0ca68-56fd-4097-83b9-f230c092c858

		changedProperty = IsHidden

	measure 'TOD3_Solde VB' = Calculate ( [_Gene_Solde GL], 'PlanCompteAEF'[RankingNiv3] in {2,4,6},'KPI'[AN]=2)
		formatString: #,##0
		displayFolder: 0. Mesures à classer
		lineageTag: 13284c31-4255-43e7-a5ae-1e2f6b6a5858

		changedProperty = IsHidden

	measure 'TOD4_type sélection' = ```
			Switch ( True(),
			and (max('KPI'[Exercice]) = "N",max('ParamAN'[AN])=1),"Ecriture d'a-nouveau, Cf note 1", 
			max('KPI'[Exercice]) = "N", "Obtenir la facture fournisseur",
			"Analyser la récurrence de la provision")
			```
		displayFolder: 0. Mesures à classer
		lineageTag: 1628c86b-f4f2-4cc8-a286-96be103cbc95

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TOD4_type sélection num' =
			Switch ( True(),
			[TOD4_type sélection]="Ecriture d'a-nouveau, Cf note 1", 1,
			[TOD4_type sélection]= "Obtenir la facture fournisseur",2,
			[TOD4_type sélection]= "Analyser la récurrence de la provision",3)
		displayFolder: 0. Mesures à classer
		lineageTag: 7e8b073a-f1e9-4a4f-9b62-be561a0448b1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Gene_Nb Lignes N-1' = ```
			
			CALCULATE(
			    COUNT('KPI'[Compte]),'KPI'[Exercice] = "N-1"
			   
			)
			```
		formatString: 0
		displayFolder: 12. JE
		lineageTag: 475803e4-5fbc-4531-9667-47e24cc23120

		changedProperty = IsHidden

	measure '_Clients_TauxDepreClient N-1' = ROUND(calculate ( [_Clients_TauxDepreClient],'KPI'[Exercice]="N-1"),2) +0
		displayFolder: 0. Mesures à classer
		lineageTag: b691cc84-9f05-42bb-bdd5-0ec54f711cd1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Achats_Solde sous jacent' = ```
			var a = CALCULATE([_Gene_Solde GL],removefilters('Compte'[Racine3Libelle],'Compte'[Racine2],'Compte'[Racine3]),removefilters('KPI'[CompteName]))
			return 
			if ( a=0,"Sélectionner un sous-jacent",a)
			```
		displayFolder: 10. Achats
		lineageTag: 393e5087-d795-4e23-b759-facc2a22c42e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Achats_Solde sous jacent N' = ```
			var a = CALCULATE([_Gene_Solde GL],removefilters('Compte'[Racine3Libelle],'Compte'[Racine2],'Compte'[Racine3]),removefilters('KPI'[CompteName]),'KPI'[Exercice]="N")
			return 
			if ( a=0,"Sélectionner un sous-jacent",a)
			```
		formatString: #,0
		displayFolder: 10. Achats
		lineageTag: a65cfb1e-134e-4e56-a0b1-e607cff81614

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Achats_Solde sous jacent N-1' = ```
			var a = CALCULATE([_Gene_Solde GL],removefilters('Compte'[Racine3Libelle],'Compte'[Racine2],'Compte'[Racine3]),removefilters('KPI'[CompteName]),'KPI'[Exercice]="N-1")
			return 
			if ( a=0,"Sélectionner un sous-jacent",a)
			```
		formatString: #,0
		displayFolder: 10. Achats
		lineageTag: 4bb3281f-1de8-4d79-86f4-8bc854c54775

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Achats_Solde N' =
			var a = CALCULATE([_Gene_Solde N],removefilters('PlanCompteAEF'[DetailNiv2],'PlanCompteAEF'[DetailNiv3]))
			return
			if ( a=0,"Sélectionner un agrégat d'AACE",a)
		formatString: #,0
		displayFolder: 10. Achats
		lineageTag: d8f0d615-a5a1-42f1-91b5-bc009e16bed8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Stocks_DépréciationTaux N-1' = calculate ([_Stocks_DépréciationTaux] , 'KPI'[Exercice] = "N-1")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 0. Mesures à classer
		lineageTag: eed4466d-b8c1-4486-afd7-a01fa78e3ef7

		changedProperty = IsHidden

	measure '_Personnel_Tx CS' = DIVIDE( CALCULATE([_Gene_Solde GL],MappingKPI[LiasseCode] = "FZ"),CALCULATE([_Gene_Solde GL],MappingKPI[LiasseCode] = "FY"),0)
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 11. Personnel\Personnel_global
		lineageTag: f1bf7bf2-ac45-4330-a9d2-ff61a638dde1

		changedProperty = IsHidden

	measure '_Personnel_Tx CS N-1' = calculate ( [_Personnel_Tx CS], 'KPI'[Exercice] = "N-1")
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 11. Personnel\Personnel_global
		lineageTag: 6c35faf6-9ab1-4e26-9802-5ee8ce21ba64

		changedProperty = IsHidden

	measure 'TOD3 Solde VNC cumulé' =
			CALCULATE (
			    [_Gene_Solde GL],
			    AND('Compte'[Racine2]>=20,'Compte'[Racine2]<=28),
			//    'KPI'[Exercice]="N",
			    FILTER (
			        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[QuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear] ),
			        AND(DimTemps[Dates] <= MAX (DimTemps[Dates]) ,
			        DimTemps[FiscalYear] = MAX ( DimTemps[FiscalYear] ))
			        ))
		displayFolder: 0. Mesures à classer
		lineageTag: f41ad145-1733-408b-af62-7ab0df6a717b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Solde carte etatsfi 1' = ```
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			CALCULATE( [_Gene_Solde Inversé carte],PlanCompteAEF[RankingNiv2] = 20),
			CALCULATE( [_Gene_Solde carte],PlanCompteAEF[RankingNiv1] = 1))
			
			```
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: 453eef9a-d25d-4e30-b5f2-b42c27c0a4b5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 1 N-1' = CALCULATE( [_Solde carte etatsfi 1],'KPI'[Exercice]="N-1")
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: c3681cef-418a-410c-97da-a80cc9de2eb4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 2' =
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			CALCULATE( [_Gene_Solde Inversé carte],PlanCompteAEF[RankingNiv2] = 21),
			CALCULATE( [_Gene_Solde carte],PlanCompteAEF[RankingNiv1] = 2))
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: e043f05f-575e-4861-af45-f4047dac91dc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 2 N-1' = CALCULATE( [_Solde carte etatsfi 2],'KPI'[Exercice]="N-1")
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: 467c0747-75d1-47c9-9916-fb39636c22a9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 3' =
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			CALCULATE( [_Gene_Solde Inversé carte],PlanCompteAEF[RankingNiv2] = 23),
			CALCULATE( [_Gene_Solde carte],PlanCompteAEF[RankingNiv1] = 3))
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: 95c3bd6d-e31e-4d9f-a646-1eb9ae73678c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 3 N-1' = CALCULATE( [_Solde carte etatsfi 3],'KPI'[Exercice]="N-1")
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: 0a0cb502-89ed-45fc-bfec-081156ca07cd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 4' =
			
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			CALCULATE( [_Gene_Solde Inversé carte],PlanCompteAEF[RankingNiv2] = 24),
			CALCULATE( [_Gene_Solde carte],PlanCompteAEF[RankingNiv1] = 4))
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: c3c5b4b0-541c-439c-9372-6b6e06b09f87

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 4 N-1' = CALCULATE( [_Solde carte etatsfi 4],'KPI'[Exercice]="N-1")
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: b33485a6-6735-4b99-9bbf-0285fac1b968

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 5' = ```
			
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			CALCULATE( [_Gene_Solde Inversé carte],PlanCompteAEF[RankingNiv2] in {25 ,26}),
			CALCULATE( [_Gene_Solde carte],PlanCompteAEF[RankingNiv1] in {5 ,6}))
			
			
			```
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: bf4b0431-a95f-499c-9276-b360dfc2c123

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 5 N-1' = CALCULATE( [_Solde carte etatsfi 5],'KPI'[Exercice]="N-1")
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: 57c395fc-7c62-498f-baac-d701810f94f4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 6' = ```
			
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			CALCULATE( [_Gene_Solde Inversé carte],PlanCompteAEF[RankingNiv2] in {27 ,28}),
			CALCULATE( [_Gene_Solde carte],PlanCompteAEF[RankingNiv1] =7 ))
			
			
			```
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: 4d646c05-8b0f-4c65-8952-a3772fa1385e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde carte etatsfi 6 N-1' = CALCULATE( [_Solde carte etatsfi 6],'KPI'[Exercice]="N-1")
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: 5b6014ff-34b1-4df2-9860-75d230e961f4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde graphe etatsfi' = ```
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			[_Gene_Solde inv],
			[_Gene_Solde Cumulé])
			
			```
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: 1621a953-4692-43f0-92d3-9fb713d433c8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Title etatsfi 1' = ```
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			"Produits d'exploitation", 
			"Actif immobilisé")
			```
		displayFolder: 07. Etats financiers
		lineageTag: b7cb5822-861f-475d-b633-62cd81aa43f7

		changedProperty = IsHidden

	measure '_Title etatsfi 2' = ```
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			"Charges d'exploitation", 
			"Actif circulant")
			```
		displayFolder: 07. Etats financiers
		lineageTag: 4dfd3c28-9d1e-4450-959b-7d9a98512d76

		changedProperty = IsHidden

	measure '_Title etatsfi 3' = ```
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			"Produits financiers", 
			"Comptes de régul. actif")
			```
		displayFolder: 07. Etats financiers
		lineageTag: c09321e5-8057-40e2-bcdf-8121199db76c

		changedProperty = IsHidden

	measure '_Title etatsfi 4' = ```
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			"Charges financières", 
			"Capitaux propres")
			```
		displayFolder: 07. Etats financiers
		lineageTag: 89186b1e-e7d2-41d1-aa40-fce0f25e0d1e

		changedProperty = IsHidden

	measure '_Title etatsfi 5' = ```
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			"Résultat exceptionnel", 
			"Dettes et PRC")
			```
		displayFolder: 07. Etats financiers
		lineageTag: ce1e8a5f-ed0d-46b3-8ec4-d5e900e8d463

		changedProperty = IsHidden

	measure '_Title etatsfi 6' = ```
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			"Impôts et participation", 
			"Comptes de régul. passif")
			```
		displayFolder: 07. Etats financiers
		lineageTag: b1004764-7b3d-4663-9075-e99b7b00fd47

		changedProperty = IsHidden

	measure 'TVA_Solde CA' = CALCULATE([Solde],Compte[Racine2]=70)
		formatString: #,0
		displayFolder: 06. Impôts et taxes
		lineageTag: cc208e48-5f09-43b0-bf3d-d07f5e563323

		changedProperty = IsHidden

	measure 'TVA_Solde tva ventes' = CALCULATE([Solde],Compte[Racine4]=4457 || Compte[Racine5] = 44587)
		formatString: #,0
		displayFolder: 06. Impôts et taxes
		lineageTag: f3cce7b1-e6bc-4d63-b367-efd476c3816b

		changedProperty = IsHidden

	measure 'TVA_strat ventes' =
			SWITCH( TRUE(),
			[TVA_Taux TVA sur ventes] = 0.2 , 1,
			[TVA_Taux TVA sur ventes] = 0.1, 2,
			[TVA_Taux TVA sur ventes]= 0.055,3,
			[TVA_Taux TVA sur ventes] = 0.021,4,
			[TVA_Taux TVA sur ventes]  in { 0, BLANK()},5,
			
			6)
		formatString: 0
		displayFolder: 06. Impôts et taxes
		lineageTag: 2c1381bf-b7ee-4591-b986-84ee7fe1bd49

		changedProperty = IsHidden

	measure 'TVA_Taux TVA sur ventes' = ```
			
			VAR Tx =  DIVIDE([TVA_Solde tva ventes],[TVA_Solde CA],0)
			RETURN
			if ( 
			    ROUND(Tx,3) in {0.055, 0.021 } , 
			    ROUND(Tx,3), 
			    ROUND(Tx,2))
			```
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 06. Impôts et taxes
		lineageTag: 57610f78-164d-42e8-9733-c87ab651e2d1

		changedProperty = IsHidden

	measure '_Gene_Solde inv credit' = calculate (-[_Gene_Solde GL],'KPI'[MTCredit]<>0)
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: d83f97d2-872d-4ef2-b075-4f3c00e89f46

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Solde table etatsfi N' =
			
			if ( MAX(PlanCompteAEF[BilanNiv1]) = "P&L", -[_Gene_Solde N], [_Gene_Solde N])
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: ab17defa-296b-418c-9523-a19162c9a89d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde table etatsfi N-1' =
			
			if ( MAX(PlanCompteAEF[BilanNiv1]) = "P&L", -[_Gene_Solde N-1], [_Gene_Solde N-1])
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: cafed526-9fdc-4119-a8ea-63343124eebd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Variation table etatsfi N' =
			
			if ( MAX(PlanCompteAEF[BilanNiv1]) = "P&L", -[_Gene_Variation N/N-1], [_Gene_Variation N/N-1])
		formatString: #,0
		displayFolder: 07. Etats financiers
		lineageTag: ee1dd50b-a380-4037-92b5-08a81dbf6b59

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Variation% table etatsfi' =
			
			if ( MAX(PlanCompteAEF[BilanNiv1]) = "P&L", - [_Gene_VariationN/N-1%], [_Gene_VariationN/N-1%])
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 07. Etats financiers
		lineageTag: 0395f04c-5c72-477a-8ed4-18f2184ea4a9

		changedProperty = IsHidden

	measure '_Titre etatsfi' = IF(MAX(PlanCompteAEF[BilanNiv1]) = "P&L","Analyse du flux par :", "Analyse du solde cumulé par :")
		displayFolder: 07. Etats financiers
		lineageTag: 55b28c34-a78c-4b9b-a294-d64d7f8bb728

		changedProperty = IsHidden

	measure '_Solde bridge etatsfi' =
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			[_Gene_Solde inv],
			-[_Gene_Solde inv])
		displayFolder: 07. Etats financiers
		lineageTag: 5942e669-b703-436a-a7bd-5c7776e51a39

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Gene_Solde N carte' = [_Gene_Solde N] + 0
		formatString: #,0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: aec55aae-0628-4fb3-bee1-ae49594af6b4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Solde N-1 carte' = [_Gene_Solde N-1] + 0
		formatString: #,0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: ba64bacb-ad72-4b17-846a-ff8f79706ac5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Debit N-1' = CALCULATE(SUM('KPI'[MTDebit]),'KPI'[Exercice]="N-1")
		formatString: #,0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 1fc1c41d-53e7-404e-bbd9-1d959be5cf3d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Debit N' = CALCULATE(SUM('KPI'[MTDebit]),'KPI'[Exercice]="N")
		formatString: #,0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 6f193efb-1631-4528-9cd2-b20503cf01f2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_nbr code journaux N-1' = CALCULATE(DISTINCTCOUNT('KPI'[CodeJournal]),'KPI'[Exercice]="N-1")
		formatString: 0
		displayFolder: 12. JE
		lineageTag: b7aeb7fb-5fd2-4651-9968-086d08d89db4

		changedProperty = IsHidden

	measure '_Gene_nbr code journaux N' = CALCULATE(DISTINCTCOUNT('KPI'[CodeJournal]),'KPI'[Exercice]="N")
		formatString: 0
		displayFolder: 12. JE
		lineageTag: 35d1df54-7abc-4e08-b7ae-4c4df700df69

		changedProperty = IsHidden

	measure '_Solde bridge etatsfi bridge' =
			if ( max(PlanCompteAEF[BilanNiv1]) = "P&L",
			-[_Gene_Solde inv],
			[_Gene_Solde inv])
		displayFolder: 07. Etats financiers
		lineageTag: 7e344eda-7fa7-4b10-a6a6-379b3f8c2737

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Stocks_DépréciationTaux N' = calculate ([_Stocks_DépréciationTaux] , 'KPI'[Exercice] = "N")
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 04. Stocks
		lineageTag: 57e54371-bdd9-4d42-8519-69f22334987e

		changedProperty = IsHidden

	measure '_Stocks_VarDépréBilan table' = ```
			CALCULATE ( [_Gene_Solde GL], Compte[Racine2] = 39, 'KPI'[Exercice] = "N" )
			    - CALCULATE ( [_Gene_Solde GL], Compte[Racine2] = 39, 'KPI'[Exercice] = "N-1" ) 
			```
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: 2504fc62-f46d-4e03-94bc-c1ada87acfaf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Stocks_DotDépréP&L table' = ```
			CALCULATE ( [_Gene_Solde N], FILTER ( Compte, Compte[Racine5] = 68173 ) ) 
			```
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: b84b84d9-a13d-4f43-b3bc-69245eb84f6d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Stocks_RepDépréP&L table' = CALCULATE ( [_Gene_Solde N], FILTER ( Compte, Compte[Racine5] = 78173 ) )
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: 798123bf-042f-4d6d-93c7-9d3a39aa75f5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Stocks_BouclageDépré table' = [_Stocks_VarDépréBilan table] + [_Stocks_DotDépréP&L table] + [_Stocks_RepDépréP&L table]
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: 38f2e533-4643-46d4-88dc-9cfb6eea01ef

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Solde debit' = calculate ([_Gene_Solde GL],'KPI'[MTDebit]<>0)
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 2a2ea517-bf45-49d5-8961-3831deeee4f5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Gene_Solde credit' = calculate ([_Gene_Solde GL],'KPI'[MTCredit]<>0)
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 3bcd5918-28af-4fe4-af41-eef110d146c3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Stocks_DépréciationTaux var' = [_Stocks_DépréciationTaux N]-[_Stocks_DépréciationTaux N-1]
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: 04. Stocks
		lineageTag: ae63a828-329a-4f8e-a8d1-5ba78a61170c

		changedProperty = IsHidden

	measure '_Gene_Solde Moyen N carte' =
			
			[_Gene_Solde Moyen N]+0
		formatString: #,0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 2877d7dc-f065-4eeb-8cc2-b68a7fda69c0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Solde Moyen N-1 carte' =
			
			[_Gene_Solde Moyen N-1]+0
		formatString: #,0.00
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: 2c57dce2-f94b-43e0-a6e0-2d8066d86b8a

		changedProperty = IsHidden

	measure '_Clients_Bouclage_Ecart pour table' = ```
			[_Clients_Var491Dépré pour table] + [_Clients_681N pour table] + [_Clients_781N pour table] 
			```
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: 775a1ee4-5be6-4be8-882e-eb55d57eface

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_Amort Bilan HorsAN pour table' =
			
			CALCULATE(
			        [_Immo_Dot Amort N],
			        'PlanCompteAEF'[DetailNiv3] = "Dép. / amort. immobilisations incorporelles"
			            ||'PlanCompteAEF'[DetailNiv3] = "Dép. / amort. immobilisations corporelles"
			            ||'PlanCompteAEF'[DetailNiv3] = "Dép. immobilisations financières",
			        ParamAN[A/N - Bridge]=""
			)
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 2dfd09a0-cc6e-4fd2-a29f-16cb374c2d3e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_Amort Bouclage Ecart pour table' = [_Immo_Amort Bilan HorsAN pour table]-[_Immo_Amort P&L pour table]
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: dae7e262-0f16-4762-a195-38e931040cd4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_Amort P&L pour table' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    'PlanCompteAEF'[DetailNiv3] = "Dot. amort, dépréciations et prov",'KPI'[Exercice]="N" ,Compte[Racine4]<=6813
			)
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 3e78aeab-17fe-46a2-a1c3-447f145f578c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_VNC P&L pour table' = CALCULATE([_Gene_Solde GL],'KPI'[Exercice]="N",Compte[Racine3]=675 && Compte[Racine4] <> 6756)
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 1bc57f0a-e009-40f6-9688-f3952d7bb010

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_VNC Bilan pour table' = ```
			
			 CALCULATE (
			        [Immos_cessions],
			        'PlanCompteAEF'[DetailNiv3] = "Immobilisations incorporelles brutes" ||
			        'PlanCompteAEF'[DetailNiv3]  = "Immobilisations corporelles brutes"
			    )
			    -CALCULATE (
			        [_Gene_Mvt Debit N],
			        'PlanCompteAEF'[DetailNiv3] = "Dép. / amort. immobilisations incorporelles" ||
			        'PlanCompteAEF'[DetailNiv3] = "Dép. / amort. immobilisations corporelles",
			        NOT('KPI'[SchemaEcriture] IN {"|280|", "|281|", "|280|681|","|281|681|", "|280|281|681|", "|280|781|","|281|781|", "|280|281|781|", "|290|781|"})
			    )
			```
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 74c3792a-11ca-472a-ad97-e2f2a1b54db2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_VNC Ecart pour table' = [_Immo_VNC Bilan pour table]- [_Immo_VNC P&L pour table]
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: f7f80987-49e8-43da-88f8-8c7a50741cb1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Mvt Credit N inv' = -[_Gene_Mvt Credit N]
		formatString: #,0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: 424c9093-5fd7-4afa-8f62-5318b24c723f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R1_Endettementglobal' =
			CALCULATE([_Gene_Solde GL], PlanCompteAEF[DetailNiv1] = "Dettes")
			// n'incluent pas YS = effet portés à l escompte et non échu
			//CALCULATE([_Gene_Solde GL],PlanCompteAEF[LiasseCode] in {"EC","EB","YS"})
		formatString: #,0
		displayFolder: 13. Ratios Diane
		lineageTag: 79dfc38f-9531-4c50-9141-f59b87586930

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R1_Taux' = Divide ([Conan R1_EBE], [Conan R1_Endettementglobal],0)
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 13. Ratios Diane
		lineageTag: 702e4600-a34e-4784-a98c-d54e8bd4923a

		changedProperty = IsHidden

	measure 'Conan R1_EBE' =
			CALCULATE([_Gene_Solde GL],PlanCompteAEF[Marquage EBE]<>"N.a.")
			//PlanCompteAEF[LiasseCode] in {"FL","FM","FN","FO","FS","FT","FU","FV","FW","FX","FY","FZ"}))
		formatString: #,0
		displayFolder: 13. Ratios Diane
		lineageTag: 6fdfe29f-624e-43d6-89bd-98da4e297112

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Solde Inversé carte N-1' = CALCULATE( [_Gene_Solde inv]+0, 'KPI'[Exercice] = "N-1")
		formatString: #,0
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: d14a8eb9-9a4f-4ce3-ba74-2f33c918d164

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Stocks_VarBrutBilan pour table' = ```
			(
			    CALCULATE ( [_Gene_Solde N], 'PlanCompteAEF'[MarquageStocks] = "Stocks bruts" )
			        - CALCULATE ( [_Gene_Solde N-1], 'PlanCompteAEF'[MarquageStocks] = "Stocks bruts" )
			) 
			```
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: 19dd9987-fd3f-43de-9ac6-432e4dddefdc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Stocks_VarBrutP&L pour table' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[MarquageStocks]="Var stocks brut" || PlanCompteAEF[LiasseCode]= "FM",
			    'KPI'[Exercice]="N"
			)
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: a431a214-52eb-46d1-b5d6-148e34d13377

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Stocks_BouclageBrut pour table' = [_Stocks_VarBrutBilan pour table] + [_Stocks_VarBrutP&L pour table]
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: b30f3d24-8507-464b-b5af-49959fe4d8c7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R2_Capitaux Permanents' =
			CALCULATE([_Gene_Solde GL],PlanCompteAEF[RankingNiv1]=4)
			+ CALCULATE([_Gene_Solde GL], PlanCompteAEF[BilanNiv1] = "P&L")
		formatString: #,0
		displayFolder: 13. Ratios Diane
		lineageTag: 08defc9c-43f2-4800-bb73-58cda99e2565

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R2_Total Bilan' = calculate ( [_Gene_Solde GL] , PlanCompteAEF[BilanNiv2] = "Actif" )
		formatString: #,0
		displayFolder: 13. Ratios Diane
		lineageTag: 94e88c63-4044-4087-86ce-51fce44d3c07

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R2_Taux' = DIVIDE([Conan R2_Capitaux Permanents],[Conan R2_Total Bilan],0)
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 13. Ratios Diane
		lineageTag: 79879ee3-3c6a-462d-8872-63c47a923136

		changedProperty = IsHidden

	measure 'Conan R3_Reel et disponible' = CALCULATE([_Gene_Solde GL], PlanCompteAEF[DetailNiv1]= "Actif Circulant")
		formatString: #,0
		displayFolder: 13. Ratios Diane
		lineageTag: 7467d3df-0ad7-4cf8-bf83-048a574dded3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R3_Taux' = DIVIDE([Conan R3_Reel et disponible], [Conan R2_Total Bilan],0)
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 13. Ratios Diane
		lineageTag: 08f81af6-b6be-4ace-8d1d-558483348569

		changedProperty = IsHidden

	measure 'Conan R4_Frais financiers' = CALCULATE([_Gene_Solde GL], PlanCompteAEF[LiasseCode] = "GR")
		formatString: #,0
		displayFolder: 13. Ratios Diane
		lineageTag: d06dedf2-3bf7-49cf-a6ad-8ca464d646ba

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R4_Chiffre d''affaires' = CALCULATE([_Gene_Solde GL], PlanCompteAEF[LiasseCode] in {"FF", "FI", "FC"})
		formatString: #,0
		displayFolder: 13. Ratios Diane
		lineageTag: 1082f50b-0c09-49f1-b05c-a5b2f84088b7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R4_Taux' = DIVIDE([Conan R4_Frais financiers],[Conan R4_Chiffre d'affaires],0)
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 13. Ratios Diane
		lineageTag: e8c904b6-edd4-4e55-a677-e028fc161a62

		changedProperty = IsHidden

	measure 'Conan R5_Frais de personnel' = CALCULATE( [_Gene_Solde GL], PlanCompteAEF[LiasseCode] in {"FY","FZ"})
		formatString: #,0
		displayFolder: 13. Ratios Diane
		lineageTag: 8ff46f40-77b9-4e55-8aa6-298b95dd6f4a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R5_Valeur ajoutee' = CALCULATE([_Gene_Solde GL], PlanCompteAEF[MarquageVA] = "VA")
		formatString: #,0
		displayFolder: 13. Ratios Diane
		lineageTag: 9eb66d9b-72d1-4aee-88c8-8d4ccab22b36

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Conan R5_Taux' = DIVIDE([Conan R5_Frais de personnel],[Conan R5_Valeur ajoutee],0)
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 13. Ratios Diane
		lineageTag: 86144dfd-86d9-4d5e-a003-e4b7eb0f3d87

		changedProperty = IsHidden

	measure 'Conan Calcul global' = 24 * [Conan R1_Taux] + 22* [Conan R2_Taux] + 16 * [Conan R3_Taux] -87 * [Conan R4_Taux] -10 * [Conan R5_Taux]
		displayFolder: 13. Ratios Diane
		lineageTag: bb48dbeb-d51f-4303-a9bf-1363862c89fa

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Conan Multiplicateur1' = 24
		formatString: 0
		displayFolder: 13. Ratios Diane
		lineageTag: 1ffb36e3-1ee9-45c4-a388-a7479401f2d8

		changedProperty = IsHidden

	measure 'Conan Multiplicateur2' = 22
		formatString: 0
		displayFolder: 13. Ratios Diane
		lineageTag: 2ba7a54d-20e0-43be-8f00-cc436b114cf3

		changedProperty = IsHidden

	measure 'Conan Multiplicateur3' = 16
		formatString: 0
		displayFolder: 13. Ratios Diane
		lineageTag: 4563ee65-bc81-4c1c-9e60-0c65036ee558

		changedProperty = IsHidden

	measure 'Conan Multiplicateur4' = -87
		formatString: 0
		displayFolder: 13. Ratios Diane
		lineageTag: 6c927c57-d7d1-4552-b21d-afa79a0fbff1

		changedProperty = IsHidden

	measure 'Conan Multiplicateur5' = -10
		formatString: 0
		displayFolder: 13. Ratios Diane
		lineageTag: 5732e6bb-945b-4f4c-ac87-1965e0943ede

		changedProperty = IsHidden

	measure 'Conan Calcul global N' = calculate ( [Conan Calcul global], 'KPI'[Exercice] = "N")
		displayFolder: 13. Ratios Diane
		lineageTag: 5e8b05ea-cd3b-4427-8b5e-c2bb7a178ca0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Conan Calcul global N-1' = calculate ( [Conan Calcul global], 'KPI'[Exercice] = "N-1")
		displayFolder: 13. Ratios Diane
		lineageTag: ae006aff-a3de-499f-99ec-317e95900206

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TVA_Filter ventes' =
			
			SWITCH( TRUE(),
			SELECTEDVALUE(CategoriesTVA[RankingTVA]) = 1 && [TVA_strat ventes] = 1, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 2 && [TVA_strat ventes] = 2, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 3 && [TVA_strat ventes] = 3, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 4 && [TVA_strat ventes] = 4, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 5 && [TVA_strat ventes] = 5, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 6 && [TVA_strat ventes] = 6, 1,
			0)
		formatString: 0
		lineageTag: 34f316d5-fe9f-4621-ad8b-b3d1335fb39b

		changedProperty = IsHidden

	measure 'TVA_Filter achats' =
			
			SWITCH( TRUE(),
			SELECTEDVALUE(CategoriesTVA[RankingTVA]) = 1 && [TVA_strat achats] = 1, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 2 && [TVA_strat achats] = 2, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 3 && [TVA_strat achats] = 3, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 4 && [TVA_strat achats] = 4, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 5 && [TVA_strat achats] = 5, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 6 && [TVA_strat achats] = 6, 1,
			0)
		lineageTag: f6118439-d449-4b27-8700-c2f12d06fc85

		changedProperty = IsHidden

	measure 'TVA_Solde Achats' = CALCULATE([Solde],and (Compte[Racine2] in {61,62,60} , Compte[Racine3] <> 603 ))
		formatString: #,0
		lineageTag: 56d883f2-1bc2-4f43-ae53-0316f8dc4f00

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'TVA_strat achats' =
			SWITCH( TRUE(),
			[TVA_Taux TVA sur achats] = 0.2 , 1,
			[TVA_Taux TVA sur achats] = 0.1, 2,
			[TVA_Taux TVA sur achats]= 0.055,3,
			[TVA_Taux TVA sur achats] = 0.021,4,
			[TVA_Taux TVA sur achats] in { 0, BLANK()},5,
			6)
		lineageTag: 1fc5dfe6-fd27-41fb-a58d-09382255caf2

		changedProperty = IsHidden

	measure 'TVA_Taux TVA sur achats' = if ( ROUND(DIVIDE([TVA_Solde tva achats],[TVA_Solde Achats],0),3) in {0.055, 0.021 } , ROUND(DIVIDE([TVA_Solde tva achats],[TVA_Solde Achats],0),3), ROUND(DIVIDE([TVA_Solde tva achats],[TVA_Solde Achats],0),2))
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 3ffb6742-eebd-4cdf-a259-717a4fb3f4f6

		changedProperty = IsHidden

	measure '_Solde table KPI N cumulé' =
			
			IF( MAX(MappingKPI[RankingAttribute]) in {1,2,3}, if ( MAX(PlanCompteAEF[BilanNiv1]) = "P&L", -[_Gene_Solde N], [_Gene_Solde N]),
			CALCULATE (
			    if ( MAX(PlanCompteAEF[BilanNiv1]) = "P&L", -[_Gene_Solde N], [_Gene_Solde N]),
			    FILTER (
			        ALLSELECTED ( MappingKPI[Attribute niveau 1],MappingKPI[RankingAttribute 2] ),
			        MappingKPI[RankingAttribute 2]<=MAX(MappingKPI[RankingAttribute 2]))))
		formatString: #,0
		lineageTag: 22a8eb69-3be1-4a06-b8c3-8efb9c69dc98

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Solde table KPI N-1 cumulé' =
			
			IF( MAX(MappingKPI[RankingAttribute]) in {1,2,3}, if ( MAX(PlanCompteAEF[BilanNiv1]) = "P&L", -[_Gene_Solde N-1], [_Gene_Solde N-1]),
			CALCULATE (
			    if ( MAX(PlanCompteAEF[BilanNiv1]) = "P&L", -[_Gene_Solde N-1], [_Gene_Solde N-1]),
			    FILTER (
			        ALLSELECTED ( MappingKPI[Attribute niveau 1],MappingKPI[RankingAttribute 2] ),
			        MappingKPI[RankingAttribute 2]<=MAX(MappingKPI[RankingAttribute 2]))))
		formatString: #,0
		lineageTag: 1186354a-b1ff-4156-aff1-b9ca8f3248a3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_variation table KPI cumulé' = [_Solde table KPI N cumulé]-[_Solde table KPI N-1 cumulé]
		formatString: #,0
		lineageTag: b382e906-8596-441f-89e3-86488a6355df

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_variation table KPI cumulé %' = DIVIDE([_variation table KPI cumulé],[_Solde table KPI N-1 cumulé],0)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 59941f21-eef4-4a1e-a82f-fbf0468a8cdd

		changedProperty = IsHidden

	measure 'KP_ Capitaux propres carte' = [_Gene_Solde inv] + CALCULATE([_Gene_Solde inv], ALL(PlanCompteAEF[DetailNiv1]),PlanCompteAEF[BilanNiv1]="P&L")+0
		formatString: #,0
		lineageTag: adfcbcbf-ef8c-4ea4-9c52-810e4c9f3cc5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'KP_ Capitaux propres carte N-1' = CALCULATE([KP_ Capitaux propres carte], 'KPI'[Exercice] = "N-1")
		formatString: #,0
		lineageTag: a7c3720d-7621-4e2b-99fb-0a8ce99ff6d4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Solde TFT Vecrit.' = CALCULATE([_Gene_Solde inv], not (Compte[Racine1] = 5 && Compte[Racine3] <> 509), 'KPI'[AN] = 2, 'KPI'[EcritureCache] in { 1,2})
		formatString: #,0
		lineageTag: d7f71988-24e8-4e20-8af5-41cfa5661822

		changedProperty = IsHidden

	measure 'Solde ouverture TFT Vecrit.' = CALCULATE([_Gene_Solde GL],Compte[Racine1] = 5 && Compte[Racine3] <> 509, 'KPI'[AN] = 1)
		formatString: #,0
		lineageTag: 9637dc97-fa20-4691-825d-8eaa4cf1eecd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Solde cloture TFT Vecrit.' = CALCULATE([_Gene_Solde GL], Compte[Racine1] = 5 && Compte[Racine3] <> 509)
		formatString: #,0
		lineageTag: 93cfeda3-5913-48f0-8c98-04e91bdf6917

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Solde variation TFT Vecrit.' = [Solde cloture TFT Vecrit.] - [Solde ouverture TFT Vecrit.]
		formatString: #,0
		lineageTag: 04fc0ebd-ca39-4182-b241-722e704d62be

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Solde ecart TFT Vecrit.' = [Solde variation TFT Vecrit.] - [Solde TFT Vecrit.]
		formatString: #,0
		lineageTag: 3551bb93-4b91-4bf8-ae01-e91fbd70a980

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_Amort Bilan' =
			
			CALCULATE(
			        [_Gene_Solde inv],
			        'PlanCompteAEF'[DetailNiv3] = "Dép. / amort. immobilisations incorporelles"
			            ||'PlanCompteAEF'[DetailNiv3] = "Dép. / amort. immobilisations corporelles",
			        ParamAN[A/N - Bridge]=""
			)
		lineageTag: 03e66b3a-fe4a-43ad-8444-c125c776e20f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAP4_DRM client N %' =
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			RETURN DIVIDE([DRM_DY BFR N],MAXIFY,0)*100
		formatString: 0
		lineageTag: fe123c7d-9a7d-420c-8846-7f2c7d265930

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'SAP4_DRM client N-1 %' =
			VAR MAXI = [Nbr jour max N-1]
			VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1
			VAR MAXIFY = [Nbr jour max full year N-1]
			RETURN DIVIDE([DRM_DY BFR N-1],MAXIFY,0)*100
		formatString: 0
		lineageTag: de81cf89-eef0-4b18-a941-c327ce075e97

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Immos_Transferts = CALCULATE([_Gene_Mvt Debit N] - [_Gene_Mvt Credit N],'KPI'[Transfert]=2)
		formatString: #,0
		lineageTag: 0d0f4ffb-0d87-46ac-8e68-1cc51e940de5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'SAP8_Solde N comptabilisé' = CALCULATE([_Gene_Solde N], Compte[Racine3] = 691)+0
		formatString: #,0
		lineageTag: a9f5fc9d-8094-4a59-8eba-e3249a456b93

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Clients_Var491Dépré pour table' = ```
			CALCULATE (
			    SUM ( 'KPI'[MTDebit] ) - SUM ( 'KPI'[MTCredit] ),
			    LEFT('KPI'[Compte],3) = "491",
			    'KPI'[Exercice] = "N", 
			    ParamAN[AN] = 2
			)
			```
		formatString: #,0
		lineageTag: 74851816-15e2-4f78-8067-e2b6955783c1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Lettrage_ Filtre' = ```
			
			SWITCH( TRUE(),
			SELECTEDVALUE(TableLettrage[CodeLet]) = 1 && NOT(ISBLANK(SELECTEDVALUE('KPI'[EcritureLet]))), 1,
			SELECTEDVALUE(TableLettrage[CodeLet]) = 0 && ISBLANK(SELECTEDVALUE('KPI'[EcritureLet])), 1)
			
			```
		formatString: 0
		lineageTag: 8d2b5320-88d8-4656-86ff-bf7d7ea91de4

		changedProperty = IsHidden

	measure 'Solde N anteriorite' = IF(MAX(Compte[Racine2]) = 41 , [_Gene_Solde N] , [_Gene_Solde N inv])
		formatString: #,0
		lineageTag: 8650f570-130d-4a0b-881c-4a3afa403f4b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'TVA_Solde tva achats' = CALCULATE([Solde],Compte[Racine4]=4456 && Compte[Racine5]<> 44562 || Compte[Racine5] = 44586)
		formatString: #,0
		lineageTag: 4d0393be-0cb1-4bc6-aada-a3243d8fdee4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Clients_681N pour table' = ```
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine5] = 68174 || Compte[Racine4] = 6714,
			    'KPI'[Exercice] = "N"
			) 
			```
		formatString: #,0
		lineageTag: 4d78643e-59fc-449c-85f2-d6892af4a390

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Clients_781N pour table' = ```
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine5] = 78174 || Compte[Racine4] = 7714,
			    'KPI'[Exercice] = "N"
			) 
			```
		formatString: #,0
		lineageTag: 1665ff5f-c6c6-4089-8b98-df995ea8d9cd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Nom_Client = MAX(Accounts[AccountLegalName])
		lineageTag: b5a47506-6e81-4c44-a4f2-e121af6b9f65

		changedProperty = IsHidden

	measure 'TVA_Taux moyen TVA col N' = CALCULATE([_Gene_Solde N], Compte[Racine4] = 4457) / CALCULATE([_Gene_Solde N],PlanCompteAEF[LiasseCode] in {"FF","FI", "FC"})
		formatString: #,0.00\ %;-#,0.00\ %;#,0.00\ %
		lineageTag: e1269f71-ffb8-4ec6-9207-60fb372a87b6

		changedProperty = IsHidden

	measure 'TVA_Taux moyen TVA ded N' = CALCULATE([_Gene_Solde N], Compte[Racine4] = 4456) / CALCULATE([_Gene_Solde N],PlanCompteAEF[LiasseCode] in {"FS","FU", "FW"})
		formatString: #,0.00\ %;-#,0.00\ %;#,0.00\ %
		lineageTag: 0b6de0f2-1662-402e-a7cc-983b25044dc3

		changedProperty = IsHidden

	measure '_Gene_Solde N inv wp' = [_Gene_Solde N inv]
		lineageTag: 17564c08-441a-4f0b-a3e3-1c1095d05776

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Gene_Solde N-1 inv wp' = [_Gene_Solde N-1 inv]
		lineageTag: f31f948a-6909-443d-b8f3-058661d9a400

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Ecart_AN = ROUND( [_Gene_Solde N AN] - [_Gene_Solde N-1] , 2)
		formatString: #,0.00
		displayFolder: 0. Mesures à classer
		lineageTag: d3d8cb2b-6988-4bfb-9fac-303605595de4

		changedProperty = IsHidden

	measure Min_date_N =
			
			CALCULATE(MIN(DimTemps[Dates]),
			FILTER(RELATEDTABLE('KPI'), 'KPI'[Exercice] = "N"))
		formatString: Short Date
		displayFolder: 0. Mesures à classer
		lineageTag: 8147baed-64f9-4bcf-ac2d-eca93952f663

		changedProperty = IsHidden

	measure Max_date_N =
			CALCULATE(MAX(DimTemps[Dates]),
			FILTER(RELATEDTABLE('KPI'), 'KPI'[Exercice] = "N"))
		formatString: Short Date
		displayFolder: 0. Mesures à classer
		lineageTag: 4c999cc9-5c15-4872-b9e1-a3de4d5c22d5

		changedProperty = IsHidden

	measure Max_date_N-1 =
			
			CALCULATE(MAX(DimTemps[Dates]),
			FILTER(RELATEDTABLE('KPI'), 'KPI'[Exercice] = "N-1"))
		formatString: Short Date
		displayFolder: 0. Mesures à classer
		lineageTag: cc040b22-a6cf-401b-9071-d7718c4a68c4

		changedProperty = IsHidden

	measure Min_date_N-1 =
			
			CALCULATE(MIN(DimTemps[Dates]),
			FILTER(RELATEDTABLE('KPI'), 'KPI'[Exercice] = "N-1"))
		formatString: Short Date
		displayFolder: 0. Mesures à classer
		lineageTag: 8f8a7f2b-edb9-4f9d-a9b4-d901b8cf0d91

		changedProperty = IsHidden

	measure '_Gene_Solde N_Let_vide' = ```
			
			CALCULATE(
			    [_Gene_Solde N],
			    FILTER('KPI',
			    ISBLANK ('KPI'[EcritureLet]) || 'KPI'[EcritureLet] IN {"","0"," ","00"}
			))
			
			```
		displayFolder: 0. Mesures à classer
		lineageTag: 92929177-d8a3-4f46-acdc-329ad10d76b8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Ecart_solde_N_Let_vide = [_Gene_Solde N] - [_Gene_Solde N_Let_vide]
		displayFolder: 0. Mesures à classer
		lineageTag: 68661c30-00e8-430c-b9e7-3ee7ceccba44

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cutoff_ mois fin exercice' =
			
			VAR A = MONTH(MAX(Parametrage[DateClotureN]))
			VAR B = MAX(DimTemps[Month])
			RETURN CALCULATE(IF(A=B , 1, 0))
		formatString: 0
		displayFolder: tt
		lineageTag: 9efa3533-be5c-40bf-8e61-f598d27550d3

		changedProperty = IsHidden

	measure '_Gene_Solde N AN inv' = - [_Gene_Solde N AN]
		formatString: #,0
		lineageTag: 7b831aab-2103-4065-ab6d-df9a6c117e00

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'QualifFEC_ nbr compte' = DISTINCTCOUNTNOBLANK('KPI'[Compte])+0
		formatString: #,0
		lineageTag: 417d8f54-2e4f-4231-8a47-6b2857af4b31

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr Comptelib' = DISTINCTCOUNTNOBLANK('KPI'[CompteLibelle])+0
		formatString: #,0
		lineageTag: 3d2f1750-e3d7-4f23-bcb4-8edd4063e48b

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr EcritureNum' = DISTINCTCOUNTNOBLANK('KPI'[EcritureNumero])+0
		formatString: #,0
		lineageTag: ed1691bc-f9f3-4082-a1c0-7e16f3f7a5c1

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr JournalCode' = DISTINCTCOUNTNOBLANK('KPI'[CodeJournal])+0
		formatString: #,0
		lineageTag: 7bc7539b-d8d6-4471-8086-6d26fce5de34

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr datecomptable' = DISTINCTCOUNTNOBLANK('KPI'[DateComptable])+0
		formatString: #,0
		lineageTag: 3e74268b-8fee-4e0f-a307-3b841b6e4b14

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr libelleecriture' = DISTINCTCOUNTNOBLANK('KPI'[EcritureLibelle])+0
		formatString: #,0
		lineageTag: de38016f-c956-442b-b04d-3e6a05aea766

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr CompAuxLib' = DISTINCTCOUNTNOBLANK('KPI'[CompAuxLib])+0
		formatString: #,0
		lineageTag: 1876c1ee-3095-4fd3-a37c-1692f197fd32

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr Codelet' = DISTINCTCOUNTNOBLANK('KPI'[EcritureLet])+0
		formatString: #,0
		lineageTag: 0852d4ad-d5df-4d5f-b1d3-8146cc3bdc72

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr utilisateur' = DISTINCTCOUNTNOBLANK('KPI'[Utilisateur])+0
		formatString: #,0
		lineageTag: 1b5e73e2-ca9d-4533-ba6f-9e049b30c6f9

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr Etablissement' = DISTINCTCOUNTNOBLANK('KPI'[CodeEtbt])+0
		formatString: #,0
		lineageTag: 89f18e70-0055-4b6b-98d4-d40b4cc1eee7

		changedProperty = IsHidden

	measure 'QualifFEC_ nbr lignes' = COUNT('KPI'[Compte])+0
		formatString: #,0
		lineageTag: 409e29b0-26d7-49dd-abfb-e589e743fa03

		changedProperty = IsHidden

	measure 'TVA_Solde FRS immos' = CALCULATE([Solde],Compte[Racine3] = 404 )
		lineageTag: db52771d-782f-41aa-8d86-53aec2470ffc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TVA_Solde tva sur immos' = CALCULATE([Solde],Compte[Racine5]=44562 )
		lineageTag: a9b1a13b-e935-41cc-8d23-4041f6d4e45f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TVA_Taux TVA sur immos' = if ( ROUND(DIVIDE([TVA_Solde tva sur immos],[TVA_Solde FRS immos],0),2) in {0.05, 0.02 } , ROUND(DIVIDE([TVA_Solde tva sur immos],[TVA_Solde FRS immos],0),3), ROUND(DIVIDE([TVA_Solde tva sur immos],[TVA_Solde FRS immos],0),2))
		lineageTag: 1c1f2ecf-2e64-400a-9add-60121471830c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TVA_strat immos' =
			SWITCH( TRUE(),
			[TVA_Taux TVA sur immos] = 0.2 , 1,
			[TVA_Taux TVA sur immos] = 0.1, 2,
			[TVA_Taux TVA sur immos]= 0.055,3,
			[TVA_Taux TVA sur immos] = 0.021,4,
			[TVA_Taux TVA sur immos] in { 0, BLANK()},5,
			6)
		formatString: 0
		lineageTag: d6f0e3c5-8b23-4c53-b965-cd73de1b424d

		changedProperty = IsHidden

	measure 'TVA_Filter immos' =
			
			SWITCH( TRUE(),
			SELECTEDVALUE(CategoriesTVA[RankingTVA]) = 1 && [TVA_strat immos] = 1, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 2 && [TVA_strat immos] = 2, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 3 && [TVA_strat immos] = 3, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 4 && [TVA_strat immos] = 4, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 5 && [TVA_strat immos] = 5, 1,
			sELECTEDVALUE(CategoriesTVA[RankingTVA]) = 6 && [TVA_strat immos] = 6, 1,
			0)
		formatString: 0
		lineageTag: a642a44e-0bc1-42aa-9c43-cfbd4c6ff920

		changedProperty = IsHidden

	measure TBC_Stocks_bruts_N = CALCULATE([_Gene_Solde N], Compte[Racine2] IN {30, 31, 32, 33, 34, 35, 36, 37, 38})
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: c35b4789-97e3-4949-978a-2f4caf3671a2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Stocks_bruts_N-1 = CALCULATE([_Gene_Solde N-1], Compte[Racine2] IN {30, 31, 32, 33, 34, 35, 36, 37, 38})
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: f2b0d23a-6e6e-4c0e-b0c2-21919605eb85

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Blank_1 = BLANK()
		formatString: #,0
		displayFolder: 0. Mesures à classer
		lineageTag: 4f86b3ee-b6ba-4c11-9ec3-7049006844a2

		changedProperty = IsHidden

	measure Blank_2 = BLANK()
		formatString: 0
		displayFolder: 0. Mesures à classer
		lineageTag: 3c1c5196-abb4-4cb4-91e8-4f0cd7bc1f81

		changedProperty = IsHidden

	measure Blank_3 = BLANK()
		formatString: 0
		displayFolder: 0. Mesures à classer
		lineageTag: f6f34aef-508d-43f9-94da-b9083350aac6

		changedProperty = IsHidden

	measure TBC_Stocks_dépré_N = CALCULATE([_Gene_Solde N], Compte[Racine2] IN {39})
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: d0e4b09b-7cf9-48da-9fb9-d92651aaca4d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Stocks_dépré_N-1 = CALCULATE([_Gene_Solde N-1], Compte[Racine2] IN {39})
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: 045bec20-5150-475a-bad2-b7ee7a3df157

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Stocks_dot_N = CALCULATE([_Gene_Mvt Credit N inv], Compte[Racine2] IN {39})
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: a64aea8a-e71f-4151-9db7-49096571c916

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Stocks_rep_N = CALCULATE([_Gene_Mvt Debit N], Compte[Racine2] IN {39})
		formatString: #,0
		displayFolder: 04. Stocks
		lineageTag: 50cf800e-ba09-46e4-beb8-e823fac762a3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Blank_4 = BLANK()
		formatString: #,0
		displayFolder: 0. Mesures à classer
		lineageTag: 89c4b065-991e-4f51-b398-651658049b88

		changedProperty = IsHidden

	measure '_Immo_fi_Dot P&L pour table' =
			
			[_Immo_fi_Dot P&L]+0
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 9d4da1bd-ceed-4fb6-875f-912f0d29d3b0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_fi_Depre Bilan HorsAN pour table' =
			
			[_Immo_fi_Depre Bilan HorsAN]+0
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: b561a744-46eb-45e2-81b0-05097e0af06c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_fi_Depre Bouclage Ecart pour table' = [_Immo_fi_Depre Bilan HorsAN pour table]-[_Immo_fi_Dot P&L pour table]-[_Immo_fi_Rep P&L pour table]
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: d2b25e48-272f-4522-b9c8-b74ec5a5e9e2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_fi_Rep P&L pour table' =
			
			[_Immo_fi_Rep P&L]+0
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 105b3b9e-6e76-47e8-af84-1ab5507f14d2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DRM_DY_STOCKS_PF_RATIO_N = calculate( DIVIDE( [DRM_DY Solde stocks PF] , [DRM_DY_stocks solde ventes HT] , 0 ) * [Nbr de jours N], 'KPI'[Exercice] = "N")+0
		formatString: 0
		displayFolder: DRM et DEM par ratio\Stocks
		lineageTag: 249d669c-7ac8-4fea-b010-2fda197ffe17

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DRM_DY_STOCKS_PF_RATIO_N-1 = calculate( DIVIDE( [DRM_DY Solde stocks PF] , [DRM_DY_stocks solde ventes HT] , 0 ) * [Nbr de jours N-1], 'KPI'[Exercice] = "N-1")+0
		formatString: 0
		displayFolder: DRM et DEM par ratio\Stocks
		lineageTag: 24672a71-ca0c-475e-890c-ea7c146c04e8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Stocks_MP_N = CALCULATE( [_Gene_Solde N], PlanCompteAEF[LiasseCode] IN {"BL", "BM", "BT", "BU"})
		displayFolder: 04. Stocks
		lineageTag: b203472e-d11a-4dff-9518-38185b1a2b15

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Achats_MP_N = CALCULATE( [_Gene_Solde N inv], PlanCompteAEF[LiasseCode] IN {"FS", "FT", "FU", "FV"})
		displayFolder: 04. Stocks
		lineageTag: 1a128845-fd92-4837-bc84-93c965986e37

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DRM_DY_STOCKS_MP_RATIO_N = CALCULATE( DIVIDE( [DRM_DY Solde stocks MP] , [DRM_DY_stocks solde achats HT] , 0 ) * [Nbr de jours N], 'KPI'[Exercice] = "N")+0
		formatString: 0
		displayFolder: DRM et DEM par ratio\Stocks
		lineageTag: ed744fc8-742c-4469-ad23-9189caddb13a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DRM_DY_STOCKS_MP_RATIO_N-1 = CALCULATE( DIVIDE( [DRM_DY Solde stocks MP] , [DRM_DY_stocks solde achats HT] , 0 ) * [Nbr de jours N-1], 'KPI'[Exercice] = "N-1")+0
		formatString: 0
		displayFolder: DRM et DEM par ratio\Stocks
		lineageTag: 3b43e3aa-9cfd-42cf-926a-d4fd80f6fa11

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Stocks_MP_N-1 = CALCULATE( [_Gene_Solde N-1], PlanCompteAEF[LiasseCode] IN {"BL", "BM", "BT", "BU"})
		displayFolder: 04. Stocks
		lineageTag: 059949c3-02e1-4c85-ae3c-feadc15d418f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Achats_MP_N-1 = CALCULATE( [_Gene_Solde N-1 inv], PlanCompteAEF[LiasseCode] IN {"FS", "FT", "FU", "FV"})
		displayFolder: 04. Stocks
		lineageTag: dc5db646-601b-42b4-8f04-14ead0cc2c27

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Ventes_PF_N = CALCULATE( [_Gene_Solde N inv], PlanCompteAEF[LiasseCode] IN {"FC", "FF", "FI", "FN", "FM"})
		displayFolder: 04. Stocks
		lineageTag: 061354cc-988b-48f2-b330-de99f327d466

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Ventes_PF_N-1 = CALCULATE( [_Gene_Solde N-1 inv], PlanCompteAEF[LiasseCode] IN {"FC", "FF", "FI", "FN", "FM"})
		displayFolder: 04. Stocks
		lineageTag: bc91b2d3-02a8-4885-9a27-35ab46690ab8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Measure 2'
		displayFolder: 04. Stocks
		lineageTag: 28d66cc7-e4f2-4dde-b8ba-fdacf794bc0d

		changedProperty = IsHidden

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure TBC_Stocks_PF_N = CALCULATE( [_Gene_Solde N], PlanCompteAEF[LiasseCode] IN {"BN", "BO", "BP", "BQ", "BR", "BS"})
		displayFolder: 04. Stocks
		lineageTag: 31930fc1-ace1-43ff-bb76-fd74cde5c316

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Stocks_PF_N-1 = CALCULATE( [_Gene_Solde N-1], PlanCompteAEF[LiasseCode] IN {"BN", "BO", "BP", "BQ", "BR", "BS"})
		displayFolder: 04. Stocks
		lineageTag: 973065ef-09d2-4f97-8815-49324b09f2c0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DRM_DY_STOCKS_MP_RATIO_LABEL = ```
			
			
			 
			var DRMN = ROUND([DRM_DY_STOCKS_MP_RATIO_N] ,0)
			var DRMN1=  ROUND([DRM_DY_STOCKS_MP_RATIO_N-1],0)
			var variation = DRMN - DRMN1
			RETURN
			    " " & 
			    IF(DRMN > DRMN1, "▲ ", IF(DRMN = DRMN1, "⩥ ","▼ ")) & 
			    FORMAT(DRMN1, "0") &  
			    " (" & 
			    IF(DRMN > DRMN1, "+",IF(DRMN < DRMN1, "","")) & 
			    IF(DRMN =  DRMN1 , "stable)",FORMAT(variation , "0") & " jours)")
			    
			```
		displayFolder: DRM et DEM par ratio\Stocks
		lineageTag: 0ac74eef-93df-4552-bc76-3943103aed4a

		changedProperty = IsHidden

	measure DRM_DY_STOCKS_MP_RATIO_VAR = ROUND( [DRM_DY_STOCKS_MP_RATIO_N] - [DRM_DY_STOCKS_MP_RATIO_N-1],0)
		displayFolder: DRM et DEM par ratio\Stocks
		lineageTag: fa2c22f5-d173-49ee-9e34-bc90e6a742c9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DRM_DY_STOCKS_PF_RATIO_VAR = ROUND([DRM_DY_STOCKS_PF_RATIO_N] - [DRM_DY_STOCKS_PF_RATIO_N-1],0)
		displayFolder: DRM et DEM par ratio\Stocks
		lineageTag: 3f50e062-dddc-4025-a576-87beaeca5e0a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DRM_DY_STOCKS_PF_RATIO_LABEL = ```
			
			
			 
			var DRMN = ROUND([DRM_DY_STOCKS_PF_RATIO_N] ,0)
			var DRMN1=  ROUND([DRM_DY_STOCKS_PF_RATIO_N-1],0)
			var variation = DRMN - DRMN1
			RETURN
			    " " & 
			    IF(DRMN > DRMN1, "▲ ", IF(DRMN = DRMN1, "⩥ ","▼ ")) & 
			    FORMAT(DRMN1, "0") &  
			    " (" & 
			    IF(DRMN > DRMN1, "+",IF(DRMN < DRMN1, "","")) & 
			    IF(DRMN =  DRMN1 , "stable)",FORMAT(variation , "0") & " jours)")
			```
		displayFolder: DRM et DEM par ratio\Stocks
		lineageTag: ed5add30-42c1-4a46-964c-742e959560b8

		changedProperty = IsHidden

	measure TBC_SAP4_DRM_client_Var = [SAP4_DRM client N] - [SAP4_DRM client N-1]
		formatString: 0
		displayFolder: 0. Mesures à classer
		lineageTag: 6537fc85-ec5e-4acb-9d48-9c5c613552c6

		changedProperty = IsHidden

	measure DRM_DY_CLIENTS_LABEL = ```
			
			
			var DRMN = ROUND([DRM_DY_CLIENTS_N],0)
			var DRMN1=  ROUND([DRM_DY_CLIENTS_N-1],0)
			var variation = DRMN - DRMN1
			RETURN
			    " " & 
			    IF(DRMN > DRMN1, "▲ ", IF(DRMN = DRMN1, "⩥ ","▼ ")) & 
			    FORMAT(DRMN1, "0") &  
			    " (" & 
			    IF(DRMN > DRMN1, "+",IF(DRMN < DRMN1, "","")) & 
			    IF(DRMN =  DRMN1 , "stable)",FORMAT(variation , "0") & " jours)")
			```
		displayFolder: DRM et DEM par apurement\Clients et BFR
		lineageTag: 2add5e15-f3d7-4de5-a241-28a006889e4b

		changedProperty = IsHidden

	measure 'SAP4_DRS MP Var' = [SAP4_DRS MP N] - [SAP4_DRS MP N-1]
		formatString: 0
		displayFolder: 0. Mesures à classer
		lineageTag: 247f30ca-6616-4952-b9a2-137b220f5a3e

		changedProperty = IsHidden

	measure 'DRM_DY STOCKS MP Label' = ```
			
			
			var DRMN = ROUND([DRM_DY_STOCKS_MP_N] ,0)
			var DRMN1=  ROUND([DRM_DY_STOCKS_MP_N-1],0)
			var variation = DRMN - DRMN1
			RETURN
			    " " & 
			    IF(DRMN > DRMN1, "▲ ", IF(DRMN = DRMN1, "⩥ ","▼ ")) & 
			    FORMAT(DRMN1, "0") &  
			    " (" & 
			    IF(DRMN > DRMN1, "+",IF(DRMN < DRMN1, "","")) & 
			    IF(DRMN =  DRMN1 , "stable)",FORMAT(variation , "0") & " jours)")
			```
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: c0426c63-9749-453d-a636-6152f68e730f

		changedProperty = IsHidden

	measure TBC_Créances_N = CALCULATE( [_Gene_Solde N], PlanCompteAEF[LiasseCode] IN {"BX"})
		displayFolder: 03. Clients\Clients_global
		lineageTag: 958cd219-cb07-4875-b170-15b744bfd47c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Créances_N-1 = CALCULATE( [_Gene_Solde N-1], PlanCompteAEF[LiasseCode] IN {"BX"})
		displayFolder: 03. Clients\Clients_global
		lineageTag: f604201b-d054-41a4-a2ac-91c8e8e75116

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Ventes_N = CALCULATE( [_Gene_Solde N inv], PlanCompteAEF[LiasseCode] IN {"FC", "FF", "FI"})
		displayFolder: 03. Clients\Clients_global
		lineageTag: 786f36fd-f2e1-40b3-a35c-8ae5c5a8c048

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Ventes_N-1 = CALCULATE( [_Gene_Solde N-1 inv], PlanCompteAEF[LiasseCode] IN {"FC", "FF", "FI"})
		displayFolder: 03. Clients\Clients_global
		lineageTag: 9c7c6076-b41c-438c-9c05-466c0a21d3fb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DRM_DY_CLIENTS_RATIO_N = CALCULATE(DIVIDE( [DRM_DY Solde créances] , [DRM_DY_clients solde ventes TTC] , 0 ) * [Nbr de jours N], 'KPI'[Exercice] = "N")+0
		formatString: 0
		displayFolder: DRM et DEM par ratio\Clients
		lineageTag: 54f4602e-11cb-48c2-8c79-48ced84707ee

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DRM_DY_CLIENTS_RATIO_N-1 = CALCULATE(DIVIDE( [DRM_DY Solde créances] , [DRM_DY_clients solde ventes TTC] , 0 ) * [Nbr de jours N-1], 'KPI'[Exercice] = "N-1")+0
		formatString: 0
		displayFolder: DRM et DEM par ratio\Clients
		lineageTag: d0f94779-8f3e-4fde-8b49-bfe77f280c07

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DRM_DY_CLIENTS_RATIO_VAR = ROUND( [DRM_DY_CLIENTS_RATIO_N] - [DRM_DY_CLIENTS_RATIO_N-1],0)
		displayFolder: DRM et DEM par ratio\Clients
		lineageTag: d5d0a5bb-7ac2-4af8-8d8b-63e96056d448

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DRM_DY_CLIENTS_RATIO_LABEL = ```
			
			var DRMN = ROUND([DRM_DY_CLIENTS_RATIO_N],0)
			var DRMN1=  ROUND([DRM_DY_CLIENTS_RATIO_N-1],0)
			var variation = DRMN - DRMN1
			RETURN
			    " " & 
			    IF(DRMN > DRMN1, "▲ ", IF(DRMN = DRMN1, "⩥ ","▼ ")) & 
			    FORMAT(DRMN1, "0") &  
			    " (" & 
			    IF(DRMN > DRMN1, "+",IF(DRMN < DRMN1, "","")) & 
			    IF(DRMN =  DRMN1 , "stable)",FORMAT(variation , "0") & " jours)")
			    
			```
		displayFolder: DRM et DEM par ratio\Clients
		lineageTag: b7dd2182-0dba-4800-b77e-9c1233b5e2b3

		changedProperty = IsHidden

	measure 'SAP4_DRM FRS Var' = [SAP4_DRM FRS N] - [SAP4_DRM FRS N-1]
		formatString: 0
		displayFolder: 0. Mesures à classer
		lineageTag: 8f1cb24e-81f2-4e27-9577-f3392a91bb38

		changedProperty = IsHidden

	measure DRM_DY_FRS_LABEL = ```
			
			
			var DRMN = ROUND([DRM_DY_FRS_N] ,0)
			var DRMN1=  ROUND([DRM_DY_FRS_N-1],0)
			var variation = DRMN - DRMN1
			RETURN
			    " " & 
			    IF(DRMN > DRMN1, "▲ ", IF(DRMN = DRMN1, "⩥ ","▼ ")) & 
			    FORMAT(DRMN1, "0") &  
			    " (" & 
			    IF(DRMN > DRMN1, "+",IF(DRMN < DRMN1, "","")) & 
			    IF(DRMN =  DRMN1 , "stable)",FORMAT(variation , "0") & " jours)")
			```
		displayFolder: DRM et DEM par apurement\Fournisseurs
		lineageTag: 253e81ea-dd12-4e9a-aa50-6c47f681e15c

		changedProperty = IsHidden

	measure TBC_Dettes_N = CALCULATE( [_Gene_Solde N inv], PlanCompteAEF[LiasseCode] IN {"DX"})
		displayFolder: 10. Achats
		lineageTag: b308e268-b728-46fd-9e68-4904ce17d9ab

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Dettes_N-1 = CALCULATE( [_Gene_Solde N-1 inv], PlanCompteAEF[LiasseCode] IN {"DX"})
		displayFolder: 10. Achats
		lineageTag: fbdca25a-b9be-4f6e-aef3-86e7f53cd9c4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Achats_N = CALCULATE( [_Gene_Solde N], PlanCompteAEF[LiasseCode] IN {"FS", "FU", "FW"})
		displayFolder: 10. Achats
		lineageTag: ceb23ecb-bd98-4483-bf03-201752b04570

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TBC_Achats_N-1 = CALCULATE( [_Gene_Solde N-1], PlanCompteAEF[LiasseCode] IN {"FS", "FU", "FW"})
		displayFolder: 10. Achats
		lineageTag: eae89075-16c9-48d3-a4d5-6a9ea7b5fb1d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DRM_DY_FRS_RATIO_N = CALCULATE( DIVIDE( [DRM_DY Solde dettes] , [DRM_DY_frs solde achats TTC], 0 ) * [Nbr de jours N],'KPI'[Exercice] = "N")+0
		formatString: 0
		displayFolder: DRM et DEM par ratio\Fournisseurs
		lineageTag: 7e7ee758-5ce3-44bb-94f4-599b19235c53

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DRM_DY_FRS_RATIO_N-1 = CALCULATE(DIVIDE( [DRM_DY Solde dettes], [DRM_DY_frs solde achats TTC], 0 ) * [Nbr de jours N-1],'KPI'[Exercice] = "N-1")+0
		formatString: 0
		displayFolder: DRM et DEM par ratio\Fournisseurs
		lineageTag: 5fa6cc33-53d0-4d02-b973-d16a50b61260

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DRM_DY_FRS_RATIO_VAR = ROUND( [DRM_DY_FRS_RATIO_N] - [DRM_DY_FRS_RATIO_N-1] , 0)
		displayFolder: DRM et DEM par ratio\Fournisseurs
		lineageTag: c31a81e2-160f-425f-9bbb-70a8df4282ec

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DRM_DY_FRS_RATIO_LABEL = ```
			
			 
			var DRMN = ROUND([DRM_DY_FRS_RATIO_N],0)
			var DRMN1=  ROUND([DRM_DY_FRS_RATIO_N-1],0)
			var variation = DRMN - DRMN1
			RETURN
			    " " & 
			    IF(DRMN > DRMN1, "▲ ", IF(DRMN = DRMN1, "⩥ ","▼ ")) & 
			    FORMAT(DRMN1, "0") &  
			    " (" & 
			    IF(DRMN > DRMN1, "+",IF(DRMN < DRMN1, "","")) & 
			    IF(DRMN =  DRMN1 , "stable)",FORMAT(variation , "0") & " jours)")
			    
			```
		displayFolder: DRM et DEM par ratio\Fournisseurs
		lineageTag: fd361393-4a23-4f2d-b8f0-3e75cf46980b

		changedProperty = IsHidden

	measure TBC_Clients_410411N = ```
			CALCULATE(
			    [_Gene_Solde N],
			    Compte[Racine3] IN {410, 411, 412}
			)
			
			```
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: 71c48046-3923-4f7f-a212-70dac11d8144

		changedProperty = IsHidden

	measure TBC_Clients_410411N_LetVide = ```
			CALCULATE(
			    [_Gene_Solde N],
			    Compte[Racine3] IN {410, 411, 412},
			    'KPI'[EcritureLet] = ""
			)
			
			```
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: 953581e0-6632-44d5-88d5-da5717c899ae

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Clients_410411N_ecart = [TBC_Clients_410411N] - [TBC_Clients_410411N_LetVide]
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: 0641d6ba-7065-4d9b-a019-f550f80fc220

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Frs_400401N_LetVide = ```
			CALCULATE(
			    [_Gene_Solde N],
			    Compte[Racine3] IN {400, 401, 402},
			    'KPI'[EcritureLet] = ""
			)
			
			```
		formatString: #,0
		displayFolder: 10. Achats
		lineageTag: 5d535ba8-1144-49c3-88fd-4b4f29924d56

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Frs_400401N = ```
			CALCULATE(
			    [_Gene_Solde N],
			    Compte[Racine3] IN {400, 401, 402}
			)
			
			```
		formatString: #,0
		displayFolder: 10. Achats
		lineageTag: c670c6b9-5850-47de-8357-378958d8a6fd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Frs_400401N_ecart = [TBC_Frs_400401N] - [TBC_Frs_400401N_LetVide]
		formatString: #,0
		displayFolder: 10. Achats
		lineageTag: 3fb8f95d-e8c5-4170-800d-89fac8cdedbb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_fi_P&L pour table' = [_Immo_fi_Dot P&L pour table] + [_Immo_fi_Rep P&L pour table]+0
		formatString: #,0
		displayFolder: 02. Immobilisations
		lineageTag: 14a0765c-5389-422d-a75d-9fbf617b2c5d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_CA_N = CALCULATE( [_Gene_Solde N inv], Compte[Racine2] IN {70})
		formatString: #,0
		displayFolder: 03. Clients\Clients_global
		lineageTag: a7057427-16d8-4495-bc5c-4ed0db93d283

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Credit N' = CALCULATE(SUM('KPI'[MTCredit]),'KPI'[Exercice]="N")
		formatString: #,0
		displayFolder: 01. Mesures globales\Débit et Crédit
		lineageTag: a4ca57eb-e063-407b-96f1-960eff13378d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TBC_Achats_N_SE = CALCULATE( [_Gene_Solde N], MappingPCG[CS_STANDARD] IN {"ACHATS", "SERVICES EXTERIEURS"})
		formatString: #,0
		displayFolder: 10. Achats
		lineageTag: 65564e73-bcd3-4a85-b3cd-0d20a7bb2240

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Blank_tooltip = " "
		displayFolder: 0. Mesures à classer
		lineageTag: 6ebad5e7-4575-4677-88cd-fa6ac05599a0

		changedProperty = IsHidden

	measure 'SAP4_P&L cumulé inv N  pour table' = ```
			
			-IF(Isblank([_Gene_Solde GL]),BLANK(),
			CALCULATE (
			    [_Gene_Solde GL] ,
			    PlanCompteAEF[BilanNiv1]="P&L",
			    'KPI'[Exercice]="N",
			    FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			)  
			```
		formatString: #,0
		lineageTag: 3e75722e-573b-4311-9c73-fb5144a2eb16

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DRM_DY_clients solde ventes TTC' = ```
			
			 
			 -IF(
			        Isblank(CALCULATE( [Solde] , PlanCompteAEF[LiasseCode] in {"FC","FF","FI"})+ CALCULATE([Solde],CONTAINSSTRING('KPI' [SchemaEcriture], "70"), Compte[Racine4] = 4457 ||Compte[Racine5] = 44587 ) )
			        ,BLANK(),
			
			        CALCULATE(CALCULATE( [Solde] , PlanCompteAEF[LiasseCode] in {"FC","FF","FI"})+ CALCULATE([Solde],CONTAINSSTRING('KPI' [SchemaEcriture], "70"), Compte[Racine4] = 4457||Compte[Racine5] = 44587) ,
			        FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			) 
			```
		formatString: #,0
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: d11b7359-cb5c-4643-a3e9-e28356710641

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DRM_DY Solde créances' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[LiasseCode] = "BX",
			    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))
		formatString: #,0
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: 4df415e6-dfed-4bc1-b0dc-c4764ff99865

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DRM_DY_CLIENTS_N = ```
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ), 
			            CALCULATE([DRM_DY_clients solde ventes TTC], 'KPI'[Exercice] = "N") > CALCULATE([DRM_DY Solde créances], 'KPI'[Exercice] = "N")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde créances], 'KPI'[Exercice] = "N")
			VAR PL =  CALCULATE([DRM_DY_clients solde ventes TTC], 'KPI'[Exercice] = "N")
			
			
			RETURN
			CALCULATE(
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0 , 
			  'KPI'[Exercice] = "N")
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Clients et BFR
		lineageTag: be5ee572-be9e-465d-a199-defc9907aef6

		changedProperty = IsHidden

	measure DRM_DY_CLIENTS_N-1 = ```
			VAR MAXI = [Nbr jour max N-1]
			VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1
			VAR MAXIFY = [Nbr jour max full year N-1]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            CALCULATE([DRM_DY_clients solde ventes TTC] , 'KPI'[Exercice] = "N-1")> CALCULATE([DRM_DY Solde créances], 'KPI'[Exercice] = "N-1")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde créances],  'KPI'[Exercice] = "N-1")
			VAR PL =  CALCULATE([DRM_DY_clients solde ventes TTC],  'KPI'[Exercice] = "N-1")
			
			
			RETURN
			
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Clients et BFR
		lineageTag: 23d9fd28-91e4-4ca4-8296-68e307a03e7f

		changedProperty = IsHidden

	measure 'DRM_DY Solde dettes' =
			
			CALCULATE (
			    - [Solde],
			    PlanCompteAEF[LiasseCode] = "DX",
			    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))
		formatString: #,0
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: 179e9f7c-d023-4229-803a-49179f7e08d0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DRM_DY_frs solde achats TTC' = ```
			
			 
			 -IF(
			        Isblank(CALCULATE( -[Solde] , PlanCompteAEF[LiasseCode] in {"FS","FU","FW"})+ CALCULATE(-[Solde],((CONTAINSSTRING('KPI'[SchemaEcriture], "|60") && NOT (CONTAINSSTRING('KPI'[SchemaEcriture], "|603,")) ) || CONTAINSSTRING('KPI'[SchemaEcriture], "|61")|| CONTAINSSTRING('KPI'[SchemaEcriture], "|62")),Compte[Racine4]=4456 && Compte[Racine5]<> 44562 || Compte[Racine5] = 44586))
			        ,BLANK(),
			
			        CALCULATE (CALCULATE( -[Solde] , PlanCompteAEF[LiasseCode] in {"FS","FU","FW"})+ CALCULATE(-[Solde],((CONTAINSSTRING('KPI'[SchemaEcriture], "|60") && NOT (CONTAINSSTRING('KPI'[SchemaEcriture], "|603|")) ) || CONTAINSSTRING('KPI'[SchemaEcriture], "|61")|| CONTAINSSTRING('KPI'[SchemaEcriture], "|62")),Compte[Racine4]=4456 && Compte[Racine5]<> 44562 || Compte[Racine5] = 44586),
			    
			        FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			) 
			```
		formatString: #,0
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: 8dd979aa-0c1e-4a01-849e-43215eced7d4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DRM_DY_FRS_N = ```
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            CALCULATE([DRM_DY_frs solde achats TTC], 'KPI'[Exercice] ="N") > CALCULATE([DRM_DY Solde dettes], 'KPI'[Exercice] = "N")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde dettes], 'KPI'[Exercice] = "N")
			VAR PL =  [DRM_DY_frs solde achats TTC]
			
			
			RETURN
			
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Fournisseurs
		lineageTag: 62688f94-d0b1-4354-ba26-1f757fed8434

		changedProperty = IsHidden

	measure DRM_DY_FRS_N-1 = ```
			VAR MAXI = [Nbr jour max N-1]
			VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1
			VAR MAXIFY = [Nbr jour max full year N-1]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            CALCULATE([DRM_DY_frs solde achats TTC], 'KPI'[Exercice] = "N-1") > CALCULATE([DRM_DY Solde dettes], 'KPI'[Exercice] = "N-1")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde dettes], 'KPI'[Exercice] = "N-1")
			VAR PL =  [DRM_DY_frs solde achats TTC]
			
			
			RETURN
			
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Fournisseurs
		lineageTag: 2cf04d14-605d-4346-9e82-d4109b1256f2

		changedProperty = IsHidden

	measure 'DRM_DY Solde BFR' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[LiasseCode] in { "BL", "BM","BN","BO","BP","BQ","BR","BS","BT","BU","BV","BW","BX","BY","BZ","CA", "CB" ,"CH", "CL", "CM", "CN", "DW", "DX", "DY", "DZ", "EA", "EB", "ED" },
			    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: 26c54d6f-e47a-496f-b7fa-64bce0121162

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY BFR N' = ```
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            CALCULATE([DRM_DY_clients solde ventes TTC], 'KPI'[Exercice] = "N") > CALCULATE([DRM_DY Solde BFR], 'KPI'[Exercice] = "N")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde BFR], 'KPI'[Exercice] = "N")
			VAR PL =  CALCULATE([DRM_DY_clients solde ventes TTC], 'KPI'[Exercice] = "N")
			
			
			RETURN
			
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Clients et BFR
		lineageTag: c67477e3-0e70-4222-9435-e0c9ec5e44bb

		changedProperty = IsHidden

	measure 'DRM_DY BFR N-1' = ```
			VAR MAXI = [Nbr jour max N-1]
			VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1
			VAR MAXIFY = [Nbr jour max full year N-1]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ),
			            CALCULATE([DRM_DY_clients solde ventes TTC] , 'KPI'[Exercice] = "N-1")> CALCULATE([DRM_DY Solde BFR], 'KPI'[Exercice] = "N-1")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde BFR], 'KPI'[Exercice] = "N-1")
			VAR PL =  CALCULATE([DRM_DY_clients solde ventes TTC], 'KPI'[Exercice] = "N-1")
			
			
			RETURN
			
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Clients et BFR
		lineageTag: c2b11cc5-191e-4906-b7a8-9397a9c6ac66

		changedProperty = IsHidden

	measure DRM_DY_FRS_VAR = ROUND([DRM_DY_FRS_N] - [DRM_DY_FRS_N-1],0)
		formatString: 0
		displayFolder: DRM et DEM par apurement\Fournisseurs
		lineageTag: b0c5c8f5-e96d-4c86-9041-0e70f297a3bb

		changedProperty = IsHidden

	measure DRM_DY_CLIENTS_VAR = ROUND([DRM_DY_CLIENTS_N] - [DRM_DY_CLIENTS_N-1],0)
		formatString: 0
		displayFolder: DRM et DEM par apurement\Clients et BFR
		lineageTag: 372fecd0-d590-4e62-a719-2cbd47fb891d

		changedProperty = IsHidden

	measure '_Immo_P CEAC pour table' = -CALCULATE([_Gene_Solde GL],'KPI'[Exercice]="N",Compte[Racine3]=775 && Compte[Racine4] <> 7756)
		formatString: #,0
		lineageTag: 47719904-f6c7-4398-8bf6-12c61c5cb7fd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_PV Cession pour table' = -[_Immo_VNC P&L pour table]+[_Immo_P CEAC pour table]
		formatString: #,0
		lineageTag: e6b4d254-a070-4111-aef3-05863fb52274

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DRM_DY_stocks solde ventes HT' = ```
			
			 
			 -IF(
			        Isblank(CALCULATE( [Solde] , PlanCompteAEF[LiasseCode] in {"FC","FF","FI", "FM", "FN"}) )
			        ,BLANK(),
			
			        CALCULATE(CALCULATE( [Solde] , PlanCompteAEF[LiasseCode] in {"FC","FF","FI", "FM", "FN"}),
			        FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			) 
			```
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Stocks
		lineageTag: 2399b21f-a030-4a9e-9ae5-30e992abee0c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY Solde stocks PF' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[LiasseCode] IN { "BN", "BO", "BP", "BQ", "BR", "BS"},
			    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Stocks
		lineageTag: 84293bc5-0a17-4d19-bf55-064eba4aa762

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY Solde stocks MP' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    PlanCompteAEF[LiasseCode] IN { "BL", "BM", "BT", "BU"},
			    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))
		formatString: #,0
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Stocks
		lineageTag: 86281932-bb47-4bcf-87dc-deeabe121f1f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DRM_DY_stocks solde achats HT' = ```
			
			 
			IF(
			        Isblank(CALCULATE( [Solde] , PlanCompteAEF[LiasseCode] in {"FS","FU","FT","FV"}))
			        ,BLANK(),
			
			        CALCULATE (CALCULATE( [Solde] , PlanCompteAEF[LiasseCode] in {"FS","FU","FT","FV"}),
			    
			        FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			) 
			```
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Stocks
		lineageTag: 49e7fdee-2ee1-49e8-8c46-5e21756b0ebf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DRM_DY_STOCKS_PF_N = ```
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ), 
			            CALCULATE([DRM_DY_stocks solde ventes HT], 'KPI'[Exercice] = "N") > CALCULATE([DRM_DY Solde stocks PF], 'KPI'[Exercice] = "N")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde stocks PF], 'KPI'[Exercice] = "N")
			VAR PL =  CALCULATE([DRM_DY_stocks solde ventes HT], 'KPI'[Exercice] = "N")
			
			
			RETURN
			CALCULATE(
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0 , 
			  'KPI'[Exercice] = "N")
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: dbf5d878-777b-4081-9dbc-5f1dcbac246b

		changedProperty = IsHidden

	measure DRM_DY_STOCKS_PF_N-1 = ```
			VAR MAXI = [Nbr jour max N-1]
			VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1
			VAR MAXIFY = [Nbr jour max full year N-1]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ), 
			            CALCULATE([DRM_DY_stocks solde ventes HT], 'KPI'[Exercice] = "N-1") > CALCULATE([DRM_DY Solde stocks PF], 'KPI'[Exercice] = "N-1")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde stocks PF], 'KPI'[Exercice] = "N-1")
			VAR PL =  CALCULATE([DRM_DY_stocks solde ventes HT], 'KPI'[Exercice] = "N-1")
			
			
			RETURN
			CALCULATE(
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0 , 
			  'KPI'[Exercice] = "N-1")
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: 70b52879-5d2e-43a3-9a24-46bd89913de9

		changedProperty = IsHidden

	measure DRM_DY_STOCKS_MP_N = ```
			VAR MAXI = [Nbr jour max N]
			VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1
			VAR MAXIFY = [Nbr jour max full year N]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ), 
			            CALCULATE([DRM_DY_stocks solde achats HT], 'KPI'[Exercice] = "N") > CALCULATE([DRM_DY Solde stocks MP], 'KPI'[Exercice] = "N")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde stocks MP], 'KPI'[Exercice] = "N")
			VAR PL =  CALCULATE([DRM_DY_stocks solde achats HT], 'KPI'[Exercice] = "N")
			
			
			RETURN
			CALCULATE(
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0 , 
			  'KPI'[Exercice] = "N")
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: 6c9eccba-13e3-47c9-9533-25ae85eaf727

		changedProperty = IsHidden

	measure DRM_DY_STOCKS_MP_N-1 = ```
			VAR MAXI = [Nbr jour max N-1]
			VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1
			VAR MAXIFY = [Nbr jour max full year N-1]
			VAR a =
			    SUMMARIZE (
			        FILTER (
			            ALL ( 'DimTemps'[Day of year inv] ), 
			            CALCULATE([DRM_DY_stocks solde achats HT], 'KPI'[Exercice] = "N-1") > CALCULATE([DRM_DY Solde stocks MP], 'KPI'[Exercice] = "N-1")
			        ),
			        "minv", MIN ( 'DimTemps'[Day of year inv] )
			    ) /* , "inv",related(DimTemps[Day of year inv]))*/
			VAR b =
			    MINX ( a, [minv] ) + 0
			VAR DRMinv = MAXIFY - b + 1
			
			VAR bilan =  CALCULATE([DRM_DY Solde stocks MP], 'KPI'[Exercice] = "N-1")
			VAR PL =  CALCULATE([DRM_DY_stocks solde achats HT], 'KPI'[Exercice] = "N-1")
			
			
			RETURN
			CALCULATE(
			if ( bilan = 0 , 0,  
			  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )
			  )+0 , 
			  'KPI'[Exercice] = "N-1")
			```
		formatString: 0
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: 710144ed-2664-4c93-8219-7e1ed8e21b4e

		changedProperty = IsHidden

	measure 'DRM_DY STOCKS PF Label' = ```
			
			
			
			var DRMN = ROUND([DRM_DY_STOCKS_PF_N] ,0)
			var DRMN1=  ROUND([DRM_DY_STOCKS_PF_N-1],0)
			var variation = DRMN - DRMN1
			RETURN
			    " " & 
			    IF(DRMN > DRMN1, "▲ ", IF(DRMN = DRMN1, "⩥ ","▼ ")) & 
			    FORMAT(DRMN1, "0") &  
			    " (" & 
			    IF(DRMN > DRMN1, "+",IF(DRMN < DRMN1, "","")) & 
			    IF(DRMN =  DRMN1 , "stable)",FORMAT(variation , "0") & " jours)")
			```
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: dc8d2f4f-0794-4888-a127-e602ec7d34f7

		changedProperty = IsHidden

	measure DRM_DY_STOCKS_MP_VAR = ROUND([DRM_DY_STOCKS_MP_N] - [DRM_DY_STOCKS_MP_N-1],0)
		formatString: 0
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: ca5543e9-cd12-4bd1-9290-6ee395911281

		changedProperty = IsHidden

	measure DRM_DY_STOCKS_MP_LABEL =
			
			[DRM_DY STOCKS MP Label]
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: 0cbc38c1-9737-41e5-8f8b-fa3c6f1a397e

		changedProperty = IsHidden

	measure DRM_DY_STOCKS_PF_VAR = ROUND( [DRM_DY_STOCKS_PF_N] - [DRM_DY_STOCKS_PF_N-1],0)
		formatString: 0
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: 3a822635-d2b4-4775-85b6-dca9ddf2cac6

		changedProperty = IsHidden

	measure DRM_DY_STOCKS_PF_LABEL =
			
			[DRM_DY STOCKS PF Label]
		displayFolder: DRM et DEM par apurement\Stocks
		lineageTag: 62d9703d-2be8-4840-ad32-9c91b940053e

		changedProperty = IsHidden

	measure '_Personnel_Tx CS N' = calculate ( [_Personnel_Tx CS], 'KPI'[Exercice] = "N")
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 11. Personnel\Personnel_global
		lineageTag: a141d34d-37f8-4486-bab8-527b7e8f5a94

	measure '_Immo_fi_Depre BouclageBrut_num' = IF(ABS([_Immo_fi_Depre Bouclage Ecart pour table])<0.1,0,1)
		formatString: 0
		displayFolder: 02. Immobilisations
		lineageTag: 11c2f259-4b19-4392-9e04-80b180b7fb64

	measure Ecart_AN_ABS = ABS([Ecart_AN])
		displayFolder: 0. Mesures à classer
		lineageTag: 49c8082f-daa6-49aa-a343-8a4d19fa0d2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Ecart_solde_N_Let_vide_ABS = ABS([Ecart_solde_N_Let_vide])
		displayFolder: 0. Mesures à classer
		lineageTag: e064e392-1008-48d3-a4f3-31ecd54ad4af

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Solde_ABS = ABS([Solde])
		displayFolder: 01. Mesures globales\Solde et Variation
		lineageTag: ae04f784-6430-430d-ab0c-88a2aaa90bfd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_stocks solde achats HT N' = CALCULATE( [DRM_DY_stocks solde achats HT] , 'KPI'[Exercice]  = "N")
		formatString: #,0
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Stocks
		lineageTag: 4c408659-fb0d-47e3-8dfa-69ce3e3cc2e4

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DRM_DY_stocks solde achats HT N-1' = CALCULATE( [DRM_DY_stocks solde achats HT] , 'KPI'[Exercice]  = "N-1")
		formatString: #,0
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Stocks
		lineageTag: 7bc2b6ef-e782-40d5-857d-0596859f7d52

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DRM_DY_frs solde achats TTC N' = CALCULATE( [DRM_DY_frs solde achats TTC] , 'KPI'[Exercice]  = "N")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: 7bd84d50-4057-4b9f-b144-2fdbe8ae0d2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_frs solde achats TTC N-1' = CALCULATE( [DRM_DY_frs solde achats TTC] , 'KPI'[Exercice]  = "N-1")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: 20e54528-a869-42ca-9374-75b100e58160

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_clients solde ventes TTC N' = CALCULATE( [DRM_DY_clients solde ventes TTC] , 'KPI'[Exercice]  = "N")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: 1cd70e21-8159-4f39-aad0-b20013049172

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_clients solde ventes TTC N-1' = CALCULATE( [DRM_DY_clients solde ventes TTC] , 'KPI'[Exercice]  = "N-1")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: 7aee542b-e7c3-4010-adff-cbb352f30511

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_stocks solde ventes HT N-1' = CALCULATE( [DRM_DY_stocks solde ventes HT] , 'KPI'[Exercice]  = "N-1")
		formatString: #,0
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Stocks
		lineageTag: 5f9f60f1-90d9-4620-a08f-a3b4fd46aab8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DRM_DY_stocks solde ventes HT N' = CALCULATE( [DRM_DY_stocks solde ventes HT] , 'KPI'[Exercice]  = "N")
		formatString: #,0
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Stocks
		lineageTag: 9f83d85a-067b-41ff-a0e2-c2e1e3e65e9e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_fi_Depre Bilan HorsAN' =
			
			CALCULATE(
			        [_Gene_Solde N inv],
			        'PlanCompteAEF'[DetailNiv3] = "Dép. immobilisations financières",
			        ParamAN[A/N - Bridge]=""
			)
		formatString: #,0
		lineageTag: 22abff9d-f5c6-4a4f-bf95-40be42279713

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _Immo_fi_P&L = [_Immo_fi_Dot P&L pour table] + [_Immo_fi_Rep P&L pour table]
		lineageTag: ee14ed4c-26d6-41e0-99cc-225e503e6b3b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Immo_fi_Depre Bouclage Ecart' = [_Immo_fi_Depre Bilan HorsAN]-[_Immo_fi_Dot P&L]-[_Immo_fi_Rep P&L]
		formatString: #,0
		lineageTag: b86592c1-73b2-4bf8-afed-438632f60183

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_fi_Dot P&L' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    'KPI'[Exercice]="N" ,Compte[Racine5]=68662
			)
		formatString: #,0
		lineageTag: 4aa9ed61-5dc9-43ad-890b-ba8f1f392cd5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Immo_fi_Rep P&L' =
			
			CALCULATE (
			    [_Gene_Solde GL],
			    'KPI'[Exercice]="N" ,Compte[Racine5]=78662
			)
		formatString: #,0
		lineageTag: a7c5dcfc-d859-449a-8d88-378f4573a203

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DRM_DY_frs solde achats HT' = ```
			
			 
			 -IF(
			        Isblank(CALCULATE( -[Solde] , PlanCompteAEF[LiasseCode] in {"FS","FU","FW"})),BLANK(),
			
			        CALCULATE (CALCULATE( -[Solde] , PlanCompteAEF[LiasseCode] in {"FS","FU","FW"}),
			    
			        FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			) 
			```
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: 5c480bed-34a7-4a9f-928c-7f1589ff3408

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_frs solde achats HT N' = CALCULATE( [DRM_DY_frs solde achats HT] , 'KPI'[Exercice]  = "N")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: c75c7e70-f2eb-4e30-a6c3-9c3dfbf5e989

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_frs solde achats HT N-1' = CALCULATE( [DRM_DY_frs solde achats HT] , 'KPI'[Exercice]  = "N-1")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: 97163598-3b83-4200-acfc-91bcfb3fe8a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_clients solde ventes HT' = ```
			
			 
			 -IF(
			        Isblank(CALCULATE( [Solde] , PlanCompteAEF[LiasseCode] in {"FC","FF","FI"}) )
			        ,BLANK(),
			
			        CALCULATE(CALCULATE( [Solde] , PlanCompteAEF[LiasseCode] in {"FC","FF","FI"}) ,
			        FILTER (
			        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),
			        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])
			        ))
			) 
			```
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: 13381d90-6c82-4443-85fc-da05e72b6318

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_clients solde ventes HT N' = CALCULATE( [DRM_DY_clients solde ventes HT] , 'KPI'[Exercice]  = "N")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: 8089982b-90b8-491d-921c-03ce3f9d4072

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_clients solde ventes HT N-1' = CALCULATE( [DRM_DY_clients solde ventes HT] , 'KPI'[Exercice]  = "N-1")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: 4f3acac2-6fd3-43f0-903c-0109e3939c1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_clients solde TVA Collectée' =
			
			
			CALCULATE([Solde],CONTAINSSTRING('KPI' [SchemaEcriture], "|70|"), Compte[Racine4]=4457 || Compte[Racine5] = 44587)
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: adb46b24-c005-49be-9eb8-188145e03b74

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_clients solde TVA Collectée N' =
			
			
			CALCULATE( [DRM_DY_clients solde TVA Collectée] , 'KPI'[Exercice] = "N")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: 0813100c-0b35-4a35-8359-fdc9ccd40d44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_clients solde TVA Collectée N-1' =
			
			
			CALCULATE( [DRM_DY_clients solde TVA Collectée] , 'KPI'[Exercice] = "N-1")
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Clients et BFR
		lineageTag: 8239829a-8c06-497f-b3f8-d049ccd4788e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_frs solde TVA déductible' = ```
			
			 
			CALCULATE(-[Solde],((CONTAINSSTRING('KPI'[SchemaEcriture], "|60") && NOT (CONTAINSSTRING('KPI'[SchemaEcriture], "|603|")) ) || CONTAINSSTRING('KPI'[SchemaEcriture], "|61")|| CONTAINSSTRING('KPI'[SchemaEcriture], "|62")),Compte[Racine4]=4456 && Compte[Racine5]<> 44562 || Compte[Racine5] = 44586)
			```
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: 4504c9d8-c300-47d4-9a25-08d167d2e40f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_frs solde TVA déductible N' = ```
			
			 CALCULATE( [DRM_DY_frs solde TVA déductible] , 'KPI'[Exercice] = "N")
			```
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: f4823ceb-cf21-478e-8b3f-2815f63b5fd5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_frs solde TVA déductible N-1' = ```
			
			 CALCULATE( [DRM_DY_frs solde TVA déductible] , 'KPI'[Exercice] = "N-1")
			```
		displayFolder: DRM et DEM - Agrégats Bilan et P&L\Fournisseurs
		lineageTag: c5400b48-93ba-48bb-b55a-6ab1b4d39bc1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Gene_Solde Inversé carte N' = CALCULATE( [_Gene_Solde inv]+0, 'KPI'[Exercice] = "N")
		formatString: #,0
		lineageTag: 781bc336-f4df-4d14-8fbe-ea2826ac47a5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Solde encaissements compensés' = ```
			
			 CALCULATE([_Gene_Solde N carte] ,Compte[CAsh detailed 1] = "CASH" ,FILTER( ALLSELECTED(SE[CAsh CAT1 V2]), SE[CAsh CAT1 V2] in {  "CA niv2 - cash partiel", "EFFETS niv2 - cash partiel"}))
			 +
			 CALCULATE( -[_Gene_Solde N carte] , FILTER( ALLSELECTED(Compte) , Compte[CAsh detailed 1] = "CREANCES"), FILTER( ALLSELECTED(SE[CAsh CAT1 V2]), SE[CAsh CAT1 V2] in { "CREANCES niv2 - cash partiel" }))
			```
		formatString: #,0
		lineageTag: d95343b5-9418-4f20-b620-4d8edc69c9b6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Solde encaissements' = CALCULATE( [_Gene_Solde N carte] , FILTER( ALLSELECTED(Compte) , Compte[CAsh detailed 1] = "CASH"), FILTER( ALLSELECTED(SE), SE[CAsh CAT1 V2] in { "CREANCES niv2 - cash total" , "CA niv2 - cash total","EFFETS niv2 - cash total"}))
		formatString: #,0
		lineageTag: 04e58fd5-b372-4b94-af81-fe61dfcd420b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Solde encaissements compensés part cash' =
			
			VAR NN = CALCULATE([Solde encaissements compensés], Compte[CAsh detailed 1] = "CASH")+ CALCULATE( [_Gene_Solde N carte] , FILTER( ALLSELECTED(Compte) , Compte[CAsh detailed 1] = "CASH"), FILTER( ALLSELECTED(SE[CAsh CAT1 V2]), SE[CAsh CAT1 V2] in { "CREANCES niv2 - cash partiel" }))
			RETURN
			"dont : "& FORMAT(NN , "# ### ###") & " de cash"
		lineageTag: a7573e7f-d08f-4df8-bbe7-b0b8e9c5041c

	measure 'DRM_DY_stocks MP mesure pour filtre' = [DRM_DY Solde stocks MP] + [DRM_DY_stocks solde achats HT]
		lineageTag: d9df762a-3c68-43cb-9441-3a55a115a319

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_stocks PF mesure pour filtre' = [DRM_DY Solde stocks PF] + [DRM_DY_stocks solde ventes HT]
		lineageTag: f0eca9d3-3e94-4279-908e-8871ab210f49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_clients mesure pour filtre' = [DRM_DY Solde créances] + [DRM_DY_clients solde ventes TTC]
		lineageTag: e371a4d3-dd07-49fd-aaaf-1894f34d61c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DRM_DY_frs mesure pour filtre' = [DRM_DY Solde dettes] + [DRM_DY_frs solde achats TTC]
		lineageTag: ae12a824-808a-4108-8a7a-09a0a61888b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Gene_Solde N AN CARTE' = ROUND(CALCULATE([_Gene_Solde N],ParamAN[AN - O/N] = "Oui"),2) +0
		formatString: #,0
		lineageTag: 2a358690-6287-4d50-b64a-a28d5052584a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Solde N hors AN' = ROUND(CALCULATE([_Gene_Solde N],ParamAN[AN - O/N] = "Non"),2)
		formatString: #,0
		lineageTag: c20af2cb-d0f7-4c86-bb5d-2375cb6d3884

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Solde N hors AN ABS' = ABS([_Gene_Solde N hors AN])
		formatString: #,0
		lineageTag: 2759e4be-f470-440e-a180-15e32d28062e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_Gene_Solde N hors AN inv' = - [_Gene_Solde N hors AN]
		formatString: #,0
		lineageTag: 6313633d-45cb-4e57-b581-a842fe1c3f23

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_CP_Var145 pour table' = ```
			CALCULATE (
			    SUM ( 'KPI'[MTDebit] ) - SUM ( 'KPI'[MTCredit] ),
			    LEFT('KPI'[Compte],3) = "145",
			    'KPI'[Exercice] = "N", 
			    ParamAN[AN] = 2
			)
			```
		formatString: #,0
		lineageTag: b90bc8f4-7088-4b11-948c-0c261bb3edfb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_CP_68725N pour table' = ```
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine5] = 68725,
			    'KPI'[Exercice] = "N"
			) 
			```
		formatString: #,0
		lineageTag: fbf3d811-58ed-48ab-99e2-90cc95842001

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_CP_78725N pour table' = ```
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine5] = 78725,
			    'KPI'[Exercice] = "N"
			) 
			```
		formatString: #,0
		lineageTag: 96703960-c81d-4f3d-83cd-f8e3721bc6e2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _CP_139N = ```
			CALCULATE (
			    SUM ( 'KPI'[MTDebit] ) - SUM ( 'KPI'[MTCredit] ),
			    LEFT('KPI'[Compte],3) = "139",
			    'KPI'[Exercice] = "N", 
			    ParamAN[AN] = 2
			) + 0
			```
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: c488a1e8-baaa-430e-8425-88b1de231d8f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _CP_777N =
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine3] = 777,
			    'KPI'[Exercice] = "N"
			) + 0
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: c3ab9093-eae9-483c-b5b4-7da280295943

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _CP_Bouclage_sub_ecart = [_CP_139N] + [_CP_777N]
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: 7359ae22-bca1-47da-97ee-e15d8f6912c1

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_CP_139N pour table' = ```
			CALCULATE (
			    SUM ( 'KPI'[MTDebit] ) - SUM ( 'KPI'[MTCredit] ),
			    LEFT('KPI'[Compte],3) = "139",
			    'KPI'[Exercice] = "N", 
			    ParamAN[AN] = 2
			)
			```
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: a13927bf-75c8-403e-80a9-f0460623b783

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_CP_777N pour table' =
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine3] = 777,
			    'KPI'[Exercice] = "N"
			)
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: 5d088d73-de78-4b53-889b-c32916f70849

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '_CP_Bouclage_sub_ecart pour table' = [_CP_139N pour table] + [_CP_777N pour table]
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: c51fdba3-e834-431d-bea1-b4b01735ac0a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _CP_68725N =
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine5] = 68725,
			    'KPI'[Exercice] = "N"
			) + 0
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: a06a9621-cdb0-49f9-aba0-c9b645e3e1e7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _CP_78725N =
			CALCULATE (
			    [_Gene_Solde GL],
			    Compte[Racine5] = 78725,
			    'KPI'[Exercice] = "N"
			) + 0
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: bbdb77da-6a1b-4859-909f-4b623a56b4ac

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _CP_Bouclage_Ecart = [_CP_Var145] + [_CP_68725N] + [_CP_78725N] + 1 * 0
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: 4487ebcf-4178-4f73-8f03-b0b266ad5a18

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _CP_Var145 = ```
			CALCULATE (
			    SUM ( 'KPI'[MTDebit] ) - SUM ( 'KPI'[MTCredit] ),
			    LEFT('KPI'[Compte],3) = "145",
			    'KPI'[Exercice] = "N", 
			    ParamAN[AN] = 2
			) + 0
			```
		formatString: #,0
		displayFolder: 05. Capitaux propres
		lineageTag: 649ac0d7-fc31-4360-b961-f026ea410985

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Measure 3'
		displayFolder: 05. Capitaux propres
		lineageTag: 689a4627-f032-4786-a41c-aa736ba044f0

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure '_CP_Bouclage_Ecart pour table' = [_CP_Var145 pour table] + [_CP_68725N pour table] + [_CP_78725N pour table]
		formatString: #,0
		lineageTag: d0e2ffe5-9ddf-49f9-b34b-fd16f46d3d84

		annotation PBI_FormatHint = {"isDecimal":true}

	column Compte
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: b7377066-2c26-45c8-967d-652cc29f0c96
		summarizeBy: none
		sourceColumn: Compte

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CompteLibelle
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: f911504c-5cd3-463c-9c3d-abf0a909eba3
		summarizeBy: none
		sourceColumn: CompteLibelle

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DateComptable
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 8fc2f313-3f0b-4d6a-8549-33e200b862d4
		summarizeBy: none
		sourceColumn: DateComptable

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CodeJournal
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 1f5b28ec-c159-4211-ad0a-9e47aa8c49e1
		summarizeBy: none
		sourceColumn: CodeJournal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EcritureNumero
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: c3a9e059-9e9d-4e7b-a374-452204354f42
		summarizeBy: none
		sourceColumn: EcritureNumero

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EcritureLibelle
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: e17440fe-4e4d-43b3-984d-57d29ea660a2
		summarizeBy: none
		sourceColumn: EcritureLibelle

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AccountNumber
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(max)
		lineageTag: 79579ef0-093c-402a-9c9d-cf107793ecd4
		summarizeBy: none
		sourceColumn: AccountNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Exercice
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 40a3979a-45b1-4344-b615-e07b06d58c3f
		summarizeBy: none
		sourceColumn: Exercice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DC
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 89eec861-d3f0-4966-97e2-a581dc0b9099
		summarizeBy: none
		sourceColumn: DC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AN
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b4a33866-a1dc-494c-88f5-bf131ec14362
		summarizeBy: none
		sourceColumn: AN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ContactMail
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 45fdd653-152a-47c0-aa99-1f64b6f7df32
		summarizeBy: none
		sourceColumn: ContactMail

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CodeEtbt
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: b201d776-d081-402e-9b04-f78ad8829d48
		summarizeBy: none
		sourceColumn: CodeEtbt

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CompAuxLib
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: b934f38c-e61c-4699-a9e2-c18d53c2cdfd
		summarizeBy: none
		sourceColumn: CompAuxLib

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EcritureLet
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 0016b6f2-4cd5-4ae8-84dd-5eb79a3ca558
		summarizeBy: none
		sourceColumn: EcritureLet

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CompteName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 4bd0fc38-a2c3-4304-ab9c-73909d1eeb04
		summarizeBy: none
		sourceColumn: CompteName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CléPCG
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 00b2b099-ce09-446b-92c9-03dfeb9d3f89
		summarizeBy: none
		sourceColumn: CléPCG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CompteSignificatifs
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 85db4694-382a-4410-a6a0-44e5a42e5154
		summarizeBy: none
		sourceColumn: CompteSignificatifs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MTDebit
		dataType: double
		formatString: #,0
		sourceProviderType: decimal
		lineageTag: e54b8870-8d1b-4713-a804-98fb7898e89b
		summarizeBy: sum
		sourceColumn: MTDebit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column MTCredit
		dataType: double
		formatString: #,0
		sourceProviderType: decimal
		lineageTag: 49607cb9-092e-4c77-939c-4bd16521ba69
		summarizeBy: sum
		sourceColumn: MTCredit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Compte6
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b8c1233c-1f6c-4ba9-9fab-2358fe459bb3
		summarizeBy: none
		sourceColumn: Compte6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CléDate
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ec1c6874-a3f5-4bb5-ac37-007c2e025d11
		summarizeBy: none
		sourceColumn: CléDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PKey_KPI
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 585530fb-01b7-4f6f-9bcf-5bb68fb7c6ad
		summarizeBy: sum
		sourceColumn: PKey_KPI

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DCCompte
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: b04e25bc-3b6b-4563-b1dd-a6d33b2771c6
		summarizeBy: none
		sourceColumn: DCCompte

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Utilisateur
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: f4f7ec6e-a046-4b12-876c-4f0b9d47fd5a
		summarizeBy: none
		sourceColumn: Utilisateur

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SoldeFirstDigit
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b5f8d314-c182-4f3b-8cbd-4a60061f27a3
		summarizeBy: sum
		sourceColumn: SoldeFirstDigit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EcritureCache
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 1e4f5821-b6e0-426a-b49f-478f973a6a06
		summarizeBy: sum
		sourceColumn: EcritureCache

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Transfert
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 4ad244bd-71fa-4d5f-b86e-5a414f360fb0
		summarizeBy: sum
		sourceColumn: Transfert

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SchemaEcriture
		dataType: string
		lineageTag: fc068c9b-4c54-4778-b87f-db1cb34931e6
		summarizeBy: none
		sourceColumn: SchemaEcriture

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CAT1 = ```
			SWITCH( TRUE(), 
			CONTAINSSTRING('KPI'[SchemaEcriture] , ",70,"), "70",  
			CONTAINSSTRING('KPI'[SchemaEcriture] , ",411,") || CONTAINSSTRING('KPI'[SchemaEcriture] , ",410,") , "411/410",  
			CONTAINSSTRING('KPI'[SchemaEcriture] , ",418,"), "418",  
			CONTAINSSTRING('KPI'[SchemaEcriture] , ",4198,"), "4198",  
			CONTAINSSTRING('KPI'[SchemaEcriture] , ",487,"), "487",
			  CONTAINSSTRING('KPI'[SchemaEcriture] , ",44587,"), "44587", "Autres")
			```
		lineageTag: 25f76d6e-909c-4bc2-baf1-38d5118828d0
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: 6cb96d26-a0e1-416e-846f-341bee53d684
		summarizeBy: count
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	partition KPI-ec318b5f-1573-452d-a769-b29395bd3eab = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("datayoyo.fr:19128", "Cacbi", [HierarchicalNavigation=true]),
				    public = Source{[Schema="public"]}[Data],
				    KPI1 = public{[Name="KPI"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(KPI1, each [ClientID] = ClientID)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

