{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.927.0 (24.02)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Accounts\",\"Choix du test\",\"Choix du test 1\",\"Choix du test_frs\",\"Compte\",\"DimTemps\",\"FieldParam_measures\",\"FieldParam_measures achats\",\"FieldParam_measures immos\",\"FieldParam_measures_fluxcumul\",\"FieldParam_measures_fluxcumul inv\",\"FieldParam_table\",\"FieldParam2\",\"Formes juridiques\",\"KPI\",\"MappingPCG\",\"Mesures\",\"ParamAN\",\"ParamDC\",\"Parametrage\",\"PlanCompteAEF\",\"SliderT1\",\"SliderT2\",\"SliderT3\",\"SliderT4\",\"SliderT5\",\"SliderT6\",\"SliderT7\",\"SliderT8\",\"SliderT9\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "72c35e38-b474-40ee-9203-7e6723578d09",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Compte6",
        "fromTable": "KPI",
        "toColumn": "Racine6",
        "toTable": "Compte"
      },
      {
        "name": "b72db5dd-b804-4196-b72f-a1324d73859a",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "CléDate",
        "fromTable": "KPI",
        "toColumn": "Clé",
        "toTable": "DimTemps"
      },
      {
        "name": "c85ca719-219c-4129-a153-0cb231aa3df1",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "CléPCG",
        "fromTable": "KPI",
        "toColumn": "Clé",
        "toTable": "MappingPCG"
      },
      {
        "name": "f55a096f-d0f6-4814-8351-ff0a46640c88",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "AN",
        "fromTable": "KPI",
        "toColumn": "AN",
        "toTable": "ParamAN"
      },
      {
        "name": "62a755ea-083f-451a-a1fb-b0634c03bb8b",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "DC",
        "fromTable": "KPI",
        "toColumn": "D/C",
        "toTable": "ParamDC"
      },
      {
        "name": "4d000095-b48f-4dac-9d5e-b138356f52da",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "AccountNumber",
        "fromTable": "KPI",
        "toColumn": "AccountNumber",
        "toTable": "Parametrage"
      },
      {
        "name": "e71c4ee7-76f9-4498-8a7a-5d6515fbdeab",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Code",
        "fromTable": "MappingPCG",
        "toColumn": "LiasseCode",
        "toTable": "PlanCompteAEF"
      },
      {
        "name": "46dc147a-4932-4aae-a8be-3939bd3de140",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "AccountNumber",
        "fromTable": "Parametrage",
        "toColumn": "AccountNumber",
        "toTable": "Accounts"
      }
    ],
    "sourceQueryCulture": "fr-FR",
    "tables": [
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "255416b680764cc48efa52eb38faa937"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "ea971fe8-fd2a-400e-96d9-ccef2546b0af",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "2081cfda-80df-4d8e-97da-770ebcdecba1",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "1f72bdf6-0b1c-4519-a4b1-97dba7384bc6",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "66bd74e9-a202-40c6-9e93-4bd19c959fe4",
        "partitions": [
          {
            "name": "Parameter-9c41ea99-8849-4ad2-89b1-f414a816efbb",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"MonthName\", NAMEOF('DimTemps'[MonthName]), 0),",
                "    (\"QuarterName\", NAMEOF('DimTemps'[QuarterName]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Accounts",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AccountLegalName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d27d1e9d-86ac-44a2-8cf3-2010235c1cbb",
            "sourceColumn": "AccountLegalName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "AccountNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "4f4c819d-db7f-4c04-bec2-ed7265db6a20",
            "sourceColumn": "AccountNumber",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f82725e8-8889-45e8-b87c-20233e2950f3",
        "partitions": [
          {
            "name": "Accounts-1fdcd369-1ec7-4aef-80ba-02ac887b064c",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    Accounts1 = public{[Name=\"Accounts\"]}[Data]",
                "in",
                "    Accounts1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Choix du test",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "d60a6761-b7cf-4d27-8ab8-11f49f93a579",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "KeyDC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c223e1ee-fc1a-42a5-8ebe-1b5a728ab6f5",
            "sourceColumn": "KeyDC",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "304a33d0-17f4-4e34-b528-108612a794a3",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0c7db5f6-671c-4c49-978d-b985e6b8ee61",
        "partitions": [
          {
            "name": "Choix du test-2d01df75-bcbc-459e-b429-618a1f2d9773",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    #\"Choix du test1\" = public{[Name=\"Choix du test\"]}[Data]",
                "in",
                "    #\"Choix du test1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Choix du test 1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "8f2d68e0-9e56-45fc-a347-9bab098da279",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50778b4c-4d4d-42e9-a80e-1bbf36f416ce",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4e0e2849-0431-4d34-8f46-6802745e4826",
        "partitions": [
          {
            "name": "Choix du test 1-12b6f02f-cd6e-4eab-8b83-5724d8d19f54",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    #\"Choix du test 2\" = public{[Name=\"Choix du test 1\"]}[Data]",
                "in",
                "    #\"Choix du test 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Choix du test_frs",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e276c9bd-ff53-4f4d-b746-b395bea4e138",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52799066-48c0-4850-a787-a3eb2201ac8c",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55a6637e-271e-4403-8921-64d5c7518543",
        "partitions": [
          {
            "name": "Choix du test_frs-45dba5a2-93b9-4626-89cd-ccebb272d307",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    #\"Choix du test_frs1\" = public{[Name=\"Choix du test_frs\"]}[Data]",
                "in",
                "    #\"Choix du test_frs1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Compte",
        "columns": [
          {
            "name": "Racine1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9eee59a0-a199-46f2-8f9d-f420d06d376b",
            "sourceColumn": "Racine1",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Racine2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce03bb69-b887-4af2-b1ec-d89ed399b64d",
            "sourceColumn": "Racine2",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Racine3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a507823-5833-4328-98ae-132ca5965015",
            "sourceColumn": "Racine3",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Racine4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f1225173-bcda-4e05-8eae-cd5f3bdfc5c0",
            "sourceColumn": "Racine4",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Racine5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3fc712c8-a589-431e-9ad6-d32fe9cbb895",
            "sourceColumn": "Racine5",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Racine6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "a0e43692-28bd-4793-9e2f-a8059f8bac36",
            "sourceColumn": "Racine6",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Racine3Libelle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0e5cbc7-b3bd-4879-b37c-670a2de251af",
            "sourceColumn": "Racine3Libelle",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          },
          {
            "name": "SapChargeSociales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f34924bc-30b3-4529-be04-22a1de4f41c4",
            "sourceColumn": "SapChargeSociales",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          },
          {
            "name": "SapDrmClients",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5fbd86f-c6ed-400c-872f-d5ac7175fc1e",
            "sourceColumn": "SapDrmClients",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          },
          {
            "name": "SapDrmDotAmor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b06910d-fd49-4172-95a4-f8372890cf2b",
            "sourceColumn": "SapDrmDotAmor",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          },
          {
            "name": "SapDrmFournisseurs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de418cbf-d858-4030-a02b-5d5e17df9b32",
            "sourceColumn": "SapDrmFournisseurs",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          },
          {
            "name": "SAPStocksVB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e56c17d3-c5e4-42ba-b955-a7089cc206fd",
            "sourceColumn": "SAPStocksVB",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c74fff70-14aa-45d6-ba8b-60f5123f4783",
        "partitions": [
          {
            "name": "Compte-335a9030-4395-4180-91be-5f13af8e97ec",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    Compte1 = public{[Name=\"Compte\"]}[Data]",
                "in",
                "    Compte1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimTemps",
        "columns": [
          {
            "name": "Dates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d1ca6c55-6017-4a5a-ad97-107156daf0cd",
            "sourceColumn": "Dates",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "Clé",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e8b93e3f-0d00-48dc-aaf6-6de7a339af1b",
            "sourceColumn": "Clé",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Day of year inv",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f86e138-f8b7-486e-b154-62059576098a",
            "sourceColumn": "Day of year inv",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Day of year inv calendar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "13846e0c-c63e-46b1-acac-58279a749aed",
            "sourceColumn": "Day of year inv calendar",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "DayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01243412-907a-49f6-bd74-8037adc6040e",
            "sourceColumn": "DayName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c033d72d-c77a-480b-b83b-949defbf9a46",
            "sourceColumn": "DayOfMonth",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f338f5f-36ac-43c2-b909-bc1d46ace2c7",
            "sourceColumn": "DayOfWeek",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4bb78cd4-667b-497a-98fb-86e94a22c01c",
            "sourceColumn": "DayOfYear",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfYear Calendar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e21cf2e-9115-484f-8d58-52e7d23e12b1",
            "sourceColumn": "DayOfYear Calendar",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "DaySuffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a569bb70-60aa-4eba-81d0-9f85731850cd",
            "sourceColumn": "DaySuffix",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "FirstDayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb105205-6848-4e0e-8a7d-6ac4d1760768",
            "sourceColumn": "FirstDayOfMonth",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "FirstFiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80e66263-7ef2-409f-b6b4-b5e8aa913f51",
            "sourceColumn": "FirstFiscalMonth",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalFirstDayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db0af3d3-3549-467e-9142-31c3acbc0519",
            "sourceColumn": "FiscalFirstDayOfMonth",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalLastDayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d44f9494-81cf-4e0d-88eb-b168b4bbb3a8",
            "sourceColumn": "FiscalLastDayOfMonth",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc081916-2feb-4961-9f5e-f8a1d1a323eb",
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalMonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ede5c35f-eb9f-4027-8d74-b95146cdf487",
            "sourceColumn": "FiscalMonthYear",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalPeriodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ca11e82-f82e-4a64-ae60-66f19dfa879b",
            "sourceColumn": "FiscalPeriodeID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c4204830-3b15-49c2-8594-35d3008f3d74",
            "sourceColumn": "FiscalQuarter",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalQuarterName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ee236b3-7104-478f-b181-d1063f992b2a",
            "sourceColumn": "FiscalQuarterName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3d9b6ff-02f2-497e-903c-24df5358fc13",
            "sourceColumn": "FiscalYear",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01ed732a-5580-443a-8244-5ec722764907",
            "sourceColumn": "FiscalYearName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "HolidayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4689baa-ebd8-46ef-959a-f04ce7dcf01b",
            "sourceColumn": "HolidayName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "IsWeekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79146f3e-f5f7-4fb5-8cfe-5cecdc9452d1",
            "sourceColumn": "IsWeekday",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "IsWorkingDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eaceb8e5-9d8c-4245-b94c-6c1199d1329e",
            "sourceColumn": "IsWorkingDay",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9da1362-e395-41dd-a765-f8022344a48a",
            "sourceColumn": "Month",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebaaeaf0-916b-405a-96a9-860690aa5302",
            "sourceColumn": "MonthName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "MonthOfQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3dafc999-e197-437d-9b0c-d32190d101a7",
            "sourceColumn": "MonthOfQuarter",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "MonthShortName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a163cedd-4d53-4c8d-a743-3a1e0af1d460",
            "sourceColumn": "MonthShortName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5aa2e6af-9c09-4ab3-bb15-f7111c43c1f2",
            "sourceColumn": "MonthYear",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac1eed50-903f-4076-bf3b-03c515d34c56",
            "sourceColumn": "PeriodeID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "105d3797-cd80-4ef7-8862-fe5548c7cc8e",
            "sourceColumn": "Quarter",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "764dbec4-507e-4a81-81d7-d0614001478c",
            "sourceColumn": "QuarterName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "WeekOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8aca9f08-83c5-40d4-9f5b-63f2abe15e5f",
            "sourceColumn": "WeekOfMonth",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "WeekOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f91a080-520d-40da-a260-c5a7513d2b1c",
            "sourceColumn": "WeekOfYear",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d488c759-6113-4095-8779-4eca8ca06aa3",
            "sourceColumn": "Year",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "YearName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "777ac285-a1ad-4b54-99e4-a13fa0a037c4",
            "sourceColumn": "YearName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a0321ef1-7121-4b3a-a222-3cafafe477c1",
        "partitions": [
          {
            "name": "DimTemps-d0f547d1-4dae-454e-bb4f-1b0d2eda62b1",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    DimTemps1 = public{[Name=\"DimTemps\"]}[Data]",
                "in",
                "    DimTemps1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FieldParam_measures",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "8392e833-c5db-4c66-97ea-1b5902cba800",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "KeyDC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40898642-30f5-4136-8779-89f39d596ca3",
            "sourceColumn": "KeyDC",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04a63b87-8a1f-4f75-8a4e-ae393721f5f8",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "627a6cde-dfad-4401-a680-bdf2e6125619",
        "partitions": [
          {
            "name": "FieldParam_measures-fb84cd1d-85e8-4949-b458-6562fdb36dbd",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    FieldParam_measures1 = public{[Name=\"FieldParam_measures\"]}[Data]",
                "in",
                "    FieldParam_measures1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FieldParam_measures achats",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "f97a2512-e0b3-4608-8edd-294398e2b6a8",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "KeyDC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f250a268-5fc1-484c-ac86-d6093af2d9b4",
            "sourceColumn": "KeyDC",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f1ed717-6914-41c1-ada9-ec322fc8ad5a",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "43caa6f3-efc2-4183-a01c-b537120d7288",
        "partitions": [
          {
            "name": "FieldParam_measures achats-aa68acbb-f95f-455a-b7a7-c06c03ece72f",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    #\"FieldParam_measures achats1\" = public{[Name=\"FieldParam_measures achats\"]}[Data]",
                "in",
                "    #\"FieldParam_measures achats1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FieldParam_measures immos",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "1df87a11-a82a-4b97-9cd0-7b5edf793b5f",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "KeyDC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f55345da-85a9-4bcd-8809-9e45effbd281",
            "sourceColumn": "KeyDC",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e0a674c-a559-4baf-a239-aaa295e649d1",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fc083397-431e-4adb-8aa3-6520d101b6bd",
        "partitions": [
          {
            "name": "FieldParam_measures immos-9f5eeeaf-019f-4644-ae6f-019e817326d1",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    #\"FieldParam_measures immos1\" = public{[Name=\"FieldParam_measures immos\"]}[Data]",
                "in",
                "    #\"FieldParam_measures immos1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FieldParam_measures_fluxcumul",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "6bb6cdbe-afd3-4986-ae67-feb48c38bd12",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "KeyDC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d98735b0-9733-4093-937b-a5ab79aa8a5d",
            "sourceColumn": "KeyDC",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f302a7d-1fe1-488c-8775-61be26c5d95f",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "840597e7-7cce-4c7f-873a-b6ac6b85687e",
        "partitions": [
          {
            "name": "FieldParam_measures_fluxcumul-30a77909-ed4c-4f3d-bf0d-2dbce11b0053",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    FieldParam_measures_fluxcumul1 = public{[Name=\"FieldParam_measures_fluxcumul\"]}[Data]",
                "in",
                "    FieldParam_measures_fluxcumul1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FieldParam_measures_fluxcumul inv",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0ad14f62-9770-48f3-bb60-b813e332c0c3",
            "sourceColumn": "Code",
            "sourceProviderType": "decimal",
            "summarizeBy": "count"
          },
          {
            "name": "KeyDC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "316b82bc-be54-4c47-8d11-6c260689d10e",
            "sourceColumn": "KeyDC",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85cfcf14-2d9d-400f-a260-61e0d24a33f4",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fcf72fd5-b8ab-45a7-8a61-81fa12ccd59e",
        "partitions": [
          {
            "name": "FieldParam_measures_fluxcumul inv-4d3e9d62-7acb-4d13-9d01-159c82fd40e4",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    #\"FieldParam_measures_fluxcumul inv1\" = public{[Name=\"FieldParam_measures_fluxcumul inv\"]}[Data]",
                "in",
                "    #\"FieldParam_measures_fluxcumul inv1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FieldParam_table",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0f25096d-3f79-480c-a5fe-5111701553f1",
            "sourceColumn": "Code",
            "sourceProviderType": "decimal",
            "summarizeBy": "count"
          },
          {
            "name": "KeyDC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6e90809-70a2-464a-bf2d-10389c766060",
            "sourceColumn": "KeyDC",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70673ca2-45fd-4afd-b155-ac4ce97ecf20",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4cdb6126-0f76-434c-a355-8c45022d2291",
        "partitions": [
          {
            "name": "FieldParam_table-8ef581cd-982a-4f0b-83e8-c5affc766eb4",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    FieldParam_table1 = public{[Name=\"FieldParam_table\"]}[Data]",
                "in",
                "    FieldParam_table1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FieldParam2",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "de234df0-8d2a-4ef9-aed8-b7f7c051661e",
            "sourceColumn": "Code",
            "sourceProviderType": "decimal",
            "summarizeBy": "count"
          },
          {
            "name": "KeyDC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e09fecd-cd2a-444e-8173-90b61e9df175",
            "sourceColumn": "KeyDC",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e560514b-be21-4a30-84d5-03bd56a0f0a3",
            "sourceColumn": "Value",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "694175ed-77e3-4c38-8054-897d42f103e8",
        "partitions": [
          {
            "name": "FieldParam2-b058222c-a274-437f-8adc-0b20b2d192d3",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    FieldParam1 = public{[Name=\"FieldParam2\"]}[Data]",
                "in",
                "    FieldParam1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Formes juridiques",
        "columns": [
          {
            "name": "Formes juridiques",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "c07d21e2-6c07-433d-88cb-4bc50b220d9a",
            "sourceColumn": "Formes juridiques",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d53085e6-8399-4348-9e2c-2008b6714b5c",
        "partitions": [
          {
            "name": "Formes juridiques-bd179f7e-3619-4107-aacb-9d846f225b86",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    #\"Formes juridiques1\" = public{[Name=\"Formes juridiques\"]}[Data]",
                "in",
                "    #\"Formes juridiques1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Compte",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7377066-2c26-45c8-967d-652cc29f0c96",
            "sourceColumn": "Compte",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CompteLibelle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f911504c-5cd3-463c-9c3d-abf0a909eba3",
            "sourceColumn": "CompteLibelle",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "DateComptable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fc2f313-3f0b-4d6a-8549-33e200b862d4",
            "sourceColumn": "DateComptable",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CodeJournal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f5b28ec-c159-4211-ad0a-9e47aa8c49e1",
            "sourceColumn": "CodeJournal",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "EcritureNumero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3a9e059-9e9d-4e7b-a374-452204354f42",
            "sourceColumn": "EcritureNumero",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "EcritureLibelle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e17440fe-4e4d-43b3-984d-57d29ea660a2",
            "sourceColumn": "EcritureLibelle",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "AccountNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "79579ef0-093c-402a-9c9d-cf107793ecd4",
            "sourceColumn": "AccountNumber",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Exercice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40a3979a-45b1-4344-b615-e07b06d58c3f",
            "sourceColumn": "Exercice",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "DC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89eec861-d3f0-4966-97e2-a581dc0b9099",
            "sourceColumn": "DC",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "AN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b4a33866-a1dc-494c-88f5-bf131ec14362",
            "sourceColumn": "AN",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "ContactMail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45fdd653-152a-47c0-aa99-1f64b6f7df32",
            "sourceColumn": "ContactMail",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CodeEtbt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b201d776-d081-402e-9b04-f78ad8829d48",
            "sourceColumn": "CodeEtbt",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CompAuxLib",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b934f38c-e61c-4699-a9e2-c18d53c2cdfd",
            "sourceColumn": "CompAuxLib",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "EcritureLet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0016b6f2-4cd5-4ae8-84dd-5eb79a3ca558",
            "sourceColumn": "EcritureLet",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CompteName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bd0fc38-a2c3-4304-ab9c-73909d1eeb04",
            "sourceColumn": "CompteName",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CléPCG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00b2b099-ce09-446b-92c9-03dfeb9d3f89",
            "sourceColumn": "CléPCG",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CompteSignificatifs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85db4694-382a-4410-a6a0-44e5a42e5154",
            "sourceColumn": "CompteSignificatifs",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "MTDebit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e54b8870-8d1b-4713-a804-98fb7898e89b",
            "sourceColumn": "MTDebit",
            "sourceProviderType": "decimal",
            "summarizeBy": "sum"
          },
          {
            "name": "MTCredit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "49607cb9-092e-4c77-939c-4bd16521ba69",
            "sourceColumn": "MTCredit",
            "sourceProviderType": "decimal",
            "summarizeBy": "sum"
          },
          {
            "name": "Compte6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8c1233c-1f6c-4ba9-9fab-2358fe459bb3",
            "sourceColumn": "Compte6",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "CléDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec1c6874-a3f5-4bb5-ac37-007c2e025d11",
            "sourceColumn": "CléDate",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "PKey_KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "585530fb-01b7-4f6f-9bcf-5bb68fb7c6ad",
            "sourceColumn": "PKey_KPI",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "DCCompte",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b04e25bc-3b6b-4563-b1dd-a6d33b2771c6",
            "sourceColumn": "DCCompte",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5e862e1b-6c7b-4a03-9a9c-d932589a30e3",
        "measures": [
          {
            "name": "_Achats_%var sous jacent",
            "displayFolder": "Achats",
            "expression": [
              "var a = CALCULATE([_Gene_VariationN/N-1%],removefilters('Compte'[Racine3Libelle],'Compte'[Racine2],'Compte'[Racine3]),removefilters('KPI'[CompteName]))",
              "return ",
              "if ( a=0,\"Sélectionner un sous-jacent\",a)"
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "b2a8d23d-254d-4fab-9632-24ed08bf9f10"
          },
          {
            "name": "_Achats_Ecart",
            "displayFolder": "Achats",
            "expression": [
              "VAR a =",
              "CALCULATE([_Gene_Solde N],removefilters('PlanCompteAEF'[DetailNiv2],'PlanCompteAEF'[DetailNiv3]))",
              "-(CALCULATE([_Gene_VariationN/N-1%],removefilters('Compte'[Racine3Libelle],'Compte'[Racine2],'Compte'[Racine3]),removefilters('KPI'[CompteName]))+1)",
              "* CALCULATE([_Gene_Solde N-1],removefilters('PlanCompteAEF'[DetailNiv2],'PlanCompteAEF'[DetailNiv3]))",
              "",
              "return",
              "if ( a=0,\"Sélectionner un agrégat d'AACE\",a)",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "dca0bc20-3e61-48f3-9f27-03e325ba9a57"
          },
          {
            "name": "_Achats_Solde N-1",
            "displayFolder": "Achats",
            "expression": [
              "var a = CALCULATE([_Gene_Solde N-1],removefilters('PlanCompteAEF'[DetailNiv2],'PlanCompteAEF'[DetailNiv3]))",
              "return",
              "if ( a=0,\"Sélectionner un agrégat d'AACE\",a)"
            ],
            "formatString": "#,##0",
            "lineageTag": "641823e2-e76e-483b-aaec-de062cf864a7"
          },
          {
            "name": "_Achats_Solde projeté",
            "displayFolder": "Achats",
            "expression": [
              "var a = (CALCULATE([_Gene_VariationN/N-1%],removefilters('Compte'[Racine3Libelle],'Compte'[Racine2],'Compte'[Racine3]),removefilters('KPI'[CompteName]))+1)",
              "* CALCULATE([_Gene_Solde N-1],removefilters('PlanCompteAEF'[DetailNiv2],'PlanCompteAEF'[DetailNiv3]))",
              "",
              "return",
              "if ( a=0,\"Sélectionner un agrégat d'AACE\",a)"
            ],
            "formatString": "#,##0",
            "lineageTag": "ebc1d18a-1ce6-4ba4-9f75-d4c0150ad40c"
          },
          {
            "name": "_Cadrage Mvts N",
            "displayFolder": "Cadrage",
            "expression": [
              "VAR mvtcred = CALCULATE (SUM ( 'KPI'[MTCredit] ),'KPI'[Exercice] = \"N\")",
              "VAR mvtdev = CALCULATE (SUM ( 'KPI'[MTDebit] ),'KPI'[Exercice] = \"N\")",
              "",
              "RETURN",
              "",
              "if( isblank(mvtcred) || mvtcred = 0, -mvtcred, mvtdev)"
            ],
            "formatString": "#,##0",
            "lineageTag": "2ca077db-996e-4ba9-b354-e6aa53d18f26"
          },
          {
            "name": "_Cadrage Mvts N-1",
            "displayFolder": "Cadrage",
            "expression": [
              "//if( isblank([_Gene_Mvt Debit N-1]) || [_Gene_Mvt Debit N-1] = 0,-[_Gene_Mvt Credit N-1],[_Gene_Mvt Debit N-1])",
              "",
              "VAR mvtcred = CALCULATE (SUM ( 'KPI'[MTCredit] ),'KPI'[Exercice] = \"N-1\")",
              "VAR mvtdev = CALCULATE (SUM ( 'KPI'[MTDebit] ),'KPI'[Exercice] = \"N-1\")",
              "",
              "RETURN",
              "",
              "if( isblank(mvtcred) || mvtcred = 0, -mvtcred, mvtdev)"
            ],
            "formatString": "#,##0",
            "lineageTag": "266cc1ad-d6a0-4fce-9da2-ea561fe40ddd"
          },
          {
            "name": "_Cadrage_DateClotureCheck",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cadrage",
            "expression": [
              "",
              "IF(",
              "    OR (",
              "        [_Cadrage_DateClotureGL] = MAX ( 'Parametrage'[DateClotureN] ),",
              "        [_Cadrage_DateClotureGL] = MAX (Parametrage[DateClotureN_1] )",
              "    ),",
              "    1,",
              "    2",
              ")"
            ],
            "lineageTag": "5b9fc91c-3156-495c-8c13-a9c5474a704e"
          },
          {
            "name": "_Cadrage_DateClotureGL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "displayFolder": "Cadrage",
            "expression": "EOMONTH ( LASTDATE ( 'KPI'[DateComptable] ), 0 )",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "c86acaa1-fba7-4cd7-b872-a29f8ad741b2"
          },
          {
            "name": "_Cadrage_DateOuvertureCheck",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cadrage",
            "expression": [
              "",
              "IF(",
              "",
              "        [_Cadrage_DateOuvertureGL]",
              "            = MAX (Parametrage[DateOuvertureN] ",
              "    ),",
              "    1,",
              "    2",
              ")"
            ],
            "lineageTag": "ef4265c1-e3f4-471f-bcf6-0b35c033cc96"
          },
          {
            "name": "_Cadrage_DateOuvertureCheck 1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cadrage",
            "expression": [
              "",
              "IF(",
              "",
              "        [_Cadrage_DateOuvertureGL]",
              "            = MAX (Parametrage[DateOuvertureN_1] ",
              "    ),",
              "    1,",
              "    2",
              ")"
            ],
            "lineageTag": "60cb636f-468f-4650-bc07-bf4813c26569"
          },
          {
            "name": "_Cadrage_DateOuvertureGL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "displayFolder": "Cadrage",
            "expression": "STARTOFMONTH ( FIRSTDATE ( 'KPI'[DateComptable] ) )",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "deadb0e5-918e-4dbf-aefb-48e3b2750e56"
          },
          {
            "name": "_Cadrage_EcartGL-BG",
            "displayFolder": "Cadrage",
            "expression": "//[_Cadrage_Solde BG]-[_Gene_Solde GL]",
            "formatString": "#,##0.00",
            "lineageTag": "6a9333a1-55a2-48fd-abc6-ea30c739c759"
          },
          {
            "name": "_Cadrage_EcartGL-BGABS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cadrage",
            "expression": "//ABS([_Cadrage_EcartGL-BG])",
            "lineageTag": "2c336a28-c02e-4cc6-9712-02981a634bbf"
          },
          {
            "name": "_Cadrage_Solde BG",
            "displayFolder": "Cadrage",
            "expression": "//CALCULATE([Solde],FILTER('KPI','KPI'[BaseType]=\"BG\"))",
            "formatString": "#,##0",
            "lineageTag": "bacb98d2-db26-4cd2-bd39-28a14c31e0b5"
          },
          {
            "name": "_Cadrage_Titre1",
            "displayFolder": "Cadrage",
            "expression": "//\"Comptes présents en \" & MAX('KPI'[BaseType]) & \" uniquement: (\" & DISTINCTCOUNT('KPI'[Compte]) & \")\"",
            "lineageTag": "17517d68-4a82-4cc9-978c-4072539605ca"
          },
          {
            "name": "_Cadrage_TitreeA",
            "displayFolder": "Cadrage",
            "expression": "//\"Comptes présents en \" & MAX('KPI'[BaseType]) & \" uniquement: (\" & DISTINCTCOUNT('KPI'[CompteSignificatifs]) & \")\"",
            "lineageTag": "ee1d98f9-980f-4707-b920-6c310ef4d533"
          },
          {
            "name": "_Gene_Cloture_Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cadrage",
            "expression": "\"Clôture du \" & FORMAT(MAX(Parametrage[DateClotureN]),\"dd/mm/yyyy\")",
            "lineageTag": "79b934bc-0ba5-44ff-947a-f8e19723dfcf"
          },
          {
            "name": "_Gene_Cloture_Date 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cadrage",
            "expression": "FORMAT(MAX(Parametrage[DateClotureN]),\"dd/mm/yyyy\")",
            "lineageTag": "e49a2c88-a0ec-4d0a-a564-715be5f8b469"
          },
          {
            "name": "_CP_CapSoc",
            "displayFolder": "Capitaux propres",
            "expression": [
              "IF(SELECTEDVALUE('Formes juridiques'[Formes juridiques]) <> {\"Autre\"},",
              "CALCULATE (",
              "    [_Gene_Solde N],",
              "    PlanCompteAEF[LiasseCode]= \"DA\"),\"Non applicable\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "a3b005e9-38a5-462d-99a5-5d1dc616b442"
          },
          {
            "name": "_CP_Controle1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Capitaux propres",
            "expression": "IF ( [_CP_SituationNette] < [_CP_MoitieCS], \"OK\", \"Attention\" )",
            "lineageTag": "0e0fcd8d-b93f-41b5-b004-67563c502a51"
          },
          {
            "name": "_CP_Controle1_num",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Capitaux propres",
            "expression": "IF([_CP_Controle1]=\"OK\",1,0)",
            "lineageTag": "f223bc73-a87e-4ca9-bc24-81a92b0acf6c"
          },
          {
            "name": "_CP_Controle2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Capitaux propres",
            "expression": [
              "IF (SELECTEDVALUE('Formes juridiques'[Formes juridiques]) = \"Autre\",\"Non applicable\",",
              "IF(DIVIDE([_CP_ReserveLegale],[_CP_CapSoc],0) >= 0.1,",
              "\"OK : \" & ROUND(DIVIDE([_CP_ReserveLegale],[_CP_CapSoc],0),4) * 100 & \"%\",",
              "\"Attention : \" & ROUND(DIVIDE([_CP_ReserveLegale],[_CP_CapSoc],0),4) * 100 & \"%\"))"
            ],
            "lineageTag": "ea54a170-c3ea-415a-a67c-5977ef9d2e8f"
          },
          {
            "name": "_CP_Controle2_num",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Capitaux propres",
            "expression": "IF( [_CP_Controle2]=\"Non applicable\",2, IF(DIVIDE([_CP_ReserveLegale] , [_CP_CapSoc],0)>=0.1,1,0))",
            "lineageTag": "8d397afa-c9eb-4215-b132-a435784598f2"
          },
          {
            "name": "_CP_HorsResultat",
            "displayFolder": "Capitaux propres",
            "expression": [
              "CALCULATE (",
              "    [_Gene_Solde N],",
              "    'PlanCompteAEF'[DetailNiv1] = \"Capitaux propres (hors résultat)\"",
              ") + 1 * 0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "050c42b0-d68f-4068-a22e-23ccd7b3d7cf"
          },
          {
            "name": "_CP_MoitieCS",
            "displayFolder": "Capitaux propres",
            "expression": [
              "CALCULATE (",
              "    [_Gene_Solde N],",
              "    'PlanCompteAEF'[LiasseLibelle] = \"DA - Capital social ou individuel\"",
              ") / 2"
            ],
            "formatString": "### ### ###",
            "lineageTag": "5e7e8d12-e1b7-42bc-af6e-8398679f39e9"
          },
          {
            "name": "_CP_ReserveLegale",
            "displayFolder": "Capitaux propres",
            "expression": [
              "IF(SELECTEDVALUE('Formes juridiques'[Formes juridiques]) <> \"Autre\",",
              "CALCULATE (",
              "    [_Gene_Solde N],",
              "    PlanCompteAEF[LiasseCode] = \"DD\"",
              "),\"Non applicable\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "f7b2fb68-9a15-462f-ad64-7a6c038a6490"
          },
          {
            "name": "_CP_ResultatNet",
            "displayFolder": "Capitaux propres",
            "expression": "CALCULATE ( [_Gene_Solde N], 'PlanCompteAEF'[BilanNiv2] = \"Résultat net\" ,ALL(PlanCompteAEF[DetailNiv3]), ALL('KPI'[CompteSignificatifs]),ALL(Compte[Racine3]),ALL('KPI'[CompteName]),ALL(PlanCompteAEF[LiasseLibelle])) + 1 * 0",
            "formatString": "### ### ###",
            "lineageTag": "7e3d798d-4228-458e-b95a-1829eb5262de"
          },
          {
            "name": "_CP_ResultatNet N-1",
            "displayFolder": "Capitaux propres",
            "expression": "CALCULATE ( [_Gene_Solde N-1], 'PlanCompteAEF'[BilanNiv2] = \"Résultat net\" ,ALL(PlanCompteAEF[DetailNiv3]), ALL('KPI'[CompteSignificatifs]),ALL(Compte[Racine3]),ALL('KPI'[CompteName]),ALL(PlanCompteAEF[LiasseLibelle])) + 1 * 0",
            "formatString": "#,##0",
            "lineageTag": "35530023-637a-44fd-a4ba-9bde746979a5"
          },
          {
            "name": "_CP_SituationNette",
            "displayFolder": "Capitaux propres",
            "expression": "[_CP_HorsResultat]+[_CP_ResultatNet]",
            "formatString": "### ### ###",
            "lineageTag": "051f35e6-fc78-4374-94ca-24d6fb3c0c09"
          },
          {
            "name": "_Client_Tx prov",
            "displayFolder": "Clients",
            "expression": "-DIVIDE([_Clients_491],[_ClientsDouteuxHT],0)",
            "formatString": "#,##0 %",
            "lineageTag": "08f5bf36-2241-45cc-b788-31cf22020912"
          },
          {
            "name": "_Clients 416",
            "displayFolder": "Clients",
            "expression": [
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    Compte[Racine3] = 416)+1*0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "a9120762-66af-4b02-a948-6f603a854172"
          },
          {
            "name": "_Clients_491",
            "displayFolder": "Clients",
            "expression": [
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    filter (Compte,Compte[Racine3] = 491))+1*0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "d281d46d-dce2-4894-be4b-13b5baa2389d"
          },
          {
            "name": "_Clients_681N",
            "displayFolder": "Clients",
            "expression": [
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    Compte[Racine5]=68174,",
              "    'KPI'[Exercice] = \"N\"",
              ") + 1 * 0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "97afabcd-3dfd-48f7-92aa-c2dbd4307221"
          },
          {
            "name": "_Clients_781N",
            "displayFolder": "Clients",
            "expression": [
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "   Compte[Racine5]=78174,",
              "    'KPI'[Exercice] = \"N\"",
              ") + 1 * 0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "daf712e3-b57a-47cc-b7e1-678ce4a23d42"
          },
          {
            "name": "_Clients_Bouclage_Ecart",
            "displayFolder": "Clients",
            "expression": "[_Clients_Var491Dépré] + [_Clients_681N] + [_Clients_781N] + 1 * 0",
            "formatString": "#,##0",
            "lineageTag": "09339a2f-a488-46e2-8b2a-f60056266650"
          },
          {
            "name": "_Clients_Bouclage_Ecart_num",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Clients",
            "expression": [
              "IF (",
              "    AND ( [_Clients_Bouclage_Ecart] > -0.1, [_Clients_Bouclage_Ecart] < 0.1 ),",
              "    1,",
              "    0",
              ")"
            ],
            "lineageTag": "e544cfcd-570a-43ff-a458-d4300cd2aab6"
          },
          {
            "name": "_Clients_DRMCltsN",
            "displayFolder": "Clients",
            "expression": [
              "DIVIDE (",
              "    CALCULATE ( [_Gene_Solde GL], 'PlanCompteAEF'[LiasseCode] in {\"BX\",\"BY\"} ),",
              "    CALCULATE ( [_Gene_Solde GL], 'PlanCompteAEF'[CategorieREX] = \"Chiffre d'affaires\" ),",
              "    0",
              ")",
              "    * DATEDIFF (",
              "        MAX ( Parametrage[DateClotureN] ),",
              "        MAX ( Parametrage[DateOuvertureN] ),",
              "        DAY",
              "    ) / ( 1 + [_mesValeurTVAN] / 100 )"
            ],
            "lineageTag": "6b31e763-faaa-453f-8020-a653a7ee817f"
          },
          {
            "name": "_Clients_DRMCltsN-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Clients",
            "expression": [
              "DIVIDE (",
              "    CALCULATE ( [_Gene_Solde GL], 'PlanCompteAEF'[LiasseCode] in {\"BX\",\"BY\"}),",
              "    CALCULATE ( [_Gene_Solde GL], 'PlanCompteAEF'[CategorieREX] = \"Chiffre d'affaires\" ),",
              "    0",
              ")",
              "    * DATEDIFF (",
              "        MAX ( Parametrage[DateClotureN_1] ),",
              "        MAX ( Parametrage[DateOuvertureN_1] ),",
              "        DAY",
              "    ) / ( 1 + [_mesValeurTVAN-1] / 100 )"
            ],
            "lineageTag": "2b36fa00-2c1b-4121-a603-71be8122b2f0"
          },
          {
            "name": "_Clients_TauxDepreClient",
            "displayFolder": "Clients",
            "expression": [
              "- DIVIDE (",
              "    CALCULATE ( [_Gene_Solde carte], 'PlanCompteAEF'[LiasseCode] = \"BY\" ),",
              "    CALCULATE ( [_Gene_Solde GL], PlanCompteAEF[LiasseCode] = \"BX\" )",
              "    ,",
              "    0",
              ")"
            ],
            "formatString": "#,##0.0 %",
            "lineageTag": "a0ef83dd-3174-47d0-9350-1d588c308cfc"
          },
          {
            "name": "_Clients_Var491Dépré",
            "displayFolder": "Clients",
            "expression": [
              "CALCULATE (",
              "    SUM ( 'KPI'[MTDebit] ) - SUM ( 'KPI'[MTCredit] ),",
              "    LEFT('KPI'[Compte],3) = 491,",
              "    'KPI'[Exercice] = \"N\"",
              ")",
              "    - CALCULATE (",
              "        SUM ( 'KPI'[MTDebit] ) - SUM ( 'KPI'[MTCredit] ),",
              "        LEFT('KPI'[Compte],3) = 491,",
              "        'KPI'[Exercice] = \"N-1\"",
              "    ) + 1 * 0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "8b148fcf-b3e9-4fed-b191-e903dced28cc"
          },
          {
            "name": "_ClientsDouteuxHT",
            "displayFolder": "Clients",
            "expression": [
              "",
              "DIVIDE(",
              "    [_Clients 416],",
              "    1+(if ( max('KPI'[Exercice]) = \"N\",[_mesValeurTVAN]/100,[_mesValeurTVAN-1]/100)),",
              "    0",
              ")+1*0"
            ],
            "formatString": "#,##0",
            "lineageTag": "ea219697-9a2f-4cef-83e4-7c41962e2686"
          },
          {
            "name": "_Gene_Mvt Credit N",
            "displayFolder": "Débit et Crédit",
            "expression": [
              "",
              "IF(OR(ISBLANK(MAX(PlanCompteAEF[LiasseCode])),ISBLANK(MAX(PlanCompteAEF[DetailNiv3]))),",
              "",
              "-[_CP_ResultatNet],",
              "",
              "CALCULATE(CALCULATE (SUM ( 'KPI'[MTCredit] ),'KPI'[Exercice] = \"N\", ParamAN[AN - O/N] = \"Non\"))",
              "",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "1c3d48da-2092-4f87-9f76-c2085632a11b"
          },
          {
            "name": "_Gene_Mvt Credit N pour carte",
            "displayFolder": "Débit et Crédit",
            "expression": [
              "[_Gene_Mvt Credit N]+0",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "495cdc67-4de3-4090-a50e-90773e16544e"
          },
          {
            "name": "_Gene_Mvt Credit N-1",
            "displayFolder": "Débit et Crédit",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'KPI'[MTCredit] ),",
              "    'KPI'[Exercice] = \"N-1\",",
              "    ParamAN[AN - O/N] = \"Non\"",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "fe4aa448-df0c-4fe5-b4a5-a1cef9dc81fc"
          },
          {
            "name": "_Gene_Mvt Credit N-1 pour carte",
            "displayFolder": "Débit et Crédit",
            "expression": [
              "[_Gene_Mvt Credit N-1]+0",
              "",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "a3947e2b-96ca-420a-93f1-e1e0c841f25f"
          },
          {
            "name": "_Gene_Mvt Debit N",
            "displayFolder": "Débit et Crédit",
            "expression": [
              "",
              "IF(OR(ISBLANK(MAX(PlanCompteAEF[LiasseCode])),ISBLANK(MAX(PlanCompteAEF[DetailNiv3]))),",
              "-[_CP_ResultatNet N-1],",
              "CALCULATE (CALCULATE (",
              "    SUM ( 'KPI'[MTDebit] ),",
              "    'KPI'[Exercice] = \"N\",",
              "    ParamAN[AN - O/N] = \"Non\"",
              ")))"
            ],
            "formatString": "#,##0",
            "lineageTag": "d13326a6-8934-4cf6-a458-bb73712f6615"
          },
          {
            "name": "_Gene_Mvt Debit N inv",
            "displayFolder": "Débit et Crédit",
            "expression": "-[_Gene_Mvt Debit N]",
            "formatString": "#,##0",
            "lineageTag": "312f08eb-564b-438a-b540-f9ff9a997a3e"
          },
          {
            "name": "_Gene_Mvt Debit N pour carte",
            "displayFolder": "Débit et Crédit",
            "expression": [
              "[_Gene_Mvt Debit N]+0",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "8e91e9a2-67d9-447f-84fc-3570f015a62a"
          },
          {
            "name": "_Gene_Mvt Debit N-1",
            "displayFolder": "Débit et Crédit",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'KPI'[MTDebit] ),",
              "    'KPI'[Exercice] = \"N-1\",",
              "    ParamAN[AN - O/N] = \"Non\"",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "7b29d2cf-8cee-4418-962c-7412ff1273fa"
          },
          {
            "name": "_Gene_Mvt Debit N-1 pour carte",
            "displayFolder": "Débit et Crédit",
            "expression": "[_Gene_Mvt Debit N-1]+0",
            "formatString": "#,##0",
            "lineageTag": "c17ce10d-0b6c-43ef-9e25-2678fda9a117"
          },
          {
            "name": "_Immo_Amort Bilan HorsAN",
            "displayFolder": "Immobilisations",
            "expression": [
              "",
              "CALCULATE(",
              "        [_Immo_Dot Amort N],",
              "        'PlanCompteAEF'[DetailNiv3] = \"Dép. / amort. immobilisations incorporelles\"",
              "            ||'PlanCompteAEF'[DetailNiv3] = \"Dép. / amort. immobilisations corporelles\"",
              "            ||'PlanCompteAEF'[DetailNiv3] = \"Dép. immobilisations financières\",",
              "        ParamAN[A/N - Bridge]=\"\"",
              ")+ 1 * 0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "b75658a4-a0a5-48c7-a536-2169e159001a"
          },
          {
            "name": "_Immo_Amort Bouclage Ecart",
            "displayFolder": "Immobilisations",
            "expression": "[_Immo_Amort Bilan HorsAN]-[_Immo_Amort P&L]",
            "formatString": "#,##0",
            "lineageTag": "0a8c79e6-a04f-4300-931d-fe4b4c9e9fb1"
          },
          {
            "name": "_Immo_Amort P&L",
            "displayFolder": "Immobilisations",
            "expression": [
              "",
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    'PlanCompteAEF'[DetailNiv3] = \"Dot. amort, dépréciations et prov\"",
              ")"
            ],
            "formatString": "### ### ###",
            "lineageTag": "8ca41d1a-bef4-4b2f-92b1-c0fa282599e6"
          },
          {
            "name": "_Immo_Dot Amort N",
            "displayFolder": "Immobilisations",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM ( 'KPI'[MTCredit] ),",
              "    'KPI'[Exercice] = \"N\",",
              "    Compte[Racine2]<>\"29\",",
              "    ParamAN[AN - O/N] = \"Non\"",
              ")"
            ],
            "formatString": "### ### ###",
            "lineageTag": "c842077f-ea56-4591-9a68-a54e25330f77"
          },
          {
            "name": "_Immo_Dot Depre N",
            "displayFolder": "Immobilisations",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM ( 'KPI'[MTCredit] ),",
              "    'KPI'[Exercice] = \"N\",",
              "    Compte[Racine2]=\"29\",",
              "    ParamAN[AN - O/N] = \"Non\"",
              ")"
            ],
            "formatString": "### ### ###",
            "lineageTag": "f1c044c1-f895-4b14-823c-b4258abc2339"
          },
          {
            "name": "_Immo_P CEAC",
            "displayFolder": "Immobilisations",
            "expression": "-CALCULATE([_Gene_Solde GL],'KPI'[Exercice]=\"N\",Compte[Racine3]=\"775\")",
            "formatString": "### ### ###",
            "lineageTag": "d2d2cce3-e4f1-4a11-a43f-7a33f19927d1"
          },
          {
            "name": "_Immo_PV Cession",
            "displayFolder": "Immobilisations",
            "expression": "[_Immo_VNC]-[_Immo_P CEAC]",
            "formatString": "#,##0",
            "lineageTag": "71d032a4-0a03-4cf1-b5cf-09d202257679"
          },
          {
            "name": "_Immo_Rep Amort N",
            "displayFolder": "Immobilisations",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM ( 'KPI'[MTDebit] ),",
              "    'KPI'[Exercice] = \"N\",",
              "    Compte[Racine2]<>\"29\",",
              "    ParamAN[AN - O/N] = \"Non\"",
              ")"
            ],
            "formatString": "### ### ###",
            "lineageTag": "4f2b092c-04b5-482a-a269-268af48f97cb"
          },
          {
            "name": "_Immo_Rep Depre N",
            "displayFolder": "Immobilisations",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM ( 'KPI'[MTDebit] ),",
              "    'KPI'[Exercice] = \"N\",",
              "    Compte[Racine2]=\"29\",",
              "    ParamAN[AN - O/N] = \"Non\"",
              ")"
            ],
            "formatString": "### ### ###",
            "lineageTag": "0315d68f-afb4-4633-99e1-fa19f0d706b1"
          },
          {
            "name": "_Immo_Taux Depre",
            "displayFolder": "Immobilisations",
            "expression": [
              "",
              "DIVIDE (",
              "    CALCULATE (",
              "       [_Gene_Solde GL],",
              "       Compte[Racine5]=\"68662\"",
              "        ),",
              "    CALCULATE (",
              "        [_Gene_Solde GL],",
              "            'PlanCompteAEF'[DetailNiv3] = \"Immobilisations incorporelles brutes\"||",
              "            'PlanCompteAEF'[DetailNiv3]  = \"Immobilisations corporelles brutes\"||",
              "            'PlanCompteAEF'[DetailNiv3]  = \"Immobilisations financières brutes\"",
              "        )",
              "    )",
              "+ 1 * 0"
            ],
            "formatString": "#,##0.0 %",
            "lineageTag": "eb4effe3-3925-4f07-9427-2ac511235a0a"
          },
          {
            "name": "_Immo_Taux Dot",
            "displayFolder": "Immobilisations",
            "expression": [
              "",
              "DIVIDE (",
              "    [_Immo_Amort P&L],",
              "    CALCULATE (",
              "        [_Gene_Solde GL],",
              "            'PlanCompteAEF'[DetailNiv3] = \"Immobilisations incorporelles brutes\"||",
              "            'PlanCompteAEF'[DetailNiv3]  = \"Immobilisations corporelles brutes\"",
              "        ),0",
              ")",
              "+ 1 * 0"
            ],
            "formatString": "#,##0.0 %",
            "lineageTag": "55374491-b2b3-4ea0-82b0-cdd4821317c0"
          },
          {
            "name": "_Immo_VNC",
            "displayFolder": "Immobilisations",
            "expression": "CALCULATE([_Gene_Solde GL],'KPI'[Exercice]=\"N\",Compte[Racine3]=\"675\")",
            "formatString": "### ### ###",
            "lineageTag": "6cc2bff1-b4ae-4b29-90d2-34cd3c069980"
          },
          {
            "name": "_Immo_VNC Bilan",
            "displayFolder": "Immobilisations",
            "expression": [
              "",
              "CALCULATE (",
              "    [_Gene_Mvt Credit N],",
              "    'PlanCompteAEF'[DetailNiv3] = \"Immobilisations incorporelles brutes\"||",
              "    'PlanCompteAEF'[DetailNiv3]  = \"Immobilisations corporelles brutes\"",
              ")",
              "-CALCULATE (",
              "    [_Gene_Mvt Debit N],",
              "    'PlanCompteAEF'[DetailNiv3] = \"Dép. / amort. immobilisations incorporelles\"||",
              "    'PlanCompteAEF'[DetailNiv3] = \"Dép. / amort. immobilisations corporelles\"",
              ")+ 1 * 0"
            ],
            "formatString": "#,##0",
            "lineageTag": "691d7843-c4f4-43f9-8e36-335976ea0118"
          },
          {
            "name": "_Immo_VNC Ecart",
            "displayFolder": "Immobilisations",
            "expression": "[_Immo_VNC Bilan]- [_Immo_VNC P&L]",
            "formatString": "#,##0",
            "lineageTag": "d3b0898d-84eb-42f4-9221-f1f3a716bd57"
          },
          {
            "name": "Nbr de jours N",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": [
              "FORMAT (",
              "    MAX ( 'Parametrage'[DateClotureN] )",
              "        - MAX ( 'Parametrage'[DateOuvertureN] ) + 1,",
              "    \"General Number\"",
              ")"
            ],
            "lineageTag": "f1493922-75d4-4a64-b476-6ea0772ab4ed"
          },
          {
            "name": "Nbr de jours N-1",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": [
              "FORMAT (",
              "    MAX ( 'Parametrage'[DateClotureN_1] )",
              "        - MAX ( 'Parametrage'[DateOuvertureN_1] ) + 1,",
              "    \"General Number\"",
              ")"
            ],
            "lineageTag": "5c63ee0a-ae55-4a6d-a1a3-ef2642472aae"
          },
          {
            "name": "Nbr jour max full year N",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": [
              "VAR AccountNumber =",
              "    SELECTEDVALUE ( 'AuditorSecurity'[AccountNumber] )",
              "VAR Col =",
              "    CALCULATE (",
              "        MAX ( 'Parametrage'[DateClotureN] ),",
              "        'Parametrage'[AccountNumber] = AccountNumber",
              "    )",
              "VAR Pre =",
              "    CALCULATE (",
              "        MAX ( 'KPI'[FirstFiscalMonth] ),",
              "        'KPI'[AccountNumber] = AccountNumber",
              "    )",
              "VAR PK =",
              "    CALCULATE (",
              "        MAX ( 'DimTemps'[PkDate] ),",
              "        'DimTemps'[FirstFiscalMonth] = Pre,",
              "        'DimTemps'[Dates] = Col",
              "    )",
              "VAR Ann =",
              "    CALCULATE ( MAX ( 'DimTemps'[FiscalYear] ), 'DimTemps'[PkDate] = PK )",
              "RETURN",
              "    IF ( MOD ( Ann, 4 ) = 0, 366, 365 )"
            ],
            "lineageTag": "14a8353b-878a-4b5f-8165-e06a4adce348"
          },
          {
            "name": "Nbr jour max full year N-1",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": [
              "VAR AccountNumber =",
              "    SELECTEDVALUE ( 'AuditorSecurity'[AccountNumber] )",
              "VAR Col =",
              "    CALCULATE ( MAX ( 'Parametrage'[DateClotureN_1] ),",
              "        'Parametrage'[AccountNumber] = AccountNumber",
              "    )",
              "VAR Pre =",
              "    CALCULATE ( MAX ( 'KPI'[FirstFiscalMonth] ),",
              "        'KPI'[AccountNumber] = AccountNumber",
              "    )",
              "VAR PK =",
              "    CALCULATE ( MAX ( 'DimTemps'[PkDate] ),",
              "        'DimTemps'[FirstFiscalMonth] = Pre,",
              "        'DimTemps'[Dates] = Col",
              "    )",
              "VAR Ann = CALCULATE ( MAX ( 'DimTemps'[FiscalYear] ),",
              "        'DimTemps'[PkDate]=PK",
              "    )",
              "",
              "",
              "",
              " ",
              "RETURN",
              "    if ( MOD ( Ann, 4 ) = 0, 366, 365 )",
              "    "
            ],
            "lineageTag": "3bd95ad9-c7ba-439a-962a-777fed241782"
          },
          {
            "name": "Nbr jour max N",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": [
              "//lookupvalue('DimTemps'[DayofYear],'DimTemps'[Dates],Max('Parametrage'[DateClotureN]))",
              "",
              "VAR AccountNumber =",
              "    SELECTEDVALUE ( 'AuditorSecurity'[AccountNumber] )",
              "VAR Col =",
              "    CALCULATE ( MAX ( 'Parametrage'[DateClotureN] ),",
              "        'Parametrage'[AccountNumber] = AccountNumber",
              "    )",
              "VAR Pre =",
              "    CALCULATE ( MAX ( 'KPI'[FirstFiscalMonth] ),",
              "        'KPI'[AccountNumber] = AccountNumber",
              "    )",
              "VAR PK =",
              "    CALCULATE ( MAX ( 'DimTemps'[PkDate] ),",
              "        'DimTemps'[FirstFiscalMonth] = Pre,",
              "        'DimTemps'[Dates] = Col",
              "    )",
              "RETURN CALCULATE ( MAX ( 'DimTemps'[DayOfYear] ),",
              "        'DimTemps'[PkDate]=PK",
              "    )",
              "//var a = SUMMARIZE(TOPN( 1, Filter ('DimTemps', 'DimTemps'[Dates]=Max('Parametrage'[DateClotureN])),'DimTemps'[DayofYear],ASC),\"maxv\",min('DimTemps'[DayofYear]) )",
              "//return ",
              "//minx(a,[maxv])+0"
            ],
            "formatString": "#,##0",
            "lineageTag": "11b5b093-34b0-4aeb-b0b7-e1c5c28c72c9"
          },
          {
            "name": "Nbr jour max N-1",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": [
              "//calculate (Max('DimTemps'[DayofYear]),'DimTemps'[Dates]=Max('Parametrage'[DateClotureN_1]))",
              "VAR AccountNumber =",
              "    SELECTEDVALUE ( 'AuditorSecurity'[AccountNumber] )",
              "VAR Col =",
              "    CALCULATE (",
              "        MAX ( 'Parametrage'[DateClotureN_1] ),",
              "        'Parametrage'[AccountNumber] = AccountNumber",
              "    )",
              "VAR Pre =",
              "    CALCULATE (",
              "        MAX ( 'KPI'[FirstFiscalMonth] ),",
              "        'KPI'[AccountNumber] = AccountNumber",
              "    )",
              "VAR PK =",
              "    CALCULATE (",
              "        MAX ( 'DimTemps'[PkDate] ),",
              "        'DimTemps'[FirstFiscalMonth] = Pre,",
              "        'DimTemps'[Dates] = Col",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        MAX ( 'DimTemps'[DayOfYear] ),",
              "        'DimTemps'[PkDate] = PK",
              "    )"
            ],
            "formatString": "#,##0",
            "lineageTag": "b9b1b0bc-194d-4889-aa87-33272995b326"
          },
          {
            "name": "Nbr jour min equiv N",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": "[Selected value T9] + [Nbr jour min N] -1",
            "lineageTag": "8739ab79-2488-4e33-89d3-58c99625da53"
          },
          {
            "name": "Nbr jour min equiv N-1",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": "[Selected value T8] + [Nbr jour min N-1] -1",
            "lineageTag": "26fdd200-c6ba-4b63-b8d3-07cb6ae07ea0"
          },
          {
            "name": "Nbr jour min N",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": [
              "[Nbr jour max N]-[Nbr de jours N]+1",
              ""
            ],
            "lineageTag": "a2e08e51-b54a-4515-af1b-a01dcf66c812"
          },
          {
            "name": "Nbr jour min N-1",
            "displayFolder": "Nombre de jours (A revoir)",
            "expression": [
              "[Nbr jour max N-1]-[Nbr de jours N-1]+1",
              ""
            ],
            "lineageTag": "a0944dca-0daa-4928-b34f-d751096e1df6"
          },
          {
            "name": "_615_Population restante",
            "displayFolder": "Population résiduelle",
            "expression": "[_615_Population totale]-[_615_Population testée]",
            "formatString": "#,##0",
            "lineageTag": "c92515a2-7ed1-4893-a7f2-d01b8c62bb3f"
          },
          {
            "name": "_615_Population testée",
            "displayFolder": "Population résiduelle",
            "expression": [
              "",
              "    calculate(",
              "        [_Gene_Solde N],",
              "        TOPN([Selected value T3],",
              "        values('KPI'[EcritureNumero]),[_Gene_Solde N],",
              "        desc)",
              "    )"
            ],
            "lineageTag": "bdeb227a-7791-4962-a9cd-28b8bcadcb49"
          },
          {
            "name": "_615_Population totale",
            "displayFolder": "Population résiduelle",
            "expression": "CALCULATE([_Gene_Solde N],ALL('KPI'[EcritureNumero]))",
            "lineageTag": "837572eb-8e8e-41f9-85a1-746e38b61549"
          },
          {
            "name": "_SAP Pop globale",
            "displayFolder": "Population résiduelle",
            "expression": "CALCULATE([_Gene_Solde N],ALL(Compte[Racine3]),ALL('KPI'[CompteName]))",
            "formatString": "#,##0",
            "lineageTag": "2bd64167-a649-4f02-bc1d-6577cc6a730f"
          },
          {
            "name": "_SAP Pop globale 1",
            "displayFolder": "Population résiduelle",
            "expression": "CALCULATE(0,ALL('KPI'[CompteName]))",
            "formatString": "#,##0",
            "lineageTag": "9db029ba-802b-4cfe-80a6-2b6c34427d2f"
          },
          {
            "name": "_SAP Pop globale bilan",
            "displayFolder": "Population résiduelle",
            "expression": "CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL(Compte[Racine3]),ALL('KPI'[CompteName]))",
            "formatString": "#,##0",
            "lineageTag": "ce2e6444-28ea-4725-93ed-44f4cd28b35b"
          },
          {
            "name": "_SAP Pop globale P&L",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Population résiduelle",
            "expression": "CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\",ALL(Compte[Racine3]),ALL('KPI'[CompteName]))",
            "lineageTag": "28a97c90-1f21-48f6-a7fb-9dd367cd7ef7"
          },
          {
            "name": "_SAP Pop non testée",
            "displayFolder": "Population résiduelle",
            "expression": "[_SAP Pop globale]-[_SAP Pop testée]",
            "formatString": "#,##0",
            "lineageTag": "db2ac946-596f-4427-ad35-5b20a8d02650"
          },
          {
            "name": "_SAP Pop non testée bilan",
            "displayFolder": "Population résiduelle",
            "expression": "[_SAP Pop globale bilan]-[_SAP Pop testée bilan]",
            "formatString": "#,##0",
            "lineageTag": "b90d0c81-c00c-41a5-91bc-319dcfb70d86"
          },
          {
            "name": "_SAP Pop non testée P&L",
            "displayFolder": "Population résiduelle",
            "expression": "[_SAP Pop globale P&L]-[_SAP Pop testée P&L]",
            "formatString": "#,##0",
            "lineageTag": "c32f422d-2f8c-4325-afcd-572463d3766f"
          },
          {
            "name": "_SAP Pop testée",
            "displayFolder": "Population résiduelle",
            "expression": "[_Gene_Solde N]",
            "formatString": "#,##0",
            "lineageTag": "121d193a-254d-4734-afa7-9c6ec890801d"
          },
          {
            "name": "_SAP Pop testée bilan",
            "displayFolder": "Population résiduelle",
            "expression": "CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"Bilan\")",
            "formatString": "#,##0",
            "lineageTag": "c5bcafb7-bc6c-4bbf-9261-aefa130e2aa1"
          },
          {
            "name": "_SAP Pop testée P&L",
            "displayFolder": "Population résiduelle",
            "expression": "CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\")",
            "formatString": "#,##0",
            "lineageTag": "9407ca1b-9d2d-435a-b3ff-9c681f54482d"
          },
          {
            "name": "_615_Rankx",
            "displayFolder": "Rank",
            "expression": [
              "",
              "if([_615_RankX EcritureN]<=[Selected value T3],\"Yes\",\"No\")"
            ],
            "lineageTag": "2834a778-1377-4d05-8e3e-86c6d96c9a8c"
          },
          {
            "name": "_615_RankX EcritureN",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Rank",
            "expression": [
              "rankx(",
              "        all('KPI'[EcritureNumero]),",
              "        calculate([_Gene_Solde N]),",
              "        ,",
              "        DESC,",
              "        Dense)"
            ],
            "lineageTag": "40ce39a7-4414-4be4-911e-82da8348e740"
          },
          {
            "name": "_CA_Rankx",
            "displayFolder": "Rank",
            "expression": [
              "",
              "if([_CA_RankX EcritureN]<=[Selected value T3],\"Yes\",\"No\")"
            ],
            "lineageTag": "4e515632-865e-4978-a892-c3922c8968ed"
          },
          {
            "name": "_CA_RankX EcritureN",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Rank",
            "expression": [
              "rankx(",
              "        all('KPI'[EcritureNumero]),",
              "        -calculate([_Gene_Solde N]),",
              "        ,",
              "        DESC,",
              "        Dense)"
            ],
            "lineageTag": "5e776ae8-1b27-448b-b0e8-79b6d09e234c"
          },
          {
            "name": "_CA_Top Ventes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Rank",
            "expression": [
              "",
              "    calculate(",
              "        [_Gene_Solde inv],",
              "        TOPN([Selected value T3],",
              "        values('KPI'[EcritureNumero]),[_Gene_Solde inv],",
              "        desc)",
              "    )"
            ],
            "lineageTag": "8a244b05-a73a-4b0c-8a6f-5997dbe9a1ed"
          },
          {
            "name": "_CA_Top Ventes N",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Rank",
            "expression": [
              "",
              "    calculate(",
              "        [_Gene_Solde N inv],",
              "        TOPN([Selected value T3],",
              "        values('KPI'[EcritureNumero]),[_Gene_Solde N inv],",
              "        desc)",
              "    )"
            ],
            "lineageTag": "64170879-f696-4dd3-b7b7-bb6a7ea3e1d2"
          },
          {
            "name": "_CA_Top Ventes N-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Rank",
            "expression": [
              "",
              "    calculate(",
              "        [_Gene_Solde N-1 inv],",
              "        TOPN([Selected value T3],",
              "        values('KPI'[EcritureNumero]),[_Gene_Solde N-1 inv],",
              "        desc)",
              "    )"
            ],
            "lineageTag": "74e34531-703c-4b6b-8355-bbce4ebd8468"
          },
          {
            "name": "_Gene_Solde carte",
            "displayFolder": "Solde et Variation",
            "expression": "[_Gene_Solde GL]+0",
            "formatString": "#,##0",
            "lineageTag": "10f200b0-3660-45a7-9074-c2bcc6726556"
          },
          {
            "name": "_Gene_Solde Cumulé",
            "displayFolder": "Solde et Variation",
            "expression": [
              "IF(Isblank([_Gene_Solde GL]),BLANK(),",
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    FILTER (",
              "        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[FiscalQuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear] ),",
              "        AND(DimTemps[Dates] <= MAX (DimTemps[Dates]) ,",
              "        DimTemps[FiscalYear] = MAX ( DimTemps[FiscalYear] ))",
              "        ))",
              ")"
            ],
            "formatString": "#,##0.00",
            "lineageTag": "53161d29-a840-4128-95cf-e75c50491291"
          },
          {
            "name": "_Gene_Solde Cumulé inv",
            "displayFolder": "Solde et Variation",
            "expression": "-[_Gene_Solde Cumulé]",
            "formatString": "#,##0.00",
            "lineageTag": "aaf90566-4d86-4a22-9f6d-e7f94d82c959"
          },
          {
            "name": "_Gene_Solde GL",
            "displayFolder": "Solde et Variation",
            "expression": "CALCULATE([Solde])",
            "formatString": "#,##0",
            "lineageTag": "874f4ab0-cae3-4666-8daf-6f8ca1fe16fa"
          },
          {
            "name": "_Gene_Solde GL pour tod",
            "displayFolder": "Solde et Variation",
            "expression": [
              "VAR filtre1 = Treatas(values ('KPI'[EcritureLibelle]), 'KPI'[EcritureLibelle])",
              "VAR filtre2 = Treatas(values ('KPI'[DateComptable]), 'KPI'[DateComptable])",
              "",
              "return",
              "",
              "CALCULATE([_Gene_Solde GL],'KPI'[EcritureLibelle] in filtre1 || 'KPI'[DateComptable] in filtre2 ) "
            ],
            "formatString": "#,##0",
            "lineageTag": "63caa64b-d498-4f7b-a8a1-e27e8f551227"
          },
          {
            "name": "_Gene_Solde inv",
            "displayFolder": "Solde et Variation",
            "expression": "-[_Gene_Solde GL]",
            "formatString": "#,##0.00",
            "lineageTag": "a97cb03b-79e2-4247-a838-a7c8fcf4b43e"
          },
          {
            "name": "_Gene_Solde inv debit",
            "displayFolder": "Solde et Variation",
            "expression": "calculate (-[_Gene_Solde GL],'KPI'[MTDebit]<>0)",
            "formatString": "#,##0.00",
            "lineageTag": "23a56995-b6d4-47c8-b6f7-0e1fd8c5ef5b"
          },
          {
            "name": "_Gene_Solde Inversé carte",
            "displayFolder": "Solde et Variation",
            "expression": "[_Gene_Solde inv]+0",
            "formatString": "#,##0",
            "lineageTag": "dcae221b-33a5-4c7c-9074-9ce910a794a4"
          },
          {
            "name": "_Gene_Solde Moyen",
            "displayFolder": "Solde et Variation",
            "expression": [
              "",
              "ABS (",
              "    CALCULATE (",
              "        DIVIDE(",
              "            [_Gene_Solde GL],",
              "            [_Gene_Nb Lignes],",
              "            0),",
              "        ALLSELECTED('KPI'[Exercice])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "1f933c2c-ecec-42b4-9055-4bdb5c55c13d"
          },
          {
            "name": "_Gene_Solde Moyen basic",
            "displayFolder": "Solde et Variation",
            "expression": [
              "",
              "    CALCULATE (",
              "        DIVIDE(",
              "            [_Gene_Solde GL],",
              "            [_Gene_Nb Lignes],",
              "            0),",
              "        ALLSELECTED('KPI'[Exercice])",
              "    )"
            ],
            "formatString": "#,##0",
            "lineageTag": "e1f28f83-eb7c-49b9-bde2-6371cd2e0823"
          },
          {
            "name": "_Gene_Solde Moyen inv",
            "displayFolder": "Solde et Variation",
            "expression": [
              "",
              "    CALCULATE (",
              "        DIVIDE(",
              "            [_Gene_Solde inv],",
              "            [_Gene_Nb Lignes],",
              "            0),",
              "        ALLSELECTED('KPI'[Exercice])",
              "    )"
            ],
            "formatString": "#,##0",
            "lineageTag": "22b4627b-c948-4dff-97f8-3e5a987c9a87"
          },
          {
            "name": "_Gene_Solde Moyen N",
            "displayFolder": "Solde et Variation",
            "expression": [
              "",
              "ABS(",
              "    CALCULATE(",
              "        DIVIDE(",
              "            [_Gene_Solde GL],",
              "            [_Gene_Nb Lignes],",
              "            0),",
              "        'KPI'[Exercice]=\"N\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "4e773e91-2adc-4c42-b63a-f6afbe5d60c4"
          },
          {
            "name": "_Gene_Solde Moyen N-1",
            "displayFolder": "Solde et Variation",
            "expression": [
              "",
              "ABS(",
              "    CALCULATE(",
              "        DIVIDE(",
              "            [_Gene_Solde GL],",
              "            [_Gene_Nb Lignes],",
              "            0),",
              "        'KPI'[Exercice]=\"N-1\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "26b68aa1-2907-430a-9ce4-2172ba7df53f"
          },
          {
            "name": "_Gene_Solde N",
            "displayFolder": "Solde et Variation",
            "expression": "CALCULATE([_Gene_Solde GL],'KPI'[Exercice]=\"N\")",
            "formatString": "#,##0",
            "lineageTag": "4f11fb4e-728c-4d4a-891d-2c1a0c0cc3f1"
          },
          {
            "name": "_Gene_Solde N AN",
            "displayFolder": "Solde et Variation",
            "expression": "CALCULATE([_Gene_Solde N],ParamAN[AN - O/N] = \"Oui\")",
            "formatString": "#,##0",
            "lineageTag": "c2948fcf-ef7b-44f5-af10-bb19c4a1ab37"
          },
          {
            "name": "_Gene_Solde N calculé",
            "displayFolder": "Solde et Variation",
            "expression": "[_Gene_Solde N-1]+[_Gene_Mvt Debit N]-[_Gene_Mvt Credit N]",
            "formatString": "#,##0",
            "lineageTag": "42110419-78d8-49d3-af48-808f10e655f0"
          },
          {
            "name": "_Gene_Solde N calculé vs réel",
            "displayFolder": "Solde et Variation",
            "expression": "[_Gene_Solde N calculé]- [_Gene_Solde N]",
            "formatString": "#,##0",
            "lineageTag": "9685850a-5fc1-4c53-9a99-e2995b0e9178"
          },
          {
            "name": "_Gene_Solde N inv",
            "displayFolder": "Solde et Variation",
            "expression": "- [_Gene_Solde N]",
            "formatString": "#,##0",
            "lineageTag": "c7f0f698-9ef1-4b9b-ad9b-24498c190d59"
          },
          {
            "name": "_Gene_Solde N-1",
            "displayFolder": "Solde et Variation",
            "expression": "CALCULATE([_Gene_Solde GL],'KPI'[Exercice]=\"N-1\")",
            "formatString": "#,##0",
            "lineageTag": "3187a39e-5af4-4d34-a0f7-96bc1b907633"
          },
          {
            "name": "_Gene_Solde N-1 inv",
            "displayFolder": "Solde et Variation",
            "expression": "- [_Gene_Solde N-1]",
            "formatString": "#,##0",
            "lineageTag": "9142e411-048e-4894-981d-830faf140383"
          },
          {
            "name": "_Gene_Solde pour excl nb jours N 1",
            "displayFolder": "Solde et Variation",
            "expression": "calculate ([_Gene_Solde N-1],AllEXCEPT('KPI','KPI'[Exercice]),All('Compte'))",
            "lineageTag": "7caaae56-4cb4-4454-8efe-98d7476c4148"
          },
          {
            "name": "_Gene_Titre CA",
            "displayFolder": "Solde et Variation",
            "expression": [
              "\" Analyse \"",
              "    & if(MAX('FieldParam_measures'[Code])=2,\"des \",\"du \")",
              "    & MAX ( 'FieldParam_measures'[Value] ) & ",
              "    \" par code journal\""
            ],
            "formatString": "#,##0.00",
            "lineageTag": "726b76af-2b94-4e0b-9149-42b831a5968a"
          },
          {
            "name": "_Gene_Variation N/N-1",
            "displayFolder": "Solde et Variation",
            "expression": "[_Gene_Solde N]-[_Gene_Solde N-1]",
            "formatString": "#,##0",
            "lineageTag": "2e4c559a-c69b-484b-bcb8-0e01bc97094f"
          },
          {
            "name": "_Gene_Variation N/N-1 abs",
            "displayFolder": "Solde et Variation",
            "expression": "abs([_Gene_Variation N/N-1])",
            "formatString": "#,##0",
            "lineageTag": "00d8ddae-7742-49a6-8e75-b10a9b25a7e0"
          },
          {
            "name": "_Gene_Variation N/N-1_inv",
            "displayFolder": "Solde et Variation",
            "expression": "-[_Gene_Variation N/N-1]",
            "formatString": "#,##0",
            "lineageTag": "2b1ae6e1-4b5d-498c-b801-1f4fd790fe60"
          },
          {
            "name": "_Gene_VariationN/N-1%",
            "displayFolder": "Solde et Variation",
            "expression": "DIVIDE([_Gene_Variation N/N-1],[_Gene_Solde N-1],0)",
            "formatString": "#,##0 %",
            "lineageTag": "2f57963d-a7ef-4ab6-b160-d872d1e67d26"
          },
          {
            "name": "_Gene_VariationN/N-1%_inv",
            "displayFolder": "Solde et Variation",
            "expression": "-[_Gene_VariationN/N-1%]",
            "formatString": "#,##0 %",
            "lineageTag": "8e442049-4063-4373-9327-855afd68bc6c"
          },
          {
            "name": "Solde",
            "displayFolder": "Solde et Variation",
            "expression": [
              "",
              "[Debit] - [Credit]"
            ],
            "lineageTag": "2ae9a227-a54c-4825-a750-4aa02c9194c2"
          },
          {
            "name": "_Stocks_BouclageBrut",
            "displayFolder": "Stocks",
            "expression": "[_Stocks_VarBrutBilan] + [_Stocks_VarBrutP&L]",
            "formatString": "#,##0",
            "lineageTag": "d096ef60-a3a1-446c-a895-b3d59b30e33f"
          },
          {
            "name": "_Stocks_BouclageBrut_num",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Stocks",
            "expression": "IF(ABS([_Stocks_BouclageBrut])<0.1,0,1)",
            "lineageTag": "8c3f50e5-93f7-4bf6-a4c8-fded870ae81a"
          },
          {
            "name": "_Stocks_BouclageDépré",
            "displayFolder": "Stocks",
            "expression": "[_Stocks_VarDépréBilan] + [_Stocks_DotDépréP&L] + [_Stocks_RepDépréP&L] + 1*0",
            "formatString": "#,##0",
            "lineageTag": "79035615-80e6-4a98-8cf9-89e75649be87"
          },
          {
            "name": "_Stocks_BouclageDépré_num",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Stocks",
            "expression": "IF( ABS([_Stocks_BouclageDépré])<0.1,0,1)",
            "lineageTag": "5b408bc1-026a-47a0-a114-e4bd0c32fe0f"
          },
          {
            "name": "_Stocks_DépréciationTaux",
            "displayFolder": "Stocks",
            "expression": [
              "DIVIDE (",
              "    CALCULATE (",
              "        - [_Gene_Solde GL],",
              "        FILTER ( 'PlanCompteAEF', 'PlanCompteAEF'[MarquageStocks] = \"Dépré Stocks\" )",
              "    ),",
              "    CALCULATE (",
              "        [_Gene_Solde GL],",
              "        FILTER ( 'PlanCompteAEF', 'PlanCompteAEF'[MarquageStocks] = \"Stocks bruts\" )",
              "    ),",
              "    0",
              ") + 1 * 0"
            ],
            "formatString": "#,##0.0 %",
            "lineageTag": "f4a485a3-14b6-4b35-b24c-eb4ace933c68"
          },
          {
            "name": "_Stocks_DotDépréP&L",
            "displayFolder": "Stocks",
            "expression": "CALCULATE ( [_Gene_Solde N], FILTER ( Compte, Compte[Racine5] = \"68173\" ) ) + 1 * 0",
            "formatString": "### ### ###",
            "lineageTag": "0c32eabb-dfae-40aa-a5d5-f0683e87c117"
          },
          {
            "name": "_Stocks_Ecoulement_MP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Stocks",
            "expression": [
              "",
              "- divide(CALCULATE (",
              "    [_Gene_Solde GL],",
              "    FILTER (",
              "        'PlanCompteAEF',",
              "        'PlanCompteAEF'[LiasseCode] IN { \"BT\", \"BL\"}",
              "    )",
              ")",
              "    , CALCULATE (",
              "        [_Gene_Solde GL],",
              "        'PlanCompteAEF'[LiasseCode] in { \"FS\",\"FU\",\"FV\",\"FT\"}",
              "    ),0)",
              "    * IF (",
              "        MAX ( 'KPI'[Exercice] ) = \"N\",",
              "        DATEDIFF (",
              "            MAX ( Parametrage[DateClotureN] ),",
              "            MAX ( Parametrage[DateOuvertureN] ),",
              "            DAY",
              "        ) + 1,",
              "        DATEDIFF (",
              "            MAX ( Parametrage[DateClotureN_1] ),",
              "            MAX ( Parametrage[DateOuvertureN_1] ),",
              "            DAY",
              "        ) + 1",
              "    ) "
            ],
            "lineageTag": "b2a3100e-5334-4fc1-b26f-08f80fe7e089"
          },
          {
            "name": "_Stocks_Ecoulement_PF",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Stocks",
            "expression": [
              "",
              "DIVIDE(CALCULATE (",
              "    [_Gene_Solde GL],",
              "    FILTER (",
              "        'PlanCompteAEF',",
              "        'PlanCompteAEF'[LiasseCode] in {\"BR\",\"BP\",\"BN\"}",
              "    )",
              ")",
              "    , CALCULATE (",
              "        [_Gene_Solde GL],",
              "        'PlanCompteAEF'[LiasseCode] in{ \"FC\",\"FF\",\"FI\"}",
              "    ),0)",
              "    * IF (",
              "        MAX ( 'KPI'[Exercice] ) = \"N\",",
              "        DATEDIFF (",
              "            MAX ( Parametrage[DateClotureN] ),",
              "            MAX ( Parametrage[DateOuvertureN] ),",
              "            DAY",
              "        ) + 1,",
              "        DATEDIFF (",
              "            MAX ( Parametrage[DateClotureN_1] ),",
              "            MAX ( Parametrage[DateOuvertureN_1] ),",
              "            DAY",
              "        ) + 1",
              "    ) "
            ],
            "lineageTag": "6f47648a-0964-4d06-8d9b-12519646f149"
          },
          {
            "name": "_Stocks_RepDépréP&L",
            "displayFolder": "Stocks",
            "expression": "CALCULATE ( [_Gene_Solde N], FILTER ( Compte, Compte[Racine5] = \"78173\" ) ) + 1 * 0",
            "formatString": "### ### ###",
            "lineageTag": "c9264a93-fe24-489f-b56f-c4c4307807ed"
          },
          {
            "name": "_Stocks_VarBrutBilan",
            "displayFolder": "Stocks",
            "expression": [
              "(",
              "    CALCULATE ( [_Gene_Solde N], 'PlanCompteAEF'[MarquageStocks] = \"Stocks bruts\" )",
              "        - CALCULATE ( [_Gene_Solde N-1], 'PlanCompteAEF'[MarquageStocks] = \"Stocks bruts\" )",
              ") + 1 * 0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "e457a372-9c7e-4f82-8f1f-4f5cfaa8b462"
          },
          {
            "name": "_Stocks_VarBrutP&L",
            "displayFolder": "Stocks",
            "expression": [
              "",
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[MarquageStocks]=\"Var stocks brut\" || PlanCompteAEF[LiasseCode]= \"FM\",",
              "    'KPI'[Exercice]=\"N\"",
              ")"
            ],
            "formatString": "### ### ###",
            "lineageTag": "88154f48-f7c9-4e3b-b489-8998a8a6791a"
          },
          {
            "name": "_Stocks_VarDépréBilan",
            "displayFolder": "Stocks",
            "expression": [
              "CALCULATE ( [_Gene_Solde GL], Compte[Racine2] = \"39\", 'KPI'[Exercice] = \"N\" )",
              "    - CALCULATE ( [_Gene_Solde GL], Compte[Racine2] = \"39\", 'KPI'[Exercice] = \"N-1\" ) + 1 * 0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "126954e0-6e72-4c04-bcc5-ebaafb8bdf51"
          },
          {
            "name": "_Gene_Nb Lignes",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT('KPI'[Compte])",
              "   ",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "57ebc3c3-1e86-4e69-b6a6-fec4f5a6283d"
          },
          {
            "name": "_Immo_VNC P&L",
            "expression": "CALCULATE ([_Gene_Solde N], Compte[Racine3] = \"675\" )+0*1",
            "formatString": "#,##0",
            "lineageTag": "f74ee121-fa91-411d-8c23-5c21772dca3b"
          },
          {
            "name": "_JE_Nb Ecritures N",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT('KPI'[EcritureNumero]),",
              "    'KPI'[Exercice]=\"N\")"
            ],
            "formatString": "0",
            "lineageTag": "7fa13119-c164-4a8f-a474-4f6cb1ad0a96"
          },
          {
            "name": "_JE_Nb EcrituresN-1",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT('KPI'[EcritureNumero]),",
              "    'KPI'[Exercice]=\"N-1\")"
            ],
            "formatString": "0",
            "lineageTag": "8107cb1e-8fae-4c26-8617-fcc690db0725"
          },
          {
            "name": "_JE_Nb Lignes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "COUNTROWS('KPI')",
            "lineageTag": "df267b5b-46ec-4f71-b39e-9aa38724d481"
          },
          {
            "name": "_KPI_Tx Marge Brute",
            "expression": [
              "",
              "DIVIDE (",
              "    CALCULATE([_Gene_Solde GL],'PlanCompteAEF'[MarquageMarge] = \"Marge brute\" ),",
              "    CALCULATE([_Gene_Solde GL],PlanCompteAEF[CategorieREX]=\"Chiffre d'affaires\"),",
              "    0",
              ")"
            ],
            "formatString": "#,##0.0 %",
            "lineageTag": "6a4e85a4-968a-47ef-afd7-c071a85a7028"
          },
          {
            "name": "_KPI_Tx REX/CA",
            "expression": [
              "DIVIDE(",
              "    CALCULATE([_Gene_Solde Inversé carte],'PlanCompteAEF'[MarquageREX] = \"REX\"),",
              "    CALCULATE(",
              "        [_Gene_Solde inv],",
              "        'PlanCompteAEF'[CategorieREX] = \"Chiffre d'affaires\"",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "#,##0.0 %",
            "lineageTag": "8527e03f-6430-4cf2-95f1-d7033063516a"
          },
          {
            "name": "_Let_Ecart",
            "expression": "[_Gene_Solde GL]-[_Let_Solde GL non let.]",
            "formatString": "#,##0",
            "lineageTag": "2c1a3a21-4856-463f-865c-e256d3d87bdb"
          },
          {
            "name": "_Let_Ecart abs",
            "expression": "abs([_Let_Ecart])",
            "formatString": "#,##0",
            "lineageTag": "49239600-a8c7-4f2c-8e9f-d6e45bd5b16b"
          },
          {
            "name": "_Let_Solde GL non let.",
            "expression": "CALCULATE([_Gene_Solde GL],isblank('KPI'[EcritureLet]))",
            "formatString": "#,##0",
            "lineageTag": "804f1476-b84c-4265-a527-eeb5eb8d7d45"
          },
          {
            "name": "_mesValeurTVAN",
            "expression": "MIN(SliderT1[Code])",
            "formatString": "### ### ###.##",
            "lineageTag": "1f0d60ed-31bf-459f-886b-3d37725c7203"
          },
          {
            "name": "_mesValeurTVAN-1",
            "expression": "MIN(SliderT2[Code])",
            "formatString": "### ### ###.##",
            "lineageTag": "d60f1bfb-f818-4a9f-8297-14b55c1129a5"
          },
          {
            "name": "_Personnel_Salaire Moyen N",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        CALCULATE(",
              "            [_Gene_Solde N],",
              "            PlanCompteAEF[LiasseCode]=\"FY\"),",
              "            [Selected value T3])+0"
            ],
            "lineageTag": "ac74369d-89c1-497d-badf-52402e5a30c3"
          },
          {
            "name": "_Personnel_Salaire Moyen N-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        CALCULATE(",
              "            [_Gene_Solde N-1],",
              "            PlanCompteAEF[LiasseCode]=\"FY\"),",
              "            [Selected value T4])+0"
            ],
            "lineageTag": "2dbef343-aaf0-4c52-acc7-5281296e7f5e"
          },
          {
            "name": "_SAP Stocks VB_ Ecart",
            "expression": "[_SAP Stocks VB_ Solde Bilan]-[_SAP Stocks VB_ Solde P&L]",
            "formatString": "#,##0",
            "lineageTag": "7b875283-049b-4318-a445-f17ae1fe1017"
          },
          {
            "name": "_SAP Stocks VB_ Solde Bilan",
            "expression": "CALCULATE([_Gene_Variation N/N-1],PlanCompteAEF[BilanNiv1]=\"Bilan\")",
            "formatString": "#,##0",
            "lineageTag": "803999b7-e17c-46dd-9407-e2aa120fcaaf"
          },
          {
            "name": "_SAP Stocks VB_ Solde P&L",
            "expression": "-CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\")",
            "formatString": "#,##0",
            "lineageTag": "8d950a92-4bd4-4d22-a39b-f05de45c6dcf"
          },
          {
            "name": "Calcul échéance +180 jours",
            "expression": [
              "VAR a =",
              "    SUMMARIZE ('KPI',",
              "                'KPI'[CompAuxLib],",
              "                'KPI'[DateComptable],",
              "                \"b\", [_Gene_Cloture_Date 2],",
              "                \"c\", datediff(max('KPI'[DateComptable]),[_Gene_Cloture_Date 2],DAY))",
              "",
              "VAR d = Calculate ([_Gene_Solde N],filter (a,[c]>=180))",
              "Return",
              "d"
            ],
            "formatString": "#,##0",
            "lineageTag": "67f52b84-b2ee-4e1a-9abf-235aae68d040"
          },
          {
            "name": "Calcul échéance 180 jours",
            "expression": [
              "VAR a =",
              "    SUMMARIZE ('KPI',",
              "                'KPI'[CompAuxLib],",
              "                'KPI'[DateComptable],",
              "                \"b\", [_Gene_Cloture_Date 2],",
              "                \"c\", datediff(max('KPI'[DateComptable]),[_Gene_Cloture_Date 2],DAY))",
              "",
              "VAR d = Calculate ([_Gene_Solde N],filter (a,and([c]<180,[c]>=90)))",
              "Return",
              "d"
            ],
            "formatString": "#,##0",
            "lineageTag": "2d407852-1096-4492-b81d-1b9336873ff9"
          },
          {
            "name": "Calcul échéance 30 jours",
            "expression": [
              "VAR a =",
              "    SUMMARIZE ('KPI',",
              "                'KPI'[CompAuxLib],",
              "                'KPI'[DateComptable],",
              "                \"b\", [_Gene_Cloture_Date 2],",
              "                \"c\", datediff(max('KPI'[DateComptable]),[_Gene_Cloture_Date 2],DAY))",
              "",
              "VAR d = Calculate ([_Gene_Solde N],filter (a,[c]<30))",
              "Return",
              "d"
            ],
            "formatString": "#,##0",
            "lineageTag": "278b20ef-fc9a-4b6f-b337-e967e437f205"
          },
          {
            "name": "Calcul échéance 60 jours",
            "expression": [
              "VAR a =",
              "    SUMMARIZE ('KPI',",
              "                'KPI'[CompAuxLib],",
              "                'KPI'[DateComptable],",
              "                \"b\", [_Gene_Cloture_Date 2],",
              "                \"c\", datediff(max('KPI'[DateComptable]),[_Gene_Cloture_Date 2],DAY))",
              "",
              "VAR d = Calculate ([_Gene_Solde N],filter (a,and([c]<60,[c]>=30)))",
              "Return",
              "d"
            ],
            "formatString": "#,##0",
            "lineageTag": "0769f98a-4e7a-4325-a9bd-fabce310ec65"
          },
          {
            "name": "Calcul échéance 90 jours",
            "expression": [
              "VAR a =",
              "    SUMMARIZE ('KPI',",
              "                'KPI'[CompAuxLib],",
              "                'KPI'[DateComptable],",
              "                \"b\", [_Gene_Cloture_Date 2],",
              "                \"c\", datediff(max('KPI'[DateComptable]),[_Gene_Cloture_Date 2],DAY))",
              "",
              "VAR d = Calculate ([_Gene_Solde N],filter (a,and([c]<90,[c]>=60)))",
              "Return",
              "d"
            ],
            "formatString": "#,##0",
            "lineageTag": "aa2b7252-48b6-41ae-95b2-f406b258c928"
          },
          {
            "name": "Comptes auxiliaires mouv",
            "expression": [
              "VAR a =",
              "    SUMMARIZE ('KPI',",
              "                'KPI'[CompAuxLib],",
              "                \"c\", abs(sum('KPI'[MTCredit]))+abs(sum('KPI'[MTDebit])))",
              "",
              "VAR d = Calculate (distinctcount('KPI'[CompAuxLib]),filter (a,[c]<>0))",
              "Return",
              "d"
            ],
            "formatString": "#,##0",
            "lineageTag": "25416cd1-2738-4c6f-85f3-b7efd3349914"
          },
          {
            "name": "Credit",
            "expression": [
              "",
              "CALCULATE ( SUM ( 'KPI'[MTCredit] ) )"
            ],
            "lineageTag": "26018837-4655-44af-9ebe-42eec9f44319"
          },
          {
            "name": "cumul",
            "expression": [
              "//if ( max ('DimTemps'[Dates]) in datesbetween('DimTemps'[Dates],max('Parametrage'[DateOuvertureN] ), max('Parametrage'[DateClotureN] )) , 1 , 2)",
              "",
              "//calculate ( [_Gene_Solde GL] ,  filter ( DimTemps[Dayofyear],(DimTemps[Dayofyear])>=[Nbr jour max N] && (DimTemps[Dayofyear]) <=[Nbr jour min N]))"
            ],
            "lineageTag": "873651c4-046f-41ca-84f9-39ee7abbd2e6"
          },
          {
            "name": "cumul 1",
            "expression": [
              "//if ( max ('DimTemps'[Dates]) in datesbetween('DimTemps'[Dates],max('Parametrage'[DateOuvertureN] ), max('Parametrage'[DateClotureN] )) , 1 , 2)",
              "",
              "//if ( isblank ( calculate ( [_Gene_Solde GL] ,  filter ( DimTemps[Dayofyear],DimTemps[Dayofyear]>=[Nbr jour max N] && DimTemps[Dayofyear] <=[Nbr jour min N])), ",
              "//blank(), CALCULATE (",
              "  //  [_Gene_Solde GL],",
              "    //FILTER (",
              "      //  ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[FiscalQuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear] ),",
              "        //DimTemps[Dates] <= MAX (DimTemps[Dates]) &&",
              "        //DimTemps[FiscalYear] = MAX ( DimTemps[FiscalYear] )))"
            ],
            "lineageTag": "1232fd13-c5be-45b2-90e9-0808abb39ee3"
          },
          {
            "name": "Debit",
            "expression": [
              "",
              "CALCULATE ( SUM ( 'KPI'[MTDebit] ) )"
            ],
            "lineageTag": "00de7042-b352-47cc-9349-7df89f48a355"
          },
          {
            "name": "Debit_N",
            "expression": [
              "",
              "IF ( ISBLANK ( [Debit] ), BLANK (), CALCULATE ( SUMX ( 'DimTemps', [Debit] ) ) )"
            ],
            "lineageTag": "b7d0810d-afdb-45c1-84d1-a802c9911cbf"
          },
          {
            "name": "Debit_N_1",
            "expression": [
              "",
              "VAR MinDates =",
              "    IF (",
              "        HASONEVALUE ( 'DimTemps'[Dates] ),",
              "        VALUES ( 'DimTemps'[Dates] ),",
              "        MIN ( 'DimTemps'[Dates] )",
              "    )",
              "VAR YYYY =",
              "    YEAR ( MinDates )",
              "VAR MaxDates =",
              "    IF (",
              "        HASONEVALUE ( 'DimTemps'[Dates] ),",
              "        VALUES ( 'DimTemps'[Dates] ),",
              "        CALCULATE (",
              "            MAX ( 'DimTemps'[Dates] ),",
              "            'DimTemps'[Dates] = YYYY,",
              "            'DimTemps'[FirstFiscalMonth] = 1",
              "        )",
              "    )",
              "RETURN",
              "    MaxDates"
            ],
            "lineageTag": "54087c38-b80c-4aff-b52d-1995dfc95988"
          },
          {
            "name": "Debit_N_1 R",
            "expression": [
              "",
              "VAR _MinDate =",
              "    CALCULATE ( MIN ( 'DimTemps'[Dates] ), VALUES ( 'DimTemps'[Dates] ) )",
              "VAR _MaxDate =",
              "    CALCULATE ( MAX ( 'DimTemps'[Dates] ), VALUES ( 'DimTemps'[Dates] ) )",
              "VAR _FirstDateLastYear =",
              "    DATE ( YEAR ( _MinDate ) - 1, MONTH ( _MinDate ), DAY ( _MinDate ) )",
              "VAR _LastDateLastYear =",
              "    DATE ( YEAR ( _MaxDate ) - 1, MONTH ( _MaxDate ), DAY ( _MaxDate ) )",
              "RETURN",
              "    _MaxDate",
              "--CALCULATE([Debit], FILTER(DimTemps, Dimtemps[Dates] <= _LastDateLastYear && Dimtemps[Dates] >= _FirstDateLastYear ))"
            ],
            "lineageTag": "7a9a5140-1c0b-4985-93da-0cc5576828e6"
          },
          {
            "name": "Debit_Trash",
            "expression": [
              "",
              "VAR MinDates =",
              "    IF (",
              "        HASONEVALUE ( 'DimTemps'[Dates] ),",
              "        VALUES ( 'DimTemps'[Dates] ),",
              "        MIN ( 'DimTemps'[Dates] )",
              "    )",
              "VAR YYYY =",
              "    YEAR ( MinDates )",
              "VAR MM =",
              "    MONTH ( MinDates )",
              "VAR Q =",
              "    QUARTER ( MinDates )",
              "VAR CountS =",
              "    CALCULATE ( COUNTA ( 'DimTemps'[Dates] ) )",
              "VAR MaxDates =",
              "    IF (",
              "        HASONEVALUE ( 'DimTemps'[Dates] ),",
              "        VALUES ( 'DimTemps'[Dates] ),",
              "        CALCULATE (",
              "            MAX ( 'DimTemps'[Dates] ),",
              "            YEAR ( 'DimTemps'[Dates] ) = YYYY,",
              "            MONTH ( 'DimTemps'[Dates] ) = MM,",
              "            ALL ( 'DimTemps' )",
              "        )",
              "    )",
              "RETURN",
              "    CountS"
            ],
            "lineageTag": "b2f9c7b5-8546-44f4-9c57-770aabdb6e22"
          },
          {
            "name": "Gene_ Couleur Transparent",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "\"#FFFFFF00\"",
            "lineageTag": "4a075812-a530-4637-b371-45b667982140"
          },
          {
            "name": "Lettrage",
            "expression": "if (isblank(max('KPI'[EcritureLet])),\"Non lettrées\",\"Lettrées\")",
            "formatString": "#,##0",
            "lineageTag": "cf14a385-b5af-4b57-a313-94525edeaee8"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(OR(ISBLANK(MAX(PlanCompteAEF[LiasseCode])),ISBLANK(MAX(PlanCompteAEF[DetailNiv3]))),",
              "[_CP_ResultatNet],",
              "CALCULATE(CALCULATE (",
              "    SUM ( 'KPI'[MTCredit] ),",
              "    ParamAN[AN - O/N] = \"Non\"",
              ")))+0",
              ""
            ],
            "lineageTag": "e883abdd-fccc-4241-b361-baf76cabcab3"
          },
          {
            "name": "SAP_ Ecart acceptable % PM",
            "expression": "DIVIDE([Selected value T5] ,[SAP_PM],0)",
            "formatString": "#,##0 %",
            "lineageTag": "4f320771-d151-4fda-bb7f-b5c618a6ab6d"
          },
          {
            "name": "SAP_Nbr de jours sélectionné N",
            "expression": [
              "VAR AX =[Nbr de jours N] - [Selected value T9]+1",
              "RETURN",
              "IF( [Selected value T9]=1, \"\",\"des \"",
              "& AX",
              "&\" derniers jours\")",
              "",
              "",
              "",
              "--If (MOD('DimTemps'[FiscalYear],4) = 0,366 ,365 )"
            ],
            "lineageTag": "0b67a8c8-df18-423a-a5a2-2ae781c663e4"
          },
          {
            "name": "SAP_Nbr de jours sélectionné N-1",
            "expression": [
              "VAR AX =[Nbr de jours N-1] - [Selected value T8]+1",
              "RETURN",
              "IF( [Selected value T8]=1, \"\",\"des \"",
              "& AX",
              "&\" derniers jours\")",
              "",
              "",
              "",
              "--If (MOD('DimTemps'[FiscalYear],4) = 0,366 ,365 )"
            ],
            "lineageTag": "29a423f1-9ec1-4ac8-ab55-4d0433cd5349"
          },
          {
            "name": "SAP_PM",
            "expression": "MAX(Parametrage[PM])",
            "formatString": "#,##0",
            "lineageTag": "ba9f33d0-66d0-4236-be0a-ecd87053eee9"
          },
          {
            "name": "SAP_quick wins % Variation",
            "expression": "CALCULATE([_Gene_VariationN/N-1%],ALL('DimTemps'[DayOfYear]))",
            "formatString": "#,##0 %",
            "lineageTag": "e121857d-f628-48b3-87f7-ffdbbedb8ee5"
          },
          {
            "name": "SAP_quick wins solde N",
            "expression": "CALCULATE([_Gene_Solde N],ALL('DimTemps'[DayOfYear]))",
            "formatString": "#,##0",
            "lineageTag": "ecd9abe6-6f51-40c5-9a65-e16411fc81ce"
          },
          {
            "name": "SAP_quick wins solde N-1",
            "expression": "CALCULATE([_Gene_Solde N-1],ALL('DimTemps'[DayOfYear]))",
            "formatString": "#,##0",
            "lineageTag": "30acce04-fe4b-4872-92b5-84d2465a2c8f"
          },
          {
            "name": "SAP_quick wins Variation N/N-1",
            "expression": "CALCULATE([_Gene_Variation N/N-1],ALL('DimTemps'[DayOfYear]))",
            "formatString": "### ### ###",
            "lineageTag": "3fb11a1b-64e2-46d3-87e0-51cb5c0621ae"
          },
          {
            "name": "SAP_Solde N ignore filter",
            "expression": "CALCULATE([_Gene_Solde GL],'KPI'[Exercice]=\"N\",ALL('DimTemps'[DayOfYear Calendar]))",
            "formatString": "#,##0",
            "lineageTag": "f4fa040e-24ab-4050-ab75-d52b5dd5c731"
          },
          {
            "name": "SAP_Vide",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "BLANK()",
            "lineageTag": "81c38da4-0355-49b3-a1ad-aebbda027201"
          },
          {
            "name": "SAP_Vide 1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "\"___________\"",
            "lineageTag": "519ed16d-f893-4286-92fe-f842b8b73c51"
          },
          {
            "name": "SAP_Zero",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "\".\"",
            "lineageTag": "e60a77b6-b5f1-4b14-8db9-942bafd546a7"
          },
          {
            "name": "SAP1_Charges de personnel attendues",
            "expression": [
              "if (ISBLANK([_Gene_Solde N-1]),BLANK() ,",
              "//Effectif moyen N",
              "    [Selected value T3]",
              "//Augmetation de salaire",
              "    *(1+[Selected value T1]/100",
              "//Nbr de jours concernés par l'augmentation",
              "    *[Selected value T2]/365)",
              "//Salaires N-1 hors éléments exceptionnels N-1",
              "    *Divide (([_Gene_Solde N-1]-[Selected value T6]),",
              "//Effectif moyen N-1",
              "    [Selected value T4],0)",
              "//Elements except. N",
              "    +[Selected value T7])"
            ],
            "formatString": "#,##0",
            "lineageTag": "f619340d-73ce-4203-9627-81a67511dcfb"
          },
          {
            "name": "SAP1_Charges de personnel comptabilisées hors éléments except.",
            "expression": [
              "if (ISBLANK([_Gene_Solde N-1]),BLANK() ,",
              "[_Gene_Solde N]-[Selected value T7])"
            ],
            "formatString": "### ### ###",
            "lineageTag": "44502b2f-ff48-4ec1-a449-9ec9d0b25a63"
          },
          {
            "name": "SAP1_Charges de personnel N",
            "expression": [
              "",
              "",
              "[_Gene_Solde N]+0",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "1fc135b5-dabf-4869-adc7-5b548ac2040c"
          },
          {
            "name": "SAP1_Charges de personnel N normalisé",
            "expression": [
              "Divide ([_Gene_Solde N]-[Selected value T7],0)",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "629e35cb-3629-49d6-8a32-38f601bf4066"
          },
          {
            "name": "SAP1_Charges de personnel N-1",
            "expression": [
              "",
              "",
              "[_Gene_Solde N-1]+0",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "c928d7d2-add1-4e54-8a8f-47b0fa2e5cde"
          },
          {
            "name": "SAP1_Charges de personnel N-1 normalisé",
            "expression": [
              "Divide ([_Gene_Solde N-1]-[Selected value T6],0)",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "26faf36e-7c19-49e5-9361-2f3647e0ae53"
          },
          {
            "name": "SAP1_Conclusion",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF (",
              "    ABS ( [SAP1_Ecart]) < [Selected value T5],",
              "    \"Inférieur à l'écart acceptable\",",
              "    \"Supérieur à l'écart acceptable\"",
              ")"
            ],
            "lineageTag": "d53adcd3-953e-4f6d-830a-3d15276f5d44"
          },
          {
            "name": "SAP1_Ecart",
            "expression": [
              "if (ISBLANK([_Gene_Solde N-1]),BLANK() ,",
              "",
              "([_Gene_Solde N]-[SAP1_Charges de personnel attendues])+1*0)"
            ],
            "formatString": "#,##0",
            "lineageTag": "0a86bf96-0244-4905-aa1d-b9f5c3ccc909"
          },
          {
            "name": "SAP1_Ecart num",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF([SAP1_Conclusion]=\"Inférieur à l'écart acceptable\",1,0)",
            "lineageTag": "039e6d14-73c4-44c8-aa9f-bcecb13491a8"
          },
          {
            "name": "SAP1_Salaire moyen attendu N",
            "expression": [
              "DIVIDE([SAP1_Charges de personnel attendues]-[Selected value T7],[Selected value T3],0)+0.01",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "d836aecc-5680-4941-82e7-39ca10cddc47"
          },
          {
            "name": "SAP1_Salaire moyen comptabilisé N",
            "expression": "DIVIDE([SAP1_Charges de personnel comptabilisées hors éléments except.],[Selected value T3],0)",
            "formatString": "#,##0",
            "lineageTag": "1c543d50-c04a-42b9-8ada-af74f147ea20"
          },
          {
            "name": "SAP1_Salaire moyen N-1",
            "expression": [
              "if (ISBLANK([_Gene_Solde N-1]),BLANK() ,",
              "DIVIDE([_Gene_Solde N-1]-[Selected value T6],[Selected value T4],0))"
            ],
            "formatString": "#,##0",
            "lineageTag": "774b691e-d312-4a96-bb0f-23c94ed93349"
          },
          {
            "name": "SAP10_Dividendes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Selected value T4]*10^6+[Selected value T6]*10^3+[Selected value T7]+[Selected value T3]*10^(-2)",
            "lineageTag": "68bd9382-87ed-42b5-a1b2-6a9e7774d479"
          },
          {
            "name": "SAP10_Solde BG N ouverture",
            "expression": "CALCULATE([_Cadrage_Solde BG],'KPI'[Exercice]=\"N-1\")",
            "formatString": "#,##0",
            "lineageTag": "3278d8a9-899f-4338-b8ec-b1ecfed5b210"
          },
          {
            "name": "SAP11_Charges comptabilisées",
            "expression": "CALCULATE([_Gene_Solde N], Compte[Racine1]=\"6\")",
            "formatString": "### ### ###",
            "lineageTag": "24196b5b-bf3c-4460-8597-c005c2598e03"
          },
          {
            "name": "SAP11_Charges d'intérêts attendue",
            "expression": "[SAP11_Montant restant à l'ouverture]*[Selected value T1]*[Selected value T6]/365/100",
            "formatString": "#,##0",
            "lineageTag": "f0c98775-4316-48de-946c-3e8df07fc33f"
          },
          {
            "name": "SAP11_Ecart",
            "expression": "[SAP11_Charges comptabilisées]-[SAP11_Charges d'intérêts attendue]",
            "formatString": "#,##0",
            "lineageTag": "18d00d12-2cb1-4292-ac3f-24731c110463"
          },
          {
            "name": "SAP11_Montant restant à l'ouverture",
            "expression": "-CALCULATE([_Gene_Solde N-1], Compte[Racine2]=\"16\")",
            "formatString": "### ### ###",
            "lineageTag": "617795db-49f0-4195-8d5b-889968b87790"
          },
          {
            "name": "SAP2_CS attendues",
            "expression": "[SAP2_Tx CS attendu]*[SAP2_Salaires N retraités]",
            "formatString": "#,##0",
            "lineageTag": "c5930bf3-15f9-45bb-9cce-f0f9d172dfec"
          },
          {
            "name": "SAP2_CS N",
            "expression": "CALCULATE ([_Gene_Solde N],Compte[SapChargeSociales] in {\"Charges sociales\"}) ",
            "formatString": "### ### ###",
            "lineageTag": "7b366e73-a691-404e-929a-14f7d199e419"
          },
          {
            "name": "SAP2_CS N-1",
            "expression": "CALCULATE ([_Gene_Solde N-1],Compte[SapChargeSociales] in {\"Charges sociales\"}) ",
            "formatString": "### ### ###",
            "lineageTag": "7dc2b8bc-d97c-44db-ba22-06126b7ebb3c"
          },
          {
            "name": "SAP2_Description comptes agrégés",
            "expression": [
              "\"Pour la partie bilantielle, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes\"",
              "& switch( true(),",
              "max('Choix du test_frs'[Code])=1, \" #409 pour couvrir les avoirs à recevoir.\",",
              "max('Choix du test_frs'[Code])=2, \" #486 pour couvrir les charges constatées d'avance.\",",
              "max('Choix du test_frs'[Code])=3, \" #408 pour couvrir les factures non parvenues.\",",
              "max('Choix du test_frs'[Code])=5, \" #419 pour couvrir les avoirs à établir.\",",
              "max('Choix du test_frs'[Code])=6, \" #487 pour couvrir les produits constatés d'avance.\",",
              "max('Choix du test_frs'[Code])=7, \" #4181 pour couvrir les factures à établir.\",",
              "",
              " \"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "fdc8ccc6-7cd1-42f1-99cb-c45901c0b459"
          },
          {
            "name": "SAP2_Description de la procédure",
            "expression": [
              "switch( true(),",
              "max('Choix du test_frs'[Code])=1, \"- Analyse prédictive des avoirs à recevoir sur la base du total des achats ;",
              "- Le niveau d'AAR attendu se fonde sur : le total des achats de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments exceptionnels saisis ;",
              "- La SAP est réalisée de manière agrégée.\",",
              "max('Choix du test_frs'[Code])=2, \"- Analyse prédictive des charges constatées d'avance sur la base du total des achats ;",
              "- Le niveau de CCA attendu se fonde sur : le total des achats de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments exceptionnels saisis ;",
              "- La SAP est réalisée de manière agrégée.\",",
              "max('Choix du test_frs'[Code])=3, \"- Analyse prédictive des factures non parvenues sur la base du total des achats ;",
              "- Le niveau de FNP attendu se fonde sur : le total des achats de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments exceptionnels saisis ;",
              "- La SAP est réalisée de manière agrégée.\",",
              "max('Choix du test_frs'[Code])=5, \"- Analyse prédictive des avoirs à établir sur la base du total des ventes ;",
              "- Le niveau d'AAE attendu se fonde sur : le total des ventes de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments non récurrents saisis ;",
              "- La SAP est réalisée de manière agrégée.\",",
              "max('Choix du test_frs'[Code])=6, \"- Analyse prédictive des produits constatés d'avance sur la base du total des ventes ;",
              "- Le niveau de PCA attendu se fonde sur : le total des ventes de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments non récurrents saisis ;",
              "- La SAP est réalisée de manière agrégée.\",",
              "max('Choix du test_frs'[Code])=7, \"- Analyse prédictive des factures à établir sur la base du total des ventes ;",
              "- Le niveau de FAE attendu se fonde sur : le total des achats de l'exercice, ajusté ou non sur une période donnée ainsi que les éventuels éléments non récurrents saisis ;",
              "- La SAP est réalisée de manière agrégée.\",",
              " \"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "c34b1888-9575-4a1a-a35b-65bc77b2c854"
          },
          {
            "name": "SAP2_Ecart",
            "expression": "[SAP2_CS N]-[SAP2_CS attendues]",
            "formatString": "#,##0",
            "lineageTag": "66b21c8e-da36-48c1-8ba5-d2bb65455029"
          },
          {
            "name": "SAP2_Ecart num",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF([SAP2_Résultat SAP]=\"Inférieur à l'écart acceptable\",1,0)",
            "lineageTag": "b327827e-f630-465f-b3f6-219b51784aba"
          },
          {
            "name": "SAP2_Résultat SAP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ABS([SAP2_Ecart])<=[Selected value T5],\"Inférieur à l'écart acceptable\",\"Supérieur à l'écart acceptable\")",
            "lineageTag": "d03878be-e087-4184-972e-ac95d5974951"
          },
          {
            "name": "SAP2_Salaires N",
            "expression": "CALCULATE([_Gene_Solde N],Compte[SapChargeSociales]=\"Salaires et traitements\")",
            "formatString": "#,##0",
            "lineageTag": "878f42ab-2792-4b28-9669-40af40547408"
          },
          {
            "name": "SAP2_Salaires N retraités",
            "expression": "[SAP2_Salaires N]- [Selected value T7]",
            "formatString": "#,##0",
            "lineageTag": "d5f30990-7499-4679-8014-2cd581e8ef01"
          },
          {
            "name": "SAP2_Salaires N-1",
            "expression": "CALCULATE([_Gene_Solde N-1],Compte[SapChargeSociales]=\"Salaires et traitements\")",
            "formatString": "#,##0",
            "lineageTag": "98e7fae5-1bca-4262-89ad-34c94f3acba0"
          },
          {
            "name": "SAP2_Salaires N-1 retraités",
            "expression": "[SAP2_Salaires N-1]- [Selected value T6]",
            "formatString": "### ### ###",
            "lineageTag": "a44ba8e2-a461-4f0a-8f53-df3b55975d2c"
          },
          {
            "name": "SAP2_Tx charges N-1",
            "expression": "DIVIDE([SAP2_CS N-1],[SAP2_Salaires N-1 retraités],0)",
            "formatString": "#,##0 %",
            "lineageTag": "2a6c8e87-6959-4a11-a507-f848e787eb2e"
          },
          {
            "name": "SAP2_Tx CS attendu",
            "expression": "[SAP2_Tx charges N-1]+[Selected value T1 %]",
            "formatString": "#,##0 %",
            "lineageTag": "387a70cb-5492-4677-b272-c06fd3fd8c29"
          },
          {
            "name": "SAP3_Charges à payer attendues",
            "expression": "[SAP3_Charges à payer N-1 retraitées]-[Selected value T7]",
            "formatString": "#,##0",
            "lineageTag": "fbbe4ffc-4f68-4f4a-a7b1-4470f72dc7b7"
          },
          {
            "name": "SAP3_Charges à payer N-1 retraitées",
            "expression": "[_Gene_Solde N-1]+[Selected value T6]",
            "formatString": "#,##0",
            "lineageTag": "9e5e9f08-3b20-48fd-856a-d00159cc4780"
          },
          {
            "name": "SAP3_Ecart",
            "expression": "[_Gene_Solde N]-[SAP3_Charges à payer attendues]",
            "formatString": "#,##0",
            "lineageTag": "de7b9630-a1f1-4140-ae11-6f5488d1abf5"
          },
          {
            "name": "SAP3_Ecart num",
            "expression": "IF([SAP3_Résultat SAP]=\"Inférieur à l'écart acceptable\",1,0)",
            "formatString": "0",
            "lineageTag": "59a3c7e5-9e57-4800-a79e-ed35fc121c8b"
          },
          {
            "name": "SAP3_Résultat SAP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ABS([SAP3_Ecart])<=[Selected value T5],\"Inférieur à l'écart acceptable\",\"Supérieur à l'écart acceptable\")",
            "lineageTag": "a41c487c-e78a-468c-bf8e-b13e87f0d339"
          },
          {
            "name": "SAP4_Bilan inv N",
            "expression": [
              "",
              "-CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"Bilan\",",
              "    'KPI'[Exercice]=\"N\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "608e639f-294f-4253-8462-7efd71a31045"
          },
          {
            "name": "SAP4_Bilan inv N-1",
            "expression": [
              "",
              "-CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"Bilan\",",
              "    'KPI'[Exercice]=\"N-1\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "749bf24d-65e7-46eb-8893-12b712b28bbc"
          },
          {
            "name": "SAP4_Bilan pour DRM inv N",
            "expression": [
              "",
              "-CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"Bilan\",",
              "    'KPI'[Exercice]=\"N\",",
              "    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))",
              "- [Selected value T7]"
            ],
            "formatString": "#,##0",
            "lineageTag": "8f5f5c6a-177c-4816-8e09-81c53e7120f1"
          },
          {
            "name": "SAP4_Bilan pour DRM inv N-1",
            "expression": [
              "",
              "-CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"Bilan\",",
              "    'KPI'[Exercice]=\"N-1\",",
              "    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))",
              "- [Selected value T6]"
            ],
            "formatString": "#,##0",
            "lineageTag": "e8970c6e-457f-42f0-90aa-9d8d0851d7e8"
          },
          {
            "name": "SAP4_Bilan pour DRM N",
            "expression": [
              "",
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"Bilan\",",
              "    'KPI'[Exercice]=\"N\",",
              "    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))",
              "- [Selected value T7]"
            ],
            "formatString": "#,##0",
            "lineageTag": "61b3973d-a69b-4d8c-8572-3eef4f457524"
          },
          {
            "name": "SAP4_Bilan pour DRM N-1",
            "expression": [
              "",
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"Bilan\",",
              "    'KPI'[Exercice]=\"N-1\",",
              "    ALL('DimTemps'[DayOfYear],'DimTemps'[Day of year inv]))",
              "- [Selected value T6]"
            ],
            "formatString": "#,##0",
            "lineageTag": "a4301555-0990-4df1-a3d8-cd2b748eb4d9"
          },
          {
            "name": "SAP4_Chiffre d'affaires HT N-1",
            "expression": "(-CALCULATE([_Gene_Solde N-1], Compte[SapDrmClients]=\"Chiffre d'affaires\"))",
            "formatString": "### ### ###.##",
            "lineageTag": "7431c0b0-0dae-463d-88e6-4a1497950bf3"
          },
          {
            "name": "SAP4_Chiffre d'affaires TTC attendu N",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(-CALCULATE([_Gene_Solde N-1], Compte[SapDrmClients]=\"Chiffre d'affaires\")-[Selected value T6])*([Selected value T2]/100+1)*([Selected value T3]/100+1)",
            "lineageTag": "b067333f-aad0-4ccf-9c37-a6f0b89410a7"
          },
          {
            "name": "SAP4_Chiffre d'affaires TTC N",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(-CALCULATE([_Gene_Solde N], Compte[SapDrmClients]=\"Chiffre d'affaires\")-[Selected value T7])*([Selected value T1]/100+1)",
            "lineageTag": "3ee6e361-c0cc-45d0-b864-92000629644c"
          },
          {
            "name": "SAP4_Chiffre d'affaires TTC N-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(-CALCULATE([_Gene_Solde N-1], Compte[SapDrmClients]=\"Chiffre d'affaires\")-[Selected value T6])*([Selected value T1]/100+1)",
            "lineageTag": "a65cb0c7-e56d-4bbd-b67d-f494c0e3f378"
          },
          {
            "name": "SAP4_Créances N",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([_Gene_Solde N],Compte[SapDrmClients]=\"Créances clients\")",
            "lineageTag": "4a164315-9f14-4689-8d76-dad4719ca917"
          },
          {
            "name": "SAP4_Créances N-1",
            "expression": "CALCULATE([_Gene_Solde N-1],Compte[SapDrmClients]=\"Créances clients\")",
            "formatString": "### ### ###.##",
            "lineageTag": "be047abe-834f-4094-b386-afd4e373a887"
          },
          {
            "name": "SAP4_DRM attendu N",
            "expression": "[SAP4_Créances N-1]/[SAP4_Chiffre d'affaires TTC attendu N]*[SAP4_Nb de jours N]+0",
            "lineageTag": "ab4a8905-9e6f-476c-8af7-7e267aa8d28c"
          },
          {
            "name": "SAP4_DRM client N",
            "expression": [
              "VAR MAXI = [Nbr jour max N]",
              "VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1",
              "VAR MAXIFY = [Nbr jour max full year N]",
              "VAR a =",
              "    SUMMARIZE (",
              "        FILTER (",
              "            ALL ( 'DimTemps'[Day of year inv] ),",
              "            [SAP4_P&L cumulé inv N] > [SAP4_Bilan pour DRM N]",
              "        ),",
              "        \"minv\", MIN ( 'DimTemps'[Day of year inv] )",
              "    ) /* , \"inv\",related(DimTemps[Day of year inv]))*/",
              "VAR b =",
              "    MINX ( a, [minv] ) + 0",
              "VAR DRMinv = MAXIFY - b + 1",
              "",
              "VAR bilan = [SAP4_Bilan pour DRM N]",
              "VAR PL = calculate ( [_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\")",
              "",
              "",
              "RETURN",
              "",
              "if ( bilan = 0 , 0,  ",
              "  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )",
              "  )"
            ],
            "formatString": "#,##0",
            "lineageTag": "89ddfcc5-6d14-4a1b-b2d2-ff3899d16190"
          },
          {
            "name": "SAP4_DRM client N 1",
            "expression": [
              "VAR MAXI = [Nbr jour max N]",
              "VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1",
              "VAR MAXIFY = [Nbr jour max full year N]",
              "VAR a =",
              "    SUMMARIZE (",
              "        FILTER (",
              "            ALL ( 'DimTemps'[Day of year inv] ),",
              "            [SAP4_P&L cumulé inv N] > [SAP4_Bilan pour DRM N]",
              "        ),",
              "        \"minv\", MIN ( 'DimTemps'[Day of year inv] )",
              "    ) /* , \"inv\",related(DimTemps[Day of year inv]))*/",
              "VAR b =",
              "    MINX ( a, [minv] ) + 0",
              "VAR DRMinv = MAXIFY - b + 1",
              "",
              "VAR bilan = [SAP4_Bilan pour DRM N]",
              "VAR PL = calculate ( [_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\")",
              "",
              "",
              "RETURN",
              "",
              "if ( bilan = 0 , 0,  ",
              "  IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )",
              "  )"
            ],
            "formatString": "#,##0",
            "lineageTag": "8c84a273-a49d-41f5-a6d5-e636a37e9c2f"
          },
          {
            "name": "SAP4_DRM client N-1",
            "expression": [
              "VAR MAXI = [Nbr jour max N-1]",
              "VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1",
              "VAR MAXIFY = [Nbr jour max full year N-1]",
              "VAR a =",
              "    SUMMARIZE (",
              "        FILTER (",
              "            ALL ( 'DimTemps'[Day of year inv] ),",
              "            [SAP4_P&L cumulé inv N-1] > [SAP4_Bilan pour DRM N-1]",
              "        ),",
              "        \"minv\", MIN ( 'DimTemps'[Day of year inv] )",
              "    ) /* , \"inv\",related(DimTemps[Day of year inv]))*/",
              "VAR b =",
              "    MINX ( a, [minv] ) + 0",
              "VAR DRMinv = MAXIFY - b + 1",
              "",
              "VAR bilan = [SAP4_Bilan pour DRM N-1]",
              "VAR PL = CALCULATE ( [_Gene_Solde N-1], PlanCompteAEF[BilanNiv1] = \"P&L\" )",
              "",
              "RETURN",
              "",
              "if ( bilan = 0 , 0,",
              "    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )",
              "    )"
            ],
            "formatString": "#,##0",
            "lineageTag": "3078e8eb-664a-4a04-9553-fb803ddbcd33"
          },
          {
            "name": "SAP4_DRM comptabilisé N",
            "expression": "DIVIDE([SAP4_Créances N],[SAP4_Chiffre d'affaires TTC N],0)*[SAP4_Nb de jours N-1]+0",
            "formatString": "### ### ###.##",
            "lineageTag": "cfdaf8f9-55eb-4534-97b7-dc52f02325e6"
          },
          {
            "name": "SAP4_DRM FRS N",
            "expression": [
              "",
              "VAR MAXI = [Nbr jour max N]",
              "VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1",
              "VAR MAXIFY = [Nbr jour max full year N]",
              "var a = SUMMARIZE(Filter( all('DimTemps'[Day of year inv]),[SAP4_P&L cumulé N]>[SAP4_Bilan pour DRM inv N]),\"minv\",min('DimTemps'[Day of year inv]) ) /* , \"inv\",related(DimTemps[Day of year inv]))*/",
              "VAR b =",
              "    MINX ( a, [minv] ) + 0",
              "VAR DRMinv = MAXIFY - b + 1",
              "",
              "VAR bilan = [SAP4_Bilan pour DRM N]",
              "VAR PL = calculate ( [_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\")",
              "",
              "",
              "RETURN",
              "if ( bilan = 0 , 0,",
              "    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )",
              "    )"
            ],
            "formatString": "#,##0",
            "lineageTag": "5458e36a-357c-4d1c-bf7a-702b210f104c"
          },
          {
            "name": "SAP4_DRM FRS N-1",
            "expression": [
              "VAR MAXI = [Nbr jour max N-1]",
              "VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1",
              "VAR MAXIFY = [Nbr jour max full year N-1]",
              "",
              "VAR a =",
              "    SUMMARIZE (",
              "        FILTER (",
              "            ALL ( 'DimTemps'[Day of year inv] ),",
              "            [SAP4_P&L cumulé N-1] > [SAP4_Bilan pour DRM inv N-1]",
              "        ),",
              "        \"minv\", MIN ( 'DimTemps'[Day of year inv] )",
              "    )",
              "VAR b =",
              "   MINX (",
              "        a,",
              "        [minv]",
              "    ) + 0",
              "VAR DRMinv = MAXIFY - b + 1",
              "",
              "VAR bilan = [SAP4_Bilan pour DRM N-1]",
              "VAR PL = CALCULATE ( [_Gene_Solde N-1], PlanCompteAEF[BilanNiv1] = \"P&L\" )",
              "",
              "RETURN",
              "",
              "if ( bilan = 0 , 0,",
              "    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )",
              ")",
              "",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "e85c9df8-9b21-4ea9-8531-f0e7b0ddc6fd"
          },
          {
            "name": "SAP4_DRM N-1",
            "expression": [
              "DIVIDE (",
              "    [SAP4_Créances N-1],",
              "    [SAP4_Chiffre d'affaires TTC N-1],",
              "    0",
              ") * [SAP4_Nb de jours N-1] + 0"
            ],
            "formatString": "### ### ###",
            "lineageTag": "6487cc1f-cee1-4004-8f3e-4bf2174663d5"
          },
          {
            "name": "SAP4_DRM Résultat SAP client",
            "expression": "IF(ABS([SAP4_écart DRM client])>=ABS([SAP4_Ecart accept. en jours]),\"> à l'écart acceptable\",\"< à l'écart acceptable\")",
            "lineageTag": "a32b02cc-ebad-473e-a325-e6f0a3bde1d4"
          },
          {
            "name": "SAP4_DRM Résultat SAP frs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ABS([SAP4_écart DRM frs])>=ABS([SAP4_Ecart accept. en jours]),\"> à l'écart acceptable\",\"< à l'écart acceptable\")",
            "lineageTag": "095aa3b1-77b8-47e5-97e0-cc93df38fbc4"
          },
          {
            "name": "SAP4_DRM Résultat SAP MP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ABS([SAP4_écart DRS MP])>=ABS([SAP4_Ecart accept. en jours]),\"> à l'écart acceptable\",\"< à l'écart acceptable\")",
            "lineageTag": "1d68bacb-a663-4203-9a6e-9880b6dbcee2"
          },
          {
            "name": "SAP4_DRS MP N",
            "expression": [
              "",
              "VAR MAXI = [Nbr jour max N]",
              "VAR MINI = [Nbr jour max N] - [Nbr de jours N] + 1",
              "VAR MAXIFY = [Nbr jour max full year N]",
              "var a = SUMMARIZE(Filter( all('DimTemps'[Day of year inv]),[SAP4_P&L cumulé N]>[SAP4_Bilan pour DRM N]),\"minv\",min('DimTemps'[Day of year inv]) ) /* , \"inv\",related(DimTemps[Day of year inv]))*/",
              "",
              "VAR b =",
              "    MINX ( a, [minv] ) + 0",
              "VAR DRMinv = MAXIFY - b + 1",
              "",
              "VAR bilan = [SAP4_Bilan pour DRM N]",
              "VAR PL = calculate ( [_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\")",
              "",
              "RETURN",
              "",
              "if ( bilan = 0 , 0,",
              "    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "65dad49f-d703-4436-8245-e8deb2790b8d"
          },
          {
            "name": "SAP4_DRS MP N-1",
            "expression": [
              "VAR MAXI = [Nbr jour max N-1]",
              "VAR MINI = [Nbr jour max N-1] - [Nbr de jours N-1] + 1",
              "VAR MAXIFY = [Nbr jour max full year N-1]",
              "VAR a =",
              "    SUMMARIZE (",
              "        FILTER (",
              "            ALL ( 'DimTemps'[Day of year inv] ),",
              "            [SAP4_P&L cumulé N-1] > [SAP4_Bilan pour DRM N-1]",
              "        ),",
              "        \"minv\", MIN ( 'DimTemps'[Day of year inv] )",
              "    ) /* , \"inv\",related(DimTemps[Day of year inv]))*/",
              "VAR b = MINX ( a, [minv] ) + 0",
              "VAR DRMinv = MAXIFY - b + 1",
              "",
              "VAR bilan = [SAP4_Bilan pour DRM N-1]",
              "VAR PL = CALCULATE ( [_Gene_Solde N-1], PlanCompteAEF[BilanNiv1] = \"P&L\" )",
              "",
              "RETURN",
              "if ( bilan = 0 , 0,",
              "    IF ( DRMinv <= MAXI && DRMinv >= MINI, MAXI - DRMinv + 1, BLANK () )",
              "    )"
            ],
            "formatString": "#,##0",
            "lineageTag": "4405e3e9-6111-4f50-b5f3-752cf81482ce"
          },
          {
            "name": "SAP4_Ecart",
            "expression": "[SAP4_DRM comptabilisé N]-[SAP4_DRM attendu N]",
            "formatString": "#,##0",
            "lineageTag": "3ef506e3-27e8-4d97-93b6-669b3be4dbf3"
          },
          {
            "name": "SAP4_Ecart accept. en jours",
            "expression": [
              "ABS(divide([Selected value T5],",
              "    DIVIDE(CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\"),DATEDIFF(MAX(Parametrage[DateClotureN]),MAX(Parametrage[DateOuvertureN]),DAY)+1,0),0)",
              "    )",
              "    *(1+[Selected value T1]/100)+0"
            ],
            "formatString": "#,##0.0",
            "lineageTag": "d1387182-b324-4942-a98a-3a4d5b7cfc3a"
          },
          {
            "name": "SAP4_écart DRM client",
            "expression": "[SAP4_DRM client N]-[SAP4_DRM client N-1]+0",
            "formatString": "#,##0",
            "lineageTag": "8572b5bd-0739-46b6-8ba4-e8f481051e46"
          },
          {
            "name": "SAP4_écart DRM frs",
            "expression": "[SAP4_DRM FRS N]-[SAP4_DRM FRS N-1]+0",
            "formatString": "#,##0",
            "lineageTag": "e9142e10-dd51-4cae-9b18-37a200eaffe2"
          },
          {
            "name": "SAP4_écart DRS MP",
            "expression": "[SAP4_DRS MP N]-[SAP4_DRS MP N-1]+0",
            "formatString": "#,##0",
            "lineageTag": "a549f801-e3c6-46b7-a269-c7b3082e0450"
          },
          {
            "name": "SAP4_Ecart num client",
            "expression": "IF([SAP4_DRM Résultat SAP client]=\"< à l'écart acceptable\",1,0)",
            "formatString": "#,##0",
            "lineageTag": "e1c30f37-2d7f-4281-98f5-d8d514d0fe46"
          },
          {
            "name": "SAP4_Ecart num frs",
            "expression": "IF([SAP4_DRM Résultat SAP frs]=\"< à l'écart acceptable\",1,0)",
            "formatString": "#,##0",
            "lineageTag": "0f8b2606-4737-411f-a2ea-fbbede332f33"
          },
          {
            "name": "SAP4_Ecart num MP",
            "expression": "IF([SAP4_DRM Résultat SAP MP]=\"< à l'écart acceptable\",1,0)",
            "formatString": "#,##0",
            "lineageTag": "3c01254a-7ee8-4fe4-9d52-42d8f5419c6e"
          },
          {
            "name": "SAP4_Nb de jours N",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "-DATEDIFF(MAX(Parametrage[DateClotureN]),MAX(Parametrage[DateOuvertureN]),DAY)+1",
            "lineageTag": "3e841c87-4fe3-49f4-a724-820cc6ac07a7"
          },
          {
            "name": "SAP4_Nb de jours N-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "-DATEDIFF(MAX(Parametrage[DateClotureN_1]),MAX(Parametrage[DateOuvertureN_1]),DAY)+1",
            "lineageTag": "4af262d1-1c51-4acf-a69f-0c92b1e8a9bd"
          },
          {
            "name": "SAP4_P&L cumulé inv N",
            "expression": [
              "",
              "-IF(Isblank([_Gene_Solde GL]),BLANK(),",
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"P&L\",",
              "    'KPI'[Exercice]=\"N\",",
              "    FILTER (",
              "        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),",
              "        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])",
              "        ))",
              ")*(1+[Selected value T1]/100)"
            ],
            "formatString": "#,##0",
            "lineageTag": "892199b5-e871-4e4d-960a-60876b1bf0fa"
          },
          {
            "name": "SAP4_P&L cumulé inv N-1",
            "expression": [
              "",
              "-IF(Isblank([_Gene_Solde GL]),BLANK(),",
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"P&L\",",
              "    'KPI'[Exercice]=\"N-1\",",
              "    FILTER (",
              "        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),",
              "        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])",
              "        ))",
              ")*(1+[Selected value T2]/100)"
            ],
            "formatString": "#,##0",
            "lineageTag": "9a97fb11-2914-4352-99a5-cf8e0bd714b3"
          },
          {
            "name": "SAP4_P&L cumulé N",
            "expression": [
              "",
              "IF(Isblank([_Gene_Solde GL]),BLANK(),",
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"P&L\",",
              "    'KPI'[Exercice]=\"N\",",
              "    FILTER (",
              "        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),",
              "        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])",
              "        ))",
              ")*(1+[Selected value T1]/100)"
            ],
            "formatString": "#,##0",
            "lineageTag": "6237e348-8895-4834-a504-8ea310c879e2"
          },
          {
            "name": "SAP4_P&L cumulé N-1",
            "expression": [
              "",
              "IF(Isblank([_Gene_Solde GL]),BLANK(),",
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    PlanCompteAEF[BilanNiv1]=\"P&L\",",
              "    'KPI'[Exercice]=\"N-1\",",
              "    FILTER (",
              "        ALLSELECTED ('DimTemps'[DayOfYear],'DimTemps'[Day of year inv] ),",
              "        'DimTemps'[Day of year inv] <= MAX ('DimTemps'[Day of year inv])",
              "        ))",
              ")*(1+[Selected value T2]/100)"
            ],
            "formatString": "#,##0",
            "lineageTag": "3c71de59-426c-46e7-9320-10590e04a9c1"
          },
          {
            "name": "SAP4_Résultat SAP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ABS([SAP4_Ecart])<=[SAP4_Ecart accept. en jours],\"Inférieur à l'écart acceptable\",\"Supérieur à l'écart acceptable\")",
            "lineageTag": "ada64b2e-1949-40e5-85d9-5663207a6587"
          },
          {
            "name": "SAP4_Variation CA sur n derniers jrs",
            "expression": "-CALCULATE([_Gene_Solde N],Compte[SapDrmClients]=\"Chiffre d'affaires\",'DimTemps'[DayOfYear Calendar]>334)",
            "formatString": "### ### ###",
            "lineageTag": "35394e1e-7662-4140-b669-619885d684b6"
          },
          {
            "name": "SAP5_AAE attendues N",
            "expression": "([SAP5_Tx AAE / CA N-1]*[SAP5_CA N]+[Selected value T7])",
            "formatString": "#,##0",
            "lineageTag": "99b67801-cafe-47af-93db-28b32880b0d6"
          },
          {
            "name": "SAP5_AAE attendues N global",
            "expression": "([SAP5_Tx AAE / CA N-1 global]*[SAP5_CA N global]+[Selected value T7])",
            "formatString": "#,##0",
            "lineageTag": "e7d31eea-1fff-42bb-9910-b12c83b69dd2"
          },
          {
            "name": "SAP5_AAE attendues N inv",
            "expression": "([SAP5_Tx AAE / CA N-1 inv]*[SAP5_CA N]+[Selected value T7])",
            "formatString": "#,##0",
            "lineageTag": "5f8fc633-4033-4786-a180-d5a519969175"
          },
          {
            "name": "SAP5_AAE avant retraitement N",
            "expression": "CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))",
            "lineageTag": "22c0a9ee-2a43-448c-b73f-0dce5f28e61f"
          },
          {
            "name": "SAP5_AAE avant retraitement N inv",
            "expression": [
              "-CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))",
              ""
            ],
            "lineageTag": "884c54f2-8853-4a5e-a1f8-fce38b92eb40"
          },
          {
            "name": "SAP5_AAE avant retraitement N-1",
            "expression": [
              "CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))",
              ""
            ],
            "lineageTag": "34b20cd5-b4eb-4b56-939b-01f188d7dc99"
          },
          {
            "name": "SAP5_AAE avant retraitement N-1 global",
            "expression": [
              "switch ( true(),",
              "max('Choix du test_frs'[Code]) in {1,2,7},[SAP5_AAE avant retraitement N-1],",
              "max('Choix du test_frs'[Code]) in {3,5,6},[SAP5_AAE avant retraitement N-1 inv],",
              "\"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "2b2400ac-4d26-44a9-a957-7982f50895a3"
          },
          {
            "name": "SAP5_AAE avant retraitement N-1 inv",
            "expression": [
              "",
              "-CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))",
              ""
            ],
            "lineageTag": "28f6ff9c-26c8-4d26-9e6e-2bfde798d88d"
          },
          {
            "name": "SAP5_AAE Comptabilisées N",
            "expression": [
              "VAR a = CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))+0",
              "return",
              "switch ( true(),",
              "max('Choix du test_frs'[Code]) in {1,2,7},a,",
              "max('Choix du test_frs'[Code]) in {3,5,6},-a,",
              "\"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "ddedc983-365d-4e49-8cc8-5971c6eac0a3"
          },
          {
            "name": "SAP5_AAE Comptabilisées N inv",
            "expression": [
              "-CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))+0",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "7ba5c414-87c0-4b80-84d4-c0e67b714689"
          },
          {
            "name": "SAP5_AAE retraitées N",
            "expression": "CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))-[Selected value T7]",
            "lineageTag": "d46cdd16-b86f-4bd0-9fbb-a95a8d0b9534"
          },
          {
            "name": "SAP5_AAE retraitées N inv",
            "expression": "-CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))-[Selected value T7]",
            "lineageTag": "4ea789ad-5bc9-43dc-839d-6713518d485c"
          },
          {
            "name": "SAP5_AAE retraitées N-1",
            "expression": "CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))-[Selected value T6]",
            "formatString": "#,##0",
            "lineageTag": "41c35d65-e52d-403b-a842-9cae82f62b20"
          },
          {
            "name": "SAP5_AAE retraitées N-1 global",
            "expression": [
              "switch ( true(),",
              "max('Choix du test_frs'[Code]) in {1,2,7},[SAP5_AAE retraitées N-1],",
              "max('Choix du test_frs'[Code]) in {3,5,6},[SAP5_AAE retraitées N-1 inv],",
              "\"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "579afc8f-5216-4ff6-b23c-29771edfd5fb"
          },
          {
            "name": "SAP5_AAE retraitées N-1 inv",
            "expression": "-CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]=\"Bilan\",ALL('DimTemps'[DayOfYear]))-[Selected value T6]",
            "formatString": "#,##0",
            "lineageTag": "d5dbadef-a604-4da5-b6ef-33cb4c6c3bec"
          },
          {
            "name": "SAP5_CA N",
            "expression": [
              "var MINI = [Nbr jour min N]",
              "VAR EquivJr= [Nbr jour min equiv N]",
              "RETURN ",
              "Calculate ([SAP5_CA N V2] , filter('DimTemps','DimTemps'[DayOfYear] >= EquivJr))",
              "",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "a2ec792d-2a4b-4824-87ae-b296e09a09e1"
          },
          {
            "name": "SAP5_CA N global",
            "expression": [
              "switch ( true(),",
              "max('Choix du test_frs'[Code]) in {1,2,3},-[SAP5_CA N],",
              "max('Choix du test_frs'[Code]) in {7,5,6},[SAP5_CA N],",
              "\"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9f9805d2-b297-415a-95a3-5eda6824f322"
          },
          {
            "name": "SAP5_CA N V2",
            "expression": [
              "- CALCULATE (",
              "        [_Gene_Solde N],",
              "        PlanCompteAEF[BilanNiv1] = \"P&L\"",
              "    )",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "cdbdafd0-4a12-4201-ba1b-2d92e5387998"
          },
          {
            "name": "SAP5_CA N-1",
            "expression": [
              "var MINI = [Nbr jour min N-1]",
              "VAR EquivJr=[Nbr jour min equiv N-1] ",
              "RETURN ",
              "Calculate ([SAP5_CA N-1 V2] , filter('DimTemps','DimTemps'[DayOfYear] >= EquivJr))",
              "",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "2eb50f75-7b49-432e-8000-1e3eb839d95e"
          },
          {
            "name": "SAP5_CA N-1 global",
            "expression": [
              "switch ( true(),",
              "max('Choix du test_frs'[Code]) in {1,2,3},-[SAP5_CA N-1],",
              "max('Choix du test_frs'[Code]) in {7,5,6},[SAP5_CA N-1],",
              "\"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "0f1a6c4b-5ef8-4cba-b9d9-ce6db23df526"
          },
          {
            "name": "SAP5_CA N-1 V2",
            "expression": "-CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]=\"P&L\")",
            "formatString": "#,##0",
            "lineageTag": "f7a828a7-9317-42bb-a03c-a83e95f945d0"
          },
          {
            "name": "SAP5_ecart",
            "expression": "[SAP5_AAE Comptabilisées N]-[SAP5_AAE attendues N global]",
            "formatString": "#,##0",
            "lineageTag": "16f4873e-ddba-42ba-8d53-b6b8ce2f9581"
          },
          {
            "name": "SAP5_ecart inv",
            "expression": "[SAP5_AAE Comptabilisées N inv]-[SAP5_AAE attendues N inv]",
            "formatString": "#,##0",
            "lineageTag": "68feead1-2355-4db0-afa2-5f2cbf561cdb"
          },
          {
            "name": "SAP5_Ecart num",
            "expression": "IF([SAP5_Résultat SAP]=\"Inférieur à l'écart acceptable\",1,0)",
            "formatString": "#,##0",
            "lineageTag": "6ad750f8-3d6b-4ae9-ad36-1e2688257bd2"
          },
          {
            "name": "SAP5_Nbr de jours sélectionné N en nombre",
            "expression": [
              "VAR AX =[Nbr de jours N] - [Selected value T9]+1",
              "RETURN",
              "IF( [Selected value T9]=1, \"\",AX)",
              "",
              "",
              "--If (MOD('DimTemps'[FiscalYear],4) = 0,366 ,365 )"
            ],
            "lineageTag": "aff6c99b-ac5d-48e5-83fe-305edef4d0db"
          },
          {
            "name": "SAP5_Nbr de jours sélectionné N-1 en nombre",
            "expression": [
              "VAR AX =[Nbr de jours N-1] - [Selected value T8]+1",
              "RETURN",
              "IF( [Selected value T8]=1, \"\",AX)",
              "",
              "",
              "",
              "--If (MOD('DimTemps'[FiscalYear],4) = 0,366 ,365 )"
            ],
            "lineageTag": "70c11fef-5bfc-4301-bb08-853a928ae934"
          },
          {
            "name": "SAP5_Résultat SAP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ABS([SAP5_ecart])<=[Selected value T5],\"Inférieur à l'écart acceptable\",\"Supérieur à l'écart acceptable\")",
            "lineageTag": "9f5adaf2-a18a-4d6c-b558-703152bdcdba"
          },
          {
            "name": "SAP5_Tx AAE / CA N-1",
            "expression": "DIVIDE([SAP5_AAE retraitées N-1],[SAP5_CA N-1],0)",
            "formatString": "#,##0 %",
            "lineageTag": "7da6882b-a031-4ad9-8882-84f93a4ec6c8"
          },
          {
            "name": "SAP5_Tx AAE / CA N-1 global",
            "expression": "DIVIDE([SAP5_AAE retraitées N-1 global],[SAP5_CA N-1 global],0)",
            "formatString": "#,##0.00 %",
            "lineageTag": "8c5e4582-60ba-4844-a9cd-4d2bbd6ac57e"
          },
          {
            "name": "SAP5_Tx AAE / CA N-1 inv",
            "expression": "DIVIDE([SAP5_AAE retraitées N-1 inv],[SAP5_CA N-1],0)",
            "formatString": "#,##0 %",
            "lineageTag": "2bcb9fce-619c-4213-b196-bb0dde5bf7c0"
          },
          {
            "name": "SAP6_Apprentissage",
            "expression": "[SAP6_Assiette taxe sur salaires]*SELECTEDVALUE(TaxeApprentissage[Value])",
            "formatString": "### ### ###.##",
            "lineageTag": "3db510ea-45ac-4c51-b524-3f146ee2189a"
          },
          {
            "name": "SAP6_Assiette taxe sur salaires",
            "expression": "CALCULATE([_Gene_Solde N],Compte[Racine2]=\"64\")",
            "formatString": "### ### ###.##",
            "lineageTag": "1f44fd1b-9bd7-4072-97fb-872d3b613a99"
          },
          {
            "name": "SAP6_CSA",
            "expression": "[SAP6_Assiette taxe sur salaires]*SELECTEDVALUE(TauxCSA[Value])",
            "formatString": "### ### ###.##",
            "lineageTag": "4a46d049-43e4-43c8-846d-bbcf6718398a"
          },
          {
            "name": "SAP6_Ecart",
            "expression": "[SAP6_Taxes sur salaires comptabilisées]-[SAP6_Taxes sur salaires calculées]",
            "formatString": "#,##0",
            "lineageTag": "ce60434f-d818-4a25-ad58-7f37de189226"
          },
          {
            "name": "SAP6_PEEC",
            "expression": "[SAP6_Assiette taxe sur salaires]*SELECTEDVALUE(PEEC[Value])",
            "formatString": "### ### ###.##",
            "lineageTag": "bc27d36d-aaa1-4610-b1a1-8c40233f233b"
          },
          {
            "name": "SAP6_Résultat SAP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ABS([SAP6_Ecart])<=[Selected value T5],\"Inférieur à l'écart acceptable\",\"Supérieur à l'écart acceptable\")",
            "lineageTag": "e87517aa-a314-4eea-aa80-f1a2d5a498d5"
          },
          {
            "name": "SAP6_Taxe transport",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[SAP6_Assiette taxe sur salaires]*[Selected value T1]",
            "lineageTag": "180b5d02-3c03-40b8-b8ad-4ef2e8167e7b"
          },
          {
            "name": "SAP6_Taxes sur salaires calculées",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[SAP6_Apprentissage]+",
              "[SAP6_Contribution formation]+",
              "[SAP6_CSA]+",
              "[SAP6_PEEC]+",
              "[SAP6_Taxe transport]"
            ],
            "lineageTag": "c6b2fe9d-f46a-4706-af34-0dd983233dab"
          },
          {
            "name": "SAP6_Taxes sur salaires comptabilisées",
            "expression": "CALCULATE([_Gene_Solde N],Compte[Racine2]=\"63\")",
            "formatString": "### ### ###.##",
            "lineageTag": "c1f350b9-7ca9-4274-949b-824f43799707"
          },
          {
            "name": "SAP7_CA",
            "expression": "CALCULATE([_Gene_Solde N inv],Compte[SapCVAE+]=\"1. Ventes\")-[Selected value T7]",
            "formatString": "### ### ###.##",
            "lineageTag": "d506c696-759a-4b8d-8aa8-755569fb4d95"
          },
          {
            "name": "SAP7_Ecart",
            "expression": "// [SAP7_Montant comptabilisé]-[SAP7_Montant attendu]",
            "formatString": "#,##0",
            "lineageTag": "b7426752-297a-48fd-b399-248c2bba405e"
          },
          {
            "name": "SAP7_Montant attendu",
            "expression": "// [SAP7_VA]*[SAP7_Tx applicable]",
            "lineageTag": "7a76a526-7f40-47b5-ab44-904a581be81c"
          },
          {
            "name": "SAP7_Montant comptabilisé",
            "expression": "// CALCULATE([_Gene_Solde N],Compte[Racine5]=\"63511\")",
            "formatString": "### ### ###.##",
            "lineageTag": "2a823848-8cc5-4c50-a1a9-8eeee139b0cf"
          },
          {
            "name": "SAP7_Résultat SAP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "// IF(ABS([SAP7_Ecart])<=[Selected value T5],\"Inférieur à l'écart acceptable\",\"Supérieur à l'écart acceptable\")",
            "lineageTag": "3db55625-a10a-4f39-9219-bd31feaebf52"
          },
          {
            "name": "SAP7_Tx applicable",
            "expression": [
              "// SWITCH(TRUE(), ",
              "//     [SAP7_CA] < 500000, 0 ,",
              "//     [SAP7_CA] >= 500000 && [SAP7_CA] < 3000000, 0.005*([SAP7_CA]-500000)/2500000 , ",
              "//     [SAP7_CA] >= 3000000 && [SAP7_CA] < 10000000, 0.005+0.009*([SAP7_CA]-3000000)/7000000 , ",
              "//     [SAP7_CA] >= 10000000 && [SAP7_CA] < 50000000, 0.014+0.001*([SAP7_CA]-10000000)/40000000 , ",
              "//     [SAP7_CA] >= 5000000 , 0.0015)"
            ],
            "lineageTag": "cf0df35b-b3a4-4748-97b5-03f07e52560f"
          },
          {
            "name": "SAP7_VA",
            "expression": "// CALCULATE([_Gene_Solde N-1 inv],NOT(ISBLANK(Compte[SapCVAE+])))-[Selected value T7]+[Selected value T6]",
            "formatString": "### ### ###.##",
            "lineageTag": "e3fee8b5-288f-4193-b3fd-3c782bc47f9d"
          },
          {
            "name": "SAP7_VA/CA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "// DIVIDE([SAP7_VA],CALCULATE([_Gene_Solde N inv],Compte[SapCVAE+]=\"1. Ventes\"),0)",
            "lineageTag": "da88dd29-489a-4ae6-bdbd-33518d698350"
          },
          {
            "name": "SAP8_Bénéfice",
            "expression": "CALCULATE([_Gene_Solde N inv],PlanCompteAEF[BilanNiv1]=\"P&L\")",
            "formatString": "### ### ###",
            "lineageTag": "02de0c70-6a78-4f69-a7d5-e053db3b93af"
          },
          {
            "name": "SAP8_Calcul de la Réserve Spéciale de Participation",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "// DIVIDE(1/2*([SAP8_Bénéfice]-0.05*[SAP8_KP])*[SAP6_Assiette taxe sur salaires],[SAP7_VA],0)",
            "lineageTag": "12bd388d-3457-483e-9afc-a3cdb05a9ea3"
          },
          {
            "name": "SAP8_Ecart",
            "expression": "[SAP8_Solde N calculé]- [SAP8_Solde BG N]",
            "formatString": "#,##0",
            "lineageTag": "a400351f-88e8-47fb-9321-e301f066dde6"
          },
          {
            "name": "SAP8_Forfait sociale",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "// IF(SELECTEDVALUE(FiabilisationDonneesUtilisees[Value])=\"Oui\",0.2,0)",
            "lineageTag": "00b0661b-4b1a-4cb2-b4b0-e13041d93c6d"
          },
          {
            "name": "SAP8_KP",
            "expression": "CALCULATE([_Gene_Solde inv],PlanCompteAEF[DetailNiv1]=\"Capitaux propres (hors résultat)\")-[Selected value T6]",
            "formatString": "### ### ###",
            "lineageTag": "5b3f304e-f026-4267-8f5c-cda758bb9721"
          },
          {
            "name": "SAP8_Participation",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "// [SAP8_Calcul de la Réserve Spéciale de Participation]*(1+[SAP8_Forfait sociale])",
            "lineageTag": "b3c98349-7c32-49dd-8cc3-dde4f8b1c82e"
          },
          {
            "name": "SAP8_Solde BG N",
            "expression": [
              "IF(",
              "    OR(ISBLANK(MAX(PlanCompteAEF[LiasseCode])),ISBLANK(MAX(PlanCompteAEF[DetailNiv3]))),",
              "    [_CP_ResultatNet],",
              "    CALCULATE([_Cadrage_Solde BG],'KPI'[Exercice]=\"N\"))"
            ],
            "formatString": "#,##0",
            "lineageTag": "20e56111-2907-4644-82ec-306b5783cad1"
          },
          {
            "name": "SAP8_Solde BG N-1",
            "expression": [
              "IF(OR(ISBLANK(MAX(PlanCompteAEF[LiasseCode])),ISBLANK(MAX(PlanCompteAEF[DetailNiv3]))),",
              "[_CP_ResultatNet N-1],",
              "CALCULATE([_Cadrage_Solde BG],'KPI'[Exercice]=\"N-1\"))"
            ],
            "formatString": "#,##0",
            "lineageTag": "76803bfc-1f81-4577-a12b-151b6186245a"
          },
          {
            "name": "SAP8_Solde N calculé",
            "expression": "[SAP8_Solde BG N-1]+[_Gene_Mvt Debit N]-[_Gene_Mvt Credit N]",
            "formatString": "#,##0",
            "lineageTag": "b7e08832-aa66-47ad-820b-220bb4c92351"
          },
          {
            "name": "Selected value Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MIN(DimTemps[Dates])",
            "lineageTag": "5f1cce2a-94ff-430f-97c2-ca5ebac72be2"
          },
          {
            "name": "Selected value T1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MIN(SliderT1[Code])",
            "lineageTag": "b1ab6883-e175-4357-90e9-c2011d3a3e8e"
          },
          {
            "name": "Selected value T1 %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "MIN(SliderT1[Code])/100",
              ""
            ],
            "lineageTag": "aca72b78-cab2-4691-a6a5-3276c1bfe76e"
          },
          {
            "name": "Selected value T2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MIN(SliderT2[Code])",
            "lineageTag": "af78ec97-dc0b-480b-a9f0-e37c6644a88d"
          },
          {
            "name": "Selected value T2 %",
            "expression": "[Selected value T2]/100",
            "formatString": "#,##0.00 %",
            "lineageTag": "a0e360af-5b56-4f99-b1df-85eef2c3b100"
          },
          {
            "name": "Selected value T3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MIN(SliderT3[Code])",
            "lineageTag": "1fd84c71-45cf-4996-ac6c-12bb95fd7f09"
          },
          {
            "name": "Selected value T3 %",
            "expression": "[Selected value T3]/100",
            "formatString": "#,##0.00 %",
            "lineageTag": "e1b4a3a4-1205-4b72-ad66-003b4e60b118"
          },
          {
            "name": "Selected value T4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MIN(SliderT4[Code])",
            "lineageTag": "cdbf4cf4-7fb9-4d1f-b44e-aeac24ecfb4f"
          },
          {
            "name": "Selected value T5",
            "expression": "MIN(SliderT5[Code])+0",
            "formatString": "0",
            "lineageTag": "6cabec17-053c-42a7-add5-f9d869ba3238"
          },
          {
            "name": "Selected value T6",
            "expression": "MIN(SliderT6[Code])",
            "formatString": "#,##0",
            "lineageTag": "422134ac-19eb-4ac4-bd7e-9c502f2c2ab7"
          },
          {
            "name": "Selected value T7",
            "expression": "MIN(SliderT7[Code])",
            "formatString": "#,##0",
            "lineageTag": "89b4760e-ddb9-49d4-b3af-4a7c6fb39b4f"
          },
          {
            "name": "Selected value T8",
            "expression": "MIN(SliderT8[Code])",
            "formatString": "#,##0",
            "lineageTag": "16503732-9318-412a-a3b9-64e3b1482f6d"
          },
          {
            "name": "Selected value T9",
            "expression": "MIN(SliderT9[Code])",
            "formatString": "#,##0",
            "lineageTag": "cfc9fa45-b9d7-4995-bb39-0ac48edc3612"
          },
          {
            "name": "SendComment",
            "expression": "1",
            "lineageTag": "c3e8662d-4de7-4a94-88bd-fdb1439820c2"
          },
          {
            "name": "Solde pour bridge immo",
            "expression": [
              "if (round(calculate ([_Gene_Solde N],filter('ParamAN','ParamAN'[A/N - Bridge]=\"A-nouveaux\") , filter('ParamDC','ParamDC'[D/C TVI]=\"Cessions\")",
              "",
              "    ),0)=0",
              "",
              ",blank(),[_Gene_Solde N])"
            ],
            "lineageTag": "0d0a49e0-efb0-4c39-87f3-99d4f8321db2"
          },
          {
            "name": "Titre KP onglets généraux",
            "expression": "if([_Gene_Solde Inversé carte]<0,\"Pertes\",\"Bénéfices\")",
            "formatString": "#,##0",
            "lineageTag": "b57f574a-b18a-432d-a81b-963245fc3c67"
          },
          {
            "name": "TOD1_Acqui N",
            "expression": [
              "var A = CALCULATE (",
              "    SUM ( 'KPI'[MTDebit] ),",
              "    'KPI'[Exercice] = \"N\",",
              "    ParamAN[AN - O/N] = \"Non\",",
              "    'PlanCompteAEF'[RankingNiv3] in {2,4,6})",
              "RETURN",
              "A",
              "//if ( max('PlanCompteAEF'[RankingNiv3]) in {2,4,6} , calculate ( [_Gene_Mvt Debit N]) , blank() )",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "47a29b69-fdab-44fa-b27b-cb09f9cd6b92"
          },
          {
            "name": "TOD1_Cession N",
            "expression": [
              "var A = CALCULATE (",
              "    SUM ( 'KPI'[MTCredit] ),",
              "    'KPI'[Exercice] = \"N\",",
              "    ParamAN[AN - O/N] = \"Non\",",
              "    'PlanCompteAEF'[RankingNiv3] in {2,4,6})",
              "RETURN",
              "A",
              "",
              "",
              "//if ( max('PlanCompteAEF'[RankingNiv3]) in {2,4,6} , calculate ( [_Gene_Mvt Credit N]) , blank() )",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "b5acc387-f0c8-4244-8ea0-03622c77747d"
          },
          {
            "name": "TOD1_Desciption comptes agrégés",
            "expression": [
              "",
              "switch( true(),",
              "max('Choix du test'[Code])in {1,2}, \"Immobilisations incorporelles, immobilisations corporelles, immobilisations en cours.\",",
              "max('Choix du test'[Code]) in {3,4}, \"Services extérieurs.\",\" \")"
            ],
            "formatString": "#,##0",
            "lineageTag": "ff141c4d-bccb-4102-bfc9-4dc76defb6b5"
          },
          {
            "name": "TOD1_Desciption comptes agrégés 2",
            "expression": [
              "",
              "switch( true(),",
              "max('Choix du test'[Code])in {1,2}, \"Il convient d'exclure les comptes d'amortissement (28) et les comptes de dépréciation (29).\",",
              "max('Choix du test'[Code]) in {3,4},\" \",\" \")"
            ],
            "formatString": "#,##0",
            "lineageTag": "30725172-d5cd-45e4-a6de-e8857c29f9e7"
          },
          {
            "name": "TOD1_Description de la procédure",
            "expression": [
              "switch( true(),",
              "max('Choix du test'[Code])=2, \"- À partir du tableau de variation des immobilisations, sélectionner les cessions à tester ;\"&Unichar(10)&\"- Pour chaque élément sélectionné, obtenir les justificatifs de cessions des immobilisations et corroborer la cession de l'actif avec la documentation pertinente afin d’effectuer les vérifications nécessaires.\",",
              "max('Choix du test'[Code])=1, \"- À partir du tableau de variation des immobilisations, sélectionner les acquisitions à tester ;\"&Unichar(10)&\"- Pour chaque élément sélectionné, obtenir les justificatifs d’achats des immobilisations et corroborer l’acquisition de l’immobilisation avec la documentation pertinente afin d’effectuer les vérifications nécessaires.\",",
              "max('Choix du test'[Code]) in {3,4}, \"- À partir du détail des charges d'entretien / petits matériel et outillages, sélectionner les dépenses à tester ;\"&Unichar(10)&\"- Pour chaque élément sélectionné, analyser le caractère immobilisable ou non des dépenses.\", \"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "50cdcff5-7ae9-4523-a38d-a48acfda961e"
          },
          {
            "name": "TOD1_Dot Amort",
            "expression": "Calculate ( [_Immo_Dot Amort N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})",
            "formatString": "#,##0",
            "lineageTag": "ff492bc0-18d9-477e-b7ae-4a3bafb13af5"
          },
          {
            "name": "TOD1_Dot Depre",
            "expression": "Calculate ( [_Immo_Dot Depre N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})",
            "formatString": "#,##0",
            "lineageTag": "9e9f411f-08f3-4a1e-b4ac-27e347666ccd"
          },
          {
            "name": "TOD1_Rep Amort",
            "expression": "Calculate ( [_Immo_Rep Amort N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})",
            "formatString": "#,##0",
            "lineageTag": "7336d7b8-cfbc-4342-baf2-f4b597661de4"
          },
          {
            "name": "TOD1_Rep Depre",
            "expression": "Calculate ( [_Immo_Rep Depre N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})",
            "formatString": "#,##0",
            "lineageTag": "5fda3c2e-0f58-4e4e-b392-be9d84b00eae"
          },
          {
            "name": "TOD1_Solde N Amort / Depre",
            "expression": "Calculate ( [_Gene_Solde N], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})",
            "formatString": "#,##0",
            "lineageTag": "763a22f6-ce74-4deb-9b9b-a1eb7808fb1d"
          },
          {
            "name": "TOD1_Solde N Amort / Depre AN",
            "expression": "Calculate ( [TOD1_Solde N Amort / Depre], ParamAN[AN - O/N] = \"Oui\")",
            "formatString": "#,##0",
            "lineageTag": "51dbccbc-6e71-4133-9d5c-8713b3e9b95c"
          },
          {
            "name": "TOD1_Solde N VB",
            "expression": "Calculate ( [_Gene_Solde N], 'PlanCompteAEF'[RankingNiv3] in {2,4,6})",
            "formatString": "#,##0",
            "lineageTag": "df427117-2895-496f-a021-6212b9309834"
          },
          {
            "name": "TOD1_Solde N-1 Amort / Depre",
            "expression": "Calculate ( [_Gene_Solde N-1], 'PlanCompteAEF'[RankingNiv3] in {3,5,7})",
            "formatString": "#,##0",
            "lineageTag": "67cfa320-fa47-4d14-bab0-07ab7808424a"
          },
          {
            "name": "TOD1_Solde N-1 VB",
            "expression": "Calculate ( [_Gene_Solde N-1], 'PlanCompteAEF'[RankingNiv3] in {2,4,6})",
            "formatString": "#,##0",
            "lineageTag": "b33fe7f1-53f1-4e39-a13f-62229d955212"
          },
          {
            "name": "TOD1_Solde TOD acquisitions",
            "expression": "If ( max('Choix du test'[Code])=1, [_Gene_Mvt Credit N] , blank () )",
            "formatString": "#,##0",
            "lineageTag": "19b41529-a7c1-4156-82cc-58119619e079"
          },
          {
            "name": "TOD1_Titre tableau de détail",
            "expression": [
              "switch( true(),",
              "max('Choix du test'[Code])=1, \"Détail des écritures débitrices (acquisitions) par n° d'écriture\",",
              "max('Choix du test'[Code])=2, \"Détail des écritures créditrices (cessions) par n° d'écriture\",",
              "max('Choix du test'[Code])=3, \"Détail des écritures de charges d'entretien\", \"Détail du grand-livre\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "f12ee3fb-2ff7-4241-876b-0d13ae8917d0"
          },
          {
            "name": "TOD1_VNC",
            "expression": "[TOD1_Solde N VB]+[TOD1_Solde N Amort / Depre]",
            "formatString": "#,##0",
            "lineageTag": "4b91247f-25d2-4e82-987c-14472f0c99fd"
          },
          {
            "name": "TOD2 Charges attendues N",
            "expression": "([TOD2 Solde bilan N-1]-[Selected value T6])*[Selected value T1 %]*[Selected value T3]/365",
            "formatString": "#,##0",
            "lineageTag": "6aac9d85-dc22-4e6e-99e6-c52c62d8716c"
          },
          {
            "name": "TOD2 Compte 1",
            "expression": [
              "IF (",
              "    CALCULATE (",
              "        [TOD2 Nombre de comptes sélectionnées],",
              "        REMOVEFILTERS ( 'KPI'[Compte] )",
              "    ) < 1,",
              "    0,",
              "CALCULATE (",
              "    MAXX (",
              "        TOPN (",
              "            1,",
              "            DISTINCT ( 'KPI'[Compte] ),",
              "            'KPI'[Compte], 1",
              "        ),",
              "        'KPI'[Compte]",
              "    ),",
              "    REMOVEFILTERS ( 'KPI'[Compte] )",
              "))"
            ],
            "formatString": "#,##0",
            "lineageTag": "445b42d9-f34c-41da-a941-25e3ddd7ca47"
          },
          {
            "name": "TOD2 Compte 2",
            "expression": [
              "IF (",
              "    CALCULATE (",
              "        [TOD2 Nombre de comptes sélectionnées],",
              "        REMOVEFILTERS ( 'KPI'[Compte] )",
              "    ) < 2,",
              "    0,",
              "CALCULATE (",
              "    MAXX (",
              "        TOPN (",
              "            2,",
              "            DISTINCT ( 'KPI'[Compte] ),",
              "            'KPI'[Compte], 1",
              "        ),",
              "        'KPI'[Compte]",
              "    ),",
              "    REMOVEFILTERS ( 'KPI'[Compte] )",
              "))"
            ],
            "formatString": "#,##0",
            "lineageTag": "1aad3571-6ab7-4b9e-afbd-8b0302172b5d"
          },
          {
            "name": "TOD2 Compte 3",
            "expression": [
              "IF (",
              "    CALCULATE (",
              "        [TOD2 Nombre de comptes sélectionnées],",
              "        REMOVEFILTERS ( 'KPI'[Compte] )",
              "    ) < 3,",
              "    0,",
              "CALCULATE (",
              "    MAXX (",
              "        TOPN (",
              "            3,",
              "            DISTINCT ( 'KPI'[Compte] ),",
              "            'KPI'[Compte], 1",
              "        ),",
              "        'KPI'[Compte]",
              "    ),",
              "    REMOVEFILTERS ( 'KPI'[Compte] )",
              "))"
            ],
            "formatString": "#,##0",
            "lineageTag": "3e4ed04e-a00f-41dc-8067-2b255e62da03"
          },
          {
            "name": "TOD2 Compte 4",
            "expression": [
              "IF (",
              "    CALCULATE (",
              "        [TOD2 Nombre de comptes sélectionnées],",
              "        REMOVEFILTERS ( 'KPI'[Compte] )",
              "    ) < 4,",
              "    0,",
              "CALCULATE (",
              "    MAXX (",
              "        TOPN (",
              "            4,",
              "            DISTINCT ( 'KPI'[Compte] ),",
              "            'KPI'[Compte], 1",
              "        ),",
              "        'KPI'[Compte]",
              "    ),",
              "    REMOVEFILTERS ( 'KPI'[Compte] )",
              "))"
            ],
            "formatString": "#,##0",
            "lineageTag": "626e47d9-3903-4d9a-921a-1d6f74b9c062"
          },
          {
            "name": "TOD2 Compte 5",
            "expression": [
              "IF (",
              "    CALCULATE (",
              "        [TOD2 Nombre de comptes sélectionnées],",
              "        REMOVEFILTERS ( 'KPI'[Compte] )",
              "    ) < 5,",
              "    0,",
              "    CALCULATE (",
              "        MAXX (",
              "            TOPN (",
              "                5,",
              "                DISTINCT ( 'KPI'[Compte] ),",
              "                'KPI'[Compte], 1",
              "            ),",
              "            'KPI'[Compte]",
              "        ),",
              "        REMOVEFILTERS ( 'KPI'[Compte] )",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e159eadf-d8e1-47d5-815c-10db60e35d93"
          },
          {
            "name": "TOD2 Compte 6",
            "expression": [
              "IF (",
              "    CALCULATE (",
              "        [TOD2 Nombre de comptes sélectionnées],",
              "        REMOVEFILTERS ( 'KPI'[Compte] )",
              "    ) < 6,",
              "    \"-\",",
              "CALCULATE (",
              "    MAXX (",
              "        TOPN (",
              "            6,",
              "            DISTINCT ( 'KPI'[Compte] ),",
              "            'KPI'[Compte], 1",
              "        ),",
              "        'KPI'[Compte]",
              "    ),",
              "    REMOVEFILTERS ( 'KPI'[Compte] )",
              "))"
            ],
            "formatString": "#,##0",
            "lineageTag": "9e274238-bc99-4249-9b3b-066c2ca2ea66"
          },
          {
            "name": "TOD2 CompteName 1",
            "expression": [
              "var A = [TOD2 Compte 1]",
              "return",
              "",
              "calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )"
            ],
            "formatString": "#,##0",
            "lineageTag": "f77509cf-a608-4a61-b0d2-bfbd969f38d4"
          },
          {
            "name": "TOD2 CompteName 2",
            "expression": [
              "var A = [TOD2 Compte 2]",
              "return",
              "",
              "calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )"
            ],
            "formatString": "#,##0",
            "lineageTag": "abf6622a-87fc-4e43-973f-96bded90a2a4"
          },
          {
            "name": "TOD2 CompteName 3",
            "expression": [
              "var A = [TOD2 Compte 3]",
              "return",
              "",
              "calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )"
            ],
            "formatString": "#,##0",
            "lineageTag": "3651a03f-10e7-4ee6-826e-b440f7e2201d"
          },
          {
            "name": "TOD2 CompteName 4",
            "expression": [
              "var A = [TOD2 Compte 4]",
              "return",
              "",
              "calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )"
            ],
            "formatString": "#,##0",
            "lineageTag": "f0d46495-4a6c-4742-9ba6-ad7de0e5a49d"
          },
          {
            "name": "TOD2 CompteName 5",
            "expression": [
              "var A = [TOD2 Compte 5]",
              "return",
              "",
              "calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )"
            ],
            "formatString": "#,##0",
            "lineageTag": "b7147f0b-7da9-432e-863c-54ff7b8bf7e8"
          },
          {
            "name": "TOD2 CompteName 6",
            "expression": [
              "var A = [TOD2 Compte 6]",
              "return",
              "",
              "calculate ( max ( 'KPI'[CompteName]), 'KPI'[Compte] = A )"
            ],
            "formatString": "#,##0",
            "lineageTag": "ace84e21-7f29-4b22-af12-6c98783a2bc8"
          },
          {
            "name": "TOD2 couleur bookmark1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If( max('Choix du test'[Code])=1,\"#FFFFFF00\",\"#FFFFFF\")",
            "lineageTag": "e809d7ad-96ad-4206-af18-863b753fc4ad"
          },
          {
            "name": "TOD2 couleur bookmark1 frs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If( max('Choix du test_frs'[Code])=1,\"#FFFFFF00\",\"#FFFFFF\")",
            "lineageTag": "d0d465dc-6d36-4676-864a-3a4b85d9936e"
          },
          {
            "name": "TOD2 couleur bookmark2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If( max('Choix du test'[Code])=2,\"#FFFFFF00\",\"#FFFFFF\")",
            "lineageTag": "0fe6c13a-6330-4fd6-83d4-9a701392cb3d"
          },
          {
            "name": "TOD2 couleur bookmark2 frs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "If( max('Choix du test_frs'[Code])=2",
              ",\"#FFFFFF00\",\"#FFFFFF\")"
            ],
            "lineageTag": "37dcd784-a352-42ab-9db1-1a0df01b0f2a"
          },
          {
            "name": "TOD2 couleur bookmark3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If( mIN('Choix du test'[Code])=3,\"#FFFFFF00\",\"#FFFFFF\")",
            "lineageTag": "b20ce867-9fbf-4976-b317-fdd47cc84e2e"
          },
          {
            "name": "TOD2 couleur bookmark3 frs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If( max('Choix du test_frs'[Code])=3,\"#FFFFFF00\",\"#FFFFFF\")",
            "lineageTag": "66075ecd-5034-4f7f-bd27-2c70715992b7"
          },
          {
            "name": "TOD2 couleur bookmark5 frs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If( max('Choix du test_frs'[Code])=5,\"#FFFFFF00\",\"#FFFFFF\")",
            "lineageTag": "98da03b6-5b93-4d96-927f-46d11caa6bbf"
          },
          {
            "name": "TOD2 couleur bookmark6 frs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If( max('Choix du test_frs'[Code])=6,\"#FFFFFF00\",\"#FFFFFF\")",
            "lineageTag": "f7827812-dbec-4e49-9fa2-4ca52795f61d"
          },
          {
            "name": "TOD2 couleur bookmark7 frs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If( max('Choix du test_frs'[Code])=7,\"#FFFFFF00\",\"#FFFFFF\")",
            "lineageTag": "44e7e448-1122-4799-b203-c4118360322b"
          },
          {
            "name": "TOD2 Ecart",
            "expression": "[TOD2 Solde P&L N]-[TOD2 Charges attendues N]",
            "formatString": "#,##0",
            "lineageTag": "839901f8-59a1-4959-a4ce-054564a4c7fd"
          },
          {
            "name": "TOD2 Nombre de comptes sélectionnées",
            "expression": "distinctCOUNT('KPI'[Compte])",
            "formatString": "#,##0",
            "lineageTag": "f8fc019a-3aeb-4b99-9670-d48c47d3346f"
          },
          {
            "name": "TOD2 SAP déagrégée - Ecart num",
            "expression": "// IF([TOD2 SAP déagrégée - Résultat]=\"Inférieur à l'écart acceptable\",1,0)",
            "formatString": "0",
            "lineageTag": "7ec64091-0482-470e-ae06-8aa56be9f162"
          },
          {
            "name": "TOD2 SAP déagrégée - Elem impactant capital",
            "expression": [
              "// var A = [TOD2 Compte 1]",
              "// var B = [TOD2 Compte 2]",
              "// var C = [TOD2 Compte 3]",
              "// var D = [TOD2 Compte 4]",
              "// var E = [TOD2 Compte 5]",
              "// var F = [TOD2 Compte 6]",
              "// return",
              "",
              "// switch ( true,",
              "// not (max('KPI'[Compte]) in {A,B,C,D,E,F}) , blank(),",
              "// max('KPI'[Compte]) = A , [Selected value T6.1],",
              "// max('KPI'[Compte]) = B , [Selected value T6.2],",
              "// max('KPI'[Compte]) = C , [Selected value T6.3],",
              "// max('KPI'[Compte]) = D , [Selected value T6.4],",
              "// max('KPI'[Compte]) = E , [Selected value T6.5],",
              "// max('KPI'[Compte]) = F , [Selected value T6.6],blank())",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "e5d8b177-4a4a-4e04-8457-fafdf545e554"
          },
          {
            "name": "TOD2 SAP déagrégée - Période écoulée",
            "expression": [
              "// var A = [TOD2 Compte 1]",
              "// var B = [TOD2 Compte 2]",
              "// var C = [TOD2 Compte 3]",
              "// var D = [TOD2 Compte 4]",
              "// var E = [TOD2 Compte 5]",
              "// var F = [TOD2 Compte 6]",
              "// return",
              "",
              "// switch ( true,",
              "// not (max('KPI'[Compte]) in {A,B,C,D,E,F}) , blank(),",
              "// max('KPI'[Compte]) = A , [Selected value T2.1],",
              "// max('KPI'[Compte]) = B , [Selected value T2.2],",
              "// max('KPI'[Compte]) = C , [Selected value T2.3],",
              "// max('KPI'[Compte]) = D , [Selected value T2.4],",
              "// max('KPI'[Compte]) = E , [Selected value T2.5],",
              "// max('KPI'[Compte]) = F , [Selected value T2.6],blank())",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "300607d6-024a-484f-b178-111589d379fe"
          },
          {
            "name": "TOD2 SAP déagrégée - Résultat",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "// IF(ABS([TOD2 SAP déagrégée -Ecart])<=[Selected value T5],\"Inférieur à l'écart acceptable\",\"Supérieur à l'écart acceptable\")",
            "lineageTag": "e69ddff1-fb49-4130-b6ca-6ca65cdfcfb7"
          },
          {
            "name": "TOD2 SAP déagrégée - Taux d'intérêt",
            "expression": [
              "// var A = [TOD2 Compte 1]",
              "// var B = [TOD2 Compte 2]",
              "// var C = [TOD2 Compte 3]",
              "// var D = [TOD2 Compte 4]",
              "// var E = [TOD2 Compte 5]",
              "// var F = [TOD2 Compte 6]",
              "// return",
              "",
              "// switch ( true,",
              "// not (max('KPI'[Compte]) in {A,B,C,D,E,F}) , blank(),",
              "// max('KPI'[Compte]) = A , [Selected value T1.1]/100,",
              "// max('KPI'[Compte]) = B , [Selected value T1.2]/100,",
              "// max('KPI'[Compte]) = C , [Selected value T1.3]/100,",
              "// max('KPI'[Compte]) = D , [Selected value T1.4]/100,",
              "// max('KPI'[Compte]) = E , [Selected value T1.5]/100,",
              "// max('KPI'[Compte]) = F , [Selected value T1.6]/100,blank())",
              ""
            ],
            "formatString": "#,##0 %",
            "lineageTag": "ae95b0d6-0360-4c0b-a185-58860f95fe89"
          },
          {
            "name": "TOD2 SAP déagrégée -Ecart",
            "expression": "// [TOD2 Solde P&L N]-[TOD2 SAP désagrégée - Charges attendues N 2]",
            "formatString": "#,##0",
            "lineageTag": "5fe5874a-ae45-45e4-906c-4875d1b1be6e"
          },
          {
            "name": "TOD2 SAP désagrégée - Charges attendues N",
            "expression": "// ([TOD2 SAP désagrégée - Solde bilan N-1 ]-[TOD2 SAP déagrégée - Elem impactant capital])*[TOD2 SAP déagrégée - Taux d'intérêt]*[TOD2 SAP déagrégée - Période écoulée]/365",
            "formatString": "#,##0",
            "lineageTag": "0bee1b29-1516-42c9-ac61-81e412dc34c3"
          },
          {
            "name": "TOD2 SAP désagrégée - Charges attendues N 2",
            "expression": [
              "// var A = [TOD2 Compte 1]",
              "// var B = [TOD2 Compte 2]",
              "// var C = [TOD2 Compte 3]",
              "// var D = [TOD2 Compte 4]",
              "// var E = [TOD2 Compte 5]",
              "// var F = [TOD2 Compte 6]",
              "",
              "// return",
              "",
              "// Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = A )",
              "// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = B )",
              "// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = C )",
              "// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = D )",
              "// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = E )",
              "// + Calculate ( [TOD2 SAP désagrégée - Charges attendues N], 'KPI'[Compte] = F )"
            ],
            "formatString": "#,##0",
            "lineageTag": "05bb6358-9c1f-4fe1-afe3-ea4bafbca1a9"
          },
          {
            "name": "TOD2 SAP désagrégée - Solde bilan N-1 ",
            "expression": [
              "var A = [TOD2 Compte 1]",
              "var B = [TOD2 Compte 2]",
              "var C = [TOD2 Compte 3]",
              "var D = [TOD2 Compte 4]",
              "var E = [TOD2 Compte 5]",
              "var F = [TOD2 Compte 6]",
              "",
              "return",
              "if( max ('KPI'[Compte]) in {A,B,C,D,E,F} , [TOD2 Solde bilan N-1] , blank() )",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "05bc0a35-36c0-4962-b3da-366c96136d55"
          },
          {
            "name": "TOD2 SAP désagrégée - Solde bilan N-1 hors except.",
            "expression": "// [TOD2 SAP désagrégée - Solde bilan N-1 ]-[TOD2 SAP déagrégée - Elem impactant capital]",
            "formatString": "#,##0",
            "lineageTag": "e6745759-a495-442f-a2ae-b793c76da4cc"
          },
          {
            "name": "TOD2 Solde bilan N-1",
            "expression": [
              "-",
              "CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]=\"Bilan\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e098e3f3-05fd-4e13-b757-e624c7a1cf2b"
          },
          {
            "name": "TOD2 Solde bilan N-1 hors except.",
            "expression": "([TOD2 Solde bilan N-1]-[Selected value T6])",
            "formatString": "#,##0",
            "lineageTag": "5a27e8e9-39d2-4d35-ad9d-146dfbd5c0b9"
          },
          {
            "name": "TOD2 Solde P&L N",
            "expression": "CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\")",
            "formatString": "#,##0",
            "lineageTag": "3b3f8eaf-64ad-4afd-ba69-41c47939c5c6"
          },
          {
            "name": "TOD2_Description abrev",
            "expression": [
              "switch( true(),",
              "max('Choix du test_frs'[Code])=1, \"AAR\",",
              "max('Choix du test_frs'[Code])=3, \"FNP\",",
              "max('Choix du test_frs'[Code])=2, \"CCA\", ",
              "max('Choix du test_frs'[Code])=5, \"AAE\",",
              "max('Choix du test_frs'[Code])=6, \"PCA\",",
              "max('Choix du test_frs'[Code])=7, \"FAE\",",
              "\"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "742d1110-170c-45b7-b4a7-470d8a6bbe31"
          },
          {
            "name": "TOD2_Description comptes agrégés",
            "expression": [
              "switch( true(),",
              "max('Choix du test_frs'[Code])=1, \"Pour couvrir les avoirs à recevoir, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #409.\",",
              "max('Choix du test_frs'[Code])=3, \"Pour couvrir les factures non parvenues, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #408.\",",
              "max('Choix du test_frs'[Code])=2, \"Pour couvrir les charges constatées d'avance, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #486.\",",
              "max('Choix du test_frs'[Code])=5, \"Pour couvrir les avoirs à établir, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #4198.\",",
              "max('Choix du test_frs'[Code])=6, \"Pour couvrir les produits constatés d'avance, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #487.\",",
              "max('Choix du test_frs'[Code])=7, \"Pour couvrir les factures à établir, et dans le cadre de l’application des normes PCG, il convient de sélectionner uniquement les comptes #4181.\"",
              ", \"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "764e96f4-a434-4dab-9c35-9e9cc9841445"
          },
          {
            "name": "TOD2_Description de la procédure",
            "expression": [
              "switch( true(),",
              "max('Choix du test_frs'[Code])=1, \"- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant du produit (tels que les avoirs reçus postérieurement, contrats ou autres justificatifs probants) ;\"&Unichar(10)&\"- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off achats et les circularisations fournisseurs.\",",
              "max('Choix du test_frs'[Code])=2, \"- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant de la charge (tels que les factures (reçues postérieurement), contrats ou autres justificatifs probants) ;\"&Unichar(10)&\"- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off achats et les circularisations fournisseurs.\",",
              "max('Choix du test_frs'[Code])=3, \"- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant de la charge (tels que les factures, contrats ou autres justificatifs probants) ;\"&Unichar(10)&\"- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off achats et les circularisations fournisseurs.\",",
              "max('Choix du test_frs'[Code])=5, \"- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant du produit (tels que les factures émises postérieurement, contrats ou autres justificatifs probants) ;",
              "- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off ventes et les circularisations clients.\",",
              "max('Choix du test_frs'[Code])=6, \"- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant du produit (tels que les factures, contrats ou autres justificatifs probants) ;",
              "- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off ventes et les circularisations clients.\",",
              "max('Choix du test_frs'[Code])=7, \"- Sélection de la population à tester et pour chaque élément retenu, obtenir les documents justifiant du produit (tels que les factures émises postérieurement, contrats ou autres justificatifs probants) ;",
              "- Corroborer ce test avec les résultats des travaux réalisés sur le cut-off ventes et les circularisations clients.\",",
              " \"\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9fc12b85-7428-427a-9550-a9daa13729d7"
          },
          {
            "name": "TOD2_Ecart num",
            "expression": "IF([TOD2_Résultat ]=\"Inférieur à l'écart acceptable\",1,0)",
            "formatString": "0",
            "lineageTag": "2ce1c6a1-3eaf-4c4c-9cff-f67ea49a9e16"
          },
          {
            "name": "TOD2_Résultat ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ABS([TOD2 Ecart])<=[Selected value T5],\"Inférieur à l'écart acceptable\",\"Supérieur à l'écart acceptable\")",
            "lineageTag": "e829cf45-8f8d-49c6-9bfc-ff0f661e826b"
          },
          {
            "name": "TOD3 Dotation aux amort. attendue",
            "expression": "[TOD3 Taux d'amort moyen normalisé N]*[TOD3 Solde bilan N hors except.]",
            "formatString": "#,##0",
            "lineageTag": "ddfd3287-40ac-45e2-a0aa-e24faedc1943"
          },
          {
            "name": "TOD3 Ecart",
            "expression": "[TOD3 Solde P&L N]-[TOD3 Dotation aux amort. attendue]",
            "formatString": "#,##0",
            "lineageTag": "249e9c53-09e1-4700-970f-5d3e4f7e73c9"
          },
          {
            "name": "TOD3 Solde Amort cumulé",
            "expression": [
              "-CALCULATE (",
              "    [_Gene_Solde GL],",
              "    and ('Compte'[Racine2]>=\"28\",'Compte'[Racine2]<\"60\"),",
              "//    'KPI'[Exercice]=\"N\",",
              "    FILTER (",
              "        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[QuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear] ),",
              "        AND(DimTemps[Dates] <= MAX (DimTemps[Dates]) ,",
              "        DimTemps[FiscalYear] = MAX ( DimTemps[FiscalYear] ))",
              "        ))",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "750e4182-cd1f-4f87-8431-3981570351bf"
          },
          {
            "name": "TOD3 Solde bilan N",
            "expression": [
              "",
              "CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"Bilan\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "5cca27b2-33b8-4618-97a7-34c1736e0da3"
          },
          {
            "name": "TOD3 Solde bilan N hors except.",
            "expression": "[TOD3 Solde bilan N]-[Selected value T7]",
            "formatString": "#,##0",
            "lineageTag": "0f5641e7-6759-4911-9d35-7ce87d7d4ca7"
          },
          {
            "name": "TOD3 Solde bilan N-1",
            "expression": [
              "",
              "CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]=\"Bilan\")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e0fc2085-b6ee-4efe-be24-7b00a34774e5"
          },
          {
            "name": "TOD3 Solde bilan N-1 hors except.",
            "expression": "([TOD3 Solde bilan N-1]-[Selected value T6])",
            "formatString": "#,##0",
            "lineageTag": "179e1f41-5e3f-4ce3-9dc9-8042d09e1797"
          },
          {
            "name": "TOD3 Solde P&L",
            "expression": "CALCULATE([_Gene_Solde GL],PlanCompteAEF[BilanNiv1]=\"P&L\")",
            "formatString": "#,##0",
            "lineageTag": "eb286066-bf79-4dc6-ab13-6a54a44c775e"
          },
          {
            "name": "TOD3 Solde P&L N",
            "expression": "CALCULATE([_Gene_Solde N],PlanCompteAEF[BilanNiv1]=\"P&L\")",
            "formatString": "#,##0",
            "lineageTag": "3fb0eedb-fcd1-4b25-b09e-f820b9ca5d53"
          },
          {
            "name": "TOD3 Solde P&L N-1",
            "expression": "CALCULATE([_Gene_Solde N-1],PlanCompteAEF[BilanNiv1]=\"P&L\")",
            "formatString": "#,##0",
            "lineageTag": "e7ced162-b6e5-4757-9ed0-8386a58a823a"
          },
          {
            "name": "TOD3 Solde VB cumulé",
            "expression": [
              "CALCULATE (",
              "    [_Gene_Solde GL],",
              "    'Compte'[Racine2]<\"28\",",
              "//    'KPI'[Exercice]=\"N\",",
              "    FILTER (",
              "        ALLSELECTED ( DimTemps[Dates],'DimTemps'[DayOfYear],DimTemps[FiscalMonth],DimTemps[MonthName],DimTemps[MonthShortName],DimTemps[QuarterName],DimTemps[FiscalPeriodeID],DimTemps[FiscalYear] ),",
              "        AND(DimTemps[Dates] <= MAX (DimTemps[Dates]) ,",
              "        DimTemps[FiscalYear] = MAX ( DimTemps[FiscalYear] ))",
              "        ))",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "3b1733bb-d00f-4dd4-8e55-f26228a89dc1"
          },
          {
            "name": "TOD3 Taux d'amort moyen N-1",
            "expression": "Divide ([TOD3 Solde P&L N-1],[TOD3 Solde bilan N-1 hors except.],0)",
            "formatString": "#,##0.00 %",
            "lineageTag": "ce978073-b209-456f-90e4-5f5ac74205e4"
          },
          {
            "name": "TOD3 Taux d'amort moyen normalisé N",
            "expression": "[TOD3 Taux d'amort moyen N-1] + [Selected value T1]/100",
            "formatString": "#,##0.00 %",
            "lineageTag": "66e8754b-dc88-4962-a138-fd00b3a77115"
          },
          {
            "name": "TOD3_Ecart num",
            "expression": "IF([TOD3_Résultat]=\"Inférieur à l'écart acceptable\",1,0)",
            "formatString": "0",
            "lineageTag": "862ba387-25cc-48e0-9cf7-f956b18fca55"
          },
          {
            "name": "TOD3_Résultat",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ABS([TOD3 Ecart])<=[Selected value T5],\"Inférieur à l'écart acceptable\",\"Supérieur à l'écart acceptable\")",
            "lineageTag": "1ef55a8d-554a-4dd0-99ec-d751282de7b7"
          },
          {
            "name": "TOD3_Solde Amort / Depre",
            "expression": "-Calculate ( [_Gene_Solde GL], 'PlanCompteAEF'[RankingNiv3] in {3,5,7},'KPI'[AN]=2)",
            "formatString": "#,##0",
            "lineageTag": "9fb0ca68-56fd-4097-83b9-f230c092c858"
          },
          {
            "name": "TOD3_Solde VB",
            "expression": "Calculate ( [_Gene_Solde GL], 'PlanCompteAEF'[RankingNiv3] in {2,4,6},'KPI'[AN]=2)",
            "formatString": "#,##0",
            "lineageTag": "13284c31-4255-43e7-a5ae-1e2f6b6a5858"
          },
          {
            "name": "TOD4_type sélection",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "Switch ( True(),",
              "and (max('KPI'[Exercice]) = \"N\",max('ParamAN'[AN])=1),\"Ecriture d'a-nouveau, Cf note 1\", ",
              "max('KPI'[Exercice]) = \"N\", \"Obtenir la facture fournisseur\",",
              "\"Analyser la récurrence de la provision\")"
            ],
            "lineageTag": "1628c86b-f4f2-4cc8-a286-96be103cbc95"
          },
          {
            "name": "TOD4_type sélection num",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "Switch ( True(),",
              "[TOD4_type sélection]=\"Ecriture d'a-nouveau, Cf note 1\", 1,",
              "[TOD4_type sélection]= \"Obtenir la facture fournisseur\",2,",
              "[TOD4_type sélection]= \"Analyser la récurrence de la provision\",3)"
            ],
            "lineageTag": "7e8b073a-f1e9-4a4f-9b62-be561a0448b1"
          }
        ],
        "partitions": [
          {
            "name": "KPI-ec318b5f-1573-452d-a769-b29395bd3eab",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    KPI1 = public{[Name=\"KPI\"]}[Data]",
                "in",
                "    KPI1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MappingPCG",
        "columns": [
          {
            "name": "Clé",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "ed717fa6-a92c-4350-b815-dac48fe0e2d0",
            "sourceColumn": "Clé",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3298bc82-bde3-40f2-a0a7-52acfc1f1cb3",
            "sourceColumn": "Code",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "aafa16b5-ccae-400f-a788-e6b74a1a13b4",
        "partitions": [
          {
            "name": "MappingPCG-f1fcb505-7461-4b36-9127-95cfeb6c061b",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    MappingPCG1 = public{[Name=\"MappingPCG\"]}[Data]",
                "in",
                "    MappingPCG1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Mesures",
        "columns": [
          {
            "name": "code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "06b6f979-dfaa-472e-a86c-22acfa7b0ab8",
            "sourceColumn": "code",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ed9455fa-720f-4a5a-bcf8-14b2ac41b7e5",
        "partitions": [
          {
            "name": "Mesures-05381d75-28c9-4a37-b893-8eb86e94968f",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    Mesures1 = public{[Name=\"Mesures\"]}[Data]",
                "in",
                "    Mesures1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ParamAN",
        "columns": [
          {
            "name": "A/N - Bridge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "59091474-b500-4e0b-ad2c-4244ea343d37",
            "sourceColumn": "A/N - Bridge",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "AN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "fce9d557-4a1c-465f-9965-b37e53cd67cf",
            "sourceColumn": "AN",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "AN - O/N",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "5fd4c6a9-4a18-4504-ac75-5374348d7a01",
            "sourceColumn": "AN - O/N",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fb068f58-1d66-49df-9d94-86dc638a2c7e",
        "partitions": [
          {
            "name": "ParamAN-d1b7c06f-e739-401b-a7c1-68acd989f772",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    ParamAN1 = public{[Name=\"ParamAN\"]}[Data]",
                "in",
                "    ParamAN1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ParamDC",
        "columns": [
          {
            "name": "D/C",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "47c9aeb5-6f28-4596-a690-fcceb359c7e5",
            "sourceColumn": "D/C",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "D/C - détaillé",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "3c33955c-6dd5-45c0-b0e3-0c676b86e728",
            "sourceColumn": "D/C - détaillé",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "D/C TVAmot.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "1fe50db2-16b8-46c0-b7e0-c7a69a8f8769",
            "sourceColumn": "D/C TVAmot.",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "D/C TVI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "c1d61512-391b-4814-b332-fa6f70e9649a",
            "sourceColumn": "D/C TVI",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1830a046-b7ab-433d-91e1-e60291dbefb1",
        "partitions": [
          {
            "name": "ParamDC-2f5db1bd-5d30-43b1-9fa4-2f40c1aa0184",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    ParamDC1 = public{[Name=\"ParamDC\"]}[Data]",
                "in",
                "    ParamDC1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parametrage",
        "columns": [
          {
            "name": "CodeAnouveauN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "350995ed-b077-4123-ba95-4ec23f6b4ecc",
            "sourceColumn": "CodeAnouveauN",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CodeAnouveauN_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c043d724-abd0-4b22-ac08-3da64e351ea2",
            "sourceColumn": "CodeAnouveauN_1",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "DateOuvertureN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecae794c-533d-4ca9-b57d-bcfded28845d",
            "sourceColumn": "DateOuvertureN",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "DateClotureN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abc63a5e-6552-49ae-86ee-b0c1d7b4d962",
            "sourceColumn": "DateClotureN",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "DateOuvertureN_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2800e56-1c1f-4115-9224-a72e6aa8915b",
            "sourceColumn": "DateOuvertureN_1",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "DateClotureN_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6506485-49bb-4fab-9398-1d20f832ebc6",
            "sourceColumn": "DateClotureN_1",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Materialite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "62c09182-5aff-448f-8e14-4d60b5908904",
            "sourceColumn": "Materialite",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "PM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fbd251c8-3755-42d2-ad1e-f877a8eda23b",
            "sourceColumn": "PM",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "AMPT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd32d9b8-30dc-4993-9fd4-f0ec0f9cae63",
            "sourceColumn": "AMPT",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "AccountNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "86664c2c-2574-41dd-aced-a02380e5e326",
            "sourceColumn": "AccountNumber",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "UserMail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84387f61-6bed-4532-b028-b93c1356ed74",
            "sourceColumn": "UserMail",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "PremierMoisExercice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac86de29-3d39-4d1c-9fc3-0c509843e439",
            "sourceColumn": "PremierMoisExercice",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9a37f6fe-c6bf-4726-a089-337c10ac25e9",
        "partitions": [
          {
            "name": "Parametrage-edd26312-49da-4fd0-80f8-5430e2608e04",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    Parametrage1 = public{[Name=\"Parametrage\"]}[Data]",
                "in",
                "    Parametrage1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PlanCompteAEF",
        "columns": [
          {
            "name": "LiasseCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "c0593838-e78e-49a8-aa86-b5fa69d13d6a",
            "sourceColumn": "LiasseCode",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "LiasseLibelle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ad643b0-74cb-4d05-a9f2-02cc20da48b2",
            "sourceColumn": "LiasseLibelle",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "BilanNiv1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ddc51b4-64a1-40f1-9d7e-361167807533",
            "sourceColumn": "BilanNiv1",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "BilanNiv2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33d85cfe-a09b-4fce-a2cf-18ff94f149e7",
            "sourceColumn": "BilanNiv2",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "DetailNiv1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d19864b8-7534-4fbe-90e6-edfa5fb8d25a",
            "sourceColumn": "DetailNiv1",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "RankingNiv1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d394250-3489-4364-b4b4-2a450acb2fab",
            "sourceColumn": "RankingNiv1",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "DetailNiv2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b62c431-4d35-4ab5-896a-27019e1820c0",
            "sourceColumn": "DetailNiv2",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "RankingNiv2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8639b10a-740b-42b6-8d85-897556eaac4b",
            "sourceColumn": "RankingNiv2",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "DetailNiv3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6879bcaa-fdd4-4667-b629-59fca03e1e86",
            "sourceColumn": "DetailNiv3",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "RankingNiv3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3a79a032-8e16-47ba-aac7-274fe954167e",
            "sourceColumn": "RankingNiv3",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "MarquageStocks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce9e6d48-a7f9-47fd-ae37-51366208712f",
            "sourceColumn": "MarquageStocks",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Visuel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fea5d7f-4dad-4240-a963-754c16aca225",
            "sourceColumn": "Visuel",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "MarquageBFR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7116f4c-e238-47b2-ba53-70e767b8c592",
            "sourceColumn": "MarquageBFR",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CategorieBFR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22ae29ea-d731-4075-9235-00d2d0101edb",
            "sourceColumn": "CategorieBFR",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "SousCategorieBFR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a1cdd81-7f5e-4401-bcab-ea48410cd123",
            "sourceColumn": "SousCategorieBFR",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "RankingBFR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13d285fe-5364-4560-ab3c-7cc5af87d1e0",
            "sourceColumn": "RankingBFR",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "MarquageMarge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "907af92f-e898-4ed1-a736-57224217229a",
            "sourceColumn": "MarquageMarge",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CategorieMarge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "829884db-e6ad-4f83-9d5f-2a2be5a2f8b9",
            "sourceColumn": "CategorieMarge",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "SousCategorieMarge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33a611f2-d8e7-406d-8ead-50c2212f0911",
            "sourceColumn": "SousCategorieMarge",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "RankingMarge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dcf1ae3-a919-4ecc-abf0-9f78be2f97a9",
            "sourceColumn": "RankingMarge",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "MarquageEndettementNet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c5b540b-16d2-4fa0-b5ea-cffaf2966eae",
            "sourceColumn": "MarquageEndettementNet",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CategorieEndettementNet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e5eeda2-f1bd-4c1c-9bec-b5bc5b88e625",
            "sourceColumn": "CategorieEndettementNet",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "RankingEndettement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fbe9417-b8a9-4e4c-b674-5459732dd0eb",
            "sourceColumn": "RankingEndettement",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "MarquageREX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dd56802-ef8a-4414-b4a0-96f367b2c222",
            "sourceColumn": "MarquageREX",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "CategorieREX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db73a735-1cf6-4b07-8305-39c24c6592cc",
            "sourceColumn": "CategorieREX",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "RankingREX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3982095-b203-48e6-b172-e1afcf66a760",
            "sourceColumn": "RankingREX",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Categorie Immo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0145735-054c-4b49-87e4-50de6c8976d0",
            "sourceColumn": "Categorie Immo",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Ranking Immo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11413564-b583-4368-ab2d-604d9391e9b8",
            "sourceColumn": "Ranking Immo",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8e9c7a46-5ca1-43c7-83bd-5cd20c76098b",
        "partitions": [
          {
            "name": "PlanCompteAEF-e1979978-0d23-46d0-8e1e-1268d88fb4eb",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    PlanCompteAEF1 = public{[Name=\"PlanCompteAEF\"]}[Data]",
                "in",
                "    PlanCompteAEF1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SliderT1",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "520e7a46-f6c3-4e4a-8186-c05fdd417c8f",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "f15b1178-068c-415e-832f-a4cec4a71a87",
        "partitions": [
          {
            "name": "SliderT1-45a3880c-df1d-4b9c-acc8-c2df6900a8e1",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    SliderT2 = public{[Name=\"SliderT1\"]}[Data]",
                "in",
                "    SliderT2"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SliderT2",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d47125e0-32ac-43a6-b4f1-cd8f975518ae",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "277a48eb-8dfc-4297-a5f7-12e21b33b48d",
        "partitions": [
          {
            "name": "SliderT2-c10a658e-9f43-4868-8421-d7cc7a911675",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    SliderT3 = public{[Name=\"SliderT2\"]}[Data]",
                "in",
                "    SliderT3"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SliderT3",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d49d10b-c80e-48e2-91e9-56b5fdfcf6e1",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "cea65956-bc9b-466b-99b6-771073dc8a69",
        "partitions": [
          {
            "name": "SliderT3-4155fd69-55eb-4adc-bc35-db2dae5aaf7b",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    SliderT4 = public{[Name=\"SliderT3\"]}[Data]",
                "in",
                "    SliderT4"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SliderT4",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f38aa5f-bf8d-4fe0-b0ba-1d5a0bc47f2a",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "4106bfc6-dde0-470c-9487-675b61ecdd83",
        "partitions": [
          {
            "name": "SliderT4-114ef8eb-d47f-47a7-83d2-b1d1b6f5105a",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    SliderT5 = public{[Name=\"SliderT4\"]}[Data]",
                "in",
                "    SliderT5"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SliderT5",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "82e73f8b-bd92-41fc-b4bb-61e5d37b64df",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "df3f64b6-8f1f-4030-8bec-703ba55a7a45",
        "partitions": [
          {
            "name": "SliderT5-68bf3184-811c-4b06-9f85-eb399b02cde8",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    SliderT6 = public{[Name=\"SliderT5\"]}[Data]",
                "in",
                "    SliderT6"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SliderT6",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2748124d-49ea-49ff-b385-a49a13017c09",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "dc211232-e6b0-4db8-a039-fd189671eedb",
        "partitions": [
          {
            "name": "SliderT6-37b4c2ed-4493-4806-81fa-dad67a469085",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    SliderT7 = public{[Name=\"SliderT6\"]}[Data]",
                "in",
                "    SliderT7"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SliderT7",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e406389-8392-4020-8888-a67876491148",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "4f3eb117-0ee8-4625-8f53-09902eca50f9",
        "partitions": [
          {
            "name": "SliderT7-49131262-1de6-44aa-94d7-483949641f3c",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    SliderT8 = public{[Name=\"SliderT7\"]}[Data]",
                "in",
                "    SliderT8"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SliderT8",
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad37f912-a480-44d6-b095-ea94b490ce33",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "82cd8530-8711-4109-b9f0-2462767fbc2b",
        "partitions": [
          {
            "name": "SliderT8-08f6913d-7924-4096-957c-22e96b3a77dd",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    SliderT10 = public{[Name=\"SliderT8\"]}[Data]",
                "in",
                "    SliderT10"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SliderT9",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6dd6c9d0-aa17-4e6f-ba2b-0e5f9a480bfa",
            "sourceColumn": "Code",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "92611141-b300-4e4b-9b11-33111e22c427",
        "partitions": [
          {
            "name": "SliderT9-237437fc-e115-4715-abae-580a9ad6923d",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"tanjabalia.com:25432\", \"Cacbi\", [HierarchicalNavigation=true]),",
                "    public = Source{[Schema=\"public\"]}[Data],",
                "    SliderT1 = public{[Name=\"SliderT9\"]}[Data]",
                "in",
                "    SliderT1"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}